#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Retipea"
	#define STR0003  "Salir"
   #define STR0004  "Par metros"
   #define STR0005  "Deshace C lculo de Activos Inmovilizados"
   #define STR0006  "El  objetivo  de  este  programa es revertir el c lculo de la "
   #define STR0007  "Correcci¢n y Depreciaci¢n de Activos Inmovilizados.   Despu‚s "
   #define STR0008  "de revertir, haga los ajustes necesarios y c lcule nuevamente."
   #define STR0009  "­­ ATENCIàN: S¢lo el éLTIMO c lculo puede ser revertido !!"
   #define STR0010  "éltimo c lculo en :"
   #define STR0011  "Presione cualquier tecla para continuar ..."
   #define STR0012  "Reversi¢n Mensual"
   #define STR0013  "Moneda del Activo: "
   #define STR0014  "Seleccionando Registros..."
#ELSE
	#IFDEF ENGLISH
           #define STR0001  "O.K.    "
           #define STR0002  "Retype  "
           #define STR0003  "Quit    "
           #define STR0004  "Parameters"
           #define STR0005  "Fixed Assets Calculation Reverse "
           #define STR0006  "This program has the purpose of reverting the calculation of  "
           #define STR0007  "Mon.Adj. and Depreciation of Fixed Assets. After that is      "
           #define STR0008  "necessary adjustments and execute again calculation. "
           #define STR0009  "ATTENT.: Only the LAST calculation can be reversed !!!     "
           #define STR0010  "Last calculation :"
           #define STR0011  "Press any key to Continue...... ...        "
           #define STR0012  "Monthly Reversion"
           #define STR0013  "Asset Currency: "
	#ELSE
		#define STR0001  "Confirma"
	   #define STR0002  "Redigita"
		#define STR0003  "Abandona"
	   #define STR0004  "Parametros"
	   #define STR0005  "Desc lculo de Ativos Imobilizados"
	   #define STR0006  "Este programa tem o objetivo de reverter o calculo da Corre‡„o"
	   #define STR0007  "e Deprecia‡„o de Ativos Imobilizados. Ap¢s o descalculo , fa‡a"
	   #define STR0008  "os ajustes  necess rios e execute novamente o c lculo."
	   #define STR0009  "ATEN€ŽO: Somente o ULTIMO c lculo pode ser descalculado !!!"
	   #define STR0010  "Ultimo c lculo em :"
	   #define STR0011  "Pressione qualquer tecla para continuar ..."
	   #define STR0012  "Desc lculo Mensal"
	   #define STR0013  "Moeda do Ativo: "
	   #define STR0014  "Selecionando Registros..."
	#ENDIF
#ENDIF		