#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Salir"
   #define STR0003  "    Transferencia Anual del Activo Inmovilizado    "
   #define STR0004  "El objetivo de este programa es hacer la transferencia de los saldos  "
   #define STR0005  "para el pr¢ximo ejercicio.  Debe ser usado al comienzo del ejercicio. "
   #define STR0006  "Todos los valores de las cuentas ser n aglomeradas en un £nico saldo, "
   #define STR0007  "que  deber  ser el saldo inicial.    La fecha del nuevo saldo inicial "
   #define STR0008  "ser  la fecha de hoy del sistema."
   #define STR0009  "para el pr¢ximo ejercicio. Todos los valores de las cuenta ser n "
   #define STR0010  "aglomerados en un £nico saldo,  que deber  ser el saldo inicial. "
   #define STR0011  "La fecha del saldo ser  la fecha de hoy del Sistema."
#ELSE
   #IFDEF ENGLISH
           #define STR0001  "O.K.    "
           #define STR0002  "Quit    "
           #define STR0003  " Annual turnover of Fixed Assets         "
           #define STR0004  "The purpose of this program is transfer the balances to the next Fiscal"
           #define STR0005  "Year. It must be used at the beginning of the fiscal year. All the     "
           #define STR0006  "account amounts will be grouped under one sole balance, which will     "
           #define STR0007  "become the opening balance. The date of the new opening balance will   "
           #define STR0008  "be the current base date of the System"
           #define STR0009  "for the next fiscal year. All the amounts will be grouped under one"
           #define STR0010  "sole balance which will become the new opening balance. The new   "
           #define STR0011  "balance date will be the System current base date."
	#ELSE
	   #define STR0001  "Confirma"
	   #define STR0002  "Abandona"
	   #define STR0003  "    Virada Anual do Ativo Imobilizado    "
	   #define STR0004  "O objetivo deste programa ‚ o de  efetuar  a  transferˆncia dos saldos "
	   #define STR0005  "para o pr¢ximo exerc¡cio.  Dever   ser utilizado quando  do in¡cio  do "
	   #define STR0006  "exerc¡cio. Todos  os  valores das contas ser„o aglutinados em um £nico "
	   #define STR0007  "saldo, o qual dever  ser o saldo inicial. A data do novo saldo inicial "
	   #define STR0008  "ser  a data base atual do sistema."
	   #define STR0009  "para o pr¢ximo exerc¡cio. Todos os valores das conta serÆo aglutinadas"
	   #define STR0010  "em um £nico saldo, o qual dever  ser o saldo inicial. A data do novo"
	   #define STR0011  "saldo ser  a data base atual do Sistema."	
	#ENDIF
#ENDIF			