#IFDEF SPANISH
   #define STR0001  "Reprocesar Saldos"
   #define STR0002  "Confirma"
   #define STR0003  "Salir "
   #define STR0004  "Par metros"
   #define STR0005  "    Rehace los Saldos Contables    "
   #define STR0006  "El objetivo de este programa es reconstruir el archivo de saldos conta-"
   #define STR0007  "bles. SINTETICO a trav‚s de los registros de Bienes (SN1+SN3)  o ANALI-"
   #define STR0008  "TICO (SN4) a trav‚s del archivo de movimientos."
   #define STR0009  "Obs: Si reconstru¡do a trav‚s de los Bienes ser n generados los saldos, "
   #define STR0010  "actualizados (Resumen) y si lo es por el movimiento ser n generados con "
   #define STR0011  "los valores hist¢ricos (cierres, depreciaciones, etc)."
#ELSE
	#IFDEF ENGLISH
           #define STR0001  "Reprocess Balance"
           #define STR0002  "O.K.   "
           #define STR0003  "Quit    "
           #define STR0004  "Parameters"
           #define STR0005  "    Remake Accounting Balances   "
           #define STR0006  "This program has the purpose of rebuilding the accounting balances "
           #define STR0007  "files. SINTHETIC(through the Assets register(SN1+SN3) and ANALYTIC "
           #define STR0008  "(SN4) through the activities files.     "
           #define STR0009  "Note: If it is rebuilt through Assets, updated balances will be "
           #define STR0010  "generated(Summary) and, if through transactions they will be updated"
           #define STR0011  "with historical values(write-offs, devaluation..)"
	#ELSE
	   #define STR0001  "Reprocessar Saldos"
	   #define STR0002  "Confirma"
	   #define STR0003  "Abandona"
	   #define STR0004  "Parametros"
	   #define STR0005  "    Refaz os Saldos Contabeis    "
	   #define STR0006  "Este programa tem o objetivo reconstruir o arquivo de saldos cont -"
	   #define STR0007  "beis. SINTETICO(atrav‚s dos cadastros de Bens(SN1+SN3) ou ANALITICO"
	   #define STR0008  "(SN4) atrav‚s do arquivo de movimenta‡”es."
	   #define STR0009  "Obs: Se for reconstru¡do atrav‚s dos Bens, ser„o gerados os saldos "
	   #define STR0010  "atualizados (Resumo) e se pela movimenta‡„o ser„o gerados com os   "
	   #define STR0011  "valores hist¢ricos (baixas,deprecia‡”es,etc)."
	#ENDIF
#ENDIF		