#IFDEF SPANISH
		#define STR0001  "B&uscar  "
		#define STR0002  "Visualizar"
		#define STR0003  "Incluir"
		#define STR0004  "Modificar"
		#define STR0005  "Borrar "
		#define STR0006  "Copia"
		#define STR0007  "Actualizaci¢n de Activos Inmovilizados"
		#define STR0008  "Salir "
		#define STR0009  "Confirma"
		#define STR0010  "Descripci¢n Extendida "
		#define STR0011  "Calculadora..."
		#define STR0012  "Agenda..."
		#define STR0013  "Controlador de Impresi¢n..."
		#define STR0014  "SUELDOS "
		#define STR0015  "Crea Autom tico"
		#define STR0016  "Help de Programa..."
		#define STR0017  "Cancelar - <Ctrl-X>"
		#define STR0018  "Crea Autom tico"
		#define STR0019  "N£mero de bienes"
#ELSE
   #IFDEF ENGLISH
                #define STR0001  "Search   "
                #define STR0002  "View      "
                #define STR0003  "Insert "
                #define STR0004  "Edit   "
                #define STR0005  "Delete "
                #define STR0006  "Copy "
                #define STR0007  "Updating Fixed Assets             "
                #define STR0008  "Quit    "
                #define STR0009  "O.K.    "
                #define STR0010  "Extended Description"
                #define STR0011  "Calculator ..."
		#define STR0012  "Agenda..."
                #define STR0013  "Print Manager...           "
                #define STR0014  "SALARIES"
                #define STR0015  "Build Automatic"
                #define STR0016  "Program Help...    "
                #define STR0017  "Cancel   - <Ctrl-X>"
                #define STR0018  "Build Automatic"
                #define STR0019  "Number of Assets"
   #ELSE
		#define STR0001  "Pesquisar"
		#define STR0002  "Visualizar"
		#define STR0003  "Incluir"
		#define STR0004  "Alterar"
		#define STR0005  "Excluir"
		#define STR0006  "Copia"
		#define STR0007  "Atualiza‡„o de Ativos Imobilizados"
		#define STR0008  "Abandona"
		#define STR0009  "Confirma"
		#define STR0010  "Descri‡„o Estendida"
		#define STR0011  "Calculadora..."
		#define STR0012  "Agenda..."
		#define STR0013  "Gerenciador de Impress„o..."
		#define STR0014  "SALARIOS"
		#define STR0015  "Cria Automatico"
		#define STR0016  "Help de Programa..."
		#define STR0017  "Cancelar - <Ctrl-X>"
		#define STR0018  "Cria Autom tico"
		#define STR0019  "N£mero de bens "
   #ENDIF
#ENDIF
