#IFDEF SPANISH
   #define STR0001  "B&uscar  "
   #define STR0002  "Visualizar"
   #define STR0003  "Mod. C¢d."
   #define STR0004  "Modificaci¢n de C¢digo"
   #define STR0005  "Confirma"
   #define STR0006  "Retipea "
	#define STR0007  "Salir   "
   #define STR0008  "Modificaci¢n de C¢digos de Bienes"
   #define STR0009  "C¢digo Base Origen"
   #define STR0010  "Ötem Inicial"
   #define STR0011  "Ötem Final"
   #define STR0012  "Nuevo C¢digo Base"
#ELSE
	#IFDEF ENGLISH
           #define STR0001  "Search   "
           #define STR0002  "View      "
           #define STR0003  "Change code"
           #define STR0004  "Code Alteration    "
           #define STR0005  "O.K.    "
           #define STR0006  "Retype  "
           #define STR0007  "Quit    "
           #define STR0008  "Change of Assets Code         "
           #define STR0009  "Origin Base Code  "
           #define STR0010  "Initial Item"
           #define STR0011  "Final Item"
           #define STR0012  "New Base Code   " 
	#ELSE
	   #define STR0001  "Pesquisar"
	   #define STR0002  "Visualizar"
	   #define STR0003  "Alt.Codigo"
	   #define STR0004  "Altera‡Æo de C¢digo"
	   #define STR0005  "Confirma"
	   #define STR0006  "Redigita"
		#define STR0007  "Abandona"
	   #define STR0008  "Altera‡„o dos C¢digos dos Bens"
	   #define STR0009  "C¢digo Base Origem"
	   #define STR0010  "Item Inicial"
	   #define STR0011  "Item Final"
   	#define STR0012  "Novo C¢digo Base"	
	#ENDIF
#ENDIF		