#IFDEF SPANISH
   #define STR0001  "Buscar "
   #define STR0002  "Visualizar"
   #define STR0003  "Ampliaci¢n"
   #define STR0004  "Ampliaci¢n del Bien"
   #define STR0005  "Confirma"
   #define STR0006  "Retipea "
	#define STR0007  "Salir   "
   #define STR0008  "Ampliaci¢n de Activos"
   #define STR0009  "Descripci¢n del Bien"
   #define STR0010  "Informaciones Financieras"
   #define STR0011  "Datos de la Ampliaci¢n"
   #define STR0012  "Historial de la Ampliaci¢n"
   #define STR0013  "C¢digo Base"
   #define STR0014  "Ötem"
   #define STR0015  "Descripci¢n"
   #define STR0016  "Cantidad Actual "
   #define STR0017  "Costo Actualizado"
   #define STR0018  "Valor Residual"
   #define STR0019  "Deprec. Acumulada"
   #define STR0020  "Valor de la Ampliaci¢n"
   #define STR0021  "Nuevo Valor"
   #define STR0022  "Historial"
#ELSE
	#IFDEF ENGLISH
           #define STR0001  "Search   "
           #define STR0002  "View      "
           #define STR0003  "Expansion" 
           #define STR0004  "Asset Expansion "
           #define STR0005  "O.K.    "
           #define STR0006  "Retype  "
           #define STR0007  "Quit    "
           #define STR0008  "Asset Expansion    "
           #define STR0009  "Description Asset"
           #define STR0010  "Financial Information  "
           #define STR0011  "Expansion Data    "
           #define STR0012  "Expansion Review      "
           #define STR0013  "Base Code  "
     	   #define STR0014  "Item"
           #define STR0015  "Descript."
           #define STR0016  "Current Quantity"
           #define STR0017  "Updated Cost    "
           #define STR0018  "Residual Value"
           #define STR0019  "Accum. Depreciat."
           #define STR0020  "Expansion Amount  "
           #define STR0021  "New amount"
           #define STR0022  "Historical"
	#ELSE
	   #define STR0001  "Pesquisar"
	   #define STR0002  "Visualizar"
	   #define STR0003  "Amplia‡„o"
	   #define STR0004  "Amplia‡„o do Bem"
	   #define STR0005  "Confirma"
	   #define STR0006  "Redigita"
		#define STR0007  "Abandona"
	   #define STR0008  "Amplia‡„o de Ativos"
   	#define STR0009  "Descri‡„o do Bem"
	   #define STR0010  "Informa‡”es Financeiras"
	   #define STR0011  "Dados da Amplia‡„o"
	   #define STR0012  "Hist¢rico da Amplia‡Æo"
	   #define STR0013  "C¢digo Base"
	   #define STR0014  "Item"
	   #define STR0015  "Descri‡„o"
	   #define STR0016  "Quantidade Atual"
	   #define STR0017  "Custo Atualizado"
	   #define STR0018  "Valor Residual"
	   #define STR0019  "Deprecia‡„o Acum."
	   #define STR0020  "Valor da Amplia‡„o"
	   #define STR0021  "Novo Valor"
	   #define STR0022  "Hist¢rico"	
	#ENDIF
#ENDIF		