#IFDEF SPANISH
   #define STR0001  "B&uscar"
   #define STR0002  "Visualizar"
   #define STR0003  "Reg Anticipo"
   #define STR0004  "Registro de Anticipos de Activos Inmovilizados"
   #define STR0005  "Activos Inmovilizados"
   #define STR0006  "Confirma"
   #define STR0007  "Retipea"
	#define STR0008  "Salir"
   #define STR0009  "Registro por Anticipo "
   #define STR0010  "Datos del Bien Nuevo"
   #define STR0011  "Criterio para Selecci¢n"
   #define STR0012  "C¢digo"
   #define STR0013  "Ötem"
   #define STR0014  "C¢digo Base de los"
   #define STR0015  "Anticipos    "
   #define STR0016  "Descripci¢n"
   #define STR0017  "Seleccionando Registros..."
   #define STR0018  "¨Cu nto a los registros?"
   #define STR0019  "Registro por Anticipos "
   #define STR0020  "Valor Total:"
   #define STR0021  "Cantidad:"
#ELSE
	#IFDEF ENGLISH
           #define STR0001  "Search   "
           #define STR0002  "View      "
           #define STR0003  "Advance W.Off"
           #define STR0004  "Write Off Advanced Fixed Assets              "
           #define STR0005  "Fixed Assets       "
           #define STR0006  "O.K.    "
           #define STR0007  "Retype  "
           #define STR0008  "Quit    "
           #define STR0009  "W.Off due to Advance  "
           #define STR0010  "Data of new asset"
           #define STR0011  "Selection Criteria   "
           #define STR0012  "Code  "
	       #define STR0013  "Item"
           #define STR0014  "Base Code of  "
           #define STR0015  "Advances     "
           #define STR0016  "Descript."
           #define STR0017  "Selecting Records ......."
           #define STR0018  "About Write offs? "
           #define STR0019  "W.Off due to Advances  "
           #define STR0020  "Total Amount"
           #define STR0021  "Quantity:  "
	#ELSE
	   #define STR0001  "Pesquisar"
	   #define STR0002  "Visualizar"
	   #define STR0003  "Baixa Adiant"
	   #define STR0004  "Baixa de Adiantamentos de Ativos Imobilizados"
	   #define STR0005  "Ativos Imobilizados"
	   #define STR0006  "Confirma"
	   #define STR0007  "Redigita"
		#define STR0008  "Abandona"
	   #define STR0009  "Baixa por Adiantamento"
	   #define STR0010  "Dados do Novo Bem"
	   #define STR0011  "Crit‚rio para Sele‡„o"
	   #define STR0012  "C¢digo"
	   #define STR0013  "Item"
	   #define STR0014  "C¢digo Base dos"
	   #define STR0015  "Adiantamentos"
	   #define STR0016  "Descri‡„o"
	   #define STR0017  "Selecionando Registros..."
	   #define STR0018  "Quanto as baixas ? "
	   #define STR0019  "Baixa por Adiantamentos"
	   #define STR0020  "Valor Total:"
	   #define STR0021  "Quantidade:"	
	#ENDIF
#ENDIF		