#IFDEF SPANISH
   #define STR0001  "TODOS   "
   #define STR0002  "Utilizado en todos los m¢dulos      "
   #define STR0003  "Activo Inmovilizado                 "
   #define STR0004  "Compras                             "
   #define STR0005  "Contabilidad                        "
   #define STR0006  "Stock/Costos                        "
   #define STR0007  "Facturaci¢n                         "
   #define STR0008  "Financiero                          "
   #define STR0009  "Sueldos y Jornales                  "
   #define STR0010  "Facturaci¢n de Servicio             "
   #define STR0011  "Libros Fiscales                     "
   #define STR0012  "Planeamiento y Control de Producci¢n"
   #define STR0013  "Veh¡culos                           "
   #define STR0014  "Control de Sucursales               "
   #define STR0015  "Telemarketing                       "
   #define STR0016  "Asistencia T‚cnica                  "
   #define STR0017  "Emisor de Informes                  "
   #define STR0018  "Reloj Fichador Electr¢nico          "
   #define STR0019  "Control de Importaci¢n              "
   #define STR0020  "Gesti¢n de Recursos Humanos         "
   #define STR0021  "Mantenimiento Industrial            "
   #define STR0022  "Espec¡ficos                         "
   #define STR0023  "Espec¡ficos I                       "
   #define STR0024  "Seleccione Archivo"
   #define STR0025  "Archivo Inv lido  "
   #define STR0026  "Archivo :"
   #define STR0027  "Copias de Seguridad"
   #define STR0028  "Brw"
   #define STR0029  "Ord"
   #define STR0030  "Campo"
   #define STR0031  "M¢dulos"
   #define STR0032  "&Browse"
   #define STR0033  "&Usado"
   #define STR0034  "Formato:"
   #define STR0035  "Borrado"
   #define STR0036  "Descripci¢n"
   #define STR0037  "Aguarde, creando ¡ndices de acuerdo con la nueva estrutura."
   #define STR0038  " Actualizaci¢n de Öndices "
   #define STR0039  "Character"
   #define STR0040  "Lista de Opciones:"
   #define STR0041  "Logic   "
   #define STR0042  "Date    "
   #define STR0043  "Memo    "
   #define STR0044  "Contexto:"
   #define STR0045  "Campo"
   #define STR0046  "Inicializador Est ndar:"
   #define STR0047  "&Modificar"
   #define STR0048  "&Visualizar"
   #define STR0049  "&Real"
   #define STR0050  "&Virtual"
   #define STR0051  "&Obligatorio"
   #define STR0052  " no existe"
   #define STR0053  "       Atualizaci¢n de la Base de Datos  "
   #define STR0054  "Los campos a seguir tubieron sus valores cortados o anulados, "
   #define STR0055  "pues los d¡gitos del campo original excedieron el tama¤o del "
   #define STR0056  "nuevo campo"
   #define STR0057  "Registro : "
   #define STR0059  "Log de Inclusi¢n"
   #define STR0060  "Log de Modificaci¢n"
   #define STR0061  "Ident.Exp."
   #define STR0062  "Ident.Exp.Datos"
   #define STR0063  "Ident.Import"
   #define STR0064  "Ident.Imp.Datos"
   #define STR0065  "Ident.Reg.   "
   #define STR0066  "Ident. Registros"
   #define STR0067  "Uso"
   #define STR0068  "Restaurando Archivos"
   #define STR0069  "Modificaciones en la Estrutura del Archivo"
   #define STR0070  "Fueron hechas modificaciones que mudan la estrutura del sistema."
   #define STR0072  "&Orden:"
   #define STR0073  " Uso de los Campos por el Sistema"
   #define STR0074  "Campo:"
   #define STR0076  "Tipo:"
   #define STR0077  " Estructura de los Archivos del Sistema "
   #define STR0078  "Tama¤o:"
   #define STR0079  " Utilizaci¢n de los campos en los Browses "
   #define STR0080  "Decimal:"
   #define STR0081  "Restaurando Archivos"
   #define STR0082  "Encabezam."
   #define STR0083  "Aguarde...Compactando Archivo"
   #define STR0084  "Definici¢n del Campo:"
   #define STR0086  "Validaci¢n del Usuario:"
   #define STR0087  "Validaci¢n del Sistema:"
   #define STR0088  "Numeric"
   #define STR0089  "Consult Est ndar:"
   #define STR0090  "Nivel:"
   #define STR0091  "Propriedad:"
   #define STR0092  "Valor Anterior : "
   #define STR0093  "Modificando la Estructura del Sistema"
   #define STR0094  " Orden de Presentaci¢n de los Campos "
   #define STR0095  "Retirando Registros Borrados del "
   #define STR0096  "Recrutamiento y Selecci¢n Personal  "  
   #define STR0097  "Calidad y Inspecci¢n de Entrega     "  
   #define STR0098  "Metrolog¡a                          " 
   #define STR0099  "Front Loja                          "
	#define STR0100  " Para Actualizar la Bases de Datos, el Sistema no debe estar "
	#define STR0101  "siendo usado por otras estaciones. El Sistema est  esperando "
	#define STR0102  "que los arquivos sean liberados. Cuando todas las estaciones "
	#define STR0103  "est‚n  fuera  del Sistema, haga clic en el bot¢n  <OK>  para "
	#define STR0104  "continuar con la actualizaci¢n.                              "
	#define STR0105  "Actualizaci¢n de Versi¢n"
	#define STR0106  "Arch   "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "ALL  "
         #define STR0002  "Uzing in all modules                "
         #define STR0003  "Fixed Asset                         "
         #define STR0004  "Purchases                           "
         #define STR0005  "Accounting                          "
         #define STR0006  "Stock/Costs                         "
         #define STR0007  "Turnover                            "
         #define STR0008  "Financial                           "
         #define STR0009  "Personnel Management                "
         #define STR0010  "Service Turnover                    "
         #define STR0011  "Fiscal Books                        "
         #define STR0012  "Production Planning and Control     "
         #define STR0013  "Vehicles                            "
         #define STR0014  "Controle of Branches                "
         #define STR0015  "Telemarketing                       "
         #define STR0016  "Workshop                            "
         #define STR0017  "Report Generator                    "
         #define STR0018  "Electronic Attendance Control       "
         #define STR0019  "Control of Imports                  "
         #define STR0020  "Human Resources Management          "
         #define STR0021  "Industrial Management               "
         #define STR0022  "Specific                            "
         #define STR0023  "Specific I                          "
         #define STR0024  "Select File"
         #define STR0025  "Invalid File  "
         #define STR0026  "File :"
         #define STR0027  "Security Copies"
         #define STR0028  "Brw"
         #define STR0029  "Ord"
         #define STR0030  "Field"
         #define STR0031  "Modules"
         #define STR0032  "&Browse"
         #define STR0033  "&Used"
         #define STR0034  "Format:"
         #define STR0035  "Deleted"
         #define STR0036  "Description"
         #define STR0037  "Wait, building indexes according to new structure ..."
         #define STR0038  " Indexes updating "
         #define STR0039  "Character"
         #define STR0040  "List of Options"
         #define STR0041  "Logic   "
         #define STR0042  "Date    "
         #define STR0043  "Memo    "
         #define STR0044  "Context: "
         #define STR0045  "Field"
         #define STR0046  "Standard Starter:"
         #define STR0047  "&Change"
         #define STR0048  "&View"
         #define STR0049  "&Real"
         #define STR0050  "&Virtual"
         #define STR0051  "C&ompulsory"
         #define STR0052  "doesnt exist"
         #define STR0053  "Updataing Database  "
         #define STR0054  "The  fields  below  had their values  cut off or  zeroed,"
         #define STR0055  "since the digits contained in the original field exceeded"
         #define STR0056  "the size of  the new field."
         #define STR0057  "Record : "
         #define STR0059  "Log of Inclusion"
         #define STR0060  "Log of Change"
         #define STR0061  "Exp.Ident."
         #define STR0062  "Data Exp.Ident."
         #define STR0063  "Import Ident."
         #define STR0064  "Data Imp.Ident."
         #define STR0065  "Rec.Ident.  "
         #define STR0066  "Records Identif."
         #define STR0067  "Use"
         #define STR0068  "Restoring Files"
         #define STR0069  "Modifications in the File Structure"
         #define STR0070  "Modifications were done changing the system's structure."
         #define STR0072  "&Order:"
         #define STR0073  " Use of Fields by System"
         #define STR0074  "Field:"
         #define STR0076  "Kind:"
         #define STR0077  "Structure of System's Files "
         #define STR0078  "Size:"
         #define STR0079  " Use of fields in Browses."
         #define STR0080  "Decimal:"
         #define STR0081  "Restoring Fields"
         #define STR0082  "Header:"
         #define STR0083  "Wait...Compacting File"
         #define STR0084  "Field Definition:"
         #define STR0086  "User Validation:"
         #define STR0087  "System Validation:"
         #define STR0088  "Numeric"
         #define STR0089  "Standard Query:"
         #define STR0090  "Level:"
         #define STR0091  "Property:"
         #define STR0092  "Prior Value : "
         #define STR0093  "Changing the system's structure "
         #define STR0094  " Order of Presentation of Fields "
         #define STR0095  "Removing Deleted Records from "
         #define STR0096  "Personnel Selection and Outplacement" 
         #define STR0097  "Delivey Quality and Control         "
         #define STR0098  "Metrology                           "
         #define STR0099  "Front Branch                        "
			#define STR0100  "Para  Atualizar a  Base de Dados , o Sistema n„o poder  estar em "
			#define STR0101  "uso por outras esta‡”es. Neste momento est  sendo aguardada a "
			#define STR0102  "libera‡„o dos arquivos.  Tecle o bot„o  <Confirma>  quando todas "
			#define STR0103  "as  esta‡„es  j   estiverem  fora  do sistema para prosseguir com a" 
			#define STR0104  "atualiza‡„o.                                                  "
			#define STR0105  "Atualiza‡„o de Vers„o"
			#define STR0106  "File   "
   #ELSE
         #define STR0001  "TODOS   "
         #define STR0002  "Utilizado em todos os m¢dulos       "
         #define STR0003  "Ativo Fixo                          "
         #define STR0004  "Compras                             "
         #define STR0005  "Contabilidade                       "
         #define STR0006  "Estoque/Custos                      "
         #define STR0007  "Faturamento                         "
         #define STR0008  "Financeiro                          "
         #define STR0009  "Gest„o de Pessoal                   "
         #define STR0010  "Faturamento de Servi‡o              "
         #define STR0011  "Livros Fiscais                      "
         #define STR0012  "Planejamento e Controle de Produ‡„o "
         #define STR0013  "Ve¡culos                            "
         #define STR0014  "Controle de Lojas                   "
         #define STR0015  "Telemarketing                       "
         #define STR0016  "Oficina                             "
         #define STR0017  "Gerador de Relat¢rios               "
         #define STR0018  "Ponto Eletr“nico                    "
         #define STR0019  "Controle de Importa‡„o              "
         #define STR0020  "Gest„o de Recursos Humanos          "
         #define STR0021  "Manuten‡„o Industrial               "
         #define STR0022  "Espec¡ficos                         "
         #define STR0023  "Espec¡ficos I                       "
         #define STR0024  "Selecione Arquivo"
         #define STR0025  "Arquivo Inv lido  "
         #define STR0026  "Arquivo :"
         #define STR0027  "C¢pias de Seguran‡a"
         #define STR0028  "Brw"
         #define STR0029  "Ord"
         #define STR0030  "Campo"
         #define STR0031  "M¢dulos"
         #define STR0032  "&Browse"
         #define STR0033  "&Usado"
         #define STR0034  "Formato:"
         #define STR0035  "Deletado"
         #define STR0036  "Descri‡„o"
         #define STR0037  "Aguarde, criando ¡ndices de acordo com a nova estrutura ..."
         #define STR0038  " Atualiza‡„o de ¡ndices "
         #define STR0039  "Caracter"
         #define STR0040  "Lista de Op‡”es:"
         #define STR0041  "L¢gico  "
         #define STR0042  "Data    "
         #define STR0043  "Memo    "
         #define STR0044  "Contexto:"
         #define STR0045  "Campo"
         #define STR0046  "Inicializador Padr„o:"
         #define STR0047  "&Alterar"
         #define STR0048  "&Visualizar"
         #define STR0049  "&Real"
         #define STR0050  "&Virtual"
         #define STR0051  "&Obrigat¢rio"
         #define STR0052  " n„o existe"
         #define STR0053  "       Atualiza‡†o da Base de Dados  "
         #define STR0054  "Os campos apresentados abaixo tiveram seus valores  truncados ou"
         #define STR0055  "zerados, pois os digitos contidos no campo original  excederam o"
         #define STR0056  "tamanho do novo campo."
         #define STR0057  "Registro : "
         #define STR0059  "Log de Inclus„o"
         #define STR0060  "Log de Altera‡„o"
         #define STR0061  "Ident.Exp."
         #define STR0062  "Ident.Exp.Dados"
         #define STR0063  "Ident.Import"
         #define STR0064  "Ident.Imp.Dados"
         #define STR0065  "Ident.Reg.   "
         #define STR0066  "Ident. Registros"
         #define STR0067  "Uso"
         #define STR0068  "Restaurando Arquivos"
         #define STR0069  "Modifica‡”es na Estrutura do Arquivo"
         #define STR0070  "Foram feitas modifica‡”es que alteram a estrutura do sistema."
         #define STR0072  "&Ordem:"
         #define STR0073  " Uso dos Campos pelo Sistema"
         #define STR0074  "Campo:"
         #define STR0076  "Tipo:"
         #define STR0077  " Estrutura dos Arquivos do Sistema "
         #define STR0078  "Tamanho:"
         #define STR0079  " Utiliza‡„o dos campos nos Browses "
         #define STR0080  "Decimal:"
         #define STR0081  "Restaurando Arquivos"
         #define STR0082  "Cabe‡alho:"
         #define STR0083  "Aguarde...Compactando Arquivo"
         #define STR0084  "Defini‡„o do Campo:"
         #define STR0086  "Valida‡„o do Usu rio:"
         #define STR0087  "Valida‡„o do Sistema:"
         #define STR0088  "Num‚rico"
         #define STR0089  "Consulta Padr„o:"
         #define STR0090  "N¡vel:"
         #define STR0091  "Propriedade:"
         #define STR0092  "Valor Anterior : "
         #define STR0093  "Alterando a Estrutura do Sistema"
         #define STR0094  " Ordem de Apresenta‡„o dos Campos "
         #define STR0095  "Removendo Registros Deletados do "
         #define STR0096  "Recrutamento e Sele‡„o Pessoal      "  
         #define STR0097  "Qualidade e Inspe‡„o de Entrega     "  
         #define STR0098  "Metrologia                          " 
         #define STR0099  "Front Loja                          " 
			#define STR0100  "Para  Atualizar a  Base de Dados , o Sistema n„o poder  estar em "
			#define STR0101  "uso por outras esta‡”es. Neste momento est  sendo aguardada a "
			#define STR0102  "libera‡„o dos arquivos.  Tecle o bot„o  <Confirma>  quando todas "
			#define STR0103  "as  esta‡„es  j   estiverem  fora  do sistema para prosseguir com a" 
			#define STR0104  "atualiza‡„o.                                                  "
			#define STR0105  "Atualiza‡„o de Vers„o"
			#define STR0106  "Arq    "
   #ENDIF
#ENDIF