#IFDEF SPANISH
   #define STR0001  "Configuraci¢n de Impresi¢n de Boletas"
   #define STR0002  "Contenido de la Boleta"
   #define STR0003  "L¡n"
   #define STR0004  "Col"
   #define STR0005  "Formateo de la Boleta"
   #define STR0006  "Mensaje"
   #define STR0007  "Local de Pago"
   #define STR0008  "Vencimiento"
   #define STR0009  "Fecha Documento"
   #define STR0010  "N£mero del Documento"
   #define STR0011  "Tipo del Documento"
   #define STR0012  "Aceptaci¢n"
   #define STR0013  "Valor en $"
   #define STR0014  "Valor en Otra Moneda"
   #define STR0015  "Pagador"
   #define STR0016  "Direcci¢n/Barrio"
   #define STR0017  "Fecha del Procesamiento"
   #define STR0018  "Mun/Prov/C.Postal"
   #define STR0019  "Inicio del Mensaje"
   #define STR0020  "Especie de Numerario"
   #define STR0021  "Cartera"
   #define STR0022  "Medidas en 1/6 1/8 (6 ¢ 8)"
   #define STR0023  "Salto Entre Boletas"
   #define STR0024  "Columnas del Formulario"
   #define STR0025  "Distancia entre Columnas"
   #define STR0026  "¨La 2¦ Columna es C¢pia 1¦?"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Configuration of Ticket printer"
         #define STR0002  "Ticket Content"
         #define STR0003  "Lin"
         #define STR0004  "Col"
         #define STR0005  "Ticket Formating"
         #define STR0006  "Message "
         #define STR0007  "Place of Payment"
         #define STR0008  "Due date"
         #define STR0009  "Document Date"
         #define STR0010  "Document Number"
         #define STR0011  "Document Category"
         #define STR0012  "Accept."
         #define STR0013  "Value in R$"
         #define STR0014  "Value in other Curr."
         #define STR0015  "Debtor"
         #define STR0016  "Address / Zone"
         #define STR0017  "Processing Date"
         #define STR0018  "City/State/Zip Code"
         #define STR0019  "Beginn.of Message"
         #define STR0020  "Money Species"
         #define STR0021  "Portfolio"
         #define STR0022  "Sizes, 1/6 or 1/8 (6 or 8)"
         #define STR0023  "Skip betw/Tickets"
         #define STR0024  "Form Columns"
         #define STR0025  "Distance betw.Columns"
         #define STR0026  "2nd.Column is Copy of 1st.?"
   #ELSE
         #define STR0001  "Configura‡„o da Impress„o de Boletos"
         #define STR0002  "Conte£do do Boleto"
         #define STR0003  "Lin"
         #define STR0004  "Col"
         #define STR0005  "Formata‡„o do Boleto"
         #define STR0006  "Mensagem"
         #define STR0007  "Local de Pagamento"
         #define STR0008  "Vencimento"
         #define STR0009  "Data Documento"
         #define STR0010  "N£mero do Documento"
         #define STR0011  "Esp‚cie do Documento"
         #define STR0012  "Aceite"
         #define STR0013  "Valor em R$"
         #define STR0014  "Valor em Outra Moeda"
         #define STR0015  "Sacado"
         #define STR0016  "Endere‡o / Bairro"
         #define STR0017  "Data do Processamento"
         #define STR0018  "Munic¡pio/Estado/Cep"
         #define STR0019  "In¡cio da Mensagem"
         #define STR0020  "Esp‚cie do Numer rio"
         #define STR0021  "Carteira"
         #define STR0022  "Medidas em 1/6 ou 1/8 (6/8)"
         #define STR0023  "Salto Entre Boletos"
         #define STR0024  "Colunas do Formul rio"
         #define STR0025  "Distƒncia entre Colunas"
         #define STR0026  "2a.Coluna ‚ C¢pia da 1a.?"
   #ENDIF
#ENDIF
