#IFDEF SPANISH
   #define STR0001  "Usuarios"
   #define STR0002  "Seleccionando Registros..."
   #define STR0003  "Clave"
   #define STR0004  "Usuario "
   #define STR0005  "L¡mite por Operaci¢n"
   #define STR0006  "L¡mite Inferior"
   #define STR0007  "L¡mite Mensual"
   #define STR0008  "Total Aprobados"
   #define STR0009  "Saldo"
   #define STR0010  "Moneda"
   #define STR0012  "Control de Pertinencias"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Users"
         #define STR0002  "Selecting Records..."
         #define STR0003  "Passw"
         #define STR0004  "User "
         #define STR0005  "Limit per Operat."
         #define STR0006  "Lower Limit"
         #define STR0007  "Monthly Limit"
         #define STR0008  "Total Released"
         #define STR0009  "Balance"
         #define STR0010  "Curr."
         #define STR0012  "Compet. Control"
   #ELSE
         #define STR0001  "Usu rios"
         #define STR0002  "Selecionando Registros..."
         #define STR0003  "Senha"
         #define STR0004  "Usu rio "
         #define STR0005  "Limite por Opera‡„o"
         #define STR0006  "Limite Inferior"
         #define STR0007  "Limite Mensal"
         #define STR0008  "Total Liberados"
         #define STR0009  "Saldo"
         #define STR0010  "Moeda"
		   #define STR0012  "Controle de Al‡adas"
   #ENDIF
#ENDIF
