#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Retipea"
   #define STR0003  "Abandona"
   #define STR0004  " A  T  E  N  C  I  à  N "
   #define STR0005  "Esta  funci¢n  exije  que los  archivos"
   #define STR0006  "a ella asociados no est‚n siendo usados"
   #define STR0007  "por otras estaciones."
   #define STR0008  "Otros usuarios deben salir del sistema,"
   #define STR0009  "de modo que el programa est‚ exclusivo."
   #define STR0010  "Presione una tecla."
   #define STR0011  "Esta  rutina  generar   un archivo  texto  en  "
   #define STR0012  "medio Magn‚tico de acuerdo con los par metros. "
   #define STR0013  "Este proceso debe ser ejecutado en modo Mono Usuario.  "
   #define STR0014  "Tecle Enter para continuar ..."
   #define STR0015  "Generaci¢n de Archivo Texto"
   #define STR0016  "Esta funci¢n crear  un archivo texto en medio "
   #define STR0017  "M gnetico  de  acuerdo  con  los  par metros. "
   #define STR0018  "Este proceso debe ser ejecutado "
   #define STR0019  "en modo Mono Usuario."
   #define STR0020  "Aguarde... Abriendo Archivos en Modo Exclusivo..."
   #define STR0021  "Generando "
   #define STR0022  "NO EXISTE"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Ok     "
         #define STR0002  "Retype"
         #define STR0003  "Quit   "
         #define STR0004  "  A T T E N T I O N  "
         #define STR0005  "This  routine requires  that  the files"
         #define STR0006  "associated to it are not in use by other"
         #define STR0007  "stations."
         #define STR0008  "Make sure that other users exit  the   "
         #define STR0009  "system, leave this program exclusive.  "
         #define STR0010  "Press a key"
         #define STR0011  "This routine will generate a TXT file in Magnetic        "
         #define STR0012  "means, according to parameters.                          "
         #define STR0013  "This processing must be executed in Mono User.           "
         #define STR0014  "Type Enter to continue ..."
         #define STR0015  "Regulatory Instruct.SRF 68"
         #define STR0016  "This routine will generate the TXT file, according       "
         #define STR0017  "to parameters.          "
         #define STR0018  "This process must be executed in Mono-user   "
         #define STR0019  "mode.    "
         #define STR0020  "Wait... Opening Files in Exclusive Mode...   "
         #define STR0021  "Generating"
         #define STR0022  "NOT EXISTS   "
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  " A  T  E  N  €  Ž  O "
         #define STR0005  "Esta  rotina  exige  que  os   arquivos"
         #define STR0006  "associados a ela n†o estejam em uso por"
         #define STR0007  "outras esta‡”es."
         #define STR0008  "Fa‡a com que os outros usu rios saim do"
         #define STR0009  "sistema ,deixe este programa exclusivo."
         #define STR0010  "Pressione uma tecla."
         #define STR0011  "Esta rotina ir  gerar arquivo texto em meio Magn‚tico    "
         #define STR0012  "conforme parƒmetros.                                     "
         #define STR0013  "Este processamento dever  ser executado em Mono Usu rio. "
         #define STR0014  "Tecle Enter para continuar ..."
         #define STR0015  "Instru‡„o Normativa SRF 68"
         #define STR0016  "Esta rotina ir  gerar arquivo texto em meio Magn‚tico conforme"
         #define STR0017  "parƒmetros."
         #define STR0018  "Este processamento dever  ser executado em modo"
         #define STR0019  "mono-usu rio."
         #define STR0020  "Aguarde... Abrindo Arquivos em Modo Exclusivo..."
         #define STR0021  "Gerando "
         #define STR0022  "NAO EXISTE"
   #ENDIF
#ENDIF