#IFDEF SPANISH
         #define STR0001  "Activo Inmovilizado"
         #define STR0002  "Compras"
         #define STR0003  "Contabilidad"
         #define STR0004  "Configurador"
         #define STR0005  "Stock/Costos"
         #define STR0006  "Control de Importaci¢n"
         #define STR0007  "Facturaci¢n"
         #define STR0008  "Financiero"
         #define STR0009  "Facturaci¢n Servicio"
         #define STR0010  "Libros Fiscales"
         #define STR0011  "Sueldos y Jornales"
         #define STR0012  "Gesti¢n de Recursos Humanos"
         #define STR0013  "Control de Negocios"
         #define STR0014  "Mantenimiento de Archivos"
         #define STR0015  "Talleres"
         #define STR0016  "Planif. Control Producci¢n"
         #define STR0017  "Reloj Fichador Elect."
         #define STR0018  "Emisor de Informes"
         #define STR0019  "Veh°culos"
         #define STR0020  "Diccion†rio de Preguntas"
         #define STR0021  "Diccion†rio de Archivo"
         #define STR0022  "Diccion†rio de Datos"
         #define STR0023  "Archivo de Agenda"
         #define STR0024  "Archivo de Tablas"
         #define STR0025  "Archivo de Par†metros"
         #define STR0026  "Archivo de Gatillos"
         #define STR0027  "Archivo de Sem†foro"
         #define STR0028  "Archivo de Consultas"
         #define STR0029  "Internet"
         #define STR0030  "Log que no graba la Tabla"
         #define STR0031  "No encontr¢ archivo de Log "
         #define STR0032  "In°cio de operaci¢n a las "
         #define STR0033  "hs en el m¢dulo "
         #define STR0034  "Fin de operaci¢n a las "
         #define STR0035  "Ejecut¢ el programa "
         #define STR0036  " a las "
         #define STR0037  "hs."
         #define STR0038  "Termin¢ el programa "
         #define STR0039  "Inicio de transacci¢n a las "
         #define STR0040  "Fin de transacci¢n a las "
         #define STR0041  "Inclusi¢n del registro "
         #define STR0042  " en la tabla "
         #define STR0043  "Modificaci¢n del registro "
         #define STR0044  "Emisi¢n del informe "
         #define STR0045  " con "
         #define STR0046  " p†gina(s) a las "
         #define STR0047  " en papel"
         #define STR0048  " en el archivo "
         #define STR0049  "FILTRO: Usuario(s), "
         #define STR0050  "; Empresa/Sucur., "
         #define STR0051  "; M¢dulo(s), "
         #define STR0052  "Tipo(s): "
         #define STR0053  "Acceso a Funciones "
         #define STR0054  "Inclusiones "
         #define STR0055  "Modificaciones "
         #define STR0056  "Informes "
         #define STR0057  "Transacciones "
         #define STR0058  "; Orden, "
         #define STR0059  "Usuario"
         #define STR0060  "Empresa"
         #define STR0061  "M¢dulo"
         #define STR0062  "Emite un informe con todos los datos de la consulta "
         #define STR0063  "al archivo SL"
         #define STR0064  "Consulta Archivo LOG Fecha: "
         #define STR0065  " "
         #define STR0066  "Administraci¢n"
         #define STR0067  "REGISTRO(S)"
         #define STR0068  "CONSULTA ARCHIVO LOG"
         #define STR0069  "TIPO EMPRESA MODULO     USUARIO         RUTINA   HORA     TABLA  REG./PAG.  PUERTO"
         #define STR0070  "Resumen"
         #define STR0071  "CANCELADO POR EL OPERADOR"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Fixed Asset"
         #define STR0002  "Purchases"
         #define STR0003  "Accounting"
         #define STR0004  "Configurator"
         #define STR0005  "Invent./Costs"
         #define STR0006  "Control of Imports"
         #define STR0007  "Invoicing"
         #define STR0008  "Financial"
         #define STR0009  "Service Invoicing"
         #define STR0010  "Fiscal Books"
         #define STR0011  "Personnel Manag."
         #define STR0012  "H. Resources Management"
         #define STR0013  "Branches Control"
         #define STR0014  "Files Maintenance"
         #define STR0015  "Workshop "
         #define STR0016  "Prod.Plann. and Control"
         #define STR0017  "Elect.Atten.Ctrl."
         #define STR0018  "Report Generator"
         #define STR0019  "Vehicles"
         #define STR0020  "Dicionary of Questions"
         #define STR0021  "Dicionary of Files"
         #define STR0022  "Dicionary of Data"
         #define STR0023  "File of Agenda"
         #define STR0024  "File of Tables"
         #define STR0025  "File of Parameters"
         #define STR0026  "File of Triggers"
         #define STR0027  "File of Semaphore"
         #define STR0028  "File of Queries"
         #define STR0029  "Internet"
         #define STR0030  "Log that not save the Table   "
         #define STR0031  "Not found the File of Log   "
         #define STR0032  "Operation Started at "
         #define STR0033  "hs in module "
         #define STR0034  "Operation Finish at"
         #define STR0035  "Ran the program "
         #define STR0036  " at "
         #define STR0037  "hrs."
         #define STR0038  "Closed the program "
         #define STR0039  "Transaction Started at "
         #define STR0040  "Transaction Finish at "
         #define STR0041  "Inclusion of register "
         #define STR0042  " in table "
         #define STR0043  "Change of register "
         #define STR0044  "Issue of report "
         #define STR0045  " with "
         #define STR0046  " page(s) at "
         #define STR0047  " in paper"
         #define STR0048  " in file "
         #define STR0049  "FILTER: User(s), "
         #define STR0050  "; Comp./Branch,   "
         #define STR0051  "; Module(s), "
         #define STR0052  "Type(s): "
         #define STR0053  "Functions Input "
         #define STR0054  "Inclusions "
         #define STR0055  "Changes "
         #define STR0056  "Reports "
         #define STR0057  "Transactions "
         #define STR0058  "; Order, "
         #define STR0059  "User"
         #define STR0060  "Comp.  "
         #define STR0061  "Module"
         #define STR0062  "Issue a report with all query data to the"
         #define STR0063  "file SL"
         #define STR0064  "Query File LOG Date: "
         #define STR0065  "Z-fold Paper"
         #define STR0066  "Management"
         #define STR0067  "REGISTER(S)"
         #define STR0068  "QUERY FILE LOG"
         #define STR0069  "TYPE COMPANY MODULE     USER            ROUTINE  HOUR     TABLE  REG./PAG.  PORT "
         #define STR0070  "Summary"
         #define STR0071  "CANCELLED BY OPERATOR"
   #ELSE
         #define STR0001  "Ativo Fixo"
         #define STR0002  "Compras"
         #define STR0003  "Contabilidade"
         #define STR0004  "Configurador"
         #define STR0005  "Estoque/Custos"
         #define STR0006  "Controle de Importaá∆o"
         #define STR0007  "Faturamento"
         #define STR0008  "Financeiro"
         #define STR0009  "Faturamento Serviáo"
         #define STR0010  "Livros Fiscais"
         #define STR0011  "Gest∆o de Pessoal"
         #define STR0012  "Gest∆o de Recursos Humanos"
         #define STR0013  "Controle de Lojas"
         #define STR0014  "Manutená∆o de Arquivos"
         #define STR0015  "Oficinas"
         #define STR0016  "Planej.Contr.Produá∆o"
         #define STR0017  "Ponto Eletrìnico"
         #define STR0018  "Gerador de Relat¢rios"
         #define STR0019  "Ve°culos"
         #define STR0020  "Dicion†rio de Perguntas"
         #define STR0021  "Dicion†rio de Arquivo"
         #define STR0022  "Dicion†rio de Dados"
         #define STR0023  "Arquivo de Agenda"
         #define STR0024  "Arquivo de Tabelas"
         #define STR0025  "Arquivo de ParÉmetros"
         #define STR0026  "Arquivo de Gatilhos"
         #define STR0027  "Arquivo de Sem†foro"
         #define STR0028  "Arquivo de Consultas"
         #define STR0029  "Internet"
         #define STR0030  "Log que n∆o grava a Tabela"
         #define STR0031  "N∆o encontrou arquivo de Log "
         #define STR0032  "In°cio de operaá∆o as "
         #define STR0033  "hs no m¢dulo "
         #define STR0034  "Fim de operaá∆o as "
         #define STR0035  "Executou o programa "
         #define STR0036  " as "
         #define STR0037  "hs."
         #define STR0038  "Encerrou o programa "
         #define STR0039  "In°cio de transaá∆o as "
         #define STR0040  "Fim de transaá∆o as "
         #define STR0041  "Inclus∆o do registro "
         #define STR0042  " na tabela "
         #define STR0043  "Alteraá∆o do registro "
         #define STR0044  "Emiss∆o do relatorio "
         #define STR0045  " com "
         #define STR0046  " p†gina(s) as "
         #define STR0047  " em papel"
         #define STR0048  " no arquivo "
         #define STR0049  "FILTRO: Usu†rio(s), "
         #define STR0050  "; Empresa/Filial, "
         #define STR0051  "; Modulo(s), "
         #define STR0052  "Tipo(s): "
         #define STR0053  "Acesso a Funá‰es "
         #define STR0054  "Inclus‰es "
         #define STR0055  "Alteraá‰es "
         #define STR0056  "Relat¢rios "
         #define STR0057  "Transaá‰es "
         #define STR0058  "; Ordem, "
         #define STR0059  "Usu†rio"
         #define STR0060  "Empresa"
         #define STR0061  "M¢dulo"
         #define STR0062  "Emite um relat¢rio com todos os dados da consulta ao"
         #define STR0063  "arquivo SL"
         #define STR0064  "Consulta Arquivo LOG Data: "
         #define STR0065  "Zebrado"
         #define STR0066  "Administraá∆o"
         #define STR0067  "REGISTRO(S)"
         #define STR0068  "CONSULTA ARQUIVO LOG"
         #define STR0069  "TIPO EMPRESA M‡DULO     USUµRIO         ROTINA   HORA     TABELA REG./PAG.  PORTA"
         #define STR0070  "Resumo"
         #define STR0071  "CANCELADO PELO OPERADOR"
	#ENDIF
#ENDIF
