#IFDEF SPANISH
         #define STR0001  "Este  programa  generar  los archivos de configuraci¢n del Forprint"
         #define STR0002  "con todos los campos definidos en el diccionario de datos Microsiga"
         #define STR0003  "y sus respectivos v¡nculos." 
         #define STR0004  "¨Efectiva el procedimiento de generaci¢n de los archivos Forprint (.FPW)?"
         #define STR0005  "¨Cu nto al Procedimiento? "
         #define STR0006  "Creando Archivos FPW"
         #define STR0007  "Aguarde"
         #define STR0008  "Criando V¡nculos entre archivos"
         #define STR0009  "No Fue Posible Cargar FWEXTFPW.DLL"
         #define STR0010  "  Dominio: "
         #define STR0011  "   Contra Dominio : "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "This program will generate the Forprint configuration files"
         #define STR0002  "with all fields defined in Microsiga's data dictionary and"
         #define STR0003  "its respective links."
         #define STR0004  "Carry out the procedure of Forprint generation (.FPW)?"
         #define STR0005  "About the procedure ? "
         #define STR0006  "Building FPW Files"
         #define STR0007  "Wait"
         #define STR0008  "Building links between files"
         #define STR0009  "Impossible to load FWEXTFPW.DLL"
         #define STR0010  "  Domain: "
         #define STR0011  "   Sub Domain :    "
   #ELSE
         #define STR0001  "Este programa ir  gerar os arquivos de configura‡„o do Forprint"
         #define STR0002  "com todos os campos definidos no dicion rio de dados Microsiga"
         #define STR0003  "e suas respectivas liga‡”es."
         #define STR0004  "Efetiva o procedimento de gera‡„o dos arquivos Forprint (.FPW)?"
         #define STR0005  "Quanto ao Procedimento ? "
         #define STR0006  "Criando Arquivos Fpw"
         #define STR0007  "Aguarde"
         #define STR0008  "Criando Liga‡”es entre arquivos"
         #define STR0009  "Nao Foi Possivel Carregar FWEXTFPW.DLL"
         #define STR0010  "  Dominio: "
         #define STR0011  "   Contra Dominio : "
   #ENDIF
#ENDIF
