#IFDEF SPANISH
     #define STR0001  "Actualizaci¢n de Versi¢n"
     #define STR0002  "Este programa har  toda la Compatibilizaci¢n de los arquivos de la"
     #define STR0003  "versi¢n existente en el cliente con la nueva enviada por MICROSIGA"
     #define STR0004  "Siempre que posible ser  dada prioridad  a las configuraciones del"
     #define STR0005  "cliente.  Tal prioridad s¢lo no ser  mantenida cuando la modifica-"
     #define STR0006  "ci¢n de la NUEVA versi¢n sea imprescindible para su funcionamiento"
     #define STR0007  "Antes de continuar con la Actualizaci¢n de Versi¢n,"
     #define STR0008  "es recomendado que se haga una copia de "
     #define STR0009  "seguridad de los arquivos de datos."
     #define STR0010  "A T E N C I à N"
     #define STR0011  "Para REINICIAR la  actualizaci¢n de Versi¢n" 
     #define STR0012  "los backups de TODOS los archivos deben ser"
     #define STR0013  "restaurados."
     #define STR0014  "Aguarde..."
     #define STR0015  "Compatibilizando Archivos"
     #define STR0016  "Actualizando campos tipo MEMO"
     #define STR0017  "Testando Integridad"
     #define STR0018  "Inconsistencia "
     #define STR0019  "Creando Archivo..."
     #define STR0020  "HLP - Help's del Sistema"
     #define STR0021  "HLS - Soluciones del Sistema"
     #define STR0022  "SINDEX - Öndices"
     #define STR0023  "SX1 - Diccionario de Preguntas"
     #define STR0024  "SX2 - Diccionario de Archivos"
     #define STR0025  "SX3 - Diccionario de Datos"
     #define STR0026  "Actualizando Base de Datos"
     #define STR0027  "SX5 - Diccionario de Tablas"
     #define STR0028  "SX6 - Diccionario de Par metros"
     #define STR0029  "SX7 - Diccionario de Gatillos"
     #define STR0030  "Borrando Archivo..."
     #define STR0031  "SX8 - Secuencia de Documentaci¢n"
     #define STR0032  "SX9 - Secuencia de V¡nculos FPW"
     #define STR0033  "SXB - Consultas V¡a F3"
     #define STR0034  "Actalizaci¢n OK"
     #define STR0035  " no encontrado"
     #define STR0036  "Actualizaci¢n Interrumpida"
     #define STR0037  "Esta actualizaci¢n est  direccionando los"
     #define STR0038  "datos para un directorio diferente !!!!"
     #define STR0039  "ANTERIOR : "
     #define STR0040  "NUEVO    : "
     #define STR0041  "Organizando Archivo           " 
     #define STR0042  "Diccionario de Tablas         "
     #define STR0043  "Diccionario de Par metros      "
     #define STR0044  "Diccionario de Gatillos        "
     #define STR0045  "Analisando normalizaci¢n"
     #define STR0046  "La Actualizaci¢n de Versi¢n fue interrompida antes de su fin. "
     #define STR0047  "Las opciones son:                                             "
     #define STR0048  "- Continuar con la misma Actualizaci¢n                        "
     #define STR0049  "- Iniciar una Nueva Actualizaci¢n                             " 
     #define STR0050  "- Abandonar el proceso de Actualizaci¢n                       " 
     #define STR0051  "&Iniciar"
     #define STR0052  "&Continuar"
     #define STR0053  "&Abandonar"
     #define STR0054  "Error Borrando Archivo "
     #define STR0055  "Incluyendo Nuevos V¡nculos"
     #define STR0056  "Actualizando V¡nculos Usuario"
     #define STR0057  "Conflicto de V¡nculos del Dominio "
     #define STR0059  " y Cnt.Dominio "
     #define STR0060  ". Este registro ser  borrado"
     #define STR0061  "Verificando Tipo de Datos"
     #define STR0062  "Öndice : "
     #define STR0063  ", Orden "
     #define STR0064  " Renumerado para "
     #define STR0065  "Adicionada pregunta: "
     #define STR0066  " Orden: "
     #define STR0067  "Creado archivo: "
     #define STR0068  "Creado campo: "
     #define STR0069  " Archivo: "
     #define STR0070  "Modificada estructura del archivo: "
     #define STR0071  "Adicionada tabla " 
     #define STR0072  ", clave "
     #define STR0073  "Creado par metro: " 
     #define STR0074  "Adicionado gatillo en el campo: "
     #define STR0076  "Adicionado Öndice: "
     #define STR0077  "Adicionado Consultas: "
     #define STR0078  "Adicionado V¡nculos : "
     #define STR0079  ", Contra Dominio: "
     #define STR0080  "Se encontraron campos en el Archivo "
     #define STR0081  "  que" 
     #define STR0082  "no constan en el SX3 :"
     #define STR0083  "Estes campos ser n eliminados durante la Actualizaci¢n "
     #define STR0084  "de Versi¢n"
     #define STR0086  "Resultado del Teste de Integridad"
     #define STR0087  "Actualizaci¢n de Versi¢n"
     #define STR0088  "Se encontraron inconsistencia en los siguientes Archivos:"
     #define STR0089  "Empresa : "
     #define STR0090  "Tipo del campo "
     #define STR0091  " no confiere con SX3"
     #define STR0092  "Campo "
     #define STR0093  "N£mero de Decimales del Campo "
     #define STR0094  "Tama¤o del campo "
     #define STR0095  "SINDEX - Öndices del Sistema   "
	  #define STR0096  "SX1 - Diccionario de Preguntas "
	  #define STR0097  "SX2 - Diccionario de Archivos  "
	  #define STR0098  "SX3 - Diccionario de Datos     "
	  #define STR0099  "SX5 - Diccionario de Tablas    "
	  #define STR0100  "SX6 - Diccionario de Par metros"
	  #define STR0101  "SX7 - Diccionario de Gatillos  "
	  #define STR0102  "SXB - Consultas V¡a F3        "
	  #define STR0103  "Archivo: "
	  #define STR0104  "Incluido  : "
	  #define STR0105  "Modificado: "
#ELSE
   #IFDEF ENGLISH
	      #define STR0001  "Version Update  "
         #define STR0002  "This  program makes all the compatibility  of  the files in the "
         #define STR0003  "Client's version to the new version sent by MICROSIGA. Whenever "
         #define STR0004  "posible  it  gives the priority to the Program's configurations."
         #define STR0005  "This  priority  will  be  modified just when the changes of the "
		   #define STR0006  "NEW version be indispensable for its functioning. "
         #define STR0007  "Before running with Version Update, "
         #define STR0008  "is recommended to make a security.  "
         #define STR0009  "copy of the data files.             "
         #define STR0010  "A T T E N T I O N"
         #define STR0011  "To RESTART the Version Update, the  "
         #define STR0012  "backups of ALL the files must be    "
         #define STR0013  "restored."
         #define STR0014  "Wait..."
         #define STR0015  "Making Files Compatibility"
         #define STR0016  "Updating fields of MEMO type"
         #define STR0017  "Testing Integrity"
         #define STR0018  "Inconsistency "
         #define STR0019  "Building File..."
         #define STR0020  "HLP - Help's of System"
         #define STR0021  "HLS - Solutions of System "
         #define STR0022  "SINDEX - Index"
         #define STR0023  "SX1 - Dictionary of Questions"
         #define STR0024  "SX2 - Dictionary of Files"
         #define STR0025  "SX3 - Dictionary of Data"
         #define STR0026  "Updating Data Base"
         #define STR0027  "SX5 - Dictionary of Tables"
         #define STR0028  "SX6 - Dictionary of Parameters"
         #define STR0029  "SX7 - Dictionary of Triggers"
         #define STR0030  "Deleting Files..."
         #define STR0031  "SX8 - Sequence of Documentation"
         #define STR0032  "SX9 - Sequence of Connections FPW"
         #define STR0033  "SXB - Queries by F3 "
         #define STR0034  "Update Ok "
         #define STR0035  " not found"
         #define STR0036  "Updating Interrupted"
         #define STR0037  "This updating is directing data "
         #define STR0038  "to a different directory !!!!"
         #define STR0039  "PREVIOUS : "
         #define STR0040  "NEW      : "
         #define STR0041  "Organizing File               " 
         #define STR0042  "Dictionary of Tables          "
         #define STR0043  "Dictionary of Parameters      "
         #define STR0044  "Dictionary of Triggers        "
         #define STR0045  "Analysing Customization" 
         #define STR0046  "The Version Updating was interrupted before its conclusion."
         #define STR0047  "The Options are :                                          "
		   #define STR0048  "- Continue  with the same Updating.                        "
         #define STR0049  "- Start new Updating.                                      " 
         #define STR0050  "- Quit Updating Process.                                   " 
         #define STR0051  "&Start"
         #define STR0052  "&Continue"
         #define STR0053  "&Quit"
         #define STR0054  "Error Deleting File "
         #define STR0055  "Including New Connections"
         #define STR0056  "Updating  User's Connections"
         #define STR0057  "Conflict of Domain and Sub     "
         #define STR0059  " Domain Connections "
         #define STR0060  ". This register must be excluded"
         #define STR0061  "Checking Type of Data"
         #define STR0062  "Index  : "
         #define STR0063  ", Order "
         #define STR0064  " Renumbered for/ "
         #define STR0065  "Question included: "
         #define STR0066  " Order: "
         #define STR0067  "Building File:  "
         #define STR0068  "Building Field: "
         #define STR0069  " File: "
         #define STR0070  "File structure modified: "
         #define STR0071  "Table Included " 
         #define STR0072  ", key "
         #define STR0073  "Building parameter: " 
         #define STR0074  "Trigger included in field: "
         #define STR0076  "Index included: "
         #define STR0077  "Queries included: "
         #define STR0078  "Connections Included: "
         #define STR0079  ", Sub Domain:     "
         #define STR0080  "Fields were found in the file "
         #define STR0081  " which" 
         #define STR0082  "do not appear in  SX3 :"
         #define STR0083  "These fields shall be deleted during the Version "
         #define STR0084  "Updating. "
         #define STR0086  "Result of Integrity Test"
         #define STR0087  "Version Updating "
         #define STR0088  "Inconsistencies were found in the following files:"
         #define STR0089  "Company : "
         #define STR0090  "Type of Field "
         #define STR0091  " not in conformity with SX3"
         #define STR0092  "Field "
         #define STR0093  "Number of Decimals of Field "
         #define STR0094  "Field Size "
         #define STR0095  "SINDEX - Indexes of System    "
 		   #define STR0096  "SX1 - Dictionary of Questions "
		   #define STR0097  "SX2 - Dictionary of Files     "
		   #define STR0098  "SX3 - Dictionary of Data      "
		   #define STR0099  "SX5 - Dictionary of Tables    "
		   #define STR0100  "SX6 - Dictionary of Parameters"
		   #define STR0101  "SX7 - Dictionary of Triggers  "
		   #define STR0102  "SXB - Queries by F3           "
		   #define STR0103  "File: "
		   #define STR0104  "Inserted : "
		   #define STR0105  "Changed  : "
   #ELSE
         #define STR0001  "Atualiza‡„o de Vers„o"
         #define STR0002  "Este  programa  far   toda a  Compatibiliza‡„o dos arquivos da vers„o"
         #define STR0003  "existente  no  cliente  com a nova vers„o enviada  pela  MICROSIGA."
         #define STR0004  "O programa sempre que poss¡vel dar  prioridade …s configura‡”es do"
         #define STR0005  "cliente.  Esta prioridade  ser   modificada  apenas quando a altera‡„o"
         #define STR0006  "da  NOVA vers„o for imprescind¡vel para o funcionamento da mesma."
         #define STR0007  "Antes de prosseguir com a Atualiza‡„o de Vers„o,"
         #define STR0008  "‚ recomendado que seja realizada uma c¢pia de "
         #define STR0009  "seguran‡a dos arquivos de dados."
         #define STR0010  "A T E N € A O"
         #define STR0011  "Para REINICIAR a Atualiza‡„o de Vers„o, os "
         #define STR0012  "backups de TODOS os arquivos dever„o ser"
         #define STR0013  "restaurados."
         #define STR0014  "Aguarde..."
         #define STR0015  "Compatibilizando Arquivos"
         #define STR0016  "Atualizando campos tipo MEMO"
         #define STR0017  "Testando Integridade"
         #define STR0018  "Inconsistˆncia "
         #define STR0019  "Criando Arquivo..."
         #define STR0020  "HLP - Help's do Sistema"
         #define STR0021  "HLS - Solu‡”es do Sistema"
         #define STR0022  "SINDEX - Indices"
         #define STR0023  "SX1 - Dicion rio de Perguntas"
         #define STR0024  "SX2 - Dicion rio de Arquivos"
         #define STR0025  "SX3 - Dicion rio de Dados"
         #define STR0026  "Atualizando Base de Dados"
         #define STR0027  "SX5 - Dicion rio de Tabelas"
         #define STR0028  "SX6 - Dicion rio de Parƒmetros"
         #define STR0029  "SX7 - Dicion rio de Gatilhos"
         #define STR0030  "Deletando Arquivo..."
         #define STR0031  "SX8 - Sequencia de Documenta‡„o"
         #define STR0032  "SX9 - Sequencia de Liga‡”es FPW"
         #define STR0033  "SXB - Consultas Via F3"
         #define STR0034  "Atualiza‡„o Ok"
         #define STR0035  " n„o encontrado"
         #define STR0036  "Atualiza‡„o Interrompida"
         #define STR0037  "Esta atualiza‡„o est  direcionando os"
         #define STR0038  "dados para um diret¢rio diferente !!!!"
         #define STR0039  "ANTERIOR : "
         #define STR0040  "NOVO     : "
         #define STR0041  "Organizando Arquivo           " 
         #define STR0042  "Dicion rio de Tabelas         "
         #define STR0043  "Dicion rio de Parƒmetros      "
         #define STR0044  "Dicion rio de Gatilhos        "
         #define STR0045  "Analisando Customiza‡„o" 
         #define STR0046  "A Atualiza‡„o de Vers„o foi Interrompida antes de seu t‚rmino."
         #define STR0047  "As Op‡”es s„o :                                               "
			#define STR0048  "- Prosseguir com a mesma Atualiza‡„o.                         "
         #define STR0049  "- Iniciar nova Atualiza‡„o.                                   " 
         #define STR0050  "- Abandonar processo de Atualiza‡„o.                          " 
         #define STR0051  "&Iniciar"
         #define STR0052  "&Prosseguir"
         #define STR0053  "&Abandonar"
         #define STR0054  "Erro Deletando Arquivo "
         #define STR0055  "Incluindo Novas Liga‡”es"
         #define STR0056  "Atualizando Liga‡”es Usu rio"
         #define STR0057  "Conflito de liga‡”es do Dom¡nio "
         #define STR0059  " e Cnt.Dom¡nio "
         #define STR0060  ". Este registro ser  exclu¡do"
         #define STR0061  "Verificando Tipo de Dados"
         #define STR0062  "Indice : "
         #define STR0063  ", Ordem "
         #define STR0064  " Renumerado p/ "
         #define STR0065  "Adicionada pergunta: "
         #define STR0066  " Ordem: "
         #define STR0067  "Criado arquivo: "
         #define STR0068  "Criado campo: "
         #define STR0069  " Arquivo: "
         #define STR0070  "Modificada estrutura do arquivo: "
         #define STR0071  "Adicionada tabela " 
         #define STR0072  ", chave "
         #define STR0073  "Criado parƒmetro: " 
         #define STR0074  "Adicionado gatilho no campo: "
         #define STR0076  "Adicionado ¡ndice: "
         #define STR0077  "Adicionado Consultas: "
         #define STR0078  "Adicionada Liga‡”es : "
         #define STR0079  ", Contra Dom¡nio: "
         #define STR0080  "Foram encontrados campos no Arquivo "
         #define STR0081  "  que" 
         #define STR0082  "n„o constam no SX3 :"
         #define STR0083  "Estes campos ser„o eliminados durante a Atualiza‡„o"
         #define STR0084  "de Vers„o. "
         #define STR0086  "Resultado do Teste de Integridade"
         #define STR0087  "Atualiza‡„o de Vers„o "
         #define STR0088  "Foram encontradas inconsistˆncias nos seguintes Arquivos:"
         #define STR0089  "Empresa : "
         #define STR0090  "Tipo do campo "
         #define STR0091  " n„o confere com SX3"
         #define STR0092  "Campo "
         #define STR0093  "Numero de Decimais do Campo "
         #define STR0094  "Tamanho do campo "
         #define STR0095  "SINDEX - Indices do Sistema   "
			#define STR0096  "SX1 - Dicion rio de Perguntas "
			#define STR0097  "SX2 - Dicion rio de Arquivos "
			#define STR0098  "SX3 - Dicion rio de Dados     "
		   #define STR0099  "SX5 - Dicion rio de Tabelas   "
		   #define STR0100  "SX6 - Dicion rio de Parƒmetros"
		   #define STR0101  "SX7 - Dicion rio de Gatilhos  "
		   #define STR0102  "SXB - Consultas Via F3        "
		   #define STR0103  "Arquivo: "
		   #define STR0104  "Incluido : "
		   #define STR0105  "Alterado : "
   #ENDIF
#ENDIF