#IFDEF SPANISH
   #define STR0001  "bUscar"
   #define STR0002  "Visualizar"
   #define STR0003  "Incluir"
   #define STR0004  "Modificar"
   #define STR0005  "Borrar"
   #define STR0006  "Asientos"
   #define STR0007  "Capa del Lote - Asientos"
   #define STR0008  "Fecha Asiento"
   #define STR0009  "Lote"
   #define STR0010  "Documento"
   #define STR0011  "Asto. Est ndar"
   #define STR0012  "Total Informado Lote"
   #define STR0013  "Total Informado"
   #define STR0014  "Total Tipeado  "
   #define STR0015  "Total D‚bito  :"
   #define STR0016  "Total Cr‚dito :"
   #define STR0017  "&Fecha: "
   #define STR0018  "&Lote : "
   #define STR0019  "&Docto : "
   #define STR0020  "¨Cu nto a la visualizaci¢n?"
   #define STR0021  "¨Cu nto a la grabaci¢n?"
   #define STR0022  "¨Cu nto a la modificaci¢n?"
   #define STR0023  "¨Cu nto al borrar?"
   #define STR0024  "Par metro que indica cual es el Per¡odo Contable que"
   #define STR0025  "tuvo sus cuentas sint‚ticas  actualizadas.  A  cada "
   #define STR0026  "car cter corresponde un per¡odo (S=S¡/N=o)."
   #define STR0027  "Pre Asientos"
   #define STR0028  "Capa del Lote - Pre Asientos"
#ELSE
   #IFDEF ENGLISH
        #define STR0001  "Search   "
        #define STR0002  "View    "
        #define STR0003  "Insert "
        #define STR0004  "Edit   "
        #define STR0005  "Delete "
        #define STR0006  "Accounting Entries "
        #define STR0007  "Lot Cover - Accounting Entries "
        #define STR0008  "Date of Entry  "
        #define STR0009  "Lot "
        #define STR0010  "Document "
        #define STR0011  "Stnd Entry "
        #define STR0012  "Total Informed Lot  "
        #define STR0013  "Total Informed "
        #define STR0014  "Total Typed in "
        #define STR0015  "Total Debit   :"
        #define STR0016  "Total Credit  :"
        #define STR0017  "&Date : "
        #define STR0018  "&Lot  : "
        #define STR0019  "&Docmt : "
        #define STR0020  "About viewing    ?"
        #define STR0021  "About recording   ?"
        #define STR0022  "About changing   ?"
        #define STR0023  "About Deleting?   "
        #define STR0024  "Parameter showing which of the Accounting Periods"
        #define STR0025  "had its synthetic accounts updated. Each        "
        #define STR0026  "character corresponds to a period(S=YES/N=NO)."
        #define STR0027  "Pre-Entries    "
        #define STR0028  "Lot Cover - Pre Entries   "
    #ELSE
   	#define STR0001  "Pesquisar"
   	#define STR0002  "Visualizar"
   	#define STR0003  "Incluir"
   	#define STR0004  "Alterar"
   	#define STR0005  "Excluir"
   	#define STR0006  "Lan‡amentos Cont beis"
   	#define STR0007  "Capa de Lote - Lan‡amentos Cont beis"
   	#define STR0008  "Data Lan‡amento"
   	#define STR0009  "Lote"
   	#define STR0010  "Documento"
   	#define STR0011  "Lcto Padr„o"
   	#define STR0012  "Total Informado Lote"
   	#define STR0013  "Total Informado"
   	#define STR0014  "Total Digitado "
   	#define STR0015  "Total D‚bito  :"
   	#define STR0016  "Total Cr‚dito :"
   	#define STR0017  "&Data : "
   	#define STR0018  "&Lote : "
   	#define STR0019  "&Docto : "
   	#define STR0020  "Quanto a visualiza‡„o?"
   	#define STR0021  "Quanto a grava‡„o?"
   	#define STR0022  "Quanto a altera‡„o?"
   	#define STR0023  "Quanto a exclus„o?"
   	#define STR0024  "Parametro que indica qual o Per¡odo Contabil que"
   	#define STR0025  "teve suas contas sint‚ticas atualizadas. A cada "
   	#define STR0026  "caractere corresponde um per¡odo (S=SIM/N=NAO)."
		#define STR0027  "Pre-Lancamentos"
		#define STR0028  "Capa de Lote - Pre Lancamentos"
  #ENDIF
#ENDIF