#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Retipea"
   #define STR0003  "Asientos   "
   #define STR0004  "Total Informado"
   #define STR0005  "Total Tipeado "
   #define STR0006  "Total Informado :"
   #define STR0007  "Total Tipeado  :"
   #define STR0008  "Total D‚bito  :"
   #define STR0009  "Total Cr‚dito :"
   #define STR0010  "¨Cu nto a la grabaci¢n?"
   #define STR0011  "­D‚bito y Cr‚dito no corresponden!, ¨Acepta Asiento?  "
   #define STR0012  "Atenci¢n"
   #define STR0013  "­Atenci¢n, D‚bito y Cr‚dito no corresponden! "
   #define STR0014  "Elige Est ndares"
   #define STR0015  " Asientos       "
   #define STR0016  "C¢digo"
   #define STR0017  "Descripci¢n"
   #define STR0018  "Elige Prorrateo "
   #define STR0019  "Valor a Prorratear : "
   #define STR0021  "Prorrateos "
   #define STR0022  "Valor"
   #define STR0023  "Pre Asientos"
	#define STR0024  "Fecha:"
	#define STR0025  "Lote:"
	#define STR0026  "Docto:"
	#define STR0027  "No fue posible trabar el registro para grabar "		
	#define STR0028  "los Asientos tipeados. Si no desea continuar, "
	#define STR0029  "el m¢dulo Contable ser  finalizado.  Si desea "
	#define STR0030  "continuar tentando trabar  el  registro elija "
	#define STR0031  "la opci¢n 'S¡'."
	#define STR0032	"continuar, el Contable ser  finalizado. Caso "
	#define STR0033	"contrario  se continuar   tentando trabar el "
	#define STR0034	"registro."
#ELSE
   #IFDEF ENGLISH
	   #define STR0001  "Confirma"
	   #define STR0002  "Redigita"
  	   #define STR0003  "Lan‡amentos Cont beis"
	   #define STR0004  "Total Informado"
 	   #define STR0005  "Total Digitado "
	   #define STR0006  "Total Informado :"
 	   #define STR0007  "Total Digitado  :"
	   #define STR0008  "Total D‚bito  :"
  	   #define STR0009  "Total Cr‚dito :"
	   #define STR0010  "Quanto a grava‡„o? "
  	   #define STR0011  "D‚bito e Cr‚dito n„o conferem !, Aceita Lan‡amento "
	   #define STR0012  "Aten‡„o"
  	   #define STR0013  "Aten‡„o, D‚bito e Cr‚dito n„o conferem ! "
	   #define STR0014  "Escolha Padr”es"
  	   #define STR0015  " Lan‡amentos Padronizados"
	   #define STR0016  "Codigo"
  	   #define STR0017  "Descri‡„o"
	   #define STR0018  "Escolha Rateio"
  	   #define STR0019  "Valor a Ratear : "
	   #define STR0021  "Rateios"
  	   #define STR0022  "Valor"	
		#define STR0023  "Pre-Lancamentos"
		#define STR0024  "Data:"
		#define STR0025  "Lote:"
		#define STR0026  "Docto:"
		#define STR0027  "N„o consegui travar o registro para  gravar "		
		#define STR0028  "os Lan‡amentos  digitados.  Se  n„o  quiser "
		#define STR0029  "continuar, o  Cont bil  sera finalizado. Se "
		#define STR0030  "quiser continuar tentando travar o registro "
		#define STR0031  "escolha a op‡„o 'Sim'."
		#define STR0032	"continuar, o  Contabil  sera finalizado. Caso "
		#define STR0033	"contrario continuarei  tentando  travar o "
		#define STR0034	"registro."		
   #ELSE
		#define STR0001  "Confirma"
		#define STR0002  "Redigita"
	  	#define STR0003  "Lan‡amentos Cont beis"
		#define STR0004  "Total Informado"
   	#define STR0005  "Total Digitado "
	   #define STR0006  "Total Informado :"
   	#define STR0007  "Total Digitado  :"
	   #define STR0008  "Total D‚bito  :"
   	#define STR0009  "Total Cr‚dito :"
	   #define STR0010  "Quanto a grava‡„o? "
   	#define STR0011  "D‚bito e Cr‚dito n„o conferem !, Aceita Lan‡amento "
	   #define STR0012  "Aten‡„o"
   	#define STR0013  "Aten‡„o, D‚bito e Cr‚dito n„o conferem ! "
	   #define STR0014  "Escolha Padr”es"
   	#define STR0015  " Lan‡amentos Padronizados"
	   #define STR0016  "Codigo"
   	#define STR0017  "Descri‡„o"
	   #define STR0018  "Escolha Rateio"
   	#define STR0019  "Valor a Ratear : "
	   #define STR0021  "Rateios"
  	   #define STR0022  "Valor"
		#define STR0023  "Pre-Lancamentos"
		#define STR0024  "Data:"
		#define STR0025  "Lote:"
		#define STR0026  "Docto:"
		#define STR0027  "N„o consegui travar o registro para  gravar "		
		#define STR0028  "os Lan‡amentos  digitados.  Se  n„o  quiser "
		#define STR0029  "continuar, o  Cont bil  sera finalizado. Se "
		#define STR0030  "quiser continuar tentando travar o registro "
		#define STR0031  "escolha a op‡„o 'Sim'."
		#define STR0032	"continuar, o  Contabil  sera finalizado. Caso "
		#define STR0033	"contrario continuarei  tentando  travar o "
		#define STR0034	"registro."
	#ENDIF
#ENDIF	
