#IFDEF SPANISH
   #define STR0001  "bUscar    "
   #define STR0002  "Visualizar"
   #define STR0003  "Incluir"
   #define STR0004  "Modificar"
   #define STR0005  "Borrar "
   #define STR0006  "Actualizaci¢n de Presupuestos"
   #define STR0007  "Presupuestos"
   #define STR0008  "Abandona"
   #define STR0009  "Confirma"
   #define STR0010  "¨Cu nto al Borrar?     "
   #define STR0011  "pRevisto Atual"
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "Seacrch  "
                #define STR0002  "View     "
                #define STR0003  "Insert "
                #define STR0004  "Edit   "
                #define STR0005  "Delete "
                #define STR0006  "Update of Budgets       "
                #define STR0007  "Budgets   "
                #define STR0008  "Quit    "
                #define STR0009  "O.K.  "
                #define STR0010  "About Deleting?  "
	            #define STR0011  "Current Forecast"
	#ELSE
		#define STR0001  "Pesquisar"
		#define STR0002  "Visualizar"
		#define STR0003  "Incluir"
		#define STR0004  "Alterar"
		#define STR0005  "Excluir"
		#define STR0006  "Atualiza‡„o de Or‡amentos"
		#define STR0007  "Or‡amentos"
		#define STR0008  "Abandona"
		#define STR0009  "Confirma"
		#define STR0010  "Quanto … exclus„o?"
		#define STR0011  "pRevisto Atual"
	#ENDIF
#ENDIF
