#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Retipea "
   #define STR0003  "Abandona"
   #define STR0004  "Par metros"
   #define STR0005  "Visualizar"
   #define STR0006  "Incluir"
   #define STR0007  "Autom tica"
   #define STR0008  "Creaci¢n de Cuentas"
   #define STR0009  " Creaci¢n de Cuentas Autom ticas "
   #define STR0010  "C¢digo                    Descripci¢n"
   #define STR0011  "&C¢digo : "
   #define STR0012  "&Descripci¢n:"
   #define STR0015  "¨Cu nto a la creaci¢n? "
   #define STR0016  "¨Est  seguro cuanto a la creaci¢n de cuentas?"
   #define STR0017  "Atenci¢n"
   #define STR0018  "Generando Autom ticamente las Cuentas..."
   #define STR0019  "Generaci¢n Autom tica"                        
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "O.K.   "
                #define STR0002  "Retype  "
                #define STR0003  "Quit    "
                #define STR0004  "Parameters"
                #define STR0005  "View       "
                #define STR0006  "Insert "
                #define STR0007  "Automatic "
                #define STR0008  "Generate of Accounts"
                #define STR0009  "Automatic Generate of Accounts "
                #define STR0010  "Code                        Descript."
                #define STR0011  "&Code   : "
                #define STR0012  "&Descript. : "
                #define STR0015  "About generating "
                #define STR0016  "Really want to generate Accounts?"
                #define STR0017  "Attention"
                #define STR0018  "Generating Accounts automatically"
                #define STR0019  "Automatic Generation"
	#ELSE
		#define STR0001  "Confirma"
		#define STR0002  "Redigita"
		#define STR0003  "Abandona"
		#define STR0004  "Parametros"
		#define STR0005  "Visualizar"
		#define STR0006  "Incluir"
		#define STR0007  "Autom tica"
		#define STR0008  "Cria‡„o de Contas"
		#define STR0009  " Cria‡„o de Contas Autom ticas "
		#define STR0010  "Codigo                      Descri‡„o"
		#define STR0011  "&C¢digo : "
		#define STR0012  "&Descri‡„o : "
		#define STR0015  "Quanto a cria‡„o ? "
		#define STR0016  "Tem certeza quanto a cria‡„o de contas?"
		#define STR0017  "Aten‡„o"
		#define STR0018  "Gerando Automaticamente as Contas..."
		#define STR0019  "Gera‡„o Autom tica"	
	#ENDIF
#ENDIF