#IFDEF SPANISH
   #define STR0001  "Consolidaci¢n de Empresas / Sucursales"
   #define STR0002  "Confirma"
   #define STR0003  "Retipea "
   #define STR0004  "Salir"
   #define STR0005  "Plan de Cuentas"
   #define STR0006  "Asientos Contables"
   #define STR0007  "Centros Costos"
   #define STR0008  " Este programa hace la Consolidaci¢n de Empresas/Sucursales"
   #define STR0009  "Archivos a Consolidar"
   #define STR0010  "Empresas a Consolidar"
   #define STR0011  ";;  Las informaciones contables relativas a las empresas/sucursales;"
   #define STR0012  "seleccionadas ser n aglomeradas y consolidadas en la empresa;"
   #define STR0013  "  Certifique  que  esta  es  la  empresa/sucursal  correcta,;"
   #define STR0014  "pu‚s los datos de las empresas/sucursales seleccionadas ser n;"
   #define STR0015  "agregados a ‚sta. Para modificar la empresa/sucursal destino,;"
   #define STR0016  "retorne al selector principal y pressione F6.            "
   #define STR0017  ";;S¢lo el Administrador del sistema tiene acceso;"
   #define STR0018  "a la rutina de consolidaci¢n contable"
   #define STR0019  "Aglomeraci¢n de datos"
   #define STR0020  "¨Cu nto a la consolidaci¢n?"
   #define STR0021  " no encontrado"
   #define STR0022  "Seleccionando Registros..."
   #define STR0023  "Confirma procesamiento en esta empresa"
   #define STR0024  "Atenci¢n"
	#define STR0025  "­­­ A  T  E  N  C  I  O N !!!"
	#define STR0026  "Es preferible que los archivos asociados"
	#define STR0027  "a esta rutina no est‚n  en uso por otras"
	#define STR0028  "estaciones.      "
	#define STR0029  "Haga con que los otros usuarios salgan   "
	#define STR0030  "del sistema. "
	#define STR0031  "Presione una tecla. "
	#define STR0032  "La opci¢n Limpia Consolidaci¢n borrar "
	#define STR0033  "TODOS los datos de la empresa: "
	#define STR0034  "¨Desea continuar?"
	#define STR0035  "­Los datos de la empresa abajo ser n borrados!"	
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "Consolidation of Companies/Branches"
                #define STR0002  "O.K.    "
                #define STR0003  "Retype  "
                #define STR0004  "Quit    "
                #define STR0005  "Accounts Plan  "
                #define STR0006  "Ledger Entries      "
                #define STR0007  "Cost Centers    "
                #define STR0008  "  This program does the Companies/Branches Consolidation"
                #define STR0009  "Files to Consolidate "
                #define STR0010  "Companies to Consolidate"
                #define STR0011  ";;  The accounting information connected to selected companies/"
                #define STR0012  "branches will be grouped and consolidated in this Company"
                #define STR0013  "  Make sure that this is the right company/branch,;    "
                #define STR0014  "since the data of companies/branches selected will be    "
                #define STR0015  "added to this one. To change the destiny company/branch,   "
                #define STR0016  "go back to the main selector and press F6.              "
                #define STR0017  ";;Only the Manager of the system has access; " 
                #define STR0018  "to the accounting consolidation routine")
                #define STR0019  "Data Grouping     "
                #define STR0020  "About Consolidation?    "
                #define STR0021  " not found    "
                #define STR0022  "Selecting Records...     "
                #define STR0023  "Confirm processing in this Company  "
                #define STR0024  "Attention"
		        #define STR0025  " A  T  T  E  N  T  I  O  N!"
                #define STR0026  "It is recomendable that tables refering"
                #define STR0027  "to this routine are not in usage by    "
                #define STR0028  "other Users.     "
                #define STR0029  "Put the other Users out of the System.   "
                #define STR0030  "         "
                #define STR0031  "Press any key.      "
		        #define STR0032  "The option Clear Consolidation will  "
		        #define STR0033  "delete ALL data of Company:"
		        #define STR0034  "Keep on or not?   "
		        #define STR0035  "Data of the Company bellow will be deleted!"		
	#ELSE
		#define STR0001  "Consolida‡„o de Empresas / Filiais"
		#define STR0002  "Confirma"
		#define STR0003  "Redigita"
		#define STR0004  "Abandona"
		#define STR0005  "Plano de Contas"
		#define STR0006  "Lan‡amentos cont beis"
		#define STR0007  "Centros de Custos"
		#define STR0008  "  Este programa faz Consolida‡„o de Empresas / Filiais"
		#define STR0009  "Arquivos a Consolidar"
		#define STR0010  "Empresas a Consolidar"
		#define STR0011  ";;  As informa‡“es cont beis relativas …s empresas/filiais;"
		#define STR0012  "selecionadas ser„o aglutinadas e consolidadas na empresa;"
		#define STR0013  "  Certifique-se  que  esta ‚ a  empresa/filial  correta,;"
		#define STR0014  "pois os dados das empresas/filiais selecionadas ser„o a-;"
		#define STR0015  "gregados a esta. Para alterar a empresa/filial  destino,;"
		#define STR0016  "retorne ao seletor principal e pressione F6.            "
		#define STR0017  ";;Apenas o Administrador do sistema tem acesso;"
		#define STR0018  "… rotina de consolida‡„o cont bil")
		#define STR0019  "Aglutina‡„o de dados"
		#define STR0020  "Quanto … consolida‡„o ? "
		#define STR0021  " n†o encontrado"
		#define STR0022  "Selecionando Registros..."
		#define STR0023  "Confirma Consolidacao nesta empresa?"
		#define STR0024  "Aten‡„o"	
		#define STR0025  " A  T  E  N  C  A  O !!!!! "
		#define STR0026  "E' melhor que os arquivos associados a "
		#define STR0027  "esta rotina  nao  estejam em  uso  por "
		#define STR0028  "outras esta‡”es. "
		#define STR0029  "Fa‡a com que os outros usu rios saiam do "
		#define STR0030  "sistema. "
		#define STR0031  "Pressione uma tecla."
		#define STR0032  "A opcao Limpa Consolidacao ira apagar"
		#define STR0033  " TODOS os dados da empresa: "
		#define STR0034  " Deseja prosseguir?"
		#define STR0035  "Os dados da empresa abaixo serao apagados!"
	#ENDIF
#ENDIF
