#IFDEF SPANISH
   #define STR0001  "Cierre de Saldos"
   #define STR0002  "Confirma"
   #define STR0003  "Retipea "
   #define STR0004  "Abandona"
   #define STR0005  "    El objetivo de este programa es ejecutar el movimiento del saldo fi-"
   #define STR0006  "nal del exerc¡cio para el saldo inicial del pr¢ximo ejerc¡cio.  Debe ser"
   #define STR0007  "ejecutado  despu‚s  del  cierre del ejerc¡cio.  Los saldos referentes al"
   #define STR0008  "ejerc¡cio  cerrado  ser n  transportados para el exerc¡cio que comienza."
   #define STR0009  "ejerc¡cio  cerrado  ser n  transportados para el exerc¡cio  que"
   #define STR0010  "comienza."
   #define STR0011  "Presione cualquier tecla para continuar..."
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "Closing Balances    "
                #define STR0002  "O.K.   "
                #define STR0003  "Retype  "
                #define STR0004  "Quit  "
                #define STR0005  "  This program has the purpose of executing the transactions from    " 
                #define STR0006  "ending balance of the period to the beginning balance of the"                       
                #define STR0007  "next period. It must be executed after the period is closed. The " 
                #define STR0008  "balances refering to the closed period, will be transported to   "
                #define STR0009  "the next period.          "
                #define STR0010  "      "
                #define STR0011  "Press any key to continue...        " 
	#ELSE
		#define STR0001  "Encerramento de Saldos"
		#define STR0002  "Confirma"
		#define STR0003  "Redigita"
		#define STR0004  "Abandona"
		#define STR0005  "  Este programa tem como objetivo executar  a  movimenta‡ao  do  saldo"
		#define STR0006  "final do exerc¡cio para o saldo inicial do pr¢ximo  exerc¡cio.  Dever "
		#define STR0007  "ser executado ap¢s o fechamento do exerc¡cio. Os saldos referentes  ao"
		#define STR0008  "exerc¡cio  encerrado  ser„o  transportados  para  o  exerc¡cio  a  ser iniciado."
		#define STR0009  "exerc¡cio  encerrado  ser„o  transportados  para  o  exerc¡cio  a  ser"
		#define STR0010  "iniciado."
		#define STR0011  "Pressione qualquer tecla para continuar..."	
	#ENDIF
#ENDIF	
