#IFDEF SPANISH
	#define STR0001  "C lculo de la Variaci¢n Monetaria"
	#define STR0002  "Confirma"
	#define STR0003  "Retipea"
	#define STR0004  "Abandona"
	#define STR0005  "  El objetivo del programa es calcular la diferencia cambial (Variaci¢n "
	#define STR0006  "Monetaria) de las monedas fuertes. Informe la tasa a usar en el c lculo:"
	#define STR0007  "     Media    : tasa simples entre cotizaciones diarias para el per¡odo "
	#define STR0008  "     Mensual  : tasa del £ltimo d¡a del per¡odo contable                "
	#define STR0009  "     Diaria   : tasa en el d¡a efectivo del asiento                     "
	#define STR0010  "     Informado: se debe informar la tasa que ser  usada                 "
	#define STR0011  "  C lculo de la Variaci¢n Monetaria"
	#define STR0012  "Presione cualquier tecla para continuar...                              "
	#define STR0013  "CRA"
        #define STR0014  "VARIACIàN MONETARIA "
	#define STR0015  "¨Confirma configuraci¢n de los par metros?"
	#define STR0016  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
                #define STR0001  "Monetary Variation Calculation"
                #define STR0002  "O.K.    "
                #define STR0003  "Retype  "
                #define STR0004  "Quit   "
                #define STR0005  "  The Program's purpose is to assess the exchange rate (Monetary Variance)"
                #define STR0006  "of strong currencies. Inform the rate to be used in calculation, being: "
                #define STR0007  "     Average  : the simple rate between the daily rates in the period.  "
                #define STR0008  "     Monthly  : the rate of the last day of the accounting period.      "
                #define STR0009  "     Daily    : the rate in the day of the effective ledger entry       "
                #define STR0010  "     Informed : the rate to be used must be informed                    "
                #define STR0011  "  Calculating Monetary Variance  "
                #define STR0012  "Press any key to continue...                                            "
		        #define STR0013  "CRA"
                #define STR0014  "MONETARY VARIANCE  "
                #define STR0015  "Confirm configuration of parameters?"
                #define STR0016  "Attention"
   #ELSE
		#define STR0001  "C lculo da Varia‡„o Monet ria"
		#define STR0002  "Confirma"
		#define STR0003  "Redigita"
		#define STR0004  "Abandona"
		#define STR0005  "     O programa objetiva apurar a diferen‡a cambial (Varia‡„o Monet ria)"
		#define STR0006  "das moedas fortes. Informe a taxa a ser utilizada para o c lculo, sendo:"
		#define STR0007  "     M‚dia    : a taxa simples entre as cota‡oes di rias do per¡odo.    "
		#define STR0008  "     Mensal   : a taxa do £ltimo dia do per¡odo cont bil.               "
		#define STR0009  "     Di ria   : a taxa no dia do efetivo lan‡amento cont bil            "
		#define STR0010  "     Informado: a taxa a ser utilizada dever  ser informada             "
		#define STR0011  "  Calculo da Variacao Monet ria  "
		#define STR0012  "Pressione qualquer tecla para continuar...                              "
		#define STR0013  "CRA"
		#define STR0014  "VARIACAO MONETARIA "
		#define STR0015  "Confirma configura‡„o dos parƒmetros?"
		#define STR0016  "Aten‡„o"
   #ENDIF
#ENDIF
