#IFDEF SPANISH
   #define STR0001  "Este programa imprimir  el Balance Anal¡tico Trimestral de     "
   #define STR0002  "acuerdo con los par metros solicitados por el usuario."
   #define STR0003  "­­ ATENCION !!  ­­ Informe el £ltimo d¡a del trimestre !!"
   #define STR0004  " "
   #define STR0005  "Administraci¢n"
   #define STR0006  "Hoja:     "
   #define STR0008  "Balance Anal¡tico y Sint‚tico en   "
   #define STR0009  "*                       *                                *                   *         MOVIMIENTOS DEL MES     *                   *"
   #define STR0010  "*  CODIGO DE LA CUENTA  *      D E S C R I P C I O N     *   SALDO ANTERIOR  *      DEBITO    *      CREDITO   *   SALDO ACTUAL    *"
   #define STR0011  "***** CANCELADO POR EL OPERADOR *****"
   #define STR0012  "T O T A L E S  DEL  M E S:"
   #define STR0013  "BALANCE ANALITICO TRIMESTRAL DE   "
   #define STR0014  " HASTA"
   #define STR0015  " EN "
   #define STR0016  "BALANCE SINTETICO TRIMESTRAL DE   "
   #define STR0017  " HASTA"
   #define STR0018  " EN "
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "This routine will print the Trimester Analitycal Trial Balance,"
                #define STR0002  "according to the parameters selected by the User.    "
                #define STR0003  "ATTENTION! Inform the last trimester's day!! "
                #define STR0004  "Z.Form "
                #define STR0005  "Management   "
                #define STR0006  "Sheet:    "
                #define STR0008  "Analytical/Synthetical Trial Balance"
                #define STR0009  "*                       *                                *                   *        MONTH'S TRANSACTION      *                   *"
                #define STR0010  "*  LEDGER ACCOUNT CODE  *     D E S C R I P T I O N      *   PRIOR BALANCE   *      DEBIT     *      CREDIT    *  CURRENT BALANCE  *"
                #define STR0011  "***** CANCELLED BY OPERATOR *****  "
                #define STR0012  "M O N T H 'S  T O T A L : "
                #define STR0013  "3 MONTH PERIOD ANALITYCAL T.BALANCE"
                #define STR0014  " TO  "
                #define STR0015  " IN "
                #define STR0016  "3 MONTH PERIOD SYNTHETICAL T.BALANCE"
                #define STR0017  " TO  "
                #define STR0018  " IN " 
	#ELSE
		#define STR0001  "Este programa ir  imprimir o Balancete Anal¡tico Trimestral em "
		#define STR0002  "de acordo com os parƒmetros solicitados pelo usu rio."
		#define STR0003  "ATENCAO!! Informe o ultimo dia do trimestre!!"
		#define STR0004  "Zebrado"
		#define STR0005  "Administracao"
		#define STR0006  "Folha:    "
		#define STR0008  "Balancete Analitico e Sintetico em "
		#define STR0009  "*                       *                                *                   *        MOVIMENTO DO MES         *                   *"
		#define STR0010  "*  CODIGO DA CONTA      *   D  E  S  C  R  I  C  A  O    *   SALDO ANTERIOR  *      DEBITO    *      CREDITO   *   SALDO ATUAL     *"
		#define STR0011  "***** CANCELADO PELO OPERADOR *****"
		#define STR0012  "T O T A I S  D O  M E S : "
		#define STR0013  "BALANCETE ANALITICO TRIMESTRAL DE "
		#define STR0014  " ATE "
		#define STR0015  " EM "
		#define STR0016  "BALANCETE SINTETICO TRIMESTRAL DE "
		#define STR0017  " ATE "
		#define STR0018  " EM "	
	#ENDIF
#ENDIF				
