#IFDEF SPANISH
	#define STR0001  "El objetivo de este programa es emitir los totales d¡a a d¡a"
	#define STR0002  "de los asientos efectuados, informando tambi‚n las diferen-"
   #define STR0003  "cias entre los valores tipeados e informados."
	#define STR0004  "  "
	#define STR0005  "Administraci¢n"
	#define STR0006  "Totales de los Asientos D¡a a D¡a"
	#define STR0007  "Fecha           Total D‚bito       Total Cr‚dito           Diferencia          Tipeado             Informado         Diferencia"
	#define STR0008  "***** CANCELADO POR EL OPERADOR *****"
	#define STR0009  "Totales"
	#define STR0010  "Lote: "
	#define STR0011  "Creando Archivo Temporario..."
   #define STR0012  "Informe Totales D¡a a D¡a "
	#define STR0013  "Seleccionando Registros..."
	#define STR0014  "Totales de los Pre-Asientos D¡a a D¡a"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "This program has the purpose of issuing the daily totals  "
         #define STR0002  "of the Accounting Entries posted, informing also the    "
         #define STR0003  "differences between values typed in and those informed."
         #define STR0004  "Z.Form "
         #define STR0005  "Management   "
         #define STR0006  "Daily Total Entries          "
         #define STR0007  "Date            Total Debit        Total Credit            Difference           Typed in            Informed           Difference"
         #define STR0008  "***** CANCELLED BY OPERATOR *****  "
         #define STR0009  "Totals"
         #define STR0010  "Lot : "
         #define STR0011  "Building Temporary File...   "
         #define STR0012  "Report on Daily Totals   "
         #define STR0013  "Selecting Records...   "
         #define STR0014  "Totals of Daily Pre-entries        "          
   #ELSE
         #define STR0001  "Este programa tem o objetivo de emitir os totais dia a dia"
         #define STR0002  "dos lan‡amentos cont beis efetuados, informando  tamb‚m as"
         #define STR0003  "diferen‡as entre os valores digitados e informados. "
         #define STR0004  "Zebrado"
         #define STR0005  "Administracao"
         #define STR0006  "Totais dos Lancamentos Dia a Dia"
         #define STR0007  "Data            Total Debito       Total Credito           Diferenca           Digitado            Informado          Diferenca"
         #define STR0008  "***** CANCELADO PELO OPERADOR *****"
         #define STR0009  "Totais"
         #define STR0010  "Lote: "
         #define STR0011  "Criando Arquivo Tempor rio..."
         #define STR0012  "Relat¢rio Totais Dia a Dia"
         #define STR0013  "Selecionando Registros..."
			#define STR0014  "Totais dos Pre-Lancamentos Dia a Dia"
	#ENDIF
#ENDIF
