#IFDEF SPANISH
	#define STR0001  "Este programa imprimir  el Mayor de la Contabilidad, de acuerdo"
	#define STR0002  "con los par metros solicitados por el usuario.  El informe ser "
	#define STR0003  "impreso en la moneda corriente y en otra elegida por el usuario."
	#define STR0004  " "
	#define STR0005  "Administraci¢n"
	#define STR0006  "Emisi¢n del Mayor en"
	#define STR0007  "***** CANCELADO POR EL OPERADOR *****"
	#define STR0008  "Mayor Anal¡tico (Totales) en Moneda Corriente y "
	#define STR0009  "Mayor Anal¡tico en Moneda Corriente y"
	#define STR0010  "|        |      |         |                                        |                             Valor                               |                     |                                                        |"
	#define STR0011  "| Fecha  | Doc. |C. Costo |Historial del Asiento                   |-----------------------------------------------------------------|---------------------|--------------------------------------------------------|"
	#define STR0012  "|        |      |         |                                        |               D‚bito|              Cr‚dito|         Saldo Actual|Per¡odo | Vlr Nominal|            D‚bito|           Cr‚dito|             Saldo|"
	#define STR0013  "|        |            |                             Valor                               |        UFIR         |             Cantidad en UFIR                           |"
	#define STR0014  "| Fecha  |            |-----------------------------------------------------------------|---------------------|--------------------------------------------------------|"
	#define STR0015  "|        |            |               D‚bito|              Cr‚dito|         Saldo Actual|Per¡odo | Vlr Nominal|            D‚bito|           Cr‚dito|             Saldo|"
	#define STR0016  " de "
	#define STR0017  " a "
	#define STR0018  "Saldo de Transporte"
	#define STR0019  "Saldo de Transporte ............................................."
	#define STR0020  "Relaci¢n de los Par metros del Informe"
	#define STR0021  "Hoja:    "
	#define STR0022  "Emisi¢n:"
	#define STR0023  "*Hora...: "
	#define STR0024  "Fch.Ref:"
	#define STR0025  "*Microsiga Software SA "
	#define STR0026  "Hora T‚rmino: "
	#define STR0027  "Seleccionando Registros..."
	#define STR0028  "Cuenta sin Movimiento en el Per¡odo"
	#define STR0029  "Cuenta: "
	#define STR0030  "Cantidad en "
	#define STR0031  "Ötem: "
#ELSE
   #IFDEF ENGLISH
		#define STR0001  "This routine will print the General Ledger, according to the"
		#define STR0002  "parameters requested by the User. The report will be printed"
		#define STR0003  "in Currency 1 and ohter Currency selected by the User.      "
		#define STR0004  "Z.Form "
		#define STR0005  "Management   "
		#define STR0006  "General Ledger's Issue"
		#define STR0007  "***** CANCELLED BY OPERATOR *****  "
		#define STR0008  "Analitycal G.Ledger (total) in current Currency"
		#define STR0009  "Analitycal G.Ledger current Currency"
		#define STR0010  "|        |      |         |                                        |                             Value                               |                     |                                                        |"
		#define STR0011  "|  Date  | Doc. |C. Center|Entry History                           |-----------------------------------------------------------------|---------------------|--------------------------------------------------------|"
		#define STR0012  "|        |      |         |                                        |               Debit |              Credit |        Current Balan| Period |Nominal Val.|            Debit |           Credit |           Balance|"
		#define STR0013  "|        |            |                             Valor                               |                     |                                                        |"
		#define STR0014  "|  Date  |            |-----------------------------------------------------------------|---------------------|--------------------------------------------------------|"
		#define STR0015  "|        |            |               Debit |              Credit |       Current Balanc|Period  |Nominal Val.|            Debit |           Credit |           Balance|"
		#define STR0016  "from"
		#define STR0017  " to"
		#define STR0018  "Balance to Transfer"
		#define STR0019  "Balance to Transfer ............................................."
		#define STR0020  "List of Report Parameters          "
		#define STR0021  "Sheet:    "
		#define STR0022  "Issue:  "
		#define STR0023  "*Hour...: "
		#define STR0024  "Ref.Dt.:"
		#define STR0025  "*Microsiga - Software S/A                              "
		#define STR0026  "Ending Hour:  "
		#define STR0027  "Selecting Records...     "
		#define STR0028  "Account w/no transact. in Period"
		#define STR0029  "Account:"
		#define STR0030  "Quantity in   "
		#define STR0031  "Item  : "
   #ELSE
		#define STR0001  "Este programa ira imprimir o Razao Contabil, de  acordo  com"
		#define STR0002  "os parametros solicitados pelo usuario. O Relatorio sera    "
		#define STR0003  "impresso em Real e outra Moeda escolhida pelo Usuario.      "
		#define STR0004  "Zebrado"
		#define STR0005  "Administracao"
		#define STR0006  "Emissao do Razao em "
		#define STR0007  "***** CANCELADO PELO OPERADOR *****"
		#define STR0008  "Razao Analitico (Totais) em Moeda Corrente e "
		#define STR0009  "Razao Analitico em Moeda Corrente e "
		#define STR0010  "|        |      |         |                                        |                             Valor                               |        UFIR         |             Quantidade em UFIR                         |"
		#define STR0011  "|  Data  | Doc. |C. Custo |Historico do Lancamento                 |-----------------------------------------------------------------|---------------------|--------------------------------------------------------|"
		#define STR0012  "|        |      |         |                                        |               Debito|              Credito|          Saldo Atual|Periodo | Vl. Nominal|            Debito|           Credito|             Saldo|"
		#define STR0013  "|        |            |                             Valor                               |        UFIR         |             Quantidade em UFIR                         |"
		#define STR0014  "|  Data  |            |-----------------------------------------------------------------|---------------------|--------------------------------------------------------|"
		#define STR0015  "|        |            |               Debito|              Credito|          Saldo Atual|Periodo | Vl. Nominal|            Debito|           Credito|             Saldo|"
		#define STR0016  " de "
		#define STR0017  " a "
		#define STR0018  "Saldo de Transporte"
		#define STR0019  "Saldo de Transporte ............................................."
		#define STR0020  "Relacao dos Parametros do Relatorio"
		#define STR0021  "Folha:    "
		#define STR0022  "Emissao:"
		#define STR0023  "*Hora...: "
		#define STR0024  "DT.Ref.:"
		#define STR0025  "*Microsiga Software SA "
		#define STR0026  "Hora Termino: "
		#define STR0027  "Selecionando Registros..."
		#define STR0028  "Conta sem Movimento no Periodo"
		#define STR0029  "Conta : "
		#define STR0030  "Quantidade em "
		#define STR0031  "Item  : "
   #ENDIF
#ENDIF