#IFDEF SPANISH
   #define STR0001  "Este programa imprimir  el Mayor de la Contabilidad en otra moneda, con-"
   #define STR0002  "forme los par metros solicitados por el usuario. Caso haya sido esco-"
   #define STR0003  "gida la impresi¢n del "
   #define STR0004  "  "
   #define STR0005  "Administraci¢n"
   #define STR0006  "Emisi¢n del Mayor en otras Monedas"
	#define STR0007  "FECHA      NéMERO         H I S T O R I A L                        CNT.PARTIDA                     DBITO      CRDITO  SALDO ACTUAL"	
   #define STR0008  "Enero"
   #define STR0009  "Febrero"
   #define STR0010  "Marzo"
   #define STR0011  "Abril"
   #define STR0012  "Mayo"
   #define STR0013  "Junio"
   #define STR0014  "Julio"
   #define STR0015  "Agosto"
   #define STR0016  "Septiembre"
   #define STR0017  "Octubre"
   #define STR0018  "Noviembre"
   #define STR0019  "Diciembre"
   #define STR0020  "***** CANCELADO POR EL OPERADOR *****"
   #define STR0021  "MAYOR  ANALÖTICO  DE "
   #define STR0022  " de "
   #define STR0023  " A "
   #define STR0024  " EN "
   #define STR0025  "A TRANSPORTAR : "
   #define STR0026  "CUENTA - "
   #define STR0027  "DE TRANSPORTE : "
   #define STR0028  "Totales  de  la  Cuenta  ======> "
   #define STR0029  "SALDO ANTERIOR : "
   #define STR0030  "Relaci¢n de los Par metros del Informe"
   #define STR0031  "Hoja:     "
   #define STR0032  "Fch.Ref:"
   #define STR0033  "*Hora...: "
   #define STR0034  "Emisi¢n:"
   #define STR0035  "*Microsiga Software S/A. "
   #define STR0036  "Hora T‚rmino: "
   #define STR0037  "Seleccionando Registros..."
	#define STR0038  ", el informe ser  comprimido."
	#define STR0039  "FECHA      NéMERO         H I S T O R I A L                       CNT PARTIDA     "
	#define STR0040  "  DBITO      CRDITO  SALDO ACTUAL"
	#define STR0041  "RAZAO  SINTETICO  DE "
#ELSE
   #IFDEF ENGLISH
      #define STR0001  "Este programa ir  imprimir o Raz„o  Cont bil  em  outra  moeda, de"
      #define STR0002  "acordo com os parƒmetros solicitados pelo usu rio. Caso seja esco-"
      #define STR0003  "lhida a impress„o do "
      #define STR0004  "Zebrado"
      #define STR0005  "Administracao"
      #define STR0006  "Emissao do Razao em outras Moedas"
	   #define STR0007  "DATA       NUMERO         H I S T O R I C O                        C/PARTIDA                       DEBITO      CREDITO   SALDO ATUAL "
      #define STR0008  "Janeiro"
      #define STR0009  "Fevereiro"
      #define STR0010  "Marco"
      #define STR0011  "Abril"
      #define STR0012  "Maio"
      #define STR0013  "Junho"
      #define STR0014  "Julho"
      #define STR0015  "Agosto"
      #define STR0016  "Setembro"
      #define STR0017  "Outubro"
      #define STR0018  "Novembro"
      #define STR0019  "Dezembro"
      #define STR0020  "***** CANCELADO PELO OPERADOR *****"
      #define STR0021  "RAZAO  ANALITICO  DE "
      #define STR0022  " de "
      #define STR0023  " A "
      #define STR0024  " EM "
      #define STR0025  "A TRANSPORTAR : "
      #define STR0026  "CONTA - "
      #define STR0027  "DE TRANSPORTE : "
      #define STR0028  "T o t a i s  d a  C o n t a  ==> "
      #define STR0029  "SALDO ANTERIOR : "
      #define STR0030  "Relacao dos Parametros do Relatorio"
      #define STR0031  "Folha:    "
      #define STR0032  "DT.Ref.:"
      #define STR0033  "*Hora...: "
      #define STR0034  "Emissao:"
      #define STR0035  "*Microsiga - Ass. Software e Com. de Computadores Ltda "
      #define STR0036  "Hora Termino: "
      #define STR0037  "Selecionando Registros..."
		#define STR0038  ", o relat¢rio ser  comprimido."
		#define STR0039  "DATA       NUMERO         H I S T O R I C O                        C/PARTIDA       "
		#define STR0040  "  DEBITO      CREDITO   SALDO ATUAL "
		#define STR0041  "RAZAO  SINTETICO  DE "
#ELSE
	#define STR0001  "Este programa ir  imprimir o Raz„o  Cont bil  em  outra  moeda, de"
	#define STR0002  "acordo com os parƒmetros solicitados pelo usu rio. Caso seja esco-"
	#define STR0003  "lhida a impress„o do "
	#define STR0004  "Zebrado"
	#define STR0005  "Administracao"
	#define STR0006  "Emissao do Razao em outras Moedas"
	#define STR0007  "DATA       NUMERO         H I S T O R I C O                        C/PARTIDA                       DEBITO      CREDITO   SALDO ATUAL "
	#define STR0008  "Janeiro"
	#define STR0009  "Fevereiro"
	#define STR0010  "Marco"
	#define STR0011  "Abril"
	#define STR0012  "Maio"
	#define STR0013  "Junho"
	#define STR0014  "Julho"
	#define STR0015  "Agosto"
	#define STR0016  "Setembro"
	#define STR0017  "Outubro"
	#define STR0018  "Novembro"
	#define STR0019  "Dezembro"
	#define STR0020  "***** CANCELADO PELO OPERADOR *****"
	#define STR0021  "RAZAO  ANALITICO  DE "
	#define STR0022  " de "
	#define STR0023  " A "
	#define STR0024  " EM "
	#define STR0025  "A TRANSPORTAR : "
	#define STR0026  "CONTA - "
	#define STR0027  "DE TRANSPORTE : "
	#define STR0028  "T o t a i s  d a  C o n t a  ==> "
	#define STR0029  "SALDO ANTERIOR : "
	#define STR0030  "Relacao dos Parametros do Relatorio"
	#define STR0031  "Folha:    "
	#define STR0032  "DT.Ref.:"
	#define STR0033  "*Hora...: "
	#define STR0034  "Emissao:"
	#define STR0035  "*Microsiga - Ass. Software e Com. de Computadores Ltda "
	#define STR0036  "Hora Termino: "
	#define STR0037  "Selecionando Registros..."
	#define STR0038  ", o relat¢rio ser  comprimido."
	#define STR0039  "DATA       NUMERO         H I S T O R I C O                        C/PARTIDA       "
	#define STR0040  "  DEBITO      CREDITO   SALDO ATUAL "
	#define STR0041  "RAZAO  SINTETICO  DE "
	#ENDIF
#ENDIF
