#IFDEF SPANISH
   #define STR0001  "Emisi¢n de la Relaci¢n de los Historiales"
   #define STR0002  "Ser† impreso de acuerdo con los par†metros solicitados por el"
   #define STR0003  "usuario."
   #define STR0004  "C¢digo"
   #define STR0005  "Descripci¢n"
   #define STR0006  " "
   #define STR0007  "Administraci¢n"
   #define STR0008  "Relaci¢n de Historiales Est†ndarizados"
   #define STR0009  "C‡DIGO   D E S C R I P C I ‡ N"
   #define STR0010  "***** CANCELADO POR EL OPERADOR *****"
   #define STR0011  "Historiales"
   #define STR0012  "Seleccionando Registros..."
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "Issue of the History Report.    "
                #define STR0002  "It will be printed according to parameters requested by the"
                #define STR0003  "User.   "
                #define STR0004  "Code "
                #define STR0005  "Descript."
                #define STR0006  "Z.Form "
                #define STR0007  "Management   "
                #define STR0008  "Report of Standardized Histories"
                #define STR0009  "CODE     D E S C R I P T ."
                #define STR0010  "***** CANCELLED BY OPERATOR *****  "
                #define STR0011  "Histories "
                #define STR0012  "Selecting Records...    " 
	#ELSE
		#define STR0001  "Emiss∆o da Relaá∆o de Hist¢ricos."
		#define STR0002  "Ser† impresso de acordo com os parÉmetros solicitados pelo"
		#define STR0003  "usu†rio."
		#define STR0004  "C¢digo"
		#define STR0005  "Descriá∆o"
		#define STR0006  "Zebrado"
		#define STR0007  "Administraá∆o"
		#define STR0008  "Relaá∆o de Hist¢ricos Padronizados"
		#define STR0009  "CODIGO   D E S C R I C A O"
		#define STR0010  "***** CANCELADO PELO OPERADOR *****"
		#define STR0011  "Hist¢ricos"
		#define STR0012  "Selecionando Registros..."	
	#ENDIF
#ENDIF