#IFDEF SPANISH
	#define STR0001  "Este programa ir† imprimir el Balancete Anal°tico y SintÇtico "
	#define STR0002  "en "
	#define STR0003  "de acuerdo con los par†metros solicitados por el usuario."
	#define STR0004  " "
	#define STR0005  "Administraci¢n"
   #define STR0007  "Balancete Anal°tico y SintÇtico en "
	#define STR0008  "*                       *                                *                   *        MOVIMENTO DEL MES        *                   *"
   #define STR0009  "*  C‡DIGO DE LA CUENTA  *      D E S C R I P C I ‡ N     *   SALDO ANTERIOR  *     DêBITO     *     CRêDITO    *   SALDO ATUAL     *"
	#define STR0010  "***** CANCELADO POR EL OPERADOR *****"
	#define STR0011  "T O T A L E S  D E L  M E S : "
   #define STR0012  "BALANCETE ANAL÷TICO DE "
	#define STR0013  " HASTA "
	#define STR0014  " EN "
   #define STR0015  "BALANCETE SINTêTICO DE "
	#define STR0018  " GRUPO SEM MOVIMENTOS NESTE PERIODO"		
#ELSE
   #IFDEF ENGLISH
		#define STR0001  "Este programa ir† imprimir o Balancete Anal°tico e SintÇtico "
		#define STR0002  "em "
		#define STR0003  "de acordo com os parÉmetros solicitados pelo usu†rio."
		#define STR0004  "Zebrado"
		#define STR0005  "Administracao"
		#define STR0007  "Balancete Analitico e Sintetico em "
		#define STR0008  "*                       *                                *                   *        MOVIMENTO DO MES         *                   *"
		#define STR0009  "*  CODIGO DA CONTA      *   D  E  S  C  R  I  C  A  O    *   SALDO ANTERIOR  *      DEBITO    *      CREDITO   *   SALDO ATUAL     *"
		#define STR0010  "***** CANCELADO PELO OPERADOR *****"
		#define STR0011  "T O T A I S  D O  M E S : "
		#define STR0012  "BALANCETE ANALITICO DE "
		#define STR0013  " ATE "
		#define STR0014  " EM "
		#define STR0015  "BALANCETE SINTETICO DE "
		#define STR0018  " GRUPO SEM MOVIMENTOS NESTE PERIODO"			
   #ELSE
		#define STR0001  "Este programa ir† imprimir o Balancete Anal°tico e SintÇtico "
		#define STR0002  "em "
		#define STR0003  "de acordo com os parÉmetros solicitados pelo usu†rio."
		#define STR0004  "Zebrado"
		#define STR0005  "Administracao"
		#define STR0007  "Balancete Analitico e Sintetico em "
		#define STR0008  "*                       *                                *                   *        MOVIMENTO DO MES         *                   *"
		#define STR0009  "*  CODIGO DA CONTA      *   D  E  S  C  R  I  C  A  O    *   SALDO ANTERIOR  *      DEBITO    *      CREDITO   *   SALDO ATUAL     *"
		#define STR0010  "***** CANCELADO PELO OPERADOR *****"
		#define STR0011  "T O T A I S  D O  M E S : "
		#define STR0012  "BALANCETE ANALITICO DE "
		#define STR0013  " ATE "
		#define STR0014  " EM "
		#define STR0015  "BALANCETE SINTETICO DE "
		#define STR0018  " GRUPO SEM MOVIMENTOS NESTE PERIODO"	
   #ENDIF
#ENDIF
