#IFDEF SPANISH
   #define STR0001  "Este informe imprimir  la relaci¢n de los Asientos,"
   #define STR0002  "almacenados en los archivos Contra Prueba."
   #define STR0003  "       "
   #define STR0004  "Administraci¢n"
   #define STR0005  "Relaci¢n de los Asientos ya Efectuados - Contra Prueba"
   #define STR0006  "Num Regs    TP Cuenta D‚bito   Cuenta Cr‚dito  Fch Venc   Origen                                                Historial                                           Valor"
   #define STR0007  "***** CANCELADO POR EL OPERADOR *****"
   #define STR0008  "No abri¢ el archivo CPROVA"
   #define STR0009  "TOTAL DEL DOCUMENTO: "
   #define STR0010  "Seleccionando Registros..."
	#define STR0011  "Relaci¢n de Asientos a£n no efectuados - Contra Prueba"
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "This report prints the report of the Accounting     "
                #define STR0002  "Entries from in the Counter Proof files.      "
                #define STR0003  "Z.Form "
                #define STR0004  "Management   "
                #define STR0005  "Report of the Entries already posted-Counter Proof "
                #define STR0006  "Entry Num   KD Debit Account   Credit Account  Due Date Origin          History                                             Value"
                #define STR0007  "***** CANCELLED BY OPERATOR   *****"
                #define STR0008  "Couldn't open Counter Proof"
                #define STR0009  "DOCUMENT TOTAL:      "
                #define STR0010  "Selecting Records...    " 
                #define STR0011  "Report of Entries still not Posted  - Counter Proof"            
	#ELSE
		#define STR0001  "Este relat¢rio ir  imprimir a rela‡Æo dos Lan‡amentos"
		#define STR0002  "Cont beis, contidos nos arquivos Contra Prova."
		#define STR0003  "Zebrado"
		#define STR0004  "Administra‡Æo"
		#define STR0005  "Rela‡Æo dos Lancamentos ja Efetuados - Contra Prova"
		#define STR0006  "Num Lanc    TP Conta D‚bito    Conta Cr‚dito   Dta Venc   Origem                                                Hist¢rico                                           Valor"
		#define STR0007  "***** CANCELADO PELO OPERADOR *****"
		#define STR0008  "NÆo conseguiu abrir CPROVA"
		#define STR0009  "TOTAL DO DOCUMENTO : "
		#define STR0010  "Selecionando Registros..."	
		#define STR0011  "Relacao de Lancamentos Ainda Nao Efetuados - Contra Prova"	
	#ENDIF
#ENDIF
