#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Retipea"
   #define STR0003  "Abandona"
   #define STR0004  "Reconciliaci¢n de Saldos Bancarios"
   #define STR0005  "  El  objetivo de este programa es recalcular y analisar el saldo Bancario "
   #define STR0006  "diario  de un determinado per¡odo hasta la fecha del sistema. Usado en el  "
   #define STR0007  "caso de necesidad de retroceder el movimiento bancario. Use como referencia"
   #define STR0008  "la fecha en que el saldo qued¢ defasado.                                   "
   #define STR0009  "      El  objetivo  de  este  programa  es  recalcular los saldos"
   #define STR0010  "Bancarios diarios de un determinado per¡odo hasta la fecha de hoy"
   #define STR0011  "del sistema. Usado en el caso de necesidad de retroceder el movi-"
   #define STR0012  "miento  bancario.  Use  como  referencia la fecha en que el saldo"
   #define STR0013  "qued¢ defasado.   " 
   #define STR0014  "Seleccionando Registros..."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "O.K."
         #define STR0002  "Retype"
         #define STR0003  "Cancel "
         #define STR0004  "Reconciliation of Bank Balances"
         #define STR0005  "This program's objective is to recalculate and analyse daily Bank "
         #define STR0006  "from one specific period until the system's base date . Used  "
         #define STR0007  "when is necessary to retroacting the bank transactions. Use as "
         #define STR0008  "reference the date in which the balance is outdated.                       "
         #define STR0009  "      The purpose of this program is to recalculate daily"
         #define STR0010  "Bank balances of a specific period until the System's"
         #define STR0011  "base date. Used when required  to retroact bank transaction"
         #define STR0012  "Use as a reference the date  in which the balance"
         #define STR0013  "became out of date.Press any key to continue ."
         #define STR0014  "Selecting Records..."
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Reconcilia‡„o de Saldos Banc rios"
         #define STR0005  "  Este programa tem como objetivo recalcular e analisar os saldos Banc rios "
         #define STR0006  "dia a dia de um determinado per¡odo at‚ a data base do sistema.  Utilizando "
         #define STR0007  "no caso de haver necessidade de retroagir a movimenta‡„o banc ria. Use como "
         #define STR0008  "referˆncia a data em que o saldo fico defasado.                             "
         #define STR0009  "      O  objetivo  deste  programa ‚ o de recalcular os saldos"
         #define STR0010  "Banc rios  dia a dia  de um  determinado periodo at‚ a data ba-"
         #define STR0011  "se do sistema. Utilizado no caso de haver necessidade de retroa-"
         #define STR0012  "gir a movimenta‡„o banc ria. Use como referˆncia a data em que"
         #define STR0013  "o saldo ficou defasado. Pressione qualquer tecla para continuar."
         #define STR0014  "Selecionando Registros..."
   #ENDIF
#ENDIF
