#IFDEF SPANISH
      #define STR0001  "bUscar    "
      #define STR0002  "Border¢"
      #define STR0003  "Cancelar"
      #define STR0004  "SisPag"
      #define STR0005  "Border¢ de Pagos"
      #define STR0006  "Confirma"
      #define STR0007  "Retipea"
      #define STR0008  "Abandona"
      #define STR0009  "Seleccionando Registros..."
      #define STR0010  "   Contrato"
      #define STR0011  "Moneda"
      #define STR0012  "Modelo "
      #define STR0013  "Tipo Pago"
      #define STR0014  "Border¢s de Pagos"
      #define STR0015  "N£mero"
      #define STR0016  "Vencto de"
      #define STR0017  "Hasta"
      #define STR0018  "L¡mite Valor"
      #define STR0019  "Banco"    
      #define STR0020  "Agencia"
      #define STR0021  "Cuenta"
      #define STR0022  "Contrato"
      #define STR0023  "Moneda"
      #define STR0024  "Modelo"
      #define STR0025  "Tipo Pago"
      #define STR0026  "Marca Todos"
      #define STR0027  "Remueve  Marcas"
      #define STR0028  "Marca/Desmarca Ötems"
      #define STR0029  "Seleccionando Registros..."
      #define STR0030  "Valor Total:"
      #define STR0031  "Cantidad:"
      #define STR0032  "¨Cu nto al Border¢?"
      #define STR0033  "  Esta opci¢n genera el Archivo de Comunicaci¢n Bancaria SisPag"
      #define STR0034  "para el Border¢ de Pagos. Se debe infomar el N§ del Border¢ que"
      #define STR0035  "se quiere enviar,  el Nombre del Archivo de Configuraci¢n (CNAB"
      #define STR0036  "SisPag) y el Nombre del Archivo que ser  generado."
      #define STR0037  "Presione cualquier tecla para continuar..."
      #define STR0038  "Generaci¢n Archivo SisPag"
      #define STR0039  "Pagos        "
      #define STR0040  " Ötem a Localizar "
      #define STR0041  "Actualizando"
#ELSE
   #IFDEF ENGLISH
      #define STR0001  "Pesquisar"
      #define STR0002  "Bordero"
      #define STR0003  "Cancelar"
      #define STR0004  "SisPag"
      #define STR0005  "Border“ de Pagamentos"
      #define STR0006  "Confirma"
      #define STR0007  "Redigita"
      #define STR0008  "Abandona"
      #define STR0009  "Selecionando Registros..."
      #define STR0010  "   Contrato"
      #define STR0011  "Moeda"
      #define STR0012  "Modelo "
      #define STR0013  "Tipo Pagto"
      #define STR0014  "Border“s de Pagamentos"
      #define STR0015  "N£mero"
      #define STR0016  "Vencto de"
      #define STR0017  "At‚"
      #define STR0018  "Limite Valor"
      #define STR0019  "Banco"    
      #define STR0020  "Agˆncia"
      #define STR0021  "Conta"
      #define STR0022  "Contrato"
      #define STR0023  "Moeda"
      #define STR0024  "Modelo"
      #define STR0025  "Tipo Pagto"
      #define STR0026  "Marca Todos"
      #define STR0027  "Remove  Marcas"
      #define STR0028  "Marca/Desmarca Itens"
      #define STR0029  "Selecionando Registros..."
      #define STR0030  "Valor Total:"
      #define STR0031  "Quantidade:"
      #define STR0032  "Quanto ao Bordero ?"
      #define STR0033  "   Esta op‡„o gera o Arquivo de  Comunica‡„o Banc ria  SisPag"
      #define STR0034  "para o  Border“ de Pagamentos. Dever  ser  informado o  N§ do"
      #define STR0035  "Border“ que se quer enviar, o Nome do Arquivo de Configura‡„o"
      #define STR0036  "(CNAB SisPag) e o Nome do Arquivo a ser Gerado."
      #define STR0037  "Pressione qualquer tecla para continuar..."
      #define STR0038  "Gera‡„o Arquivo SisPag"
      #define STR0039  "Pagamentos   "
      #define STR0040  " Item a Localizar "
      #define STR0041  "Atualizando"
  #ELSE
      #define STR0001  "Pesquisar"
      #define STR0002  "Bordero"
      #define STR0003  "Cancelar"
      #define STR0004  "SisPag"
      #define STR0005  "Border“ de Pagamentos"
      #define STR0006  "Confirma"
      #define STR0007  "Redigita"
      #define STR0008  "Abandona"
      #define STR0009  "Selecionando Registros..."
      #define STR0010  "   Contrato"
      #define STR0011  "Moeda"
      #define STR0012  "Modelo "
      #define STR0013  "Tipo Pagto"
      #define STR0014  "Border“s de Pagamentos"
      #define STR0015  "N£mero"
      #define STR0016  "Vencto de"
      #define STR0017  "At‚"
      #define STR0018  "Limite Valor"
      #define STR0019  "Banco"    ,
      #define STR0020  "Agˆncia"
      #define STR0021  "Conta"
      #define STR0022  "Contrato"
      #define STR0023  "Moeda"
      #define STR0024  "Modelo"
      #define STR0025  "Tipo Pagto"
      #define STR0026  "arca Todos"
      #define STR0027  "emove  Marcas"
      #define STR0028  "Marca/Desmarca Itens"
      #define STR0029  "Selecionando Registros..."
      #define STR0030  "Valor Total:"
      #define STR0031  "Quantidade:"
      #define STR0032  "Quanto ao Bordero ?"
      #define STR0033  "   Esta op‡„o gera o Arquivo de  Comunica‡„o Banc ria  SisPag"
      #define STR0034  "para o  Border“ de Pagamentos. Dever  ser  informado o  N§ do"
      #define STR0035  "Border“ que se quer enviar, o Nome do Arquivo de Configura‡„o"
      #define STR0036  "(CNAB SisPag) e o Nome do Arquivo a ser Gerado."
      #define STR0037  "Pressione qualquer tecla para continuar..."
      #define STR0038  "Gera‡„o Arquivo SisPag"
      #define STR0039  "Pagamentos   "
      #define STR0040  " Item a Localizar "
      #define STR0041  "Atualizando"
	#ENDIF
#ENDIF
	
