#IFDEF SPANISH
   #define STR0001  "bUscar    "
   #define STR0002  "Visualizar"
   #define STR0003  "Border¢"
   #define STR0004  "Border¢ de Dep¢sito de Cheques"
   #define STR0005  "Confirma"
   #define STR0006  "Retipea"
   #define STR0007  "Abandona"
   #define STR0008  "Border¢ de Dep¢sitos"
   #define STR0009  "Border¢ N§"
   #define STR0010  "Vencimiento"
   #define STR0011  "a la"
   #define STR0012  "L¡mite"
   #define STR0013  "Banco "
   #define STR0014  "Agencia"
   #define STR0015  "Cuenta"
   #define STR0016  "Cheques Para Dep¢sito"
   #define STR0017  "Valor Total:"
   #define STR0018  "Cantidad:"
   #define STR0019  "¨Imprime Informe? "
   #define STR0020  " Atenci¢n"
   #define STR0021  "Relaci¢n de Border¢ de Cheques"
   #define STR0022  "Banco Agencia Cta. Corriente TP    N£mero del Cheque           Valor"
   #define STR0023  "Este informe imprimir  la relaci¢n de los cheques marcados que"
   #define STR0024  "ser n depositados. "
   #define STR0025  ""
   #define STR0026  "Administraci¢n"
   #define STR0027  "Total de Cheques "
   #define STR0028  "Total General del Border¢ "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search"
         #define STR0002  "View"
         #define STR0003  "Border."
         #define STR0004  "Cheque Dep.Slip Border."
         #define STR0005  "O.K."
         #define STR0006  "Retype"
         #define STR0007  "Cancel "
         #define STR0008  "Deposit Bordereaux"
         #define STR0009  "Border. Nr"
         #define STR0010  "Due Date"
         #define STR0011  "to"
         #define STR0012  "Limit"
         #define STR0013  "Bank"
         #define STR0014  "Agency"
         #define STR0015  "Accnt"
         #define STR0016  "Cheques for Deposit"
         #define STR0017  "Total Value:"
         #define STR0018  "Quantity:"
         #define STR0019  "Print Report ? "
         #define STR0020  "Attention"
         #define STR0021  "List of Cheques Bordereaux"
         #define STR0022  "Bank Agency Currenct Account TP  Cheque Number              Value"
         #define STR0023  "This report will print the list of selected cheques to be      "
         #define STR0024  "deposited.       "
         #define STR0025  "C.Form"
         #define STR0026  "Management"
         #define STR0027  "Total N.of Cheques"
         #define STR0028  "Gen.Total of Bordereau "  
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Visualizar"
         #define STR0003  "Bordero"
         #define STR0004  "Bordero de Dep¢sito de Cheques"
         #define STR0005  "Confirma"
         #define STR0006  "Redigita"
         #define STR0007  "Abandona"
         #define STR0008  "Border“ de Dep¢sitos"
         #define STR0009  "Border“ N§"
         #define STR0010  "Vencimento"
         #define STR0011  "…"
         #define STR0012  "Limite"
         #define STR0013  "Banco "
         #define STR0014  "Agˆncia"
         #define STR0015  "Conta"
         #define STR0016  "Cheques Para Dep¢sito"
         #define STR0017  "Valor Total:"
         #define STR0018  "Quantidade:"
         #define STR0019  "Imprime Relat¢rio ? "
         #define STR0020  " Aten‡„o"
         #define STR0021  "Relacao de Bordero de Cheques"
         #define STR0022  "Banco Agencia Conta Corrente TP  Numero do Cheque              Valor"
         #define STR0023  "Este relatorio ira imprimir a relacao dos cheques marcados para"
         #define STR0024  "serem depositados. "
         #define STR0025  "Zebrado"
         #define STR0026  "Administracao"
         #define STR0027  "Total de Cheques "
         #define STR0028  "Total Geral do Bordero "
   #ENDIF
#ENDIF
