#IFDEF SPANISH
   #define STR0001  "Par metros"
   #define STR0002  "Visualizar"
   #define STR0003  "Recibir Archivo"
   #define STR0004  "Abandona"
   #define STR0005  "Confirma"
   #define STR0006  "Comunica.Bancaria Retorno"
   #define STR0007  "Comun.Bancaria Retorno"
   #define STR0008  "¨Cu nto a la recepci¢n? "
   #define STR0009  "Seleccionando Registros..."
   #define STR0010  "Valor recibido sobre T¡tulo"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Parameters"
         #define STR0002  "View"
         #define STR0003  "Receive File"
         #define STR0004  "Cancel "
         #define STR0005  "O.K."
         #define STR0006  "Bank Commumnication-Reply"
         #define STR0007  "Bank Communic.-Reply"
         #define STR0008  " About Receiption ? "
         #define STR0009  "Selecting Records..."
         #define STR0010  "Value Received o/ Bill"
   #ELSE
         #define STR0001  "Parametros"
         #define STR0002  "Visualizar"
         #define STR0003  "Receber Arquivo"
         #define STR0004  "Abandona"
         #define STR0005  "Confirma"
         #define STR0006  "Comunica‡„o Banc ria-Retorno"
         #define STR0007  "Comun.Banc ria-Retorno"
         #define STR0008  "  Quanto   recep‡„o ? "
         #define STR0009  "Selecionando Registros..."
         #define STR0010  "Valor recebido s/ Titulo"
   #ENDIF
#ENDIF
