#IFDEF SPANISH
   #define STR0001  "Contabiliza Correcci¢n Monetaria"
   #define STR0002  "   El objetivo de este programa es calcular la diferencia entre la fecha"
   #define STR0003  "de emisi¢n y la fecha de hoy de los t¡tulos en abierto en moneda fuerte."
   #define STR0004  "La diferencia ser  registrada en la contabilidad (Variaci¢n Monetaria)."
   #define STR0005  "Confirma"
   #define STR0006  "Retipea"
   #define STR0007  "Abandona"
   #define STR0008  "El objetivo de este programa es calcular la diferencia entre la fecha de "
   #define STR0009  "emisi¢n y la fecha de hoy de los t¡tulos en abierto en moneda fuerte.    "
   #define STR0010  "La diferencia ser  registrada en la contabilidad (Variaci¢n Monetaria).  "
   #define STR0011  "Presione cualquier tecla para continuar."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Accounting of Monetary Adjustm."
         #define STR0002  "    The purpose of this program consists in calculating the difference"
         #define STR0003  "between the date of issue and the base date of the open bills in main  "
         #define STR0004  "currency. The difference will be entered in the Ledger(Monetary Variation)."
         #define STR0005  "O.K."
         #define STR0006  "Retype"
         #define STR0007  "Cancel "
         #define STR0008  "The purpose of this program consists in calculating the diference between"
         #define STR0009  "the date of issue and the base date of the bill maturing in mains  currency"
         #define STR0010  "The difference will  be entered in the Ledger(Monetary Variation)"
         #define STR0011  "Press any key to continue."
   #ELSE
         #define STR0001  "Contabiliza Corre‡„o monet ria"
         #define STR0002  "    O objetivo deste programa consiste em efetuar a  apura‡„o  da diferen‡a"
         #define STR0003  "entre a data de emiss„o e data base dos t¡tulos em aberto em moeda forte. A"
         #define STR0004  "diferen‡a ser  lan‡ada na contabilidade (Varia‡„o Monet ria)."
         #define STR0005  "Confirma"
         #define STR0006  "Redigita"
         #define STR0007  "Abandona"
         #define STR0008  "O objetivo deste programa consiste em efetuar a  apura‡„o  da diferen‡a"
         #define STR0009  "entre a data de emiss„o e data base dos t¡tulos em aberto em moeda for-"
         #define STR0010  "te. A diferen‡a ser  lan‡ada na contabilidade (Varia‡„o Monet ria)."
         #define STR0011  "Pressione qualquer tecla para continuar."
   #ENDIF
#ENDIF
