#IFDEF SPANISH
   #define STR0001  "Abandona"
   #define STR0002  "Confirma"
   #define STR0003  "Par metros"
   #define STR0004  "Emitir Archivo"
   #define STR0005  "Emisi¢n Archivo Env¡o"
   #define STR0006  "  ¨Cu nto a la Emisi¢n? "
   #define STR0007  "Seleccionando Registros..."
   #define STR0008  "Border¢ Existente"
   #define STR0009  "El border¢ n£mero:"
   #define STR0010  "ya fue enviado al banco."
   #define STR0011  "Para continuar elija una de las opciones"
   #define STR0012  "Emite con ese border¢"
   #define STR0013  "Ignora ese border¢"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Cancel "
         #define STR0002  "O.K."
         #define STR0003  "Parameters"
         #define STR0004  "Generate File"
         #define STR0005  "Generate Send File   "
         #define STR0006  "About Generation ? "
         #define STR0007  "Selecting Records..."
         #define STR0008  "Bordereau Exists  "
         #define STR0009  "Bordereau Number:"
         #define STR0010  "was sent already to bank"
         #define STR0011  "To continue choose one option"
         #define STR0012  "Gen. with this Bordereau"
         #define STR0013  "Ignore this Bordereau"
   #ELSE
         #define STR0001  "Abandona"
         #define STR0002  "Confirma"
         #define STR0003  "Parametros"
         #define STR0004  "Gerar Arquivo"
         #define STR0005  "Gera‡„o Arquivo Envio"
         #define STR0006  "  Quanto … Gera‡„o ? "
         #define STR0007  "Selecionando Registros..."
         #define STR0008  "Bordero Existente"
         #define STR0009  "O border“ n£mero:"
         #define STR0010  "j  foi enviado ao banco."
         #define STR0011  "Para prosseguir escolha uma das op‡äes"
         #define STR0012  "Gera com esse border“"
         #define STR0013  "Ignora esse border“"
   #ENDIF
#ENDIF
