#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Retipea"
   #define STR0003  "Abandona"
   #define STR0004  "     El objetivo de este programa es el de generar Asientos"
   #define STR0005  "Contables off para t¡tulos emitidos y/o cierres efectuados "
   #define STR0006  "en un determinado per¡odo."
   #define STR0007  "Presione cualquier tecla para continuar"
   #define STR0008  "¨Cu nto al Procesamiento?"
   #define STR0009  "Contabilizaci¢n Off-Line"
   #define STR0010  "  El objetivo de este programa es generar Asientos Contable Off para t¡tulos"
   #define STR0011  "emitidos y/o cierres efectuados."
   #define STR0012  "Localizar"
   #define STR0013  "Pagar"
   #define STR0014  "Recibir"
   #define STR0015  "Borrar "
   #define STR0016  "Transferir"
   #define STR0017  "Clasificar"
   #define STR0018  "Seleccionando Registros..."
   #define STR0019  "Contabilizaci¢n"
   #define STR0020  "     Fue encontrado un Registro en el archivo SE5 que no tiene corres-"
   #define STR0021  "pondiente en los archivos de Cobranzas. Usted puede parar ahora la    "
   #define STR0022  "contabilizaci¢n o continuar aun as¡.                    "
   #define STR0023  "Obs.: El procedimiento de rehacer acumulados ajusta el archivo SE5.   "
   #define STR0024  "Archivo : "
   #define STR0025  "Datos del T¡tulo: "
   #define STR0026  "Continua"
   #define STR0027  "     Fue  encontrado un Registro en el archivo SE5 que no tiene corres-"
   #define STR0028  "pondientes en los archivos de Cobranzas o a Pagar. Usted puede parar  "
   #define STR0029  "ahora la contabilizaci¢n o continuar aun as¡.      "
   #define STR0030  "Obs.: El procedimiento de rehacer acumulados ajusta el archivo SE5.   "
   #define STR0031  "¨Cu nto a la Contabilizaci¢n?"
 #ELSE	
   #IFDEF ENGLISH
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "     O objetivo deste programa ‚ o de gerar Lan‡amentos"
         #define STR0005  "Cont beis off para t¡tulos emitidos e/ou baixas efetuadas"
         #define STR0006  "em um determinado periodo."
         #define STR0007  "Pressione qualquer tecla para continuar"
         #define STR0008  "Quanto ao Processamento ?"
         #define STR0009  "Contabiliza‡„o Off Line"
         #define STR0010  "  Este programa tem como objetivo gerar Lan‡amentos Cont beis Off para t¡tulos"
         #define STR0011  "emitidos e/ou baixas efetuadas."
         #define STR0012  "Localizar"
         #define STR0013  "Pagar"
         #define STR0014  "Receber"
         #define STR0015  "Excluir"
         #define STR0016  "Transferir"
         #define STR0017  "Classificar"
         #define STR0018  "Selecionando Registros..."
         #define STR0019  "Contabiliza‡„o"
         #define STR0020  "     Foi encontrado  um  Registro no arquivo SE5 que n„o possui "
         #define STR0021  "correspondˆncia nos arquivos de Contas a Receber ou Pagar. Vocˆ "
         #define STR0022  "pode parar agora a contabiliza‡„o ou continuar assim mesmo.     "
         #define STR0023  "Obs.: A rotina de refaz acumulados ajusta o arquivo SE5.        "
         #define STR0024  "Arquivo : "
         #define STR0025  "Dados do Titulo: "
         #define STR0026  "Continua"
         #define STR0027  "     Foi encontrado um Registro no arquivo SE5 que n„o possui  "
         #define STR0028  "correspondˆncia nos arquivos de Contas a Receber ou Pagar. Vocˆ"
         #define STR0029  "pode parar agora a contabiliza‡„o ou continuar assim mesmo.    "
         #define STR0030  "Obs.: A rotina de refaz acumulados ajusta o arquivo SE5.       "
         #define STR0031  "Quanto a Contabiliza‡„o ?"
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "     O objetivo deste programa ‚ o de gerar Lan‡amentos"
         #define STR0005  "Cont beis off para t¡tulos emitidos e/ou baixas efetuadas"
         #define STR0006  "em um determinado periodo."
         #define STR0007  "Pressione qualquer tecla para continuar"
         #define STR0008  "Quanto ao Processamento ?"
         #define STR0009  "Contabiliza‡„o Off Line"
         #define STR0010  "  Este programa tem como objetivo gerar Lan‡amentos Cont beis Off para t¡tulos"
         #define STR0011  "emitidos e/ou baixas efetuadas."
         #define STR0012  "Localizar"
         #define STR0013  "Pagar"
         #define STR0014  "Receber"
         #define STR0015  "Excluir"
         #define STR0016  "Transferir"
         #define STR0017  "Classificar"
         #define STR0018  "Selecionando Registros..."
         #define STR0019  "Contabiliza‡„o"
         #define STR0020  "     Foi encontrado  um  Registro no arquivo SE5 que n„o possui "
         #define STR0021  "correspondˆncia nos arquivos de Contas a Receber ou Pagar. Vocˆ "
         #define STR0022  "pode parar agora a contabiliza‡„o ou continuar assim mesmo.     "
         #define STR0023  "Obs.: A rotina de refaz acumulados ajusta o arquivo SE5.        "
         #define STR0024  "Arquivo : "
         #define STR0025  "Dados do Titulo: "
         #define STR0026  "Continua"
         #define STR0027  "     Foi encontrado um Registro no arquivo SE5 que n„o possui  "
         #define STR0028  "correspondˆncia nos arquivos de Contas a Receber ou Pagar. Vocˆ"
         #define STR0029  "pode parar agora a contabiliza‡„o ou continuar assim mesmo.    "
         #define STR0030  "Obs.: A rotina de refaz acumulados ajusta o arquivo SE5.       "
         #define STR0031  "Quanto a Contabiliza‡„o ?"
   #ENDIF
#ENDIF
