#IFDEF SPANISH
   #define STR0001  "Abandona"
   #define STR0002  "Confirma"
   #define STR0003  "Par metros"
   #define STR0004  "Generar Archivo"
   #define STR0005  "Comunicaci¢n Bancaria-Env¡o"
   #define STR0006  "Comun.Bancaria-Env¡o"
   #define STR0007  "  ¨Cu nto a la Generaci¢n? "
   #define STR0008  "Seleccionando Registros..."
   #define STR0009  "Border¢ Existente"
   #define STR0010  "El border¢ n£mero:"
   #define STR0011  "ya fue enviado al banco."
   #define STR0012  "Para continuar elija una de las opciones"
   #define STR0013  "Genera con ese border¢"
   #define STR0014  "Ignora ese border¢"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Cancel "
         #define STR0002  "O.K."
         #define STR0003  "Parameters"
         #define STR0004  "Generate File"
         #define STR0005  "Bank Commun.-Delivery"
         #define STR0006  "Bank Commun.-Delivery"
         #define STR0007  "  About Generation ? "
         #define STR0008  "Selecting Records..."
         #define STR0009  "Bordereau Exists  "
         #define STR0010  "Bordereau Number:"
         #define STR0011  "Already sent to bank"
         #define STR0012  "To continue, choose one option"
         #define STR0013  "Generate w/this bord."
         #define STR0014  "Ignore this Border."
   #ELSE
         #define STR0001  "Abandona"
         #define STR0002  "Confirma"
         #define STR0003  "Parƒmetros"
         #define STR0004  "Gerar Arquivo"
         #define STR0005  "Comunica‡„o Banc ria-Envio"
         #define STR0006  "Comun.Banc ria-Envio"
         #define STR0007  "  Quanto   Gera‡„o ? "
         #define STR0008  "Selecionando Registros..."
         #define STR0009  "Bordero Existente"
         #define STR0010  "O border“ n£mero:"
         #define STR0011  "j  foi enviado ao banco."
         #define STR0012  "Para prosseguir escolha uma das op‡äes"
         #define STR0013  "Gera com esse border“"
         #define STR0014  "Ignora esse border“"
   #ENDIF
#ENDIF
