#IFDEF SPANISH
   #define STR0001  "Par metros"
   #define STR0002  "Visualizar"
   #define STR0003  "Reconciliaci¢n"
   #define STR0004  "Salir   "
   #define STR0005  "Confirma"
   #define STR0006  "Reconciliaci¢n Bancaria Autom tica"
   #define STR0007  "Seleccionando Registros..."
   #define STR0008  "  ¨Cu nto a la Recepci¢n? "
   #define STR0009  "Seleccionando Registros..."
   #define STR0010  "Sec."
   #define STR0011  "Fecha"
   #define STR0012  "Docto.Bco."
   #define STR0013  "Valor Extracto"
   #define STR0014  "Tipo"
   #define STR0015  "D/C"
   #define STR0016  "Docto.SE5"
   #define STR0017  "Valor SE5"
   #define STR0019  "Leyenda"
   #define STR0020  "Secuencia a Reconciliar"
   #define STR0021  "Este movimiento ya est  reconciliado         "
   #define STR0022  "             ¨Desea cancelar?                "
   #define STR0023  "  Reconciliado"
   #define STR0024  "  Reconc. Parcial"
   #define STR0025  "  No Reconciliado"
   #define STR0026  "Leyenda - Reconciliaci¢n Autom tica"
   #define STR0027  "Efectivaci¢n de Registros en el SE5"
   #define STR0028  "Hay registros semejantes en Fecha, Valor y Cartera. En "
   #define STR0029  "su archivo de movimientos bancarios.  En caso de duda, "
   #define STR0030  "no efectivo el registro, pues podr  generar duplicidad."
   #define STR0031  "¨Desea hacer efectivo este registro?"
   #define STR0032  "Modalidad del Registro"
   #define STR0033  "¨Confirma Efectivaci¢n?"
   #define STR0034  "Atenci¢n"
   #define STR0035  "  Reconciliado Anteriormente"
   #define STR0036  "Efectiva Regist."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Parƒmetros"
         #define STR0002  "Visualizar"
         #define STR0003  "Reconcilia‡„o"
         #define STR0004  "Abandona"
         #define STR0005  "Confirma"
         #define STR0006  "Reconcilia‡„o Banc ria Autom tica"
         #define STR0007  "Selecionando Registros..."
         #define STR0008  "  Quanto   recep‡„o ? "
         #define STR0009  "Selecionando Registros..."
         #define STR0010  "Seq."
         #define STR0011  "Data"
         #define STR0012  "Docto.Bco."
         #define STR0013  "Valor Extrato"
         #define STR0014  "Tipo"
         #define STR0015  "D/C"
         #define STR0016  "Docto.SE5"
         #define STR0017  "Valor SE5"
         #define STR0019  "Legenda"
         #define STR0020  "Sequˆncia a Reconciliar"
         #define STR0021  "Esta movimenta‡„o j  se encontra reconciliada"
         #define STR0022  "             Deseja cancelar ?               "
         #define STR0023  "  Reconciliado"
         #define STR0024  "  Reconc. Parcial"
         #define STR0025  "  N„o Reconciliado"
         #define STR0026  "Legenda - Reconcilia‡„o Autom tica"
         #define STR0027  "Efetiva‡„o de Lan‡amento no SE5"
         #define STR0028  "Existe lan‡amento semelhante em Data, Valor e Carteira."
         #define STR0029  "no seu arquivo de movimentos banc rios. Em caso de     "
         #define STR0030  "d£vida, n„o efetive o lan‡amento, pois poder  gerar    "
         #define STR0031  "duplicidade. Deseja efetivar este lan‡amento ?   "
         #define STR0032  "Natureza do Lan‡amento"
         #define STR0033  "Confirma Efetiva‡„o ?"
         #define STR0034  "Aten‡„o"
         #define STR0035  "  Reconciliado Anteriormente"
         #define STR0036  "Efetiva Lancto."
   #ELSE
         #define STR0001  "Parƒmetros"
         #define STR0002  "Visualizar"
         #define STR0003  "Reconcilia‡„o"
         #define STR0004  "Abandona"
         #define STR0005  "Confirma"
         #define STR0006  "Reconcilia‡„o Banc ria Autom tica"
         #define STR0007  "Selecionando Registros..."
         #define STR0008  "  Quanto   recep‡„o ? "
         #define STR0009  "Selecionando Registros..."
         #define STR0010  "Seq."
         #define STR0011  "Data"
         #define STR0012  "Docto.Bco."
         #define STR0013  "Valor Extrato"
         #define STR0014  "Tipo"
         #define STR0015  "D/C"
         #define STR0016  "Docto.SE5"
         #define STR0017  "Valor SE5"
         #define STR0019  "Legenda"
         #define STR0020  "Sequˆncia a Reconciliar"
         #define STR0021  "Esta movimenta‡„o j  se encontra reconciliada"
         #define STR0022  "             Deseja cancelar ?               "
         #define STR0023  "  Reconciliado"
         #define STR0024  "  Reconc. Parcial"
         #define STR0025  "  N„o Reconciliado"
         #define STR0026  "Legenda - Reconcilia‡„o Autom tica"
         #define STR0027  "Efetiva‡„o de Lan‡amento no SE5"
         #define STR0028  "Existe lan‡amento semelhante em Data, Valor e Carteira."
         #define STR0029  "no seu arquivo de movimentos banc rios. Em caso de     "
         #define STR0030  "d£vida, n„o efetive o lan‡amento, pois poder  gerar    "
         #define STR0031  "duplicidade. Deseja efetivar este lan‡amento ?   "
         #define STR0032  "Natureza do Lan‡amento"
         #define STR0033  "Confirma Efetiva‡„o ?"
         #define STR0034  "Aten‡„o"
         #define STR0035  "  Reconciliado Anteriormente"
         #define STR0036  "Efetiva Lancto."
   #ENDIF
#ENDIF