#IFDEF SPANISH 
   #define STR0001  "PAGO DE T÷TULOS POR LOTE "
   #define STR0002  "Descuento sobre Recib.T°tulo"
   #define STR0003  "Intereses sobre Recib.T°tulo"
   #define STR0004  "Multa sobre Recib.T°tulo"
   #define STR0005  "Correcci¢n Monet sin Receb.T°tulo"
   #define STR0006  "Valor recibido sin T°tulo"
   #define STR0007  "Toler Recib. sin T°tulo"
   #define STR0008  "Devoluci¢n de Anticipo"
   #define STR0009  "Descuento sobre Pago de T°tulo"
   #define STR0010  "MODALIDAD PRêSTAMOS"
   #define STR0011  "MODALIDAD INVERSIONES"
   #define STR0015  "Compens. Anticipo"
   #define STR0016  "Pago por Compensaci¢n"
   #define STR0017  "MODALIDAD PAGO DE PRêSTAMOS"
   #define STR0018  "MODALIDAD RESCATE INVERSIONES"
#ELSE
   #IFDEF ENGLISH
     #define STR0001  "BILL WRITE-OFF PER LOT  "
     #define STR0002  "Discount on Bill Receipt"
     #define STR0003  "Interest on Bill Rec"
     #define STR0004  "Fine on Bill Receipt"
     #define STR0005  "Price Level Adj over Received Bill"
     #define STR0006  "Amount received over Bill"
     #define STR0007  "Toler Receiv over Bill"
     #define STR0008  "Devolution of Advance Paym"
     #define STR0009  "Discount over Bill Paid   "
     #define STR0010  "LOAN CLASS          "
     #define STR0011  "INVESTMENT CLASS    "
     #define STR0015  "Compens. Advance Paym"
     #define STR0016  "Write-off per Compens"
     #define STR0017  "CLASS PAYMENT LOANS        "
     #define STR0018  "CLASS REDEMPTION INVESTMENTS "
   #ELSE
     #define STR0001  "BAIXA DE TITULOS P/LOTE "
     #define STR0002  "Desconto s/Receb.Titulo"
     #define STR0003  "Juros s/Receb.Titulo"
     #define STR0004  "Multa s/Receb.Titulo"
     #define STR0005  "Correcao Monet s/Receb.Titulo"
     #define STR0006  "Valor recebido s/ titulo"
     #define STR0007  "Toler Receb. s/ Titulo"
     #define STR0008  "Devolucao de Adiantamento"
     #define STR0009  "Desconto sobre T°tulo Pago "
     #define STR0010  "NATUREZA EMPRESTIMOS"
     #define STR0011  "NATUREZA APLICACOES"
     #define STR0015  "Compens. Adiantamento"
     #define STR0016  "Baixa por Compensacao"
     #define STR0017  "NATUREZA PAGTO. EMPRESTIMOS"
     #define STR0018  "NATUREZA RESGATE APLICACOES"
   #ENDIF
#ENDIF
