#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Retipea"
   #define STR0003  "Salir"
   #define STR0004  "B&uscar"
   #define STR0005  "Visualizar"
   #define STR0006  "Incluir"
   #define STR0007  "Modificar"
   #define STR0008  "Borrar"
   #define STR0009  "Archivo de Conceptos"
   #define STR0010  "Salir"
   #define STR0011  "Seleccionando Registros..."
   #define STR0012  "¨Cu nto al Borrar?"
   #define STR0013  "Esta funci¢n verifica la existencia del concepto"
   #define STR0014  "que  ser  borrado,  en los diversos archivos del"
   #define STR0015  "m¢dulo. ­­  La verificaci¢n puede demorar !!"
   #define STR0016  "¨Confirma borrar el concepto?          "
   #define STR0017  "Atenci¢n"
   #define STR0018  "El concepto que ser  borrado se encuentra en"
   #define STR0019  "el archivo "
   #define STR0020  "="
   #define STR0021  "."
   #define STR0022  "Hasta que las referencias a este concepto  "
   #define STR0023  "sean eliminadas, ‚l no podr  ser borrado.  "
   #define STR0024  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
           #define STR0001  "O.K.    "
           #define STR0002  "Retype  "
           #define STR0003  "Quit    "
           #define STR0004  "Search   "
           #define STR0005  "View      "
           #define STR0006  "Insert "
           #define STR0007  "Edit   "
           #define STR0008  "Delete "
           #define STR0009  "Register of Funds "
           #define STR0010  "Quit    "
           #define STR0011  "Selecting Records ......."
           #define STR0012  "About Deleting   ?"
           #define STR0013  "This routine checks the existence of the Fund  "
           #define STR0014  "to be deleted, in the various files of the    "
           #define STR0015  "module. The checking can take time!!      "
           #define STR0016  "Confirm deletion of the Fund ?            "
           #define STR0017  "Attention"
           #define STR0018  "The Fund to be deleted is present in   "
           #define STR0019  "the file"
	   #define STR0020  "="
   	#define STR0021  "."
           #define STR0022  "Until the references to this fund are    "
           #define STR0023  "removed, it cannot be deleted.            "
           #define STR0024  "Attention"
   #ELSE
	   #define STR0001  "Confirma"
	   #define STR0002  "Redigita"
	   #define STR0003  "Abandona"
	   #define STR0004  "Pesquisar"
	   #define STR0005  "Visualizar"
	   #define STR0006  "Incluir"
	   #define STR0007  "Alterar"
	   #define STR0008  "Excluir"
	   #define STR0009  "Cadastro de Verbas"
	   #define STR0010  "Abandona"
	   #define STR0011  "Selecionando Registros..."
	   #define STR0012  "Quanto … exclus„o?"
	   #define STR0013  "Esta  rotina  verifica  a  existˆncia da  verba"
	   #define STR0014  "a  ser  excluida,  nos  diversos  arquivos  do"
	   #define STR0015  "m¢dulo. A verifica‡„o pode ser demorada !!"
	   #define STR0016  "Confirma a exclus„o da verba ?            "
	   #define STR0017  "Aten‡„o"
	   #define STR0018  "A verba a ser excluida est  presente no"
	   #define STR0019  "arquivo "
	   #define STR0020  "="
	   #define STR0021  "."
	   #define STR0022  "At‚ que as referˆncias a esta verba sejam"
	   #define STR0023  "eliminadas, a mesma n„o pode ser excluida."
	   #define STR0024  "Aten‡„o"
   #ENDIF
#ENDIF