#IFDEF SPANISH
         #define STR0001  "Confirma"
         #define STR0002  "Retipea "
         #define STR0003  "Salir   "
         #define STR0004  "Contabilidad de la Liquidaci¢n"
         #define STR0005  "Par metros"
         #define STR0006  "Autom tica"
         #define STR0007  "Contabilidad de la Liquidaci¢n"
         #define STR0008  "Este programa contabilizar  los asientos de la liquidaci¢n para"
         #define STR0009  "el Dpto de Contabilidad, leyendo el archivo (SRZ). Se debe usar"
         #define STR0010  "despu‚s de la emisi¢n de la liquidaci¢n, GRPS y provisiones."
         #define STR0011  "Contabilizaci¢n de la Liquidaci¢n"
         #define STR0012  "Contabilizaci¢n de la Liquidaci¢n         "
         #define STR0013  "Este programa contabilizar  los asientos de la liquidaci¢n para   "
         #define STR0014  "el Dpto. de Contabilidad leyendo el archivo (SRZ). Se debe usar   "
         #define STR0015  "despu‚s de la emisi¢n de la liquidaci¢n, de la G.R.P.S, provi-    "
         #define STR0016  "si¢n de vacaciones y de aguinaldo.                                "
         #define STR0017  "Presione cualquer tecla para continuar ..."
         #define STR0018  "Procesando la Contabilizaci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "O.K.    "
         #define STR0002  "Retype  "
         #define STR0003  "Quit    "
         #define STR0004  "Payroll Accounting    "
         #define STR0005  "Parameters"
         #define STR0006  "Automatic "
         #define STR0007  "Payroll Accounting     "
         #define STR0008  "This program will account the payroll entries to Accounting, by  "
         #define STR0009  "reading the file (SRZ). It must be used after the       "
         #define STR0010  "the issuance of payrolls, GPRS and Revenues.     "
         #define STR0011  "Payroll Accoounting    "
         #define STR0012  "Payroll Accounting                         "
         #define STR0013  "This program will account the payroll entries to Accounting, by  "
         #define STR0014  "for accounting reading file  (SRZ). It must be used after  the"
         #define STR0015  "issuance of payroll, the issuance of GRPS and revenues from      "
         #define STR0016  "Vacation and 13th Salary. "
         #define STR0017  "Press any key to continue.................."
         #define STR0018  "Processing the Accounting   "
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Contabiliza‡„o da Folha"
         #define STR0005  "Parƒmetros"
         #define STR0006  "Autom tica"
         #define STR0007  "Contabiliza‡„o da Folha"
         #define STR0008  "Este programa contabilizar  os lan‡amentos da folha de pagamento "
         #define STR0009  "para a contabilidade lendo o arquivo (SRZ) . Dever  ser utilizado"
         #define STR0010  "apos as emissäes da folha, GRPS e provisäes."
         #define STR0011  "Contabiliza‡„o da Folha"
         #define STR0012  "Contabiliza‡„o da Folha                   "
         #define STR0013  "Este programa contabilizar  os lan‡amentos da folha de pagamento  "
         #define STR0014  "para contabilidade lendo arquivo (SRZ). Dever  ser utilizado apos "
         #define STR0015  "a emiss„o da folha de pagamento, a emiss„o da G.R.P.S e provis”es "
         #define STR0016  "de f‚rias e 13§ Salario."
         #define STR0017  "Pressione qualquer tecla para continuar ..."
         #define STR0018  "Processando a Contabiliza‡„o"
   #ENDIF
#ENDIF