#IFDEF SPANISH
         #define STR0001  "Generaci¢n PIS para Cr‚dito en la Liquidaci¢n"
         #define STR0002  "Este programa har  los pagos de abonos y remuneraciones a los empleados"
         #define STR0003  "que participan del PIS, a trav‚s del cr‚dito en la liquidaci¢n."
         #define STR0004  "Generaci¢n PIS para cr‚dito en la liquidaci¢n"
         #define STR0005  "Confirma"
         #define STR0006  "Retipea "
         #define STR0007  "Salir   "
         #define STR0008  "Generaci¢n PIS para Cr‚dito en la Liquidaci¢n"
         #define STR0009  "Este programa har  los pagos de abono y remuneraci¢n a los empleados"
         #define STR0010  "que participan del PIS, a trav‚s del cr‚dito en la liquidaci¢n."
         #define STR0011  "Confirma"
         #define STR0012  "Retipea "
         #define STR0013  "Salir   "
         #define STR0014  "Importando Archivo del PIS"
         #define STR0015  "Importando Archivo del PIS"
         #define STR0016  "Generando Cr‚dito del PIS"
         #define STR0017  "Seleccionando Registros..."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Gener.Soc.Int.Pr. for Credit in Payroll"
         #define STR0002  "This routine will carry out payments of premiums and revenues to   "
         #define STR0003  "employees, integrating the Soc.Int.Pr. through credit in payroll   "
         #define STR0004  "Gener.of Soc.Int.Pr. for credit in payroll"
         #define STR0005  "O.K.    "
         #define STR0006  "Retype  "
         #define STR0007  "Quit    "
         #define STR0008  "Gener.Soc.Int.Pr.for credit in Payroll"
         #define STR0009  "This program carries out payments of premiums and revenues to the  "
         #define STR0010  "employees integrating the Soc.Int.Pr. through the credit in Payroll."
         #define STR0011  "O.K.    "
         #define STR0012  "Retype  "
         #define STR0013  "Quit    "
         #define STR0014  "Importing Soc.Int.Pr.file"
         #define STR0015  "Importing Soc.Int.Pr.file"
         #define STR0016  "Generat.Soc.Int.Pr.credit" 
         #define STR0017  "Selecting Records...     "
   #ELSE
         #define STR0001  "Gera‡„o PIS para Cr‚dito em Folha"
         #define STR0002  "Este programa ira efetuar os pagamentos do abono e rendimentos aos "
         #define STR0003  "funcion rios participantes do PIS, atrav‚s do cr‚dito em folha.    "
         #define STR0004  "Gera‡„o PIS para cr‚dito em folha"
         #define STR0005  "Confirma"
         #define STR0006  "Redigita"
         #define STR0007  "Abandona"
         #define STR0008  "Gera‡„o PIS para Cr‚dito em Folha "
         #define STR0009  "Este programa ira efetuar os pagamentos do abono e rendimentos aos "
         #define STR0010  "funcion rios participantes do PIS, atrav‚s do cr‚dito em folha.    "
         #define STR0011  "Confirma"
         #define STR0012  "Redigita"
         #define STR0013  "Abandona"
         #define STR0014  "Importando Arquivo do PIS"
         #define STR0015  "Importando Arquivo do PIS"
         #define STR0016  "Gerando Credito do PIS"
         #define STR0017  "Selecionando Registros..."
   #ENDIF
#ENDIF