#IFDEF SPANISH
         #define STR0001  "C lculo del Anticipo de Sueldo    "
         #define STR0002  "Este programa calcula el anticipo de sueldo   "
         #define STR0003  "Confirma"
         #define STR0004  "Retipea "
         #define STR0005  "Salir   "
         #define STR0006  "Confirma"
         #define STR0007  "Salir   "
         #define STR0008  "C lculo del Anticipo de Sueldo     "
         #define STR0009  "Este programa calcula el anticipo de sueldo   "
         #define STR0010  "Sucursal  : "
         #define STR0011  "Matr¡cula : "
         #define STR0012  "Nombre    : "
         #define STR0013  "¨Confirma la configuraci¢n de los par metros?"
         #define STR0014  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Salary Advance Payment Calculation"
         #define STR0002  "This will calculate the Salary Advance Payment."
         #define STR0003  "O.K.    "
         #define STR0004  "Retype  "
         #define STR0005  "Quit    "
         #define STR0006  "O.K.    "
         #define STR0007  "Quit    "
         #define STR0008  "Salary Advance Payment Calculation "
         #define STR0009  "This will calculate the Salary Advance Payment."
         #define STR0010  "Branch    : "
         #define STR0011  "Registrat.: "
         #define STR0012  "Name      : "
         #define STR0013  "Confirm the Parameter setup?         "
         #define STR0014  "Attention"
   #ELSE
         #define STR0001  "Calculo do Adiantamento de Sal rio"
         #define STR0002  "Este programa calcula adiantamento de salario "
         #define STR0003  "Confirma"
         #define STR0004  "Redigita"
         #define STR0005  "Abandona"
         #define STR0006  "Confirma"
         #define STR0007  "Abandona"
         #define STR0008  "Calculo do Adiantamento de Salario "
         #define STR0009  "Este programa calcula adiantamento de salario "
         #define STR0010  "Filial    : "
         #define STR0011  "Matricula : "
         #define STR0012  "Nome      : "
         #define STR0013  "Confirma configura‡„o dos parƒmetros?"
         #define STR0014  "Aten‡„o"
   #ENDIF
#ENDIF