#IFDEF SPANISH
         #define STR0001  "Instrucci¢n Normativa 65 "
         #define STR0002  "Este programa genera los archivos de la Instrucci¢n Normativa 65."
         #define STR0003  "Ser n generados conforme la selecci¢n de par metros del usuario."
         #define STR0004  "Instrucci¢n Normativa 65"
         #define STR0005  "Confirma"
         #define STR0006  "Retipea "
         #define STR0007  "Salir   "
         #define STR0008  "Instrucci¢n Normativa 65 "
         #define STR0009  "Este programa genera los archivos de la Instrucci¢n Normativa 65. "
         #define STR0010  "Ser n generados conforme la selecci¢n de par metros del usuario."
         #define STR0011  "Generando Instrucci¢n Normativa 65"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Normative Instruction 65"
         #define STR0002  "This will generate the Normative Instruction 65 Files.   "
         #define STR0003  "It will be generated according to parameters selected by the user "
         #define STR0004  "Normative Instruction 65"
         #define STR0005  "O.K     "
         #define STR0006  "Retype  "
         #define STR0007  "Quit    "
         #define STR0008  "Normative Instruction 65"
         #define STR0009  "This will generate the Normative Instruction 65 files.            "
         #define STR0010  "It will be generated according to parameters selected by the User."
         #define STR0011  "Generating Normative Instr.65"
   #ELSE
         #define STR0001  "Instru‡„o Normativa 65 "
         #define STR0002  "Este programa gera os arquivos da Instru‡„o Normativa 65."
         #define STR0003  "Sera gerado de acordo com os parametros selecionados pelo usuario."
         #define STR0004  "Instru‡„o Normativa 65"
         #define STR0005  "Confirma"
         #define STR0006  "Redigita"
         #define STR0007  "Abandona"
         #define STR0008  "Instru‡„o Normativa 65  "
         #define STR0009  "Este programa gera os arquivos da Instru‡„o Normativa 65.         "
         #define STR0010  "Ser  gerado de acordo com os parametros selecionados pelo usuario."
         #define STR0011  "Gerando Instru‡„o Normativa 65"
   #ENDIF
#ENDIF