#IFDEF SPANISH
         #define STR0001  "Cierre Anual     "
         #define STR0002  " ATENCION:  Los datos de los empleados despedidos hasta la fecha "
         #define STR0003  " ser n borrados f¡sicamente de los archivos, es necesario que se "
         #define STR0004  " haga una copia de seguridad antes de ejecutar esta opci¢n.      "
         #define STR0005  "Cierre Anual "
         #define STR0006  "Confirma"
         #define STR0007  "Retipea "
         #define STR0008  "Salir   "
         #define STR0009  "Cierre Anual             "
         #define STR0010  " ATENCION:  Los datos de los empleados despedidos hasta la fecha  "
         #define STR0011  " ser n borrados f¡sicamente de los archivos, es necesario que se  "
         #define STR0012  " haga una copia de seguridad antes de ejecutar esta opci¢n.       "
         #define STR0013  " Presione cualquier tecla para continuar ...                      "
         #define STR0014  " ARCHIVO SIENDO PROCESADO -->"
         #define STR0015  "Cierre Anual    "
         #define STR0016  "Cierre Anual    "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Yearly Closing   "
         #define STR0002  " ATTENT.: The data referring to employees dismissed until the current "
         #define STR0003  " date will be removed from the files, it is necessary to make a       "
         #define STR0004  " security copy before executing this option.                          "
         #define STR0005  "Yearly Closing   "
         #define STR0006  "O.K.     "
         #define STR0007  "Retype   "
         #define STR0008  "Quit    "
         #define STR0009  "Yearly Closing           "
         #define STR0010  " ATTENT.: The data referring to employees dismissed up to the present "
         #define STR0011  " date will be physically excluded from the files, it is necessary to  "
         #define STR0012  " make a security copy before executing this option.                   "
         #define STR0013  " Press any key to continue...                                         "
         #define STR0014  " FILE BEING PROCESSED     -->"
         #define STR0015  "Yearly Closing  "
         #define STR0016  "Yearly Closing  "
   #ELSE
         #define STR0001  "Fechamento Anual "
         #define STR0002  " ATEN€ŽO: Os dados referentes aos funcion rios demitidos at‚ esta data"
         #define STR0003  " ser„o excluidos fisicamente dos arquivos, ‚ necessario que seja feita"
         #define STR0004  " uma copia de seguran‡a antes de executar esta op‡„o.                 "
         #define STR0005  "Fechamento Anual "
         #define STR0006  "Confirma"
         #define STR0007  "Redigita"
         #define STR0008  "Abandona"
         #define STR0009  "Fechamento Anual         "
         #define STR0010  " ATEN€ŽO: Os dados referentes aos funcion rios demitidos at‚ esta data"
         #define STR0011  " ser„o excluidos fisicamente dos arquivos, ‚ necessario que seja feita"
         #define STR0012  " uma copia de seguran‡a antes de executar esta op‡„o.                 "
         #define STR0013  " Pressione qualquer tecla para continuar ...                          "
         #define STR0014  " ARQUIVO SENDO PROCESSADO -->"
         #define STR0015  "Fechamento Anual"
         #define STR0016  "Fechamento Anual"
   #ENDIF
#ENDIF