#IFDEF SPANISH
         #define STR0001  "Generaci¢n de Conceptos"
         #define STR0002  "Este programa genera los conceptos durante el movimiento mensual."
         #define STR0003  "Ser  procesado de acuerdo con los par metros seleccionados"
         #define STR0004  "por el usuario."
         #define STR0005  "Generando Conceptos"
         #define STR0006  "Confirma"
         #define STR0007  "Retipea "
         #define STR0008  "Salir   "
         #define STR0009  "Generando Conceptos          "
         #define STR0010  "Este programa genera conceptosdurante el movimiento mensual.          "
         #define STR0011  "Ser  procesado conforme la selecci¢n de par metros del usuario.       "
         #define STR0012  "B&uscar  "
         #define STR0013  "Visualizar"
         #define STR0014  "Incluir"
         #define STR0015  "Modificar"
         #define STR0016  "Borrar "
         #define STR0017  " Horas "
         #define STR0018  " Valor "
         #define STR0019  "Porcentaje"
         #define STR0020  " D¡as"
         #define STR0021  "Faja  De  "
         #define STR0022  "Faja Hasta"
         #define STR0023  "M¡nimo"
         #define STR0024  "M ximo"
         #define STR0025  "   Informe las Fajas    "
         #define STR0026  "Informe las Fajas"
         #define STR0027  "Generando Conceptos"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Fund Generation     "
         #define STR0002  "This will generate Funds in a Monthly Traansaction."
         #define STR0003  "Will be processed, according to parameters selected"
         #define STR0004  "by the User. "
         #define STR0005  "Generat Funds"
         #define STR0006  "O.K.    "
         #define STR0007  "Retype  "
         #define STR0008  "Quit    "
         #define STR0009  "Generating Funds             "
         #define STR0010  "This will generate Funds in the Montly Transactions.                  "
         #define STR0011  "It will be processed according to parameters selected by the user.    "
         #define STR0012  "Search   "
         #define STR0013  "View      "
         #define STR0014  "Insert "
         #define STR0015  "Edit   "
         #define STR0016  "Delete "
         #define STR0017  " Hours "
         #define STR0018  " Amount"
         #define STR0019  "Percentage"
         #define STR0020  " Days"
         #define STR0021  "Range of"
         #define STR0022  "Range until"
         #define STR0023  "Minim."
         #define STR0024  "Maxim."
         #define STR0025  "   Inform the Ranges    "
         #define STR0026  "Inform the Ranges"
         #define STR0027  "Generation of Funds"
   #ELSE
         #define STR0001  "Gera‡„o de Verbas "
         #define STR0002  "Este programa gera verbas no movimento mensal."
         #define STR0003  "Ser  processado de acordo com parƒmetros selecionados"
         #define STR0004  "pelo usuario."
         #define STR0005  "Gerando Verba"
         #define STR0006  "Confirma"
         #define STR0007  "Redigita"
         #define STR0008  "Abandona"
         #define STR0009  "Gera‡„o de Verbas            "
         #define STR0010  "Este programa gera verbas no movimento mensal.                        "
         #define STR0011  "Ser  processado de acordo com os parametros selecionados pelo us£ario."
         #define STR0012  "Pesquisar"
         #define STR0013  "Visualizar"
         #define STR0014  "Incluir"
         #define STR0015  "Alterar"
         #define STR0016  "Excluir"
         #define STR0017  " Horas "
         #define STR0018  " Valor "
         #define STR0019  "Percentual"
         #define STR0020  " Dias"
         #define STR0021  "Faixa De"
         #define STR0022  "Faixa Ate"
         #define STR0023  "Minimo"
         #define STR0024  "Maximo"
         #define STR0025  "   Informe as Faixas    "
         #define STR0026  "Informe as Faixas"
         #define STR0027  "Gera‡„o de Verbas"
   #ENDIF
#ENDIF