#IFDEF SPANISH
         #define STR0001  "C lculo de la Liquidaci¢n    " 
         #define STR0002  "Este programa calcula la liquidaci¢n     "
         #define STR0003  "Confirma"
         #define STR0004  "Retipea "
         #define STR0005  "Salir   "
         #define STR0006  "Contin£a"
         #define STR0007  "Salir   "
         #define STR0008  "C lculo de la Liquidaci¢n     "
         #define STR0009  "Este programa calcula la liquidaci¢n      "
         #define STR0010  "C lculo de la Liquidaci¢n      "
         #define STR0011  "Este programa calcula la liquidaci¢n      "
         #define STR0012  "Sucursal  : "
         #define STR0013  "Matr¡cula : "
         #define STR0014  "Nombre    : "
         #define STR0015  "¨Confirma la configuraci¢n de los par metros?"
         #define STR0016  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Payroll Calculation          "
         #define STR0002  "This program will calculate the Payroll "
         #define STR0003  "O.K.    "
         #define STR0004  "Retype  "
         #define STR0005  "Quit    "
         #define STR0006  "Continue"
         #define STR0007  "Quit    "
         #define STR0008  "Payroll Calculation          "
         #define STR0009  "This program calculates payroll          "
         #define STR0010  "Payroll Calculation            "
         #define STR0011  "This will calculate the Payroll          "
         #define STR0012  "Branch           : "
         #define STR0013  "Registrat.: "
         #define STR0014  "Name      : "
         #define STR0015  "Confirm configuration of parameters ?"
         #define STR0016  "Attention"
   #ELSE
         #define STR0001  "Calculo da Folha de Pagamento"
         #define STR0002  "Este programa calcula folha de pagamento"
         #define STR0003  "Confirma"
         #define STR0004  "Redigita"
         #define STR0005  "Abandona"
         #define STR0006  "Continua"
         #define STR0007  "Abandona"
         #define STR0008  "Calculo da Folha de Pagamento "
         #define STR0009  "Este programa calcula folha de pagamento "
         #define STR0010  "Calculo da Folha de Pagamento  "
         #define STR0011  "Este programa calcula folha de pagamento "
         #define STR0012  "Filial    : "
         #define STR0013  "Matricula : "
         #define STR0014  "Nome      : "
         #define STR0015  "Confirma configura‡„o dos parƒmetros?"
         #define STR0016  "Aten‡„o"
   #ENDIF
#ENDIF