#IFDEF SPANISH
         #define STR0001  "Generaci¢n de neto en disco ( SISPAG ) "
         #define STR0002  "El objetivo de este programa es generar el archivo neto en disco en "
         #define STR0003  "el modelo SISPAG.  Antes de ejecutar este programa se debe hacer el "
         #define STR0004  "registro del lay-out del archivo en el m¢dulo SIGACFG opci¢n SISPAG."
         #define STR0005  "Generaci¢n de neto en disco (SISPAG)"
         #define STR0006  "Confirma"
         #define STR0007  "Retipea "
         #define STR0008  "Salir   "
         #define STR0009  "Generaci¢n de neto en disco ( SISPAG )"
         #define STR0010  "El objetivo de este programa es generar el archivo neto en disco en "
         #define STR0011  "el modelo SISPAG.  Antes de ejecutar este programa se debe hacer el "
         #define STR0012  "registro del lay-out del archivo en el m¢dulo SIGACFG opci¢n SISPAG."
         #define STR0013  "Neto en Disco ( SISPAG )"
         #define STR0014  "C¢digo Banco   "
         #define STR0015  "N§ Agencia     "
         #define STR0016  "N§ C/C.        "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Generation of Net Amount in Disk ( SISPAG )"
         #define STR0002  "This program has the purpose of generating the Net in disk in SISPAG "
         #define STR0003  "standard. Before running this program, is necessary to register the  "
         #define STR0004  "file lay-out in the Module SIGACFG, option SISPAG.                 "
         #define STR0005  "Generate Net Amount in Disk   (SISPAG)"
         #define STR0006  "O.K.    "
         #define STR0007  "Retype  "
         #define STR0008  "Quit    "
         #define STR0009  "Generate Net Amount in Disk   (SISPAG)"
         #define STR0010  "This program has the purpose of generating the Net in disk in the "
         #define STR0011  "SISPAG standard. Before running the program, is necessary to register  "
         #define STR0012  "the file lay-out in the SIGACFG Module, option SISPAG."
         #define STR0013  "Net in Disk         ( SISPAG )"
         #define STR0014  "Bank Code      "
         #define STR0015  "Agency Number  "
         #define STR0016  "C/A Number     "
   #ELSE
         #define STR0001  "Gera‡„o de liquido em disquete ( SISPAG ) "
         #define STR0002  "Este programa tem o objetivo de gerar o arquivo de liquido em disco no"
         #define STR0003  "padr„o SISPAG. Antes de rodar este programa  ‚  necess rio cadastrar o"
         #define STR0004  "lay-out do arquivo no Modulo SIGACFG op‡„o SISPAG.                    "
         #define STR0005  "Gera‡„o de liquido em disquete (SISPAG)"
         #define STR0006  "Confirma"
         #define STR0007  "Redigita"
         #define STR0008  "Abandona"
         #define STR0009  "Gera‡„o de liquido em disquete ( SISPAG )"
         #define STR0010  "Este programa tem o objetivo de gerar o arquivo de liquido em disco no"
         #define STR0011  "padr„o SISPAG. Antes de rodar este programa  ‚  necess rio cadastrar o"
         #define STR0012  "lay-out do arquivo no Modulo SIGACFG op‡„o SISPAG. "
         #define STR0013  "Liquido em Disquete ( SISPAG )"
         #define STR0014  "Codigo Banco   "
         #define STR0015  "Num. Agencia   "
         #define STR0016  "Num. C/C.      "
   #ENDIF
#ENDIF