#IFDEF SPANISH
         #define STR0001  "Generaci¢ Archivo de D. I. R. F."
         #define STR0002  "Este programa genera el archivo de D.I.R.F."
         #define STR0003  "Confirma"
         #define STR0004  "Retipea "
         #define STR0005  "Salir   "
         #define STR0006  "Generaci¢n Archivo de D.I.R.F."
         #define STR0007  "Este programa genera el archivo de D.I.R.F."
         #define STR0008  "Confirma"
         #define STR0009  "Retipea "
         #define STR0010  "Salir   "
         #define STR0011  "Sucursal  : "
         #define STR0012  "Matr¡cula : "
         #define STR0013  "Nombre    : "
         #define STR0014  "¨Confirma configuraci¢n de los par metros?"
         #define STR0015  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Generating  D. I. R. F. File  "
         #define STR0002  "This routine will generate a D.I.R.F.file"
         #define STR0003  "O.K.    "
         #define STR0004  "Retype  "
         #define STR0005  "Quit    "
         #define STR0006  "Generating D.I.R.F. file"
         #define STR0007  "This routine will generate a D.I.R.F.file"
         #define STR0008  "O.K.    "
         #define STR0009  "Retype  "
         #define STR0010  "Quit    "
         #define STR0011  "Branch    : "
         #define STR0012  "Registrat.: "
         #define STR0013  "Name      : "
         #define STR0014  "Confirm configuration of parameters ?"
         #define STR0015  "Attention"
   #ELSE
         #define STR0001  "Gera‡„o do Arquivo da D. I. R. F."
         #define STR0002  "Este programa gera o arquivo da D.I.R.F."
         #define STR0003  "Confirma"
         #define STR0004  "Redigita"
         #define STR0005  "Abandona"
         #define STR0006  "Gera‡„o do Arquivo da D.I.R.F."
         #define STR0007  "Este programa gera o arquivo da D.I.R.F."
         #define STR0008  "Confirma"
         #define STR0009  "Redigita"
         #define STR0010  "Abandona"
         #define STR0011  "Filial    : "
         #define STR0012  "Matricula : "
         #define STR0013  "Nome      : "
         #define STR0014  "Confirma configura‡„o dos parƒmetros?"
         #define STR0015  "Aten‡„o"
   #ENDIF
#ENDIF