#IFDEF SPANISH
	#define STR0001  "Relaci¢n de la Cesta B sica                               "
	#define STR0002  "Ser  impresa de acuerdo con los par metros solicitados por"
	#define STR0003  "el usuario."
	#define STR0004  "Centro de Costo"
	#define STR0005  "Matr¡cula"
	#define STR0006  " "
	#define STR0007  "Administraci¢n"
	#define STR0008  "SUC C.COSTO   MATRICULA   NOMBRE                              COSTO BENEFICIARIO     COSTO EMPRESA        COSTO TOTAL"
	#define STR0009  " RELACION DE LA CESTA BASICA"
	#define STR0010  "SUC. :  "
	#define STR0011  " CCTO: "
	#define STR0012  "COSTO BENEFICIARIO     COSTO EMPRESA        COSTO TOTAL  CESTA BASICA"
	#define STR0013  "SUC. :  "
	#define STR0014  "COSTO BENEFICIARIO     COSTO EMPRESA        COSTO TOTAL  CESTA BASICA"
	#define STR0015  "Empresa: "
	#define STR0016  "COSTO BENEFICIARIO     COSTO EMPRESA        COSTO TOTAL  CESTA BASICA"
   #define STR0017  "Nombre"
   #define STR0018  "Centro de Costo + Nombre"
#ELSE
   #IFDEF ENGLISH
                #define STR0001  "List of Food Basket                                    "
                #define STR0002  "Will be printed according to parameters requested bt the  "
                #define STR0003  "User   ."
                #define STR0004  "Cost Center    "
                #define STR0005  "Registration"
                #define STR0006  "Z.Form "
                #define STR0007  "Management   "
                #define STR0008  "BR. C.CENTER  REGISTRAT   NAME                                BENEFICIARY COST       COMPANY COST         TOTAL COST "
                #define STR0009  " LIST OF FOOD BASKET     "
                #define STR0010  "BRANCH: "
		        #define STR0011  " CCENT:"
                #define STR0012  "BENEFICIARY COST       COMPANT COST         TOTAL COST   FOOD BASKET "
                #define STR0013  "BRANCH: "
                #define STR0014  "BENEFICIARY COST       COMPANY COST         TOTAL COST   FOOD BASKET "
                #define STR0015  "Company: "
                #define STR0016  "BENEFICIARY COST       COMPANY COST         TOTAL COST   FOOD BASKET "
                #define STR0017  "Name"
                #define STR0018  "Cost Center + Nane    "
   #ELSE
		#define STR0001  "Rela‡„o da Cesta Basica                                   "
		#define STR0002  "Ser  impresso de acordo com os parametros solicitados pelo"
		#define STR0003  "usu rio."
		#define STR0004  "Centro de Custo"
		#define STR0005  "Matr¡cula"
		#define STR0006  "Zebrado"
		#define STR0007  "Administra‡„o"
		#define STR0008  "FIL C.CUSTO   MATRICULA   NOME                                CUSTO BENEFICIARIO     CUSTO EMPRESA        CUSTO TOTAL"
		#define STR0009  " RELA€ŽO DA CESTA BASICA "
		#define STR0010  "FILIAL: "
		#define STR0011  " CCTO: "
		#define STR0012  "CUSTO BENEFICIARIO     CUSTO EMPRESA        CUSTO TOTAL  CESTA BASICA"
		#define STR0013  "FILIAL: "
		#define STR0014  "CUSTO BENEFICIARIO     CUSTO EMPRESA        CUSTO TOTAL  CESTA BASICA"
		#define STR0015  "Empresa: "
		#define STR0016  "CUSTO BENEFICIARIO     CUSTO EMPRESA        CUSTO TOTAL  CESTA BASICA"
      #define STR0017  "Nome"
   	#define STR0018  "Centro de Custo + Nome"
   #ENDIF
#ENDIF