#IFDEF SPANISH
	#define STR0001  "Cup¢n de Lectura X"
	#define STR0002  "Para Emitir la Lectura X de la Impresora fiscal, se debe "
	#define STR0003  "estar archivado como usuario fiscal y con los par metros correctos de la impresora. "
	#define STR0004  "Atenci¢n"
	#define STR0005  "Objetivo del Programa"
	#define STR0006  "               El objetivo de este "
	#define STR0007  "programa es hacer la impresi¢n del "
	#define STR0008  "cup¢n de lectura X de la impresora fiscal "
	#define STR0009  "fiscal "
	#define STR0010  "¨Impresora Ok?"
	#define STR0011  "Atenci¢n"
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "Reading Voucher X"
                #define STR0002  "To issue the X Reading of the fiscal printer, you must"
                #define STR0003  "be registered as a fiscal user and under the correct printer parameters.         "
                #define STR0004  "Attention"
                #define STR0005  "Program Objective   "
                #define STR0006  "          This program has the   "
                #define STR0007  "purpose of making the printing of"
                #define STR0008  "the Reading Voucher X of the fiscal"
                #define STR0009  "printer Bematech"
                #define STR0010  "Printer   Ok?"
                #define STR0011  "Attention"
	#ELSE
		#define STR0001  "Cupom de Leitura X"
		#define STR0002  "Para Emitir a Leitura X da Impressora fiscal, deve-se "
		#define STR0003  "estar cadastrado como usu rio fiscal e com os parƒmetros da impressora corretos. "
		#define STR0004  "Aten‡„o"
		#define STR0005  "Objetivo do Programa"
		#define STR0006  "          Este programa tem como "
		#define STR0007  "objetivo efetuar a impress„o  do "
		#define STR0008  "cupom de leitura X da impressora fiscal "
		#define STR0009  "fiscal "
		#define STR0010  "Impressora Ok?"
		#define STR0011  "Aten‡„o"
	#ENDIF
#ENDIF