#IFDEF SPANISH
	#define STR0001 "Factor - Propio "
	#define STR0002 "Factor - Otros"
	#define STR0003 "Simple"
	#define STR0004  "Vuelva Siempre"
	#define STR0005 "Datos del Producto"
	#define STR0006 "C¢digo"
	#define STR0007 "Unidad "
	#define STR0008 "Grupo"
	#define STR0009 "Descripci¢n"
	#define STR0010 "Stock: "
	#define STR0011 "Inicial"
	#define STR0012 "Actual"
	#define STR0013 "Precios de Venta:"
	#define STR0014 "Anticipado"
	#define STR0015 "Mensual"
	#define STR0016 "P¢sfijado"
	#define STR0017 "Diario"
	#define STR0018 "Semanal"
	#define STR0019 "Quincenal"
	#define STR0020 "Mensual"
	#define STR0021 "Bimestral"
	#define STR0022 "Trimestral"
	#define STR0023 "Semestral"
	#define STR0024 "Anual"
	#define STR0025 "Condici¢n Negociada"
	#define STR0026 "Condici¢n Negoc."
	#define STR0027 "Simple"
	#define STR0028 "Anticipado"
	#define STR0029 "Serie Anticipada"
	#define STR0030 "P¢sfijado"
	#define STR0031 "Serie P¢sfijada"
	#define STR0032 "Financista  "
	#define STR0033 "¨Confirma la salida de la rutina?"
	#define STR0034 "Forma de Pago"
	#define STR0035 "Datos del Cheque"
	#define STR0036 "Serie/Fac"
	#define STR0037 "Impresi¢n de Cheques"
	#define STR0038 "Consulta Stock  "
	#define STR0039 "Tablas de Precios"
	#define STR0040 " La condici¢n de pago actual no tiene factor"
	#define STR0041 " financiero para la adminitradora elegida."
	#define STR0042 " Elija otra condici¢n, y caso no haya ninguna, por favor la registre"
	#define STR0043 " con anticipaci¢n"
	#define STR0044 "Atenci¢n"
	#define STR0045 "Administradora"
	#define STR0046 " No hay administradoras de financiaci¢n con permiso para usar"
	#define STR0047 " usar factor. Incluya una administradora y registre los factores"
	#define STR0048 " referentes a ‚lla."
	#define STR0049 "Financiaci¢n"
	#define STR0050 "Detalles"
	#define STR0051 "Condici¢n de Pago:"
	#define STR0052 "¨Financiaci¢n Propia?"
	#define STR0053 "S¡"
	#define STR0054 "No"
	#define STR0055 "Fecha"
	#define STR0056 "Valor a pagar"
	#define STR0057 "Fecha y Valores a Pagar"
	#define STR0058 "Total:"
	#define STR0059 "Cuotas:"
	#define STR0060 "Factor:"
	#define STR0061 "Condici¢n:"
	#define STR0062 "¨Desea imprimir el comprobante de "
	#define STR0063 "Financiaci¢n?"
	#define STR0064 "Impresi¢n"
	#define STR0065 " No hay proceso de impresi¢n para el comprobante de"
	#define STR0066 " financiaci¢n. - Revise si los archivos IMPFATOR.PRX"
	#define STR0067 " y IMPFATOR._IW est n en el directorio de la Tablas"
	#define STR0068 " de configuraci¢n del sistema, normalmente \SIGAADV\."
	#define STR0069 "   La al¡cuota de ICMS utilizada en este producto no est  registrada"
	#define STR0070 "en la Impresora Fiscal. Utilize la opci¢n Agrega Al¡cuota en el men£"
	#define STR0071 "Miscelanea, M¢dulo Fiscal, para registrarla en la Impresora."
	#define STR0072 "la al¡cuota no registrada es:"
	#define STR0073 "Ning£n Drive"
	#define STR0074 "Tabla"
	#define STR0075 "Precio"
	#define STR0076 "Duplo clic del mouse para elegir la tabla"
	#define STR0077 "Serie"
	#define STR0078 "N£mero"
	#define STR0079 "Imprimiendo el Presupuesto. Espere..."
	#define STR0080 "Salir"
	#define STR0081 "Admin. no Registrada"
   #define STR0082 " C lculo de Juros "
 	#define STR0083 " Administradora "
	#define STR0084 " Dados do Pagamento "
	#define STR0085 "Valor Base"
	#define STR0086 "Entrada"
	#define STR0087 "Taxa Juros"
	#define STR0088 "Parcelas"
	#define STR0089 "Intervalo"
	#define STR0090 "Utilizar Financiadora"
	#define STR0091 "Simples"
	#define STR0092 "S‚rie Pgtos"
   #define STR0093 "Price"
	#define STR0094 "SAC"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "Factor- Private"
                #define STR0002 "Factor- Others"
                #define STR0003 "Simple "
                #define STR0004  "Welcome Back"
                #define STR0005 "Product Data    :"
                #define STR0006 "Code  "
                #define STR0007 "Unit   "
                #define STR0008 "Group"
                #define STR0009 "Descript."
                #define STR0010 "Invent.:"
                #define STR0011 "Initial"
                #define STR0012 "Curr."
                #define STR0013 "Sales Prices   :"
                #define STR0014 "In Advance"
                #define STR0015 "Monthly"
                #define STR0016 "Post-fixed"
                #define STR0017 "Daily "
                #define STR0018 "Weekly "
                #define STR0019 "Fortnight"
                #define STR0020 "Monthly"
                #define STR0021 "Bimestrial"
                #define STR0022 "Quaterly   "
                #define STR0023 "Bi-Annual"
                #define STR0024 "Annual"
                #define STR0025 "Negotiated Condit."
                #define STR0026 "Negociat.Condit"
                #define STR0027 "Simple "
                #define STR0028 "In Advance"
                #define STR0029 "Antecip.Series  "
                #define STR0030 "Post-fixed"
                #define STR0031 "Post fixed Series"
                #define STR0032 "Financing instit."
                #define STR0033 "Confirm routine Exit      ?"
                #define STR0034 "Payment Modality  "
                #define STR0035 "Cheque Data    "
                #define STR0036 "Series/Inv"
                #define STR0037 "Cheque Printing     "
                #define STR0038 "Search Inventory"
                #define STR0039 "Price List       "
                #define STR0040 "The current payment condition does not  "
                #define STR0041 " contain financial factor for the selected Administr."
                #define STR0042 " Select another condition and if therre isnt't one, please register  "
                #define STR0043 " it previously"
                #define STR0044 "Attention"
                #define STR0045 "Administrator "
                #define STR0046 "There are no financing administrators licenced to "
                #define STR0047 " use the Factor.Include one administrator and register the factor  "
                #define STR0048 " referring to it. "
                #define STR0049 "Financing    "
                #define STR0050 "Details "
                #define STR0051 "Payment Conditions:   "
                #define STR0052 "Self Financing        ? "
                #define STR0053 "Yes"
                #define STR0054 "No "
                #define STR0055 "Date"
                #define STR0056 "Amount payable"
                #define STR0057 "Dates and Amount payable"
		          #define STR0058 "Total:"
                #define STR0059 "Instalm.:"
                #define STR0060 "Factor"
                #define STR0061 "Condit. :"
                #define STR0062 "Do you wish to print the Financing"
                #define STR0063 "Voucher       ?"
                #define STR0064 "Printing "
                #define STR0065 "Printing script for the financing script"
                #define STR0066 " does not exist - Check whether the file         "
                #define STR0067 " IMPFATOR.PRX e IMPFATOR._IW are in the directory  "
                #define STR0068 " of the System's Configuration Tables. Usually \SIGAADV\."
                #define STR0069 "The VAT rate used in this product is not registered "
                #define STR0070 "in the fiscal Printer .Use the option Add Rate in the menu         "
                #define STR0071 "Miscellaneous, Fiscal Module, in order to register it in the printer"
                #define STR0072 "the non registered rate is  : "
                #define STR0073 "No Drive    "
                #define STR0074 "List  "
                #define STR0075 "Price"
                #define STR0076 "Doble click mouse to select the list       "
                #define STR0077 "Series"
                #define STR0078 "Number"
                #define STR0079 "Printing the Budget. Wait ........"
                #define STR0080 "Exit"
                #define STR0081 "Admin. not Registered"
		          #define STR0082 " C lculo de Juros "
		          #define STR0083 " Administradora "
		          #define STR0084 " Dados do Pagamento "
		          #define STR0085 "Valor Base"
		          #define STR0086 "Entrada"
		          #define STR0087 "Taxa Juros"
		          #define STR0088 "Parcelas"
		          #define STR0089 "Intervalo"
		          #define STR0090 "Utilizar Financiadora"
		          #define STR0091 "Simples"
		          #define STR0092 "S‚rie Pgtos"
		          #define STR0093 "Price"
                #define STR0094 "SAC"
	#ELSE
		#define STR0001 "Fator - Pr¢prio"
		#define STR0002 "Fator - Outros"
		#define STR0003 "Simples"
		#define STR0004  "Volte Sempre"
		#define STR0005 "Dados do Produto:"
		#define STR0006 "C¢digo"
		#define STR0007 "Unidade"
		#define STR0008 "Grupo"
		#define STR0009 "Descri‡Æo"
		#define STR0010 "Estoque:"
		#define STR0011 "Inicial"
		#define STR0012 "Atual"
		#define STR0013 "Pre‡os de Venda:"
		#define STR0014 "Antecipado"
		#define STR0015 "Mensal"
		#define STR0016 "P¢s-fixado"
		#define STR0017 "Di rio"
		#define STR0018 "Semanal"
		#define STR0019 "Quinzenal"
		#define STR0020 "Mensal"
		#define STR0021 "Bimestral"
		#define STR0022 "Trimestral"
		#define STR0023 "Semestral"
		#define STR0024 "Anual"
		#define STR0025 "Condi‡„o Negociada"
		#define STR0026 "Condi‡„o Negoc."
		#define STR0027 "Simples"
		#define STR0028 "Antecipado"
		#define STR0029 "S‚rie Antecipada"
		#define STR0030 "P¢s-fixado"
		#define STR0031 "S‚rie P¢s-fixada"
		#define STR0032 "Financiadora"
		#define STR0033 "Confirma a Saida da rotina?"
		#define STR0034 "Forma de Pagamento"
		#define STR0035 "Dados do Cheque"
		#define STR0036 "S‚rie/NF"
		#define STR0037 "Impress„o de Cheques"
		#define STR0038 "Consulta Estoque"
		#define STR0039 "Tabelas de Pre‡os"
		#define STR0040 "A condi‡„o de pagamento atual n„o cont‚m"
		#define STR0041 " fator financeiro para a administradora escolhida."
		#define STR0042 " Escolha outra condi‡„o, e caso n„o exista nenhuma, favor cadastra-l "
		#define STR0043 " previamente."
		#define STR0044 "Aten‡„o"
		#define STR0045 "Administradora"
		#define STR0046 "N„o existem administradoras de financiamento habilitadas"
		#define STR0047 " a utilizar Fator. Incluir uma adminitradora e cadastrar os fatores"
		#define STR0048 " referˆntes a ela."
		#define STR0049 "Financiamento"
		#define STR0050 "Detalhes"
		#define STR0051 "Condi‡„o de pagamento:"
		#define STR0052 "Financiamento Pr¢prio ? "
		#define STR0053 "Sim"
		#define STR0054 "N„o"
		#define STR0055 "Data"
		#define STR0056 "Valor a pagar"
		#define STR0057 "Datas e Valores a Pagar"
		#define STR0058 "Total:"
		#define STR0059 "Parcelas:"
		#define STR0060 "Fator:"
		#define STR0061 "Condi‡Æo:"
		#define STR0062 "Deseja imprimir o comprovante de "
		#define STR0063 "Financiamento ?"
		#define STR0064 "Impress„o"
		#define STR0065 "Script de impress„o para o comprovante "
		#define STR0066 " de financiamento n„o exite - Verifique se o arquivo"
		#define STR0067 " IMPFATOR.PRX e IMPFATOR._IW est„o no diret¢rio das"
		#define STR0068 " Tabelas de configura‡„o do Sistema. Normalmente \SIGAADV\."
		#define STR0069 "A al¡quota de Icms utilizada neste produto n„o est  "
		#define STR0070 "cadastrada na Impressora fiscal. utilize a op‡„o adiciona Aliquota "
		#define STR0071 "no menu Miscelƒnea, M¢dulo fiscal, para cadastr -la na Impressora. "
		#define STR0072 "a al¡quota n„o cadastrada ‚ : "
		#define STR0073 "Nenhum Drive"
		#define STR0074 "Tabela"
		#define STR0075 "Preco"
		#define STR0076 "Duplo Click do mouse para escolher a tabela"
		#define STR0077 "S‚rie"
		#define STR0078 "N£mero"
		#define STR0079 "Imprimindo o Or‡amento. Aguarde..."
		#define STR0080 "Sair"
		#define STR0081 "Admin. n„o Cadastrada"
		#define STR0082 " C lculo de Juros "
		#define STR0083 " Administradora "
		#define STR0084 " Dados do Pagamento "
		#define STR0085 "Valor Base"
		#define STR0086 "Entrada"
		#define STR0087 "Taxa Juros"
		#define STR0088 "Parcelas"
		#define STR0089 "Intervalo"
		#define STR0090 "Utilizar Financiadora"
		#define STR0091 "Simples"
		#define STR0092 "S‚rie Pgtos"
		#define STR0093 "Price"
		#define STR0094 "SAC"
	#ENDIF
#ENDIF