#IFDEF SPANISH
	#define STR0001 "Solicitud, Punto de Reposici¢n"
	#define STR0002 "   El objetivo de este informe es relacionar las Solicitudes de"
	#define STR0003 "Compra para los materiales que llegaron al Punto de Reposici¢n,"
	#define STR0004 "considerando el Lote de Compras."
	#define STR0005 "Relaci¢n de la Solicitud de Compra"
	#define STR0006 "  "
	#define STR0007 "Administraci¢n"
	#define STR0008 "Por C¢digo"
	#define STR0009 "Por Descripci¢n"
	#define STR0010 "*  N§ Solicitud    *  Ötem  *  Emisi¢n   *  C¢digo Producto  *  Descripci¢n del Producto        *  Local.  *  UM  *     Cantidad   *"
	#define STR0011 "El objetivo de este programa es generar las Solicitudes de Compra pa-"
	#define STR0012 "ra los materiales que llegaron al Punto de Reposici¢n,  considerando"
	#define STR0013 "el lote de Compras.  Tambi‚n emite una lista de estas Solicitudes de"
	#define STR0014 "de Compras antes que ellas sean hechas efectivas.                   "
	#define STR0015 "El objetivo de esta rutina es generar las Solicitudes de Compra para"
	#define STR0016 "los materiales que llegaron al Punto de Reposici¢n,  considerando el"
	#define STR0017 "Lote de Compras. Iden lista emitida.                                "
	#define STR0018 "ANULADO POR EL OPERADOR"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "Request for Replacement Point"
                #define STR0002 "This report has the purpose of listing Purchase Requests for the  "
                #define STR0003 "material that have reached the Replacement Point, considering the "
                #define STR0004 "Purchase Lot.     "
                #define STR0005 "List of the Purchasse Requests   "
                #define STR0006 "Z.Form "
                #define STR0007 "Management   "
                #define STR0008 "Per Code  "
                #define STR0009 "Per Descript."
                #define STR0010 "*  Request N.      *  Item  *  Issuance  *  Product Code     *  Product Description             *  Local.  * S.U. *     Quantity   *"
                #define STR0011 "This program has the purpose of generating Purchase Requests for the"
                #define STR0012 "material that have reached Replacement Point, considering the Purchase"
                #define STR0013 "Lot. It also issues a list of Purchase Requests before these are    "
                #define STR0014 "carried out.                                                        "
                #define STR0015 "This routine has the purpose of generating Purchase Orders for those "
                #define STR0016 "material that have reached the Replacement Point, considering the    "
                #define STR0017 "Purchase Lot. Idem list issued.                                              "
                #define STR0018 "CANCELLED BY OPERATOR  "
	#ELSE
		#define STR0001 "Solic. p/ Ponto Reposicao"
		#define STR0002 "Este relat¢rio tem como objetivo relacionar Solicita‡”es de Compra"
		#define STR0003 "para os materiais que atingiram o Ponto de Reposi‡„o, considerando"
		#define STR0004 "o Lote de Compras."
		#define STR0005 "Rela‡„o de Solicita‡”es de Compra"
		#define STR0006 "Zebrado"
		#define STR0007 "Administracao"
		#define STR0008 "Por Codigo"
		#define STR0009 "Por Descricao"
		#define STR0010 "*  No.Solicitacao  *  Item  *  Emissao   *  Codigo Produto   *  Descricao do Produto            *  Local.  *  UM  *     Quantidade *"
		#define STR0011 "Este programa tem como objetivo gerar Solicita‡”es de Compra para os"
		#define STR0012 "materiais que atingiram o Ponto de Reposi‡„o, considerando o Lote de"
		#define STR0013 "Compras. Emite ainda uma rela‡„o destas Solicita‡”es de Compra antes"
		#define STR0014 "destas serem efetivadas.                                            "
		#define STR0015 "Esta rotina tem como objetivo gerar Solicita‡”es de Compra para os  "
		#define STR0016 "materiais que atingiram o Ponto de Reposi‡„o, considerando o  Lote  "
		#define STR0017 "de Compras. Idem rela‡„o emitida.                                   "
		#define STR0018 "CANCELADO PELO OPERADOR"
	#ENDIF
#ENDIF