#IFDEF SPANISH
	#define STR0001 "Para archivar una al¡cuota en la Impresora Fiscal, se debe estar registrado"
	#define STR0002 "como usuario fiscal y con los par metros correctos de la impresora."
	#define STR0003 "Atenci¢n"
	#define STR0004 "Opci¢n disponible s¢lo en impersoras  Bematech"
	#define STR0005 "Agregador de Al¡cuotas"
	#define STR0006 "Objetivo del Programa"
	#define STR0007 "                  El objetivo de este programa es el"
	#define STR0008 " archivamiento de la al¡cuota con la cual su empresa"
	#define STR0009 " har  las operaciones fiscales."
	#define STR0010 "Al¡cuota (%):"
	#define STR0011 "Al¡cuota ya archivada"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "To register a rate in the Fiscal Printer, you must be     " 
                #define STR0002 "registered as a fiscal user and under the right printer paameters .              "
                #define STR0003 "Attention"
                #define STR0004 "Option Available only for BemaTech printer      "
                #define STR0005 "Rates Summing Machine   "
                #define STR0006 "Objetive of Program "
                #define STR0007 "               This program has the purpose of "
                #define STR0008 " registering the rate that your company will use to carry out    "
                #define STR0009 " fiscal operations."
                #define STR0010 "Rate     (%):"
                #define STR0011 "Rate already registered"
	#ELSE
		#define STR0001 "Para cadastrar uma aliquota na Impressora fiscal, deve-se "
		#define STR0002 "estar cadastrado como usu rio fiscal e com os parƒmetros da impressora corretos. "
		#define STR0003 "Aten‡„o"
		#define STR0004 "Op‡„o dispon¡vel apenas para impressora Bematech"
		#define STR0005 "Adicionador de Al¡quotas"
		#define STR0006 "Objetivo do Programa"
		#define STR0007 "               Este programa tem como objetivo "
		#define STR0008 " o cadastramento da al¡quota com a qual a sua empresa ir  efetuar"
		#define STR0009 " opera‡”es fiscais."
		#define STR0010 "Aliquota (%):"
		#define STR0011 "Al¡quota j  cadastrada"
	#ENDIF
#ENDIF