#IFDEF SPANISH
	#define STR0001 "Confirma"
	#define STR0002 "Retipea "
	#define STR0003 "Salir   "
	#define STR0004 " A  T  E  N  C  I  O  N "
	#define STR0005 "    Para actualizar la Base de Datos,"
	#define STR0006 "el  sistema no podr† estar en uso por"
	#define STR0007 "otras estaciones. Ahora se est† espe-"
	#define STR0008 "rando la  liberaci¢n de los archivos."
	#define STR0009 "Para  seguir  con  la  actualizaci¢n,"
	#define STR0010 "tecle <Enter> cuando  todas las esta-"
	#define STR0011 "ciones estÇn fuera del sistema."
	#define STR0012 "Actualizaci¢n Servidor X Estaci¢n"
	#define STR0013 "Archivos"
	#define STR0014 "Objetivo del Programa"
	#define STR0015 "Productos"
	#define STR0016 "Clientes"
	#define STR0017 "Otros"
	#define STR0018 "Cajas(Actual.)"
	#define STR0019 "Cajas(Compl.)"
	#define STR0020 "        El objetivo de este programa es generar un juego"
	#define STR0021 " de archivos definidos por el usuario para hacer posible"
	#define STR0022 " la actualizaci¢n entre Servidor y Estaci¢n."
	#define STR0023 ". ≠≠≠No es consolidaci¢n!!!"
	#define STR0024 "    En el cuadro al lado se deber†n informar cuales archivos ser†n generados."
	#define STR0025 "Generando  "
	#define STR0026 "Generaci¢n Terminada"
	#define STR0027 "Generaci¢n Interrumpida"
	#define STR0028 "      Es necesario informar el directorio donde ser†n generados los"
	#define STR0029 " archivos para actualizar el Front Loja. Favor cambiar el par†metro"
	#define STR0030 " MV_UPSERV en el Configurador."
	#define STR0031 "Atenci¢n"
	#define STR0032 "≠El directorio informado "
	#define STR0033 " no existe!"
	#define STR0034 " Informe un directorio v†lido en el Configurador. Par†metro MV_UPSERV"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "OK      "
                #define STR0002 "Retype  "
                #define STR0003 "Quit    "
                #define STR0004 " A T T E N T I O N   "
                #define STR0005 "To update the Data Base, the System"
                #define STR0006 "cannot be in use by other stations."
                #define STR0007 "At this moment the release of files"
                #define STR0008 "is being expected.Press<Enter> when"
                #define STR0009 "all stations are already outside   "
                #define STR0010 " the System and then carry on with "
                #define STR0011 "updating.                          "
                #define STR0012 "Updating Server X Station     "
                #define STR0013 "Files  "
                #define STR0014 "Program Objective   "
                #define STR0015 "Products"
                #define STR0016 "Customers"
                #define STR0017 "Others"
                #define STR0018 "Cashiers(Updat)"
                #define STR0019 "Cashiers(Compl)"
                #define STR0020 "       This program consists in    "
                #define STR0021 " generating a set of files defined by the "
                #define STR0022 " User to allow updating between Server and Station       "
                #define STR0023 "It is not consolidation!"
                #define STR0024 "      In the Table below inform which files will be generated.            "
                #define STR0025 "Generating                 "
                #define STR0026 "Generation concluded"
                #define STR0027 "Generat.interrupted "
                #define STR0028 "It is necessary to inform the directory where will be "
                #define STR0029 "generated the files for updating the FrontLoja. Please change parameter  "
                #define STR0030 " MV_UPSERV on Configurator."
                #define STR0031 "Attention"
                #define STR0032 "The directory informed"
                #define STR0033 "not exists !!!"
                #define STR0034 " Inform a valid directory in the Configurator. Parameter MV_UPSERV"
	#ELSE
		#define STR0001 "Confirma"
		#define STR0002 "Redigita"
		#define STR0003 "Abandona"
		#define STR0004 " A  T  E  N  C  A  O "
		#define STR0005 "Para Atualizar a  Base de Dados , o"
		#define STR0006 "sistema nÑo poder† estar em uso por"
		#define STR0007 "outras estaáîes. Neste momento est†"
		#define STR0008 "sendo aguardada a liberaáÜo dos ar-"
		#define STR0009 "quivos. Tecle <Enter>  qdo todas as"
		#define STR0010 " estaáîes j† estiverem fora do sis-"
		#define STR0011 "tema p/ prosseguir c/ a atualizaáÜo."
		#define STR0012 "AtualizaáÑo Servidor X EstaáÑo"
		#define STR0013 "Arquivos"
		#define STR0014 "Objetivo do Programa"
		#define STR0015 "Produtos"
		#define STR0016 "Clientes"
		#define STR0017 "Outros"
		#define STR0018 "Caixas(Atual.)"
		#define STR0019 "Caixas(Compl.)"
		#define STR0020 "       Este programa consiste em gerar"
		#define STR0021 " um jogo de arquivos definido pelo usu†rio"
		#define STR0022 " para possibilitar a atualizaáÑo entre Servidor e EstaáÑo"
		#define STR0023 ". NÑo Ç consolidaáÑo!!!"
		#define STR0024 "      No quadro ao lado dever† ser informado quais arquivos serÑo gerados."
		#define STR0025 "Gerando    "
		#define STR0026 "GeraáÑo Conclu°da"
		#define STR0027 "GeraáÑo Interrompida"
		#define STR0028 "ê necess†rio informar o diret¢rio onde serÑo gerados"
		#define STR0029 " os arquivos para atualizar o Front Loja. Favor alterar o parÉmetro"
		#define STR0030 " MV_UPSERV no Configurador."
		#define STR0031 "AtenáÑo"
		#define STR0032 "O diret¢rio informado "
		#define STR0033 " nÑo existe!"
		#define STR0034 " Informe um diret¢rio v†lido no Configurador. ParÉmetro MV_UPSERV"
	#ENDIF
#ENDIF