#IFDEF SPANISH
	#define STR0001 "Apertura/Cierre    "
	#define STR0002 "Visualiza"
	#define STR0003 "Apertura"
	#define STR0004 "Cierre    "
	#define STR0005 "Seleccionando Cajas..."
	#define STR0006 "Abrir la Caja"
	#define STR0007 "Caja "
	#define STR0008 "Fecha Movimiento"
	#define STR0009 "Nomb."
	#define STR0010 "La rutina permite la  APERTURA  del movimiento de la Caja. S¢lo despu‚s de su confirmaci¢n ser  posible la realizaci¢n de las Ventas."
	#define STR0011 "APERTURA"
	#define STR0012 "VUELTO    "
	#define STR0013 "Entrada de vuelto en la Caja"
	#define STR0014 "Saldo Anterior"
	#define STR0015 "VUELTO"
	#define STR0016 "Cerrar la Caja"
	#define STR0017 "Esta rutina premite el  CIERRE   del movimiento de la Caja. Despu‚s de su confirmaci¢n no ser  posible la realizaci¢n de las Ventas."
	#define STR0018 "CIERRE    "
	#define STR0019 "No fueron hechas las sangr¡as del d¡a anterior."
	#define STR0020 "       Usted podr  cerrar la Caja en este momento, pero el "
	#define STR0021 "movimiento actual ser  totalizado con el que ya existe."
	#define STR0022 "Para continuar confirme la operaci¢n de Cierre, o  "
	#define STR0023 "Cancele y Sangre la caja."
	#define STR0024 "Atenci¢n"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "Opening/Closing    "
                #define STR0002 "View     "
                #define STR0003 "Opening "
                #define STR0004 "Closing   "
                #define STR0005 "Selecting Cashiers ..."
                #define STR0006 "Open the Cashier"
                #define STR0007 "Cashier"
                #define STR0008 "Transact.Date "
                #define STR0009 "Name"
                #define STR0010 "This routine allows the OPENING of the Cashier Transact. Only after its confirmation it will be possible to execute Sales."
                #define STR0011 "OPENING "
                #define STR0012 "CHANGE    "
                #define STR0013 "Change inflow in Cashier "
                #define STR0014 "Prev. Balance "
                #define STR0015 "CHANGE"
                #define STR0016 "Close Cashier "
                #define STR0017 "This will enable the CLOSING of the Cashier Transactions. After its confirmation it will be possible to execute Sales. "
                #define STR0018 "CLOSING   "
                #define STR0019 "The partial closings of the previous day have not occurred"
                #define STR0020 "You can close the Cashier at this time, however the "
                #define STR0021 "current transactions will be summed to the existing one."
                #define STR0022 "To carry on confirm the closing operation, or Cancel  "
                #define STR0023 "and Partially close Cashier"
                #define STR0024 "Attention"
	#ELSE
		#define STR0001 "Abertura/Fechamento"
		#define STR0002 "Visualiza"
		#define STR0003 "Abertura"
		#define STR0004 "Fechamento"
		#define STR0005 "Selecionando Caixas..."
		#define STR0006 "Abrir o Caixa"
		#define STR0007 "Caixa"
		#define STR0008 "Data Movimento"
		#define STR0009 "Nome"
		#define STR0010 "Esta rotina permite a ABERTURA da movimenta‡„o do Caixa. Somente ap¢s sua confirma‡„o ser  poss¡vel a realiza‡„o de Vendas."
		#define STR0011 "ABERTURA"
		#define STR0012 "TROCO     "
		#define STR0013 "Entrada de troco no Caixa"
		#define STR0014 "Saldo Anterior"
		#define STR0015 "TROCO"
		#define STR0016 "Fechar o Caixa"
		#define STR0017 "Esta rotina permite o FECHAMENTO da movimenta‡„o do Caixa. Ap¢s sua confirma‡„o n„o ser  poss¡vel a realiza‡„o de Vendas."
		#define STR0018 "FECHAMENTO"
		#define STR0019 "N„o foram efetuadas as sangrias do dia anterior. "
		#define STR0020 "Vocˆ poder  fechar o Caixa neste momento, porem a "
		#define STR0021 "movimenta‡Æo atual ser  totalizada com a j  existente. "
		#define STR0022 "Para prosseguir confirme a opera‡Æo de Fechamento, ou "
		#define STR0023 "Cancele e Sangre o Caixa."
		#define STR0024 "Aten‡„o"
	#ENDIF
#ENDIF