#IFDEF SPANISH
	#define STR0001  "Forma/Condici¢n &Pago"
	#define STR0002  "&Descuento Valor/Porcentaje"
	#define STR0003  "Total Final a Pagar"
	#define STR0004  "Impresi¢n"
	#define STR0005  "Fecha"
	#define STR0006  "Valor"
	#define STR0007  "Forma de Pago"
	#define STR0008  "Doble clic para elegir las administradoras"
	#define STR0009  "&Factura"
	#define STR0010  "Cup¢n Fisca&l"
	#define STR0011  "&Cup¢n de Control"
	#define STR0012  "&Imprime Cheques"
	#define STR0013  "Tablas de Precios"
	#define STR0014  "Tabla"
	#define STR0015  "Precio"
	#define STR0016  "Doble clic del mouse para eligir la tabla"	
	#define STR0017  "No fueron espec¡ficados los ¡tems para la venta."
	#define STR0018  "Atenci¢n"
	#define STR0019  "Cierre de la Venta"
#ELSE
	#IFDEF ENGLISH
                #define STR0001  "Form/Condition&Payment  "
                #define STR0002  "&Amount Discount/Percentage"
                #define STR0003  "End Payable Total"
                #define STR0004  "Printing "
                #define STR0005  "Date"
                #define STR0006  "Amount"
                #define STR0007  "Payment Modality  "
                #define STR0008  "Double Click to select  Administrators      "
                #define STR0009  "&Invoice    "
                #define STR0010  "fiscal Ticket"
                #define STR0011  "&Control Ticket   "
                #define STR0012  "&Print Checks   " 
	            #define STR0013  "Tables of Prices "
		        #define STR0014  "Table "
		        #define STR0015  "Price"	
		        #define STR0016  "Double click the mouse to select the Table."		
    	        #define STR0017  "Were not specified items for Sale.         "
	            #define STR0018  "Attention"
		#define STR0019  "Sale Closing       "
	#ELSE
		#define STR0001  "Forma/Condi‡„o &Pagamento"
		#define STR0002  "&Desconto Valor/Percentual"
		#define STR0003  "Total a Pagar final"
		#define STR0004  "Impress„o"
		#define STR0005  "Data"
		#define STR0006  "Valor"
		#define STR0007  "Forma de Pagamento"
		#define STR0008  "Duplo click para escolher as Administradoras"
		#define STR0009  "&Nota Fiscal"
		#define STR0010  "Cupom &Fiscal"
		#define STR0011  "&Cupom de Controle"
		#define STR0012  "&Imprime Cheques"
		#define STR0013  "Tabelas de Pre‡os"
		#define STR0014  "Tabela"
		#define STR0015  "Pre‡o"		
 		#define STR0016  "Duplo Click do mouse para escolher a tabela"		
	   	#define STR0017  "N„o foram especificados itens para a Venda."
   		#define STR0018  "Aten‡„o"
		#define STR0019  "Fechamento da Venda"
	#ENDIF
#ENDIF