#IFDEF SPANISH
	#define STR0001 "     Para emitir el informe de la Memoria Fiscal de la impresora se debe estar"
	#define STR0002 "registrado como usuario fiscal y con los par metros de la impresora correctos."
	#define STR0003 "Atenci¢n"
	#define STR0004 "Lectura de Memoria Fiscal"
	#define STR0005 "Objetivo del Programa"
	#define STR0006 "               El objetivo de este programa es "
	#define STR0007 " hacer la  impresi¢n  de la lectura  de   memoria   fiscal  de la"
	#define STR0008 " impresora   fiscal "
	#define STR0009 "Fecha Inicial:"
	#define STR0010 "Final:"
	#define STR0011 "¨Impresora Ok?"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "To issue the report of the Printer's Fiscal Memory  you "
                #define STR0002 "must be registered as a fiscal user and with right printer parameters.                   "
                #define STR0003 "Attention"
                #define STR0004 "Reading of Fiscal Memory "
                #define STR0005 "Objective of Program"
                #define STR0006 "               This program has the purpose of "
                #define STR0007 " making the printing of the fiscal memory of the fiscal printer "
                #define STR0008 " Bematech.                     "
                #define STR0009 "Initial Date:"
		        #define STR0010 "Final:"
                #define STR0011 "Printer OK   ?"
	#ELSE
	  #define STR0001 "Para emitir o relat¢rio da Mem¢ria Fiscal da impressora "
	  #define STR0002 "deve-se estar cadastrado como usu rio fiscal e com os parƒmetros da impressora corretos. "
	  #define STR0003 "Aten‡„o"
	  #define STR0004 "Leitura de Mem¢ria Fiscal"
	  #define STR0005 "Objetivo do Programa"
	  #define STR0006 "               Este programa tem como objetivo "
	  #define STR0007 " efetuar  a  impress„o   da leitura  de   mem¢ria    fiscal   da"
	  #define STR0008 " impressora   fiscal "
	  #define STR0009 "Data Inicial:"
	  #define STR0010 "Final:"
	  #define STR0011 "Impressora Ok?"
	#ENDIF
#ENDIF