#IFDEF SPANISH
	#define STR0001 "N§ de Factura"
	#define STR0002 "Serie Factura"
	#define STR0003 "Cliente     "
	#define STR0004 "Buscar "
	#define STR0005 "Visualizar"
	#define STR0006 "Incluir"
	#define STR0007 "Borrar "
	#define STR0008 "Facturas de Salida    "
	#define STR0009 "Factura de Salida de Mercader¡as"
	#define STR0010 "Tipo"
	#define STR0011 "Factura    "
	#define STR0012 "Serie"
	#define STR0013 "Emisi¢n"
	#define STR0014 "Proveedor "
	#define STR0015 "Cliente   "
	#define STR0016 "Tipo de Documento"
	#define STR0017 "Proveedor: "
	#define STR0018 "Cliente: "
	#define STR0019 "Total Factura"
	#define STR0020 "Confirma"
	#define STR0021 "Retipea "
	#define STR0022 "Salir   "
	#define STR0023 "Factura de Salida Mercader¡as"
	#define STR0024 "Tipo"
	#define STR0025 "Factura "
	#define STR0026 "Serie"
	#define STR0027 "Emisi¢n"
	#define STR0028 "Tipo de Documento"
	#define STR0029 "La Impresora no est  lista. ¨Tenta nuevamente?"
	#define STR0030 "¨ Imprime la N.F ?"
	#define STR0031 "¨ Formulario Colocado ?"
	#define STR0032 "   La al¡cuota de ICMS utilizada en este producto no est  registrada"
	#define STR0033 "en la Impresora Fiscal. Utilize la opci¢n Agrega Al¡cuota en el men£"
	#define STR0034 "Miscelanea, M¢dulo Fiscal, para registrarla en la Impresora."
	#define STR0035 "la al¡cuota no registrada es:"
	#define STR0036 "Atenci¢n"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "Invoice Numb"
                #define STR0002 "Invoice Serie"
                #define STR0003 "Customer    "
                #define STR0004 "Search   "
                #define STR0005 "View      "
                #define STR0006 "Insert "
                #define STR0007 "Delete "
                #define STR0008 "Outflow Invoice      "
                #define STR0009 "Outflow Invoice of Goods      "
                #define STR0010 "kind"
                #define STR0011 "Invoice    "
                #define STR0012 "Series"
                #define STR0013 "Issued "
                #define STR0014 "Supplier  "
                #define STR0015 "Customer  "
                #define STR0016 "Kind of Document "
                #define STR0017 "Supplier  : "
                #define STR0018 "Customer:"
                #define STR0019 "Invoice Total"
                #define STR0020 "OK      "
                #define STR0021 "Retype  "
                #define STR0022 "Quit    "
                #define STR0023 "Goods Inflow Invoice   "
                #define STR0024 "Kind"
                #define STR0025 "Invoice    "
                #define STR0026 "Series"
                #define STR0027 "Issuance"
                #define STR0028 "Kind of Document" 
			       #define STR0029 "Printer is not ready. Try again?             "
			       #define STR0030 "Print the Inv.?"
			       #define STR0031 "Form is positioned?  "
                #define STR0032 "The VAT rate used in this product is not registered "
                #define STR0033 "in the fiscal Printer .Use the option Add Rate in the menu         "
                #define STR0034 "Miscellaneous, Fiscal Module, in order to register it in the printer"
                #define STR0035 "the non registered rate is  : "
                #define STR0036 "Attention"
	#ELSE
		#define STR0001 "Numero da NF"
		#define STR0002 "Serie da NF "
		#define STR0003 "Cliente     "
		#define STR0004 "Pesquisar"
		#define STR0005 "Visualizar"
		#define STR0006 "Incluir"
		#define STR0007 "Excluir"
		#define STR0008 "Notas Fiscais de Sa¡da"
		#define STR0009 "Nota de Saida de Mercadorias"
		#define STR0010 "Tipo"
		#define STR0011 "Nota Fiscal"
		#define STR0012 "S‚rie"
		#define STR0013 "Emiss„o"
		#define STR0014 "Fornecedor"
		#define STR0015 "Cliente   "
		#define STR0016 "Tipo de Documento"
		#define STR0017 "Fornecedor: "
		#define STR0018 "Cliente: "
		#define STR0019 "Total da Nota"
		#define STR0020 "Confirma"
		#define STR0021 "Redigita"
		#define STR0022 "Abandona"
		#define STR0023 "Nota de Sa¡da Mercadorias"
		#define STR0024 "Tipo"
		#define STR0025 "Nota Fiscal"
		#define STR0026 "S‚rie"
		#define STR0027 "Emiss„o"
		#define STR0028 "Tipo de Documento"
		#define STR0029 "Impressora n„o est  pronta. Tentar novamente?"
		#define STR0030 "Imprime a N.F ?"
		#define STR0031 "Formul rio Inserido ?"
		#define STR0032 "A al¡quota de Icms utilizada neste produto n„o est  "
		#define STR0033 "cadastrada na Impressora fiscal. utilize a op‡„o adiciona Aliquota "
		#define STR0034 "no menu Miscelƒnea, M¢dulo fiscal, para cadastr -la na Impressora. "
		#define STR0035 "a al¡quota n„o cadastrada ‚ : "
		#define STR0036 "Aten‡„o"
	#ENDIF
#ENDIF