#IFDEF SPANISH
	#define STR0001 "Borrar Factura/Presupuesto"
	#define STR0002 "B£squeda"
	#define STR0003 "Borrar Fac/Pres."
	#define STR0004 "Esta venda s¢lo podr  ser borrada por la impresora fiscal que"
	#define STR0005 "la efectu¢. N£mero de la impresora que registr¢ la venda:    "
	#define STR0006 "Atenci¢n"
	#define STR0007 "Esta venta fue efectuada por otra caja "
	#define STR0008 "El Pdv que hizo la venta fue: "
	#define STR0009 "Por tratarse de impresora fiscal, s¢lo se podr  borrar el £ltimo"
	#define STR0010 "cup¢n vendido."
	#define STR0011 "Presupuesto"
	#define STR0012 "Su Pedido:"
	#define STR0013 "Cliente:"
	#define STR0014 "Vendedor:"
	#define STR0015 "Total de Mercader¡as:"
	#define STR0016 "Descuento:"
	#define STR0017 "Neto:"
	#define STR0018 "Validez:"
	#define STR0019 "Valor en caja menor que valor anulado,"
	#define STR0020 " los saldos no ser n actualizados"
	#define STR0021 "Saldo Insuficiente"
	#define STR0022 "¨Confirma Borrar Fac./Pres.?"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "Invoice/Budg.Exclusion"
                #define STR0002 "Search  "
                #define STR0003 "IN/Budg Exclus." 
                #define STR0004 "This sale can only be deleted by the Fiscal printer that "
                #define STR0005 "has issued it. Printer number that has registered the sale:      "
                #define STR0006 "Attention"
                #define STR0007 "This sale was carried out by another cashier"
                #define STR0008 "The Registr.Machine ref.to sale was:"
                #define STR0009 "Since it is a fiscal printer, only the last Ticket can be    "
                #define STR0010 "deleted.    (See convention VAT  - ......)   "
                #define STR0011 "Budget:   "
                #define STR0012 "Your Order:"
                #define STR0013 "Customer:"
                #define STR0014 "Seller  :"
                #define STR0015 "Total Goods:         "
                #define STR0016 "Discount:"
                #define STR0017 "Net:    "
                #define STR0018 "Validity:"
                #define STR0019 "Cashier Amount is smaller than cancelled one."
                #define STR0020 "the balances will not be updated"
                #define STR0021 "Insufficient Funds"
                #define STR0022 "Confirm Deleting of Invoice/Budget   ?"
	#ELSE
		#define STR0001 "Exclus„o N.F./Orcam."
		#define STR0002 "Pesquisa"
		#define STR0003 "Exclus„o NF/Orc."
		#define STR0004 "Esta venda s¢ poder  ser exclu¡da pela impressora fiscal "
		#define STR0005 "que efetuou a mesma. Numero da impressora que registrou a venda: "
		#define STR0006 "Aten‡„o"
		#define STR0007 "Esta venda foi efetuada por outro caixa "
		#define STR0008 "O Pdv que efetuou a venda foi: "
		#define STR0009 "Por se tratar de impressora fiscal, s¢ poder  ser excluido o £ltimo "
		#define STR0010 "Cupom vendido. (Vide convˆnio ICMS - 156/96)"
		#define STR0011 "Or‡amento:"
		#define STR0012 "Seu Pedido:"
		#define STR0013 "Cliente:"
		#define STR0014 "Vendedor:"
		#define STR0015 "Total de Mercadorias:"
		#define STR0016 "Desconto:"
		#define STR0017 "L¡quido:"
		#define STR0018 "Validade:"
		#define STR0019 "Valor em caixa menor que valor cancelado"
		#define STR0020 " os saldos n„o ser„o atualizados"
		#define STR0021 "Saldo Insuficiente"
		#define STR0022 "Confirma Exclus„o de N.F. / Or‡amento?"
	#ENDIF
#ENDIF