#IFDEF SPANISH
	#define STR0001 "Buscar   "
	#define STR0002 "Visualizar"
	#define STR0003 "Productos"
	#define STR0004 "PASE LA LECTORA"
	#define STR0005 "No hay historial para este producto"
	#define STR0006 "Consulta Stock  "
	#define STR0007 "C¢digo"
	#define STR0008 "Descripci¢n de Producto"
	#define STR0009 "Precio"
	#define STR0010 "­Producto No Registrado!"
	#define STR0011 "DE CODIGO DE BARRAS"
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "Search   "
                #define STR0002 "View      "
                #define STR0003 "Products"
                #define STR0004 "PASS THE READER"
                #define STR0005 "There is no record for this product   "
                #define STR0006 "Consult Inventory"
                #define STR0007 "Code  "
                #define STR0008 "Product Description "
                #define STR0009 "Price"
                #define STR0010 "Product Not Registered!"
                #define STR0011 "OF BAR CODE        "
	#ELSE
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Produtos"
		#define STR0004 "PASSE O LEITOR"
		#define STR0005 "NÆo existe hist¢rico para este produto"
		#define STR0006 "Consulta Estoque"
		#define STR0007 "C¢digo"
		#define STR0008 "Descri‡Æo de Produto"
		#define STR0009 "Pre‡o"
		#define STR0010 "Produto NÆo Cadastrado!"
		#define STR0011 "DE CODIGO DE BARRAS"
	#ENDIF
#ENDIF