#IFDEF SPANISH
	#define STR0001 "Atenci¢n"
	#define STR0002 "CLIENTE ESTANDAR"
	#define STR0003 "VENDEDOR ESTANDAR"
	#define STR0004 "A VISTA"
	#define STR0005 "ENTRADA MERCADERIAS"
	#define STR0006 "SALIDA DE MERCADERIAS"
	#define STR0007 "Clave sin validez"
	#define STR0008 "Autorizaci¢n para borrar TEF"
	#define STR0009 "Autorizaci¢n para venda forzada"
	#define STR0010 "Autorizaci¢n"
	#define STR0011 "Tipee la Clave:"
	#define STR0012 "Pase el "
	#define STR0013 " cheque y espera la lectura..."
	#define STR0014 "Error al abrir el puerto: "
	#define STR0015 "Error al cerrar el puerto: "
	#define STR0016 "Problemas con el archivo de Retorno"
	#define STR0017 "La Impresora no est  lista. ¨Intenta de nuevo?"
	#define STR0018 "Teste para Anular Cup¢n "
	#define STR0019 "La impresora fiscal no tiene ninguna al¡cuota de ICMS "
	#define STR0020 " registrada.  Use la opci¢n de Agregar Al¡cuotas para "
	#define STR0021 " registrar una."
	#define STR0022 "Impresora fiscal sin al¡cuota de ICMS registrada."
	#define STR0023 "Primero"
	#define STR0024 "Segundo"
	#define STR0025 "Tercero"
	#define STR0026 "Cuarto"
	#define STR0027 "Quinto"
	#define STR0028 "Sexto"
	#define STR0029 "S‚ptimo"
	#define STR0030 "Octavo"
	#define STR0031 "Nono"
	#define STR0032 "D‚cimo"
	#define STR0033 "Vig‚simo"
	#define STR0034 "Trig‚simo"
	#define STR0035 "Quadrag‚simo"
	#define STR0036 "Quinquag‚simo"
	#define STR0037 "Sexag‚simo"
	#define STR0038 "Septuag‚simo"
	#define STR0039 "Octog‚simo"
	#define STR0040 "Nonag‚simo"
	#define STR0041 "Cent‚simo"
	#define STR0042 "Aguarde por favor..."
	#define STR0043 "Error al tentar abrir la comunicaci¢n con la impresora en el puerto: "
	#define STR0044 " Verificar..."
	#define STR0045 "Error de comunicaci¢n f¡sica con la impresora."
	#define STR0046 " Revise si la impresora est  conectada al puerto o   "
	#define STR0047 " o si est  enchuflada.    ."
	#define STR0048 "Los par metros mandados a la impresora no tienen validez."
	#define STR0049 "Revisar  ..."
	#define STR0050 "La impresora no soporta el comando que le fue enviado.            "
	#define STR0051 "Error al tentar cerrar la comunicaci¢n con la impressora en el Puerto: "
	#define STR0052 "Problemas con la Impresora Fiscal"
	#define STR0053 "Dinero  "
	#define STR0054 "Devoluci¢n (Forma de pago)"
	#define STR0055 "Forma"
	#define STR0056 "Valor a devolver"
	#define STR0057 "CANCEL REF.DEVOL. VUELTO"
	#define STR0058 "DEV./VUELTO"
	#define STR0059 "El valor que ser  devuelto en esta forma de pago para el cliente no "
	#define STR0060 "est  disponible en caja. Elija otra forma o informe el supervisor. "
	#define STR0061 "Usted eligi¢: "
#ELSE
	#IFDEF ENGLISH
                #define STR0001 "Attention"
                #define STR0002 "STANDARD CUSTOM"
                #define STR0003 "STANDARD SELLER"
                #define STR0004 "SIGHT  "
                #define STR0005 "INFLOW OF GOODS    "
                #define STR0006 "OUTFLOW OF GOODS    "
                #define STR0007 "Invalid Password "
                #define STR0008 "Authorization for deletion TEF"
                #define STR0009 "Authorizat.for forced sale    "
                #define STR0010 "Authorizat."
                #define STR0011 "Type Password :"
                #define STR0012 "Pass the"
                #define STR0013 "Check and Wait the reading..."
                #define STR0014 "Error opening port:   "
                #define STR0015 "Error closing port:    "
                #define STR0016 "Problems with the Return file     "
                #define STR0017 "Printer is not ready. Try again?             "
                #define STR0018 "Ticket cancellation Test      "
                #define STR0019 "Thew fiscal printer does not have the VAT rate "
                #define STR0020 " registered. Use the option Add rates in order to register  "
                #define STR0021 " one.          "
                #define STR0022 "Fiscal Printer without VAT rate registered.       "
                #define STR0023 "First   "
                #define STR0024 "Second "
                #define STR0025 "Third   "
                #define STR0026 "Fourth"
                #define STR0027 "Fifth "
                #define STR0028 "Sixth"
                #define STR0029 "Seventh"
                #define STR0030 "Eighth"
                #define STR0031 "Ninth"
                #define STR0032 "Tenth"
                #define STR0033 "Twentieth"
                #define STR0034 "Thirtieth"
                #define STR0035 "Fourtieth   "
                #define STR0036 "Fiftieth     "
                #define STR0037 "Sixtieth    "
                #define STR0038 "Seventieth  "
                #define STR0039 "Eightieth  "
                #define STR0040 "Ninetieth  "
                #define STR0041 "One Hundredth"
                #define STR0042 "Wait please........."
                #define STR0043 "Error trying to open communication with Printer in Port:     "
                #define STR0044 " Check...    "
                #define STR0045 "Physical communication error with printer   "
                #define STR0046 " Check if printer is connected to port or if it "
                #define STR0047 " on.                       "
                #define STR0048 "The parameters sent to the printer are invalid          "
                #define STR0049 "Check ......"
                #define STR0050 "The command sent to the printer is not supported by it.        "
                #define STR0051 "Error trying to close the communication with Printer in Port: "
                #define STR0052 "Problems with Fiscal Printer     "
                #define STR0053 "Money   "
                #define STR0054 "Return (Payment Modality)     "
                #define STR0055 "Modal"
                #define STR0056 "Amount to Return"
                #define STR0057 "W.OFF REF. RETURN CHANGE"
                #define STR0058 "CHANGE"
                #define STR0059 "The amount to be returned to the Customer in this payment modality"
                #define STR0060 "is not available in the cashier. Select another modality or inform the supervisor"
                #define STR0061 "You chose:     "
	#ELSE
		#define STR0001 "Aten‡„o"
		#define STR0002 "CLIENTE PADRAO"
		#define STR0003 "VENDEDOR PADRAO"
		#define STR0004 "A VISTA"
		#define STR0005 "ENTRADA MERCADORIAS"
		#define STR0006 "SAIDA DE MERCADORIAS"
		#define STR0007 "Senha Inv lida"
		#define STR0008 "Autoriza‡„o para exclus„o TEF"
		#define STR0009 "Autoriza‡„o para venda for‡ada"
		#define STR0010 "Autoriza‡„o"
		#define STR0011 "Digite a Senha:"
		#define STR0012 "Passe o "
		#define STR0013 " cheque e Aguarde a leitura..."
		#define STR0014 "Erro abrindo a porta: "
		#define STR0015 "Erro Fechando a porta: "
		#define STR0016 "Problemas com o arquivo de Retorno"
		#define STR0017 "Impressora n„o est  pronta. Tentar novamente?"
		#define STR0018 "Teste de Cancelamento de Cupom"
		#define STR0019 "A impressora fiscal nao tem nenhuma aliquota de"
		#define STR0020 " ICMS cadastrada. Utilize a Op‡„o de Adiciona aliquotas para"
		#define STR0021 " cadastrar uma."
		#define STR0022 "Impressora fiscal sem aliquota de Icms cadastrada."
		#define STR0023 "Primeiro"
		#define STR0024 "Segundo"
		#define STR0025 "Terceiro"
		#define STR0026 "Quarto"
		#define STR0027 "Quinto"
		#define STR0028 "Sexto"
		#define STR0029 "S‚timo"
		#define STR0030 "Oit vo"
		#define STR0031 "Nono"
		#define STR0032 "D‚cimo"
		#define STR0033 "Vig‚simo"
		#define STR0034 "Trig‚simo"
		#define STR0035 "Quadrag‚simo"
		#define STR0036 "Quinquag‚simo"
		#define STR0037 "Sexag‚simo"
		#define STR0038 "Septuag‚simo"
		#define STR0039 "Octog‚simo"
		#define STR0040 "Nonag‚simo"
		#define STR0041 "Cent‚simo"
		#define STR0042 "Aguarde por favor..."
		#define STR0043 "Erro ao tentar abrir a comunica‡„o com a Impressora na Porta: "
		#define STR0044 " Verificar..."
		#define STR0045 "Erro de comunica‡„o f¡sica com a impressora."
		#define STR0046 " Verifique se a impressora est  conectada a porta "
		#define STR0047 " ou se a mesma est  ligada."
		#define STR0048 "Os parƒmetros enviados para a impressoras s„o inv lidos "
		#define STR0049 "Verificar..."
		#define STR0050 "O comando enviado para a impressora n„o ‚ suportado pela mesma."
		#define STR0051 "Erro ao tentar fechar a comunica‡„o com a Impressora na Porta: "
		#define STR0052 "Problemas com a Impressora Fiscal"
		#define STR0053 "Dinheiro"
		#define STR0054 "Devolu‡„o (Forma de pagamento)"
		#define STR0055 "Forma"
		#define STR0056 "Valor a devolver"
		#define STR0057 "BAIXA REF. DEVOL. TROCA"
		#define STR0058 "DEV./TROCA"
		#define STR0059 "O valor a ser devolvido nesta forma de pagamento para o cliente "
		#define STR0060 "n„o est  dispon¡vel em caixa. Escolha outra forma ou informe o supervisor."
		#define STR0061 "Vocˆ escolheu: "
	#ENDIF
#ENDIF