#IFDEF SPANISH
         #define STR0001  "C¢dig.Sucursal"
         #define STR0002  "Fecha Emisi¢n"
         #define STR0003  "N£mero de la SC"
         #define STR0004  "Abandona"
         #define STR0005  "Confirma"
         #define STR0006  "bUscar    "
         #define STR0007  "Visualizar"
         #define STR0008  "Incluir"
         #define STR0009  "Modificar"
         #define STR0010  "Borrar "
         #define STR0011  "Solicitud de Compras"
         #define STR0012  "&N£mero"
         #define STR0013  "&Solicitante"
         #define STR0014  "&Fecha de Emisi¢n"
         #define STR0015  "C&entro de Costo"
         #define STR0016  "&Unid. Requis."
         #define STR0017  "&C¢d. Comprador"
         #define STR0018  "Requisitante: "
         #define STR0019  "Comprador: "
	 #define STR0020  "­Solicitud en Pedido! ¨Confirma Exclusi¢n?"
    	 #define STR0021  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Branch Code  "
         #define STR0002  "Issue Date   "
         #define STR0003  "Number of PR"
         #define STR0004  "Cancel  "
         #define STR0005  "O.K.   "
         #define STR0006  "Search   "
         #define STR0007  "View     "
         #define STR0008  "Insert" 
         #define STR0009  "Edit   "
         #define STR0010  "Delete "
         #define STR0011  "Purchase Requests"
         #define STR0012  "&Number"
         #define STR0013  "&Requestor  "
         #define STR0014  "&Issue Date     "
         #define STR0015  "C&ost Center "
         #define STR0016  "&Request.Unit"
         #define STR0017  "&Buyer Code    "
         #define STR0018  "Requestor   : "
         #define STR0019  "Buyer       :  "
         #define STR0020  "Request in Order  !  Confirm Deleting? "
         #define STR0021  "Attention"

   #ELSE
         #define STR0001  "Codig.Filial"
         #define STR0002  "Data Emissao"
         #define STR0003  "Numero da SC"
         #define STR0004  "Abandona"
         #define STR0005  "Confirma"
         #define STR0006  "Pesquisar"
         #define STR0007  "Visualizar"
         #define STR0008  "Incluir"
         #define STR0009  "Alterar"
         #define STR0010  "Excluir"
         #define STR0011  "Solicita‡„o de Compras"
         #define STR0012  "&N£mero"
         #define STR0013  "&Solicitante"
         #define STR0014  "&Data de Emiss„o"
         #define STR0015  "C&entro Custo"
         #define STR0016  "&Unid. Requis."
         #define STR0017  "&Cod. Comprador"
         #define STR0018  "Requisitante: "
         #define STR0019  "Comprador: "
	 #define STR0020  "Solicitacao em Pedido! Confirma Exclusao?"
	 #define STR0021  "Aten‡„o"

   #ENDIF
#ENDIF
