#IFDEF SPANISH
         #define STR0001  "N£mero del PC"
         #define STR0002  "Proveedor    "
         #define STR0003  "Abandona"
         #define STR0004  "Confirma"
         #define STR0005  "bUscar    "
         #define STR0006  "Aprobar"
         #define STR0007  "Devolver Liberaci¢n"
         #define STR0008  "Autom tico"
         #define STR0009  "Aprobaci¢n del PC"
         #define STR0010  "Seleccionando Registros..."
         #define STR0011  "Aprobaci¢n del Pedido de Compra"
         #define STR0012  "L¡mite por operaci¢n :"
         #define STR0013  "Saldo :"
         #define STR0014  "&N£mero :"
         #define STR0015  "C&ontacto :"
         #define STR0016  "&Emisi¢n :"
         #define STR0017  "&Proveedor :"
         #define STR0018  "&Cod. Pago :"
         #define STR0019  "&Sucur. p.Entrega :"
         #define STR0020  "C lculo I V A: "
         #define STR0021  "Proveedor  :"
         #define STR0022  "Devoluci¢n de la Aprobaci¢n del P.Compras "
         #define STR0023  "Aprobaci¢n Autom tica de Pedidos de Compras "
         #define STR0024  "El objetivo de este programa es generar autom ticamente           "
         #define STR0025  "las aprobaciones de pedidos, tomando como base el Control de       "
         #define STR0026  "Pertinencias, conforme lo definido para cada usuario.                "
         #define STR0027  "Buscar    "
         #define STR0028  "N£mero + Ötem"
         #define STR0029  "Nota de pi‚ del P.Compra"
         #define STR0030  "Tipo Flete"
         #define STR0031  "Reaj."
         #define STR0032  "Descuentos%"
         #define STR0033  "Flete"
         #define STR0034  "I V A "
         #define STR0035  "Descuento"
         #define STR0036  "Total del Pedido"
         #define STR0037  "&Emisi¢n :"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "P. Order Nr."
         #define STR0002  "Supplier    "
         #define STR0003  "Cancel  "
         #define STR0004  "O.K.   "
         #define STR0005  "Search   "
         #define STR0006  "Release"
         #define STR0007  "Reverse Release   "
         #define STR0008  "Automatic "
         #define STR0009  "Release of PR  "
         #define STR0010  "Selecting Records..."
         #define STR0011  "Release of Purchase Order    "
         #define STR0012  "Limit per Operation :"
         #define STR0013  "Balance:"
         #define STR0014  "&Number :"
         #define STR0015  "Contact  :"
         #define STR0016  "&Issue   :"
         #define STR0017  "&Supplier   :"
         #define STR0018  "&Paym.Code  :"
         #define STR0019  "&Branch f/Delivery:"
         #define STR0020  "Calcul Exc.Tx"
         #define STR0021  "Supplier   :"
         #define STR0022  "Reversal of Purchase Order Release     "
         #define STR0023  "Automatic Release of Purchase Order      "
         #define STR0024  "The purpose of this program is to generate automatically        "
         #define STR0025  "the order releases, based on the control of the                  "
         #define STR0026  "Abilities, as indicates for each user.                             "
         #define STR0027  "Search   "
         #define STR0028  "Number + Item"
         #define STR0029  "Footer of Purchase Order  "
         #define STR0030  "Freight Mod."
         #define STR0031  "Readj."
         #define STR0032  "Descounts%"
         #define STR0033  "Freight"
         #define STR0034  "Exc.Tx"
         #define STR0035  "Discount"
         #define STR0036  "Total of Order "
         #define STR0037  "&Issue   :"
   #ELSE
         #define STR0001  "Numero do PC"
         #define STR0002  "Fornecedor  "
         #define STR0003  "Abandona"
         #define STR0004  "Confirma"
         #define STR0005  "Pesquisar"
         #define STR0006  "Liberar"
         #define STR0007  "Estornar Libera‡„o"
         #define STR0008  "Autom tico"
         #define STR0009  "Libera‡„o de PC"
         #define STR0010  "Selecionando Registros..."
         #define STR0011  "Libera‡„o do Pedido de Compra"
         #define STR0012  "Limite por opera‡„o :"
         #define STR0013  "Saldo :"
         #define STR0014  "&N£mero :"
         #define STR0015  "C&ontato :"
         #define STR0016  "&Emiss„o :"
         #define STR0017  "&Fornecedor :"
         #define STR0018  "&Cod. Pagto :"
         #define STR0019  "&Filial p/Entrega :"
         #define STR0020  "C lculo IPI :"
         #define STR0021  "Fornecedor :"
         #define STR0022  "Estorno da Libera‡„o do Pedido de Compra"
         #define STR0023  "Libera‡„o Automatica de Pedidos de Compras"
         #define STR0024  "Este programa tem como objetivo gerar automaticamente           "
         #define STR0025  "as libera‡”es de pedidos, tomando-se como base o controle         "
         #define STR0026  "de Al‡adas, conforme definido para cada usu rio.                  "
         #define STR0027  "Pesquisar"
         #define STR0028  "Número + Item"
         #define STR0029  "Rodapé do Pedido de Compra"
         #define STR0030  "Tipo Frete"
         #define STR0031  "Reaj."
         #define STR0032  "Descontos%"
         #define STR0033  "Frete"
         #define STR0034  "IPI"
         #define STR0035  "Desconto"
         #define STR0036  "Total do Pedido"
         #define STR0037  "&Emiss„o :"
   #ENDIF
#ENDIF
