#IFDEF SPANISH
         #define STR0001  "Esta rutina ser  ejecutada en modo"
         #define STR0002  "compartido, conforme indicado por"
         #define STR0003  "el par metro MV_CUSTEXC."
         #define STR0004  "Los movimientos que ocurran durante el"
         #define STR0005  "proceso pueden influir en el c lculo."
         #define STR0006  "ATENCIàN"
         #define STR0007  "Rec lculo de los Saldos"
         #define STR0008  "El objetivo de este programa es recalcular el saldo actual de todos los ¡tems del Stock (en Cantidad y Valor)."
         #define STR0009  "Comienza en el saldo inicial del per¡odo y considerar  todas las Facturas de Entrada, Facturas de Salida, "
         #define STR0010  "Solicitudes, Devoluciones y Producciones hechas hasta el momento."
         #define STR0011  "Efectuando Rec lculo de los Saldos..."
         #define STR0012  "Esta rutina exige que los archivos a   "
         #define STR0013  "ella asociados no est‚n siendo usados  "
         #define STR0014  "por otras estaciones."
         #define STR0015  "Haga con que los otros usuarios salgan  "
         #define STR0016  "del sistema."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "This routine will  be executed in"
         #define STR0002  "sharing mode, as indicated    "
         #define STR0003  "by parameter  MV_CUSTEXC. "
         #define STR0004  "The transactions that occur during "
         #define STR0005  "the process can affect calculation."
         #define STR0006  "ATTENT."
         #define STR0007  "Recalculating Balances"
         #define STR0008  "This program has the purpose of recalculating the current balance of Inventory items (in Quantity and Value)."
         #define STR0009  "It starts from the initial balance of period and will consider all Inflow and Outflow Invoices,Requisitions"
         #define STR0010  "Return to Vendor and Productions occured up to the current date"
         #define STR0011  "Recalculating the Balances...    "
         #define STR0012  "This routine requires that files to it     "
         #define STR0013  "associated are not being used by other"
         #define STR0014  "stations      ."
         #define STR0015  "Make sure other users exit the     "
         #define STR0016  "System. "
   #ELSE
         #define STR0001  "Esta rotina ser  executada em modo"
         #define STR0002  "compartilhado , conforme indicado"
         #define STR0003  "pelo parƒmetro MV_CUSTEXC."
         #define STR0004  "As movimenta‡”es que ocorrerem durante"
         #define STR0005  "o processo podem influir no c lculo."
         #define STR0006  "ATEN€ŽO"
         #define STR0007  "Recalculo dos Saldos"
         #define STR0008  "Este programa tem o objetivo de recalcular o saldo atual de todos os itens do Estoque (em Quantidade e Valor)."
         #define STR0009  "Ele partir  do saldo inicial do per¡odo e considerar  todas as Notas Fiscais de Entrada , Notas Fiscais"
         #define STR0010  "de Sa¡da , Requisi‡”es ,Devolu‡”es e Produ‡”es feitas at‚ o momento."
         #define STR0011  "Efetuando Rec lculo dos Saldos..."
         #define STR0012  "Esta  rotina  exige  que  os   arquivos"
         #define STR0013  "associados a ela n†o estejam em uso por"
         #define STR0014  "outras esta‡”es."
         #define STR0015  "Fa‡a com que os outros usu rios saiam do"
         #define STR0016  "sistema."
   #ENDIF
#ENDIF