#IFDEF SPANISH
         #define STR0001  "Proyecci¢n de Stocks"
         #define STR0002  "Periodicidad de la Proyecci¢n"
         #define STR0003  "Per¡odo Diario"
         #define STR0004  "Per¡odo Semanal"
         #define STR0005  "Per¡odo Quincenal"
         #define STR0006  "Per¡odo Mensal"
         #define STR0007  "Per¡odo Trimestral"
         #define STR0008  "Per¡odo Semestral"
         #define STR0009  "Per¡odos Diversos"
         #define STR0010  "Cantidad de Per¡odos:"
         #define STR0011  "Utiliza el Plazo de Entrega para proyectar el desembolso Financiero"
         #define STR0012  "Plazo Medio de Pago:"
         #define STR0013  "Considera Pedidos en Cartera"
         #define STR0014  "Tipos de Material"
         #define STR0015  "Grupos de Material"
         #define STR0016  "Apertura de Archivos"
         #define STR0017  "Abriendo Archivos..."
         #define STR0018  "¨Confirma la proyecci¢n de Stock?"
         #define STR0019  "Atenci¢n"
         #define STR0020  "bUscar    "
         #define STR0021  "&Visualizar"
         #define STR0022  "&Imprimir"
         #define STR0023  "&Generar OP/SC"
         #define STR0024  "&Abandonar"
         #define STR0025  "Esta Rutina generar  las Ordenes de Producci¢n y las Solicitudes de"
         #define STR0026  "Compra  necesarias para  satisfacer el  c lculo de la proyecci¢n de"
         #define STR0027  "stocks. Certifique que  realmente  los  c lculos de las necesidades"
         #define STR0028  "est‚n correctas, antes de generar estos documentos en los archivos."
         #define STR0029  "Los  per¡odos  para  generaci¢n  pueden  ser escojidos a trav‚s del"
         #define STR0030  "bot¢n de par metros."
         #define STR0031  "¨Confirma Generaci¢n de OPS y SCS?"
         #define STR0032  "SC's"
         #define STR0033  "OP's"
         #define STR0034  "Emite OP's y SC's"
         #define STR0035  "Emitindo OP's y SC's para las previsiones de Venda ..."
         #define STR0036  "Proyecci¢n de Necesidades"
         #define STR0037  "Calculando Necesidades ..."
         #define STR0038  "Per¡odos para generaci¢n de "
         #define STR0039  "Visualizar"
         #define STR0040  "Descripci¢n:"
         #define STR0041  "UM:"
         #define STR0042  "Grupo:"
         #define STR0043  "Alternativo:"
         #define STR0044  "Saldo:"
         #define STR0045  "Punto de Pedido:"
         #define STR0046  "Stock de Seguridad:"
         #define STR0047  "Plazo de Entrega:"
         #define STR0048  "Lote Econ¢mico:"
         #define STR0049  "Lote M¡nimo:"
         #define STR0050  "Tolerancia:"
         #define STR0051  "Fc. L¡mite Compra/Producci¢n:"
         #define STR0052  "bUscar    "
         #define STR0053  "Producto a Localizar "
         #define STR0054  "Selecci¢n de Per¡odos Variables"
         #define STR0055  "Per¡odos"
         #define STR0056  "Fecha:"
         #define STR0057  "Seleccionando Registros..."
         #define STR0058  "Proyecci¢n de SCs"
         #define STR0059  "Analisando SCs ..."
         #define STR0060  "Proyecci¢n de Pedidos de Compra"
         #define STR0061  "Analisando Pedidos de Compra ..."
         #define STR0062  "Proyecci¢n de Saldos Iniciales"
         #define STR0063  "Analisando Saldos Iniciales ..."
         #define STR0064  "Proyecci¢n del Plan Principal de Producci¢n"
         #define STR0065  "Analisando Plan Principal de Producci¢n ..."
         #define STR0066  "Rec lculo de Necesidades"
         #define STR0067  "Recalculando Necesidades ..."
         #define STR0068  "Proyecci¢n de OPs"
         #define STR0069  "Analisando OPs ..."
         #define STR0070  "Proyecci¢n de Pedidos de Venta"
         #define STR0071  "Analisando Pedidos de Venta ..."
         #define STR0072  "Proyecci¢n de Previsiones de Venta"
         #define STR0073  "Analisando Previsiones de Venta ..."
         #define STR0074  "Proyecci¢n de Solicitaciones de Compra"
         #define STR0075  "Analisando Solicitaciones de Compra ..."
         #define STR0076  "Proyecci¢n de Pedidos de Compra"
         #define STR0077  "Analisando Pedidos de Compra ..."
         #define STR0078  "Proyecci¢n de Reservas"
         #define STR0079  "Analisando Reservas ..."
         #define STR0080  "Saldo Ant. "
         #define STR0081  "Entradas   "
         #define STR0082  "Salidas    "
         #define STR0083  "Saldo      "
         #define STR0084  "Necesidad  "
         #define STR0085  "Valor      "
         #define STR0086  "FORA DE LA FECHA CONTR. APARCERÖA"
         #define STR0087  "SIN CONTRATO DE APARCERÖA"
         #define STR0088  "Generando Indice Cond.Saldos"
         #define STR0089  "An lisis de OPs e PPPs"
         #define STR0090  "Analisando OPs e PPPs ..."
         #define STR0091  "Generando Öndice OP's"
         #define STR0092  "Generando Öndice PPP's"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Stock Projections"
         #define STR0002  "Projection Periodicity"
         #define STR0003  "Daily Period"
         #define STR0004  "Weekly Period"
         #define STR0005  "Fortnightly Period"
         #define STR0006  "Monthly Period"
         #define STR0007  "Quarterly Period"
         #define STR0008  "Six Month Period"
         #define STR0009  "Different Periods"
         #define STR0010  "Number of Periods:"
         #define STR0011  "Use the delivery term for projecting Financial Disbursement"
         #define STR0012  "Average Period of Payment:"
         #define STR0013  "Consider Orders in Portfolio"
         #define STR0014  "Kinds of Material"
         #define STR0015  "Groups of Material"
         #define STR0016  "Opening of Files"
         #define STR0017  "Opening Files..."
         #define STR0018  "Confirms Stock Projection?"
         #define STR0019  "Attention"
         #define STR0020  "&Search"
         #define STR0021  "&View"
         #define STR0022  "&Print"
         #define STR0023  "&Gener.PO/PR"
         #define STR0024  "&Quit"
         #define STR0025  "This Routine will generate Production Orders and Purchase Requisit."
         #define STR0026  "necessary for making the calculation of stock projection."
         #define STR0027  "Make sure that the calculations of necessities are really correct"
         #define STR0028  "before generating these documents in the Files."
         #define STR0029  "The periods for generation can be chosen through the parameter"
         #define STR0030  "buttons."
         #define STR0031  "Confirm Generation POs and PRs ?"
         #define STR0032  "PR's"
         #define STR0033  "PO's"
         #define STR0034  "Issue PO's and PR's"
         #define STR0035  "Issuing  PO's and PR's for Sales forecast ..."
         #define STR0036  "Projection of Necessities"
         #define STR0037  "Calculating Necessities ..."
         #define STR0038  "Period for generation of"
         #define STR0039  "View"
         #define STR0040  "Descript.:"
         #define STR0041  "SU:"
         #define STR0042  "Group:"
         #define STR0043  "Alternative:"
         #define STR0044  "Balance"
         #define STR0045  "Order Condition:"
         #define STR0046  "Safety Stock:"
         #define STR0047  "Delivery Term    "
         #define STR0048  "Economic Lot:"
         #define STR0049  "Minimum Lot:"
         #define STR0050  "Tolerance:"
         #define STR0051  "Purchase/Product.Limit Date:"
         #define STR0052  "Search"
         #define STR0053  "Product to Find "
         #define STR0054  "Selection of Variable Periods"
         #define STR0055  "Periods"
         #define STR0056  "Date:"
         #define STR0057  "Selecting Records..."
         #define STR0058  "Projection of PRs"
         #define STR0059  "Analysing PRs ..."
         #define STR0060  "Projection Purchase Orders"
         #define STR0061  "Analysing Purchase Orders ..."
         #define STR0062  "Projection of Initial Balances"
         #define STR0063  "Analysing Initial Balances..."
         #define STR0064  "Projection of Production Master Plan"
         #define STR0065  "Analysing the Production Master Plan..."
         #define STR0066  "Recalculation of Necessities"
         #define STR0067  "Recalculating Necessities... "
         #define STR0068  "Projection of Production Orders   "
         #define STR0069  "Analysing  PO's..."
         #define STR0070  "Projection of Sales Orders"
         #define STR0071  "Analysing Sales Orders ..."
         #define STR0072  "Projection of Sales Forecast"
         #define STR0073  "Analysing Sales Forecast ..."
         #define STR0074  "Projection of Purchase Orders"
         #define STR0075  "Analysing Purchase Requests ..."
         #define STR0076  "Projection of Purchase Orders"
         #define STR0077  "Analysing Purchase Orders ..."
         #define STR0078  "Allocation Projection    "
         #define STR0079  "Allocation Analisys... "
         #define STR0080  "Prev.Balance"
         #define STR0081  "Inflows   "
         #define STR0082  "Outflows   "
         #define STR0083  "Balance    "
         #define STR0084  "Necessity"
         #define STR0085  "Value      "
         #define STR0086  "OUT OF PARTNERSHIP CONTR.DATE"
         #define STR0087  "WITHOUT PARTNERSHIP CONTRACT"
         #define STR0088  "Gerating Ind.Cond.Balances"
         #define STR0089  "Analysis of POs and PPPs"
         #define STR0090  "Analysing POs and PPPs ..."
         #define STR0091  "Generating PO's Index"
         #define STR0092  "Generat.PPP's index"
   #ELSE
         #define STR0001  "Proje‡„o de Estoques"
         #define STR0002  "Periodicidade da Proje‡„o"
         #define STR0003  "Per¡odo Di rio"
         #define STR0004  "Per¡odo Semanal"
         #define STR0005  "Per¡odo Quinzenal"
         #define STR0006  "Per¡odo Mensal"
         #define STR0007  "Per¡odo Trimestral"
         #define STR0008  "Per¡odo Semestral"
         #define STR0009  "Per¡odos Diversos"
         #define STR0010  "Quantidade de Per¡odos:"
         #define STR0011  "Utiliza o Prazo de Entrega para projetar o desembolso Financeiro"
         #define STR0012  "Prazo M‚dio de Pagamento:"
         #define STR0013  "Considera Pedidos em Carteira"
         #define STR0014  "Tipos de Material"
         #define STR0015  "Grupos de Material"
         #define STR0016  "Abertura de Arquivos"
         #define STR0017  "Abrindo Arquivos..."
         #define STR0018  "Confirma a proje‡„o de Estoque?"
         #define STR0019  "Aten‡„o"
         #define STR0020  "&Pesquisar"
         #define STR0021  "&Visualizar"
         #define STR0022  "&Imprimir"
         #define STR0023  "&Gerar OP/SC"
         #define STR0024  "&Abandonar"
         #define STR0025  "Esta Rotina ir  gerar as Ordens de Produ‡„o e as Solicita‡”es de"
         #define STR0026  "Compra necess rias para atender o c lculo da proje‡„o de estoques."
         #define STR0027  "Certifique-se de que realmente os c lculos das necessidades est„o"
         #define STR0028  "corretos antes de gerar estes documentos nos Arquivos."
         #define STR0029  "Os per¡odos para gera‡„o podem ser escolhidos atrav‚s do bot„o de"
         #define STR0030  "parƒmetros."
         #define STR0031  "Confirma Gera‡„o de OPS e SCS ?"
         #define STR0032  "SC's"
         #define STR0033  "OP's"
         #define STR0034  "Emite OP's e SC's"
         #define STR0035  "Emitindo OP's e SC's para as previsoes de Venda ..."
         #define STR0036  "Proje‡„o de Necessidades"
         #define STR0037  "Calculando Necessidades ..."
         #define STR0038  "Periodos para gera‡„o de "
         #define STR0039  "Visualizar"
         #define STR0040  "Descri‡„o:"
         #define STR0041  "UM:"
         #define STR0042  "Grupo:"
         #define STR0043  "Alternativo:"
         #define STR0044  "Saldo:"
         #define STR0045  "Ponto de Pedido:"
         #define STR0046  "Estoque de Seguran‡a:"
         #define STR0047  "Prazo de Entrega:"
         #define STR0048  "Lote Econ“mico:"
         #define STR0049  "Lote M¡nimo:"
         #define STR0050  "Tolerƒncia:"
         #define STR0051  "Dt. Limite Compra/Produ‡„o:"
         #define STR0052  "Pesquisar"
         #define STR0053  "Produto a Localizar "
         #define STR0054  "Sele‡„o de Per¡odos Vari veis"
         #define STR0055  "Per¡odos"
         #define STR0056  "Data:"
         #define STR0057  "Selecionando Registros..."
         #define STR0058  "Proje‡„o de SCs"
         #define STR0059  "Analisando SCs ..."
         #define STR0060  "Proje‡„o de Pedidos de Compra"
         #define STR0061  "Analisando Pedidos de Compra ..."
         #define STR0062  "Proje‡„o de Saldos Iniciais"
         #define STR0063  "Analisando Saldos Iniciais ..."
         #define STR0064  "Proje‡„o do Plano Mestre de Produ‡„o"
         #define STR0065  "Analisando Plano Mestre de Producao ..."
         #define STR0066  "Recalculo de Necessidades"
         #define STR0067  "Recalculando Necessidades ..."
         #define STR0068  "Proje‡„o de OPs"
         #define STR0069  "Analisando OPs ..."
         #define STR0070  "Proje‡„o de Pedidos de Venda"
         #define STR0071  "Analisando Pedidos de Venda ..."
         #define STR0072  "Proje‡„o de Previs”es de Venda"
         #define STR0073  "Analisando Previsoes de Venda ..."
         #define STR0074  "Proje‡„o de Solicita‡”es de Compra"
         #define STR0075  "Analisando Solicitacoes de Compra ..."
         #define STR0076  "Proje‡„o de Pedidos de Compra"
         #define STR0077  "Analisando Pedidos de Compra ..."
         #define STR0078  "Proje‡„o de Empenhos"
         #define STR0079  "Analisando Empenhos ..."
         #define STR0080  "Saldo Ant. "
         #define STR0081  "Entradas   "
         #define STR0082  "Saidas     "
         #define STR0083  "Saldo      "
         #define STR0084  "Necessidade"
         #define STR0085  "Valor      "
         #define STR0086  "FORA DA DATA CONTR. PARCERIA"
         #define STR0087  "SEM CONTRATO DE PARCERIA"
         #define STR0088  "Gerando Indice Cond.Saldos"
         #define STR0089  "Analise de OPs e PMPs"
         #define STR0090  "Analisando OPs e PMPs ..."
         #define STR0091  "Gerando Indice OP's"
         #define STR0092  "Gerando Indice PMP's"
   #ENDIF
#ENDIF
