#IFDEF SPANISH
         #define STR0001  "Confirma"
         #define STR0002  "Retipea"
         #define STR0003  "Abandona"
         #define STR0004  "Procesar"
         #define STR0005  "Esta rutina ser  ejecutada en modo"
         #define STR0006  "compartido,  conforme indicado por"
         #define STR0007  "el par metro MV_CUSTEXC."
         #define STR0008  "Los movimientos que ocurran durante el"
         #define STR0009  "proceso pueden influir en el c lculo."
         #define STR0010  "ATENCIàN"
         #define STR0011  "Rec lculo del Costo Medio" 
         #define STR0012  "Este programa permite que el costo medio sea recalculado de tres formas diferentes, atendiendo"
         #define STR0013  "cualquier exigencia legal."
         #define STR0014  "Fecha Inicial de Procesamiento : "
         #define STR0015  "Efectuando Rec lculo del Costo Medio..."
         #define STR0016  "Seleccionando Entradas..."
         #define STR0017  "Seleccionando Salidas..."
         #define STR0018  "Seleccionando Movimientos..."
         #define STR0019  "Seleccionando Dev.Venta..." 
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "OK     "
         #define STR0002  "Retype "
         #define STR0003  "Quit "
         #define STR0004  "Process  "
         #define STR0005  "This rouitine will be executed in sharing "
         #define STR0006  "mode, as indicated            "
         #define STR0007  "by parameter MV_CUSTEXC.  "
         #define STR0008  "The transactions that occur during    "
         #define STR0009  "the process can affect calculation ."
         #define STR0010  "ATTENTION"
         #define STR0011  "Recalculating Average Cost"
         #define STR0012  "This program allows the average cost to be recalculated in three different ways, attending  "
         #define STR0013  "any legal requirement. "
         #define STR0014  "Initial Processing Date:        "
         #define STR0015  "Recalculating Average Cost ...      "
         #define STR0016  "Selecting Inputs...    "
         #define STR0017  "Selecting Outputs...   "
         #define STR0018  "Selecting Transactions... "
         #define STR0019  "Selecting Sales Return..."
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Processar"
         #define STR0005  "Esta rotina ser  executada em modo"
         #define STR0006  "compartilhado , conforme indicado"
         #define STR0007  "pelo parƒmetro MV_CUSTEXC."
         #define STR0008  "As movimenta‡”es que ocorrerem durante"
         #define STR0009  "o processo podem influir no c lculo."
         #define STR0010  "ATEN€ŽO"
         #define STR0011  "Rec lculo do Custo M‚dio"
         #define STR0012  "Este programa permite que o custo m‚dio seja recalculado de trˆs formas diferentes, atendendo"
         #define STR0013  "qualquer exigˆncia legal."
         #define STR0014  "Data Inicial de Processamento : "
         #define STR0015  "Efetuando Recalculo do Custo Medio..."
         #define STR0016  "Selecionando Entradas..."
         #define STR0017  "Selecionando Saidas..."
         #define STR0018  "Selecionando Movimentos..."
         #define STR0019  "Selecionando Dev.Venda..."
   #ENDIF
#ENDIF
