#IFDEF SPANISH
    #define STR0001  "Cierre de Presupuestos"
    #define STR0002  "bUscar"
    #define STR0003  "Visualizar"
    #define STR0004  "Borrar"
    #define STR0005  "Cerrar"
    #define STR0006  "cAncelar"
    #define STR0007  "Buscar"
    #define STR0008  "Visual"
    #define STR0009  "ATENCIàN"
    #define STR0010  "Las OP's intermediarias y las SC's no " COLOR "b/bg"
    #define STR0011  "fueron generadas." COLOR "b/bg"
    #define STR0012  "Las opciones son:" COLOR "b/bg"
    #define STR0013  "  - Confirmar para generarlas ahora   " COLOR "b/bg"
    #define STR0014  "  - Cancelar  para generarlas despu‚s " COLOR "b/bg"
    #define STR0015  "Confirma"
    #define STR0016  "Cancelar"
    #define STR0017  "CA"
    #define STR0018  "Generando "
    #define STR0019  "Generaci¢n de OPs Intermediarias y SCs"
    #define STR0020  "Generaci¢n de OPs Intermediarias y SCs..."
    #define STR0021  "Orden de Producci¢n"
    #define STR0022  "Pedido de Venta"
    #define STR0023  "Reserva"	 
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Budget Write off"
         #define STR0002  "Search   "
         #define STR0003  "View      "
         #define STR0004  "Delete "
         #define STR0005  "Effective"
         #define STR0006  "Delete"
         #define STR0007  "Search"
         #define STR0008  "View  "
         #define STR0009  "ATTENTION"
         #define STR0010  "The intermediary POs and the PRs non " COLOR "b/bg"
         #define STR0011  "were generated" COLOR "b/bg"
         #define STR0012  "The options are"COLOR "b/bg"
         #define STR0013  "   - Confirm to generate them now  " COLOR "b/bg"
         #define STR0014  "   - Quit to generate them later      " COLOR "b/bg"
         #define STR0015  "O.K.    "
         #define STR0016  "Quit    "
         #define STR0017  "CA"
         #define STR0018  "Generating.."
         #define STR0019  "Generation of Intermediary POs& PRs"
         #define STR0020  "Generating Intermediary POs &PRs..."
         #define STR0021  "Production Order   "
         #define STR0022  "Sales Order    " 
         #define STR0023  "Allocate"
   #ELSE
         #define STR0001  "Baixa de Or‡amentos"
         #define STR0002  "Pesquisar"
         #define STR0003  "Visualizar"
         #define STR0004  "Excluir"
         #define STR0005  "eFetiva"
         #define STR0006  "Cancelar"
         #define STR0007  "Pesq."
         #define STR0008  "Visual"
         #define STR0009  "ATEN€„O"
         #define STR0010  "As OP'S intermediarias e as SC's n„o " COLOR "b/bg"
         #define STR0011  "foram geradas." COLOR "b/bg"
         #define STR0012  "As Op‡”es s„o:" COLOR "b/bg"
         #define STR0013  "   - Confirmar para gera-las agora " COLOR "b/bg"
         #define STR0014  "   - Abandonar para gera‡„o posterior " COLOR "b/bg"
         #define STR0015  "Confirma"
         #define STR0016  "Abandona"
         #define STR0017  "CA"
         #define STR0018  "Gerando..."
         #define STR0019  "Gera‡„o de OPs Intermediarias e SCs"
         #define STR0020  "Gerando OPs Intermediarias e SCs..."
         #define STR0021  "Ordem de Produ‡„o"
         #define STR0022  "Pedido de Venda" 
         #define STR0023  "Empenhos"
   #ENDIF
#ENDIF
