#IFDEF SPANISH
         #define STR0001  "Procesar"
         #define STR0002  "Ajuste del Inventario"
         #define STR0003  "Este programa generar  movimientos de ajuste para corregir el saldo del stock."
         #define STR0004  "Estos movimientos ser n baseados en los recuentos realizados y registrados en la Rutina Inventario."
         #define STR0005  "El programa deber  generar un Requerimiento o una Devoluci¢n autom tica, dependiendo de la diferencia encontrada."
         #define STR0006  "Nota: Ser  considerado s¢lo el stock con inventario a la fecha de la selecci¢n (par metros)."
         #define STR0007  "Caso alg£n producto presente divergencias, ser  generado un informe."
         #define STR0008  "Si el dep¢sito en inventario es el dep¢sito del Control de Calidad, la cantidad rechazada "
         #define STR0009  "ser  onsiderada como la cantidad en stock."
         #define STR0010  "Efectuando Ajuste del Inventario..."
         #define STR0011  "Confirma"
         #define STR0012  "Retipea "
         #define STR0013  "Salir   "
         #define STR0014  "Informe de Saldo Negativo"
         #define STR0015  "Mismo estando con el par metro MV_ESTNEG activo algunos productos"
         #define STR0016  "del stock quedaron con saldo negativo. Este informe es un listado"
         #define STR0017  "de tales productos."
         #define STR0018  " "
         #define STR0019  "Administraci¢n"
         #define STR0020  "REGISTRO(S)"
         #define STR0021  "PRODUCTO          DESCRIPCION                          LOCAL   CANTIDAD"
         #define STR0022  "Seleccionando Registros..."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Process  "
         #define STR0002  "Inventory Adjustment        "
         #define STR0003  "This program will generate adjustment transactions and correct the Stock Balance."
         #define STR0004  "These transactions will be based on counting carried out and recorded on the Inventory Routine."
         #define STR0005  "The program will generate an automatic Requisition or Devolution, depending on the difference met."
         #define STR0006  "Obs: Only the physical inventory registered on the selection date (parameters)."
         #define STR0007  "If any product presents any divergences, a report will be generated "
         #define STR0008  "If the Local accounted is the Quality Control local, will be considered as a quantity in Stock    "
         #define STR0009  "the rejected quantity."
         #define STR0010  "Adjusting Inventory...         "
         #define STR0011  "OK      "
         #define STR0012  "Retype  "
         #define STR0013  "Quit    "
         #define STR0014  "Report of Negative Balance "
         #define STR0015  "Even presenting an active MV_ESTNEG parameter some inventory"
         #define STR0016  "products remained with a negative balance.This report is a listing of "
         #define STR0017  "these products."
         #define STR0018  "Z-Form"
         #define STR0019  "Management  "
         #define STR0020  "RECORD(S)"
         #define STR0021  "PRODUCT           DESCRIPT.                            PLACE   QUANTITY "
         #define STR0022  "Selecting Records     "
   #ELSE
         #define STR0001  "Processar"
         #define STR0002  "Acerto do Invent rio"
         #define STR0003  "Este programa ir  gerar movimenta‡”es de ajuste para corrigir o saldo do estoque."
         #define STR0004  "Estas movimenta‡”es ser„o baseadas nas contagens realizadas e cadastradas na Rotina Invent rio."
         #define STR0005  "O programa dever  gerar uma Requisi‡„o ou uma Devolu‡„o autom tica, dependendo da diferen‡a encontrada."
         #define STR0006  "Nota: Ser  considerado apenas o estoque inventariado na data da sele‡„o (parƒmetros)."
         #define STR0007  "Caso algum produto apresente divergˆncias, ser  gerado um relat¢rio."
         #define STR0008  "Se o almoxarifado inventariado for o almoxarifado do CQ, sera considerada como quantidade em estoque "
         #define STR0009  "a quantidade rejeitada."
         #define STR0010  "Efetuando Acerto do Inventario..."
         #define STR0011  "Confirma"
         #define STR0012  "Redigita"
         #define STR0013  "Abandona"
         #define STR0014  "Relatorio de Saldo Negativo"
         #define STR0015  "Mesmo estando com o parametro MV_ESTNEG ativo alguns produtos do"
         #define STR0016  "estoque ficaram com saldo negativo. Este relatorio e uma listagem"
         #define STR0017  "destes produtos."
         #define STR0018  "Zebrado"
         #define STR0019  "Administracao"
         #define STR0020  "REGISTRO(S)"
         #define STR0021  "PRODUTO           DESCRICAO                            LOCAL   QUANTIDADE"
         #define STR0022  "Selecionando Registros..."
   #ENDIF
#ENDIF
