#IFDEF SPANISH
         #define STR0001  "Estructuras"
         #define STR0002  "bUscar    "
         #define STR0003  "Visualizar"
         #define STR0004  "Incluir"
         #define STR0005  "Modificar"
         #define STR0006  "Borrar "
         #define STR0007  "Seleccionando Registros..."
         #define STR0008  "Abandona"
         #define STR0009  "Confirma"
         #define STR0010  "Componente"
         #define STR0011  "¨Cu nto al Borrar?     "
         #define STR0012  "  Ninguna Divergencia..."
         #define STR0013  "  Total"
         #define STR0014  "Mapa de Divergencias"
         #define STR0015  "Modificaci¢n"
         #define STR0016  "Inclusi¢n"
         #define STR0017  "Borrar   "
         #define STR0018  "Visualizaci¢n"
         #define STR0019  "C¢digo:"
         #define STR0020  "Unidad:"
         #define STR0021  "Estructura Similar:"
         #define STR0022  "Cantidad Base:"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Structures"
         #define STR0002  "Search   "
         #define STR0003  "View   "
         #define STR0004  "Insert "
         #define STR0005  "Edit   "
         #define STR0006  "Delete  "
         #define STR0007  "Selecting Records   ..."
         #define STR0008  "Quit  "
         #define STR0009  "OK   "
         #define STR0010  "Component "
         #define STR0011  "About Deleting?      "
         #define STR0012  "  No Divergence    ..."
         #define STR0013  "  Total"
         #define STR0014  "Map of Divergencies"
         #define STR0015  "Edit      " 
         #define STR0016  "Insert  "
         #define STR0017  "Delete    "
         #define STR0018  "View     "
         #define STR0019  "Code  :"
         #define STR0020  "Unit   :"
         #define STR0021  "Similar Structure :"
         #define STR0022  "Base Quantity :"
   #ELSE
         #define STR0001  "Estruturas"
         #define STR0002  "Pesquisar"
         #define STR0003  "Visualizar"
         #define STR0004  "Incluir"
         #define STR0005  "Alterar"
         #define STR0006  "Excluir"
         #define STR0007  "Selecionando Registros..."
         #define STR0008  "Abandona"
         #define STR0009  "Confirma"
         #define STR0010  "Componente"
         #define STR0011  "Quanto … exclus„o?"
         #define STR0012  "  Nenhuma Divergencia..."
         #define STR0013  "  Total"
         #define STR0014  "Mapa de Divergencias"
         #define STR0015  "Altera‡„o"
         #define STR0016  "Inclus„o"
         #define STR0017  "Exclus„o"
         #define STR0018  "Visualiza‡„o"
         #define STR0019  "C¢digo:"
         #define STR0020  "Unidade:"
         #define STR0021  "Estrutura Similar:"
         #define STR0022  "Quantidade Base:"
   #ENDIF
#ENDIF
