#IFDEF SPANISH
         #define STR0001  "bUscar    "
         #define STR0002  "Orden"
         #define STR0003  "Generar Fact."
         #define STR0004  "Retornar"
         #define STR0005  "Preparaci¢n de la Factura    "
         #define STR0006  "Seleccionando Registros..."
         #define STR0007  "Marcando Ötems de los Pedidos.."
         #define STR0008  "¨Confirma Retorno de la Aprobaci¢n?"
         #define STR0009  "Atenci¢n"
         #define STR0010  "El objetivo de este programa es generar las Facturas de venta de los  "
         #define STR0011  " pedidos marcados.                                                   "
         #define STR0012  "Generando Factura...."
         #define STR0013  "Busca        "
         #define STR0014  "La Factura    "
         #define STR0015  " Serie "
         #define STR0016  " ya existe."
         #define STR0017  "Continuando el procesamiento, ser  utilizado el pr¢ximo n£mero    "
         #define STR0018  "disponible.                                                      "
         #define STR0019  "¨Cancela la aprobaci¢n de los ¡tems marcados?"
		   #define STR0020  " no est  disponible para la facturaci¢n."
			#define STR0021  "La Solicitud/Ötem(SC9) : "
			#define STR0022  "La Solicitud/Ötem(SC6) : "
			#define STR0023  "La Solicitud(SC5) : "
			#define STR0024  " est  inconsistente en relaci¢n a la cantidad."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search   "
         #define STR0002  "Order"
         #define STR0003  "Gener.Bills"
         #define STR0004  "Reverse "
         #define STR0005  "Preparing the Invoice    "
         #define STR0006  "Selecting Records ...    "
         #define STR0007  "Marking Items in Order    .."
         #define STR0008  "Confirm the Reversal of Release?"
         #define STR0009  "Attention"
         #define STR0010  "  This program has the purpose of generating the invoices of the sales of the  "
         #define STR0011  "  marked order.                                                                 "
         #define STR0012  "Generating Invoice .."
         #define STR0013  "Research"
         #define STR0014  "The Invoice   "
         #define STR0015  " Series"
         #define STR0016  " already exists"
         #define STR0017  "Continuing processing, the next available number will be used.   "
         #define STR0018  "                                                                 "
         #define STR0019  "Reverse the Release of the selected? "
         #define STR0020  " not available for invoicing.           "
         #define STR0021  "The Order/Item(SC9): "
         #define STR0022  "The Order/Item(SC6): "
         #define STR0023  "The Order(SC5): "
         #define STR0024  " is inconsistent in refering to quantity.   "
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Ordem"
         #define STR0003  "Gera Notas"
         #define STR0004  "Estornar"
         #define STR0005  "Prepara‡„o da Nota Fiscal"
         #define STR0006  "Selecionando Registros..."
         #define STR0007  "Marcando Itens dos Pedidos.."
         #define STR0008  "Confirma o Estorno da Libera‡„o?"
         #define STR0009  "Aten‡„o"
         #define STR0010  "  Este programa  tem  como  objetivo  gerar  as notas fiscais   de   venda dos "
         #define STR0011  "  pedidos marcados.                                                             "
         #define STR0012  "Gerando Nota Fiscal.."
         #define STR0013  "Pesquisa"
         #define STR0014  "A Nota Fiscal "
         #define STR0015  " S‚rie "
         #define STR0016  " j  existe."
         #define STR0017  "Prosseguindo o processamento, ser  utilizado o pr¢ximo n£mero    "
         #define STR0018  "dispon¡vel.                                                      "
			#define STR0019  "Estorna Libera‡„o dos itens marcados ?"
		   #define STR0020  " n„o est  disponivel para o faturamento."
			#define STR0021  "O Pedido/Item(SC9) : "
			#define STR0022  "O Pedido/Item(SC6) : "
			#define STR0023  "O Pedido(SC5) : "
			#define STR0024  " est  inconsistente em rela‡„o a quantidade."
   #ENDIF
#ENDIF