#IFDEF SPANISH
         #define STR0001  "Confirma"
         #define STR0002  "Abandona"
         #define STR0003  "Retipea"
         #define STR0004  "Movimientos Internos"
         #define STR0005  "bUscar    "
         #define STR0006  "Visualizar"
         #define STR0007  "Incluir"
         #define STR0008  "Devolver"
         #define STR0009  "N£mero Documento"
         #define STR0010  "TM"
         #define STR0011  "Centro Costo"
         #define STR0012  "Emisi¢n"
         #define STR0013  "¨Confirma la devoluci¢n del movimiento?"
         #define STR0014  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "OK      "
         #define STR0002  "Quit    "
         #define STR0003  "Retype  "
         #define STR0004  "Internal Transact. "
         #define STR0005  "Search   "
         #define STR0006  "View      "
         #define STR0007  "Insert "
         #define STR0008  "Reverse"
         #define STR0009  "Document Number "
         #define STR0010  "TP"
         #define STR0011  "Cost Center     "
         #define STR0012  "Issue  "
         #define STR0013  "Confirms the reversal of Transact.?"
         #define STR0014  "Attention"
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Abandona"
         #define STR0003  "Redigita"
         #define STR0004  "Movimentos Internos"
         #define STR0005  "Pesquisar"
         #define STR0006  "Visualizar"
         #define STR0007  "Incluir"
         #define STR0008  "Estornar"
         #define STR0009  "N£mero Documento"
         #define STR0010  "TM"
         #define STR0011  "Centro de Custo"
         #define STR0012  "Emissao"
         #define STR0013  "Confirma o estorno da movimenta‡„o ?"
         #define STR0014  "Aten‡„o"
   #ENDIF
#ENDIF
