#IFDEF SPANISH
         #define STR0001  "Agrupa OPs"
         #define STR0002  "Per¡odos para a Agrupamiento"
         #define STR0003  "Este programa permite que las ordenes de producci¢n"
         #define STR0004  "de un mismo producto sean agrupadas de acuerdo con"
         #define STR0005  "los per¡odos definidos al lado."
         #define STR0006  "Per¡odo Diario"
         #define STR0007  "Per¡odo Semanal"
         #define STR0008  "Per¡odo Quincenal"
         #define STR0009  "Per¡odo Mensual"
         #define STR0010  "Per¡odo Trimestral"
         #define STR0011  "Per¡odo Semestral"
         #define STR0012  "Seleccionando Registros..."
         #define STR0013  "Ok"
         #define STR0014  "Orden de Producci¢n"
         #define STR0015  "Producto"
         #define STR0016  "Cantidad"
         #define STR0017  "Selecci¢n de las OPs"
         #define STR0018  "Agrupando OPs..."
         #define STR0019  "Esta rutina ir  agrupar las Ordenes de Producci¢n,"
         #define STR0020  "de acuerdo con los par metros seleccionados."
         #define STR0021  "¨Confirma el agrupamiento de las OPs? "
         #define STR0022  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Group POs"
         #define STR0002  "Periods for Grouping"
         #define STR0003  "This program allows the Production Orders of the "
         #define STR0004  "same product to be grouped according to the "
         #define STR0005  "defined periods on the side"
         #define STR0006  "Daily Period"
         #define STR0007  "Weekly Period"
         #define STR0008  "Fortnightly Period"
         #define STR0009  "Monthly Period"
         #define STR0010  "Quarterly Period"
         #define STR0011  "Six Month Period"
         #define STR0012  "Selecting Records..."
         #define STR0013  "Ok"
         #define STR0014  "Production Order "
         #define STR0015  "Product"
         #define STR0016  "Quantity"
         #define STR0017  "Select.of POs"
         #define STR0018  "Grouping Pos..."
         #define STR0019  "This routine will group the Production Orders"
         #define STR0020  "according to the selected parameters"
         #define STR0021  "Confirm the grouping of POs ?"
         #define STR0022  "Attention"
   #ELSE
         #define STR0001  "Aglutina OPs"
         #define STR0002  "Per¡odos para a Aglutina‡„o"
         #define STR0003  "Este programa permite que as ordens de produ‡„o de"
         #define STR0004  "um mesmo produto sejam aglutinadas conforme os"
         #define STR0005  "per¡odos definidos ao lado."
         #define STR0006  "Per¡odo Di rio"
         #define STR0007  "Per¡odo Semanal"
         #define STR0008  "Per¡odo Quinzenal"
         #define STR0009  "Per¡odo Mensal"
         #define STR0010  "Per¡odo Trimestral"
         #define STR0011  "Per¡odo Semestral"
         #define STR0012  "Selecionando Registros..."
         #define STR0013  "Ok"
         #define STR0014  "Ordem de Producao"
         #define STR0015  "Produto"
         #define STR0016  "Quantidade"
         #define STR0017  "Sele‡„o das OPs"
         #define STR0018  "Aglutinando OPs..."
         #define STR0019  "Esta rotina ir  aglutinar as Ordens de Produ‡„o"
         #define STR0020  "conforme os parƒmetros selecionados."
         #define STR0021  "Confirma a aglutina‡„o das OPs ?"
         #define STR0022  "Aten‡„o"
   #ENDIF
#ENDIF
