#IFDEF SPANISH
         #define STR0001  "Aprobaci¢n del Stock"
         #define STR0002  "bUscar    "
         #define STR0003  "Orden"
         #define STR0004  "Autom tica"
         #define STR0005  "Manual"
         #define STR0006  "El objetivo de este programa es aprobar autom ticamente "
         #define STR0007  "los pedidos de venta con bloqueo de Stock.              "
         #define STR0008  "Aprobaci¢n del Stock "
         #define STR0009  "Pedido"
         #define STR0010  "Cond.Pago"
         #define STR0011  "Bloqueo"
         #define STR0012  "Cliente"
         #define STR0013  "Riesgo"
         #define STR0014  "Producto"
         #define STR0015  "Saldo"
         #define STR0016  "Dep¢sito"
         #define STR0017  "N£mero Sublote"
         #define STR0018  "Localizaci¢n"
         #define STR0019  "Ctd.Total Pedido"
         #define STR0020  "Fecha élt.Salida"
         #define STR0021  "Ctd.Total 2a.UM"
         #define STR0022  "Ctd.en este Ötem"
         #define STR0023  "Seleccionando registros..."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Inventory Release   "
         #define STR0002  "Search   "
         #define STR0003  "Order"
         #define STR0004  "Automatic "
         #define STR0005  "Manual"
         #define STR0006  "  This program has the purpose of automatically releasing the Sale Orders     "
         #define STR0007  "  with inventory blocking                                                    "
         #define STR0008  "Inventory Release   "
         #define STR0009  "Order "
         #define STR0010  "paym.Cond."
         #define STR0011  "Blocking"
         #define STR0012  "Customer"
         #define STR0013  "Risk "
         #define STR0014  "Product"
         #define STR0015  "Balan"
         #define STR0016  "Wareh."
         #define STR0017  "Lot Number "
         #define STR0018  "Location   "
         #define STR0019  "Tot.Qty.Order   "
         #define STR0020  "Date Last Outfl"
         #define STR0021  "Tot.Qty.2nd UM"
         #define STR0022  "Qty.in this item"
         #define STR0023  "Selecting records ...   "
   #ELSE
         #define STR0001  "Libera‡„o de Estoque"
         #define STR0002  "Pesquisar"
         #define STR0003  "Ordem"
         #define STR0004  "Autom tica"
         #define STR0005  "Manual"
         #define STR0006  "  Este programa  tem  como  objetivo  liberar  automaticamente os pedidos de  "
         #define STR0007  "  venda com bloqueio de estoque                                               "
         #define STR0008  "Libera‡„o de Estoque"
         #define STR0009  "Pedido"
         #define STR0010  "Cond.Pagto."
         #define STR0011  "Bloqueio"
         #define STR0012  "Cliente"
         #define STR0013  "Risco"
         #define STR0014  "Produto"
         #define STR0015  "Saldo"
         #define STR0016  "Almox."
         #define STR0017  "N£mero Lote"
         #define STR0018  "Localiza‡„o"
         #define STR0019  "Qtd.Total Pedido"
         #define STR0020  "Data Ult.Sa¡da"
         #define STR0021  "Qtd.Total 2a.UM"
         #define STR0022  "Qtd.neste Ötem"
	 #define STR0023  "Selecionando registros..."
   #ENDIF
#ENDIF