#IFDEF SPANISH
         #define STR0001  "bUscar    "
         #define STR0002  "Orden"
         #define STR0003  "Autom tica"
         #define STR0004  "Manual"
         #define STR0005  "Aprobaci¢n de Cr‚dito"
         #define STR0006  "Consulta Posici¢n Clientes"
         #define STR0007  "Cr‚dito"
         #define STR0008  "L¡mite de Cr‚dito Vencido"
         #define STR0009  "Rechazado "
         #define STR0010  "Consulta"
         #define STR0011  "Apr.Todos"
         #define STR0012  "Rechaza"
         #define STR0013  "Pedido :"
         #define STR0014  "Cond.Pago :"
         #define STR0015  "Bloqueo :"
         #define STR0016  "Cliente :"
         #define STR0017  "Riesgo:"
         #define STR0018  "L¡mite de Cr‚dito :"
         #define STR0019  "T¡tulos Protestados :"
         #define STR0020  "En"
         #define STR0021  "Saldo T¡tulo :"
         #define STR0022  "Cheques Devueltos :"
         #define STR0023  "Pedidos Aprobados :"
         #define STR0024  "Mayor Compra :"
         #define STR0025  "Saldo L¡m.Cr‚dito :"
         #define STR0026  "Mayor T¡tulo :"
         #define STR0027  "Ötem Pedido Actual:"
         #define STR0028  "d¡as"
         #define STR0029  "Prom‚dio Atrasos:"
         #define STR0030  "Saldo de los Pedidos :"
         #define STR0031  "Vencto.L¡m.Cr‚dito :"
         #define STR0032  "Atraso Actual :"
         #define STR0033  "Fecha L¡mite Aprobaci¢n:"
         #define STR0034  "¨Confirma Aprobaci¢n Autom tica de los Pedidos?"
         #define STR0035  "Atenci¢n"
         #define STR0036  "Pedido Actual"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search   "
         #define STR0002  "Order"
         #define STR0003  "Automatic "
         #define STR0004  "Manual"
         #define STR0005  "Credit Release      "
         #define STR0006  "Check Customer Situation "
         #define STR0007  "Credit "
         #define STR0008  "Expired Credit Limit     "
         #define STR0009  "Rejected "
         #define STR0010  "Query   "
         #define STR0011  "Release All"
         #define STR0012  "Reject "
         #define STR0013  "Order  :"
         #define STR0014  "Paym.Condit.:"
         #define STR0015  "Blocking :"
         #define STR0016  "Customer:"
         #define STR0017  "Risk  :"
         #define STR0018  "Credit Limit      :"
         #define STR0019  "Protested Bills     :"
         #define STR0020  "In"
         #define STR0021  "Duplicate Balances"
         #define STR0022  "Returned Cheques   :"
         #define STR0023  "Released Orders   :"
         #define STR0024  "Biggest Purchase"
         #define STR0025  "Credit Limit Balance"
         #define STR0026  "Biggest T. Note  "
         #define STR0027  "Current Order Item:"
         #define STR0028  "days"
         #define STR0029  "Average Delays:"
         #define STR0030  "Order Balances:   "
         #define STR0031  "Limit Credit Expiry:"
         #define STR0032  "Current Delay:"
         #define STR0033  "Release Limit Date    :"
         #define STR0034  "Confirm Automatic Release of Orders       ?"
         #define STR0035  "Attention"
         #define STR0036  "Current Order"
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Ordem"
         #define STR0003  "Autom tica"
         #define STR0004  "Manual"
         #define STR0005  "Libera‡„o de Cr‚dito"
         #define STR0006  "Consulta Posi‡„o Clientes"
         #define STR0007  "Cr‚dito"
         #define STR0008  "Limite de Cr‚dito Vencido"
         #define STR0009  "Rejeitado"
         #define STR0010  "Consulta"
         #define STR0011  "Lib.Todos"
         #define STR0012  "Rejeita"
         #define STR0013  "Pedido :"
         #define STR0014  "Cond.Pagto. :"
         #define STR0015  "Bloqueio :"
         #define STR0016  "Cliente :"
         #define STR0017  "Risco :"
         #define STR0018  "Limite de Cr‚dito :"
         #define STR0019  "Titulos Protestados :"
         #define STR0020  "Em"
         #define STR0021  "Saldo Duplicatas :"
         #define STR0022  "Cheques Devolvidos :"
         #define STR0023  "Pedidos Liberados :"
         #define STR0024  "Maior Compra :"
         #define STR0025  "Saldo Lim.Cr‚dito :"
         #define STR0026  "Maior Duplicata :"
         #define STR0027  "Item Pedido Atual :"
         #define STR0028  "dias"
         #define STR0029  "M‚dia Atrasos :"
         #define STR0030  "Saldo de Pedidos :"
         #define STR0031  "Vencto.Lim.Cr‚dito :"
         #define STR0032  "Atraso Atual :"
         #define STR0033  "Data Limite Libera‡„o :"
         #define STR0034  "Confirma Libera‡„o Automatica dos Pedidos ?"
         #define STR0035  "Aten‡„o"
         #define STR0036  "Pedido Atual"
   #ENDIF
#ENDIF
