#IFDEF SPANISH
         #define STR0001  "bUscar    "
         #define STR0002  "Visualizar"
         #define STR0003  "Incluir"
         #define STR0004  "Devolver"
         #define STR0005  "Cerrar"
         #define STR0006  "Producciones"
         #define STR0007  "Abandona"
         #define STR0008  "Confirma"
         #define STR0009  "¨Cu nto a la devoluci¢n?"
         #define STR0010  "¨Cu nto al Cierre?"
         #define STR0011  "Dif. Saldo en Stock/Sublote"
         #define STR0012  "Sin Saldo por Sublote"
         #define STR0013  "Sin Saldo en Stock"
         #define STR0014  "Ötems Sin Saldo / Bloqueados"
         #define STR0015  "Producto"
         #define STR0016  "Local"
         #define STR0017  "Saldo"
         #define STR0018  "Evento"
         #define STR0019  "OP"
         #define STR0020  "Cantidad"
         #define STR0021  "Sublote"
         #define STR0022  "Lote"
         #define STR0023  "Fecha de Validez"
         #define STR0024  "Creaci¢n de Sublotes en la Producci¢n"
         #define STR0025  "OPs de este Producto"
         #define STR0026  "N£mero"
         #define STR0027  "Ötem"
         #define STR0028  "Secuencia"
         #define STR0029  "La OP "         
			#define STR0030  " fue finalizada. Despu‚s de la devoluci¢n de este"
         #define STR0031  "apunte de producci¢n la OP quedar  con saldo para producir."
         #define STR0032  "¨La OP debe ser aprobada para produci¢n?"
         #define STR0033  "Devoluci¢n OP "
         #define STR0034  "Bloqueado pa. Invent rio"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search   "
         #define STR0002  "View      "
         #define STR0003  "Insert "
         #define STR0004  "Reversal"
         #define STR0005  "End     "
         #define STR0006  "Productions"
         #define STR0007  "Quit   "
         #define STR0008  "OK        "
         #define STR0009  "About Reversal   ?"
         #define STR0010  "About Closing     ?"
         #define STR0011  "Dif.Balance in Invent/Lot"
         #define STR0012  "Without balance per lot"
         #define STR0013  "W/o inventory balance"
         #define STR0014  "Items w/o Balance/Blocked"
         #define STR0015  "Product"
         #define STR0016  "Place"
         #define STR0017  "Balance"
         #define STR0018  "Event"
         #define STR0019  "OP"
         #define STR0020  "Quantity "
         #define STR0021  "Sub-Lot "
         #define STR0022  "Lot "
         #define STR0023  "Date of Validity"
         #define STR0024  "Building Lots in Production"
         #define STR0025  "POs of this Product"
         #define STR0026  "Number"
         #define STR0027  "Item"
         #define STR0028  "Sequence"
         #define STR0029  "The PO"
         #define STR0030  "is closed. After the reversal of this"
         #define STR0031  "production allocation the PO will have balance for product"
         #define STR0032  "The PO must be released for production?"
         #define STR0033  "OP Reversal"
         #define STR0034  "Blocked for Inventory"
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Visualizar"
         #define STR0003  "Incluir"
         #define STR0004  "Estornar"
         #define STR0005  "enceRrar"
         #define STR0006  "Produ‡”es"
         #define STR0007  "Abandona"
         #define STR0008  "Confirma"
         #define STR0009  "Quanto ao estorno?"
         #define STR0010  "Quanto ao Encerramento?"
         #define STR0011  "Dif. Saldo em Estoque/Lote"
         #define STR0012  "Sem Saldo por Lote"
         #define STR0013  "Sem Saldo em Estoque"
         #define STR0014  "Itens Sem Saldo / Bloqueados"
         #define STR0015  "Produto"
         #define STR0016  "Local"
         #define STR0017  "Saldo"
         #define STR0018  "Ocorrˆncia"
         #define STR0019  "OP"
         #define STR0020  "Quantidade"
         #define STR0021  "Sub-Lote"
         #define STR0022  "Lote"
         #define STR0023  "Data de Validade"
         #define STR0024  "Cria‡„o de Lotes na Produ‡„o"
         #define STR0025  "OPs deste Produto"
         #define STR0026  "N£mero"
         #define STR0027  "Item"
         #define STR0028  "Sequˆncia"
         #define STR0029  "A OP "
         #define STR0030  " est  encerrada. Ap¢s o estorno deste "
         #define STR0031  "apontamento de produc„o a OP ficar  com saldo p/ produzir. "
         #define STR0032  "A OP deve ser liberada p/ produ‡„o ?"
         #define STR0033  "Estorno OP "
         #define STR0034  "Bloqueado p/ Invent rio"
   #ENDIF
#ENDIF