#IFDEF SPANISH
         #define STR0001  "Esta rutina ser  ejecutada en modo"
         #define STR0002  "compartido, conforme indicado por"
         #define STR0003  "el par metro MV_CUSTEXC."
         #define STR0004  "Los movimientos que sucedan durante el"
         #define STR0005  "proceso pueden influir en el c lculo."
         #define STR0006  "ATENCION"
         #define STR0007  "Cierre del Per¡odo en el Stock"
         #define STR0008  "Este programa har  la transferencia de los saldos finales, calculados en la rutina de Rec lculo del Costo Promedio, para los saldos iniciales del pr¢ximo per¡odo. Traer  la fecha del £ltimo rec lculo como sugerencia, esta fecha ser  la base para la limpieza de los archivos de Compras, Ventas y Movimientos Internos del sistema. Certifiquese de que la misma est‚ correcta."
         #define STR0009  "Fecha base para ejecutar el cierre:  "
         #define STR0010  "Para hacer la transferencia de los saldos ser  necesario informar los nombres de los archivos donde ser n descargados los movimientos a la fecha del cierre. Estos nombres deberan tener un m xino de 5 caracteres cada uno, el sistema se encargar  de complementarlos con el modelo usado en la rutina de Depuraci¢n de Archivos."
         #define STR0011  "Facturas de Compras ---> Encabezamiento"
         #define STR0012  "Facturas de Ventas  ---> Encabezamiento"
         #define STR0013  "SF1.AMT       Ötems"
         #define STR0014  "SF2.AMT       Ötems"
         #define STR0015  "Movimientos Internos   --------------------->"
         #define STR0016  "Orden de Producci¢n      --------------------->"
         #define STR0017  "Cierre Mensual"
         #define STR0018  "Efectuando el Cierre Mensual..."
         #define STR0019  "¨Confirma configuraci¢n de los par metros?"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "This routine shall be executed on a"
         #define STR0002  "share modality as indicated   "
         #define STR0003  "in parameter MV_CUSTEXC."
         #define STR0004  "The transactions that take place during"
         #define STR0005  "the process can influence in the calcul."
         #define STR0006  "ATTENTION"
         #define STR0007  "Closing of Period in Stock      "
         #define STR0008  "this program will  transfer the end balances, calculated in the Average Cost calculation routine,to the Initial Balance of the next period. It will provide the date of the last recalculation as suggestion,this date will be the base for clearing Purchase, Sale and Internal Transactions of the System. Make sure that it is correct."
         #define STR0009  "Base Date for proceed closing:      "
         #define STR0010  "To carry out the transfer of balances it is necessary to inform the names of the files where will  be unloaded the previous transactions of the closing date. These names must contain 5 characters each acters each.The system will ocmplete with the standard used in the e standard used in the Depuration Files routine.  "
         #define STR0011  "Creditor Invoice        ---> Header   "
         #define STR0012  "Debtor Invoice          ---> Header   "
         #define STR0013  "SF1.AMT       Items"
         #define STR0014  "SF2.AMT       Items"
         #define STR0015  "Internal Transactions  --------------------->"
         #define STR0016  "Production Order   --------------------->"
         #define STR0017  "Monthly Closing"
         #define STR0018  "Carrying out Monthly Closing.."
         #define STR0019  "Confirms configuration of parameters"
   #ELSE
         #define STR0001  "Esta rotina ser  executada em modo"
         #define STR0002  "compartilhado , conforme indicado"
         #define STR0003  "pelo parƒmetro MV_CUSTEXC."
         #define STR0004  "As movimenta‡”es que ocorrerem durante"
         #define STR0005  "o processo podem influir no c lculo."
         #define STR0006  "ATEN€ŽO"
         #define STR0007  "Fechamento do Per¡odo no Estoque"
         #define STR0008  "Este programa far  a transferˆncia dos saldos finais, calculados na rotina de Rec lculo do Custo M‚dio, para os saldos iniciais do pr¢ximo per¡odo. Ele trar  a data do £ltimo rec lculo como sugest„o, esta data ser  a base para a limpeza dos arquivos de Compras , Vendas e  Movimenta‡”es Internas do sistema. Certifique-se de que a mesma esteja correta."
         #define STR0009  "Data Base para executar o fechamento:"
         #define STR0010  "Para efetuar a transferˆncia dos saldos ser  necess rio informar os nomes dos arquivos onde ser„o descarregados os movimentos anteriores … data do fechamento. Estes nomes dever„o conter no m†ximo 5 caracteres cada um , o sistema se encarregar  de complement -los com o padr„o utilizado na rotina de Depura‡„o de arquivos."
         #define STR0011  "Notas Fiscais de Compra ---> Cabe‡alho"
         #define STR0012  "Notas Fiscais de Venda  ---> Cabe‡alho"
         #define STR0013  "SF1.AMT       Itens"
         #define STR0014  "SF2.AMT       Itens"
         #define STR0015  "Movimenta‡”es Internas --------------------->"
         #define STR0016  "Ordem de Produ‡„o        --------------------->"
         #define STR0017  "Fechamento Mensal"
         #define STR0018  "Efetuando Fechamento Mensal..."
         #define STR0019  "Confirma configura‡„o dos parƒmetros?"
   #ENDIF
#ENDIF
