#IFDEF SPANISH
         #define STR0001  "bUscar    "
         #define STR0002  "Generar"
         #define STR0003  "Incluir"
         #define STR0004  "Modificar"
         #define STR0005  "Borrar "
         #define STR0006  "Composici¢n Selectiva"
         #define STR0007  "Entre con los datos"
         #define STR0008  "Ruta Est ndar"
         #define STR0009  "Producto Est ndar"
         #define STR0010  "PRODUCTOS QUE NO TIENEN SELECTIVIDAD"
         #define STR0011  "Este programa har  la lista de los productos que presentaron "
         #define STR0012  "divergencias, pu‚s est n en el archivo de pedidos de venta, "
         #define STR0013  "pero no tienen Composici¢n Selectiva en el archivo. "
         #define STR0014  "  "
         #define STR0015  "Administraci¢n"
         #define STR0016  "PEDIDO      ÖTEM PEDIDO     PRODUCTO          COD    "
         #define STR0017  "DE VENDA    DE VENDA                          FIJO   "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search"
         #define STR0002  "Gener."
         #define STR0003  "Insert"
         #define STR0004  "Edit  "
         #define STR0005  "Delete"
         #define STR0006  "Selective Composit."
         #define STR0007  "Enter Data:"
         #define STR0008  "Standard Routine"
         #define STR0009  "Standard Product"
         #define STR0010  "PRODUCTS THAT DO NOT HAVE SELECTIVITY"
         #define STR0011  "This program will list the products that presented  "
         #define STR0012  "divergencies,since these are registered in the sale orders"
         #define STR0013  "but do not have registered selective composition"
         #define STR0014  "Z.Form"
         #define STR0015  "Management"
         #define STR0016  "SALE       ITEM OF        PRODUCT           COD    "
         #define STR0017  "ORDER      SALE ORDER                       FIXED  "
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Gerar"
         #define STR0003  "Incluir"
         #define STR0004  "Alterar"
         #define STR0005  "Excluir"
         #define STR0006  "Composi‡„o Seletiva"
         #define STR0007  "Entre com os dados:"
         #define STR0008  "Roteiro Padr„o"
         #define STR0009  "Produto Padr„o"
         #define STR0010  "PRODUTOS QUE NAO POSSUEM SELETIVIDADE"
         #define STR0011  "Este programa ir  listar os produtos que apresentaram "
         #define STR0012  "divergˆncias, pois est„o cadastrados em pedidos de venda,"
         #define STR0013  "por‚m n„o tem Composi‡„o Seletiva cadastrada."
         #define STR0014  "Zebrado"
         #define STR0015  "Administracao"
         #define STR0016  "PEDIDO      ITEM PEDIDO     PRODUTO           COD    "
         #define STR0017  "DE VENDA    DE VENDA                          FIXO   "
   #ENDIF
#ENDIF
