#IFDEF SPANISH
         #define STR0001  "C lculo del Lote Econ¢mico"
         #define STR0002  "Efectuando C lculo del Lote Econ¢mico..."
         #define STR0003  "Seleccionando Registros..."
         #define STR0004  "Lote Econ¢mico"
         #define STR0005  "Actualizaci¢n del Consumo del Mes"
         #define STR0006  "C lculos"
         #define STR0007  "Por Peso"
         #define STR0008  "Por la Tendencia"
         #define STR0009  "Incremento:"
         #define STR0010  "N£mero de Meses:"
         #define STR0011  "C lculo del Lote Econ¢mico"
         #define STR0012  "C lculo del Punto de Pedido"
         #define STR0013  "Ajusta Lote Econ¢mico por la dispo-"
         #define STR0014  "nibilidad financiera"
         #define STR0015  "Clasificaci¢n ABC"
         #define STR0016  "Per¡odo de Adquisici¢n(meses)"
         #define STR0017  "Distribuci¢n Porcentual (%) "
         #define STR0018  "Tipos de Material"
         #define STR0019  "Grupos de Material"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Economic Lot Calculation "
         #define STR0002  "Calculating the Economic Lot..."
         #define STR0003  "Selecting Records    ..."
         #define STR0004  "Economic Lot  "
         #define STR0005  "Updating Monthly Consumption    "
         #define STR0006  "Calculations"
         #define STR0007  "Per Weight"
         #define STR0008  "Per Tendency "
         #define STR0009  "Increase  :"
         #define STR0010  "Number of Months"
         #define STR0011  "Economic Lot Calculation"
         #define STR0012  "Calculating the Order item"
         #define STR0013  "Adjusts Economic Lot according to"
         #define STR0014  "financial availability"
         #define STR0015  "ABC Classification"
         #define STR0016  "Purchase Period (months)   "
         #define STR0017  "Percentual Distribution (%)"
         #define STR0018  "Types of Material"
         #define STR0019  "Groups of Material"
   #ELSE
         #define STR0001  "C lculo do Lote Econ“mico"
         #define STR0002  "Efetuando C lculo do Lote Econ“mico..."
         #define STR0003  "Selecionando Registros..."
         #define STR0004  "Lote Econ“mico"
         #define STR0005  "Atualiza‡„o do Consumo do Mˆs"
         #define STR0006  "C lculos"
         #define STR0007  "Por Peso"
         #define STR0008  "Pela Tendˆncia"
         #define STR0009  "Incremento:"
         #define STR0010  "N£mero de Meses:"
         #define STR0011  "C lculo do Lote Econ“mico"
         #define STR0012  "C lculo do Ponto de Pedido"
         #define STR0013  "Ajusta Lote Econ“mico pela dispo-"
         #define STR0014  "nibilidade financeira"
         #define STR0015  "Classifica‡„o ABC"
         #define STR0016  "Per¡odo de Aquisi‡„o(meses)"
         #define STR0017  "Distribui‡„o Percentual (%)"
         #define STR0018  "Tipos de Material"
         #define STR0019  "Grupos de Material"
   #ENDIF
#ENDIF
