#IFDEF SPANISH
         #define STR0001  "Salir   "
         #define STR0002  "Confirma"
         #define STR0003  "B&uscar   "
         #define STR0004  "Visualizar"
         #define STR0005  "Incluir"
         #define STR0006  "Modificar"
         #define STR0007  "Borrar "
         #define STR0008  "Actualizaci¢n Producto vs Proveedor"
         #define STR0009  "¨Cu nto al Borrar?"
         #define STR0010  "Justificaci¢n Situaci¢n"
         #define STR0011  "Actualizado autom ticamente por el sistema."
         #define STR0012  "Justificaci¢n Skip-Lote"
         #define STR0013  "Justificaci¢n Plan de Muestreo a"
         #define STR0014  "Justificaci¢n Plan de Muestreo b"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Quit    "
         #define STR0002  "O.K.    "
         #define STR0003  "Search   "
         #define STR0004  "View      "
         #define STR0005  "Insert"
         #define STR0006  "Edit   "
         #define STR0007  "Delete "
         #define STR0008  "Update of Product x Supplier   "
         #define STR0009  "About deleting?    "
         #define STR0010  "Justification of Situat."
         #define STR0011  "Updated by the System automaticaly.     "
         #define STR0012  "Justification of Skip-Lot"
         #define STR0013  "Justification of Sampling Plan a"
         #define STR0014  "Justification of Sampling Plan b"
   #ELSE
         #define STR0001  "Abandona"
         #define STR0002  "Confirma"
         #define STR0003  "Pesquisar"
         #define STR0004  "Visualizar"
         #define STR0005  "Incluir"
         #define STR0006  "Alterar"
         #define STR0007  "Excluir"
         #define STR0008  "Atualiza‡„o Produto x Fornecedor"
         #define STR0009  "Quanto … exclus„o?"
         #define STR0010  "Justificativa Situa‡„o"
         #define STR0011  "Atualizado automaticamente pelo sistema."
         #define STR0012  "Justificativa Skip-Lote"
         #define STR0013  "Justificativa Plano Amostragem a"
         #define STR0014  "Justificativa Plano Amostragem b"
   #ENDIF
#ENDIF