#IFDEF SPANISH
         #define STR0001  "Sucur."
         #define STR0002  "N§ Sol. Dep."
         #define STR0003  "Salir"
         #define STR0004  "Confirma"
         #define STR0005  "Buscar"
         #define STR0006  "Visualizar"
         #define STR0007  "Incluir"
         #define STR0008  "Modificar"
         #define STR0009  "Borrar"
         #define STR0010  "Solicitud al Dep¢sito"
         #define STR0011  "&N£mero"
         #define STR0012  "&Solicitante"
         #define STR0013  "&Fecha de Emisi¢n"
 #ELSE
   #IFDEF ENGLISH
         #define STR0001  "Filial"
         #define STR0002  "Numero da SA"
         #define STR0003  "Abandona"
         #define STR0004  "Confirma"
         #define STR0005  "Pesquisar"
         #define STR0006  "Visualizar"
         #define STR0007  "Incluir"
         #define STR0008  "Alterar"
         #define STR0009  "Excluir"
         #define STR0010  "Solicita‡„o ao Almoxarifado"
         #define STR0011  "&N£mero"
         #define STR0012  "&Solicitante"
         #define STR0013  "&Data de Emiss„o"
   #ELSE
         #define STR0001  "Filial"
         #define STR0002  "Numero da SA"
         #define STR0003  "Abandona"
         #define STR0004  "Confirma"
         #define STR0005  "Pesquisar"
         #define STR0006  "Visualizar"
         #define STR0007  "Incluir"
         #define STR0008  "Alterar"
         #define STR0009  "Excluir"
         #define STR0010  "Solicita‡„o ao Almoxarifado"
         #define STR0011  "&N£mero"
         #define STR0012  "&Solicitante"
         #define STR0013  "&Data de Emiss„o"
   #ENDIF
#ENDIF