#IFDEF SPANISH
         #define STR0001  "Esta  rutina  exige  que  los  archivos"
         #define STR0002  "asociados a ella no est‚n en uso por"
         #define STR0003  "otras estaciones."
         #define STR0004  "Haga con que los otros usuarios salgan  "
         #define STR0005  "del sistema."
         #define STR0006  "ATENCIàN"
         #define STR0007  "Actualizaci¢n Mensual de Productos"
         #define STR0008  "Este programa har  el c lculo mensual de los productos (consumo mensual).                           "
         #define STR0009  "Calcula con base en el mes y a¤o informados, s¢lamente para ventas. No calcula consumos (salidas)   "
         #define STR0010  "para transferencia o producci¢n . "
         #define STR0011  "Efectuando Actualizaci¢n Mensual de los Productos.."
         #define STR0012  "Seleccionando Registros..."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "This routine requires the files to it  "
         #define STR0002  "associated are not in use by other     "
         #define STR0003  "Users.          "
         #define STR0004  "Make sure the other Users quit the      "
         #define STR0005  "System."
         #define STR0006  "ATTENTION"
         #define STR0007  "Product Monthly Update        "
         #define STR0008  "This routine will perform the monthly calculation of Products (Monthly Comsuption). It is    "
         #define STR0009  "based on the month and year informed, just for Sales, not refering to Comsuptions (outflows)    "
         #define STR0010  "for transfering or production.           "
         #define STR0011  "Performing Monthly Updating of Products ... "
         #define STR0012  "Selecting Records...      "
   #ELSE
         #define STR0001  "Esta  rotina  exige  que  os   arquivos"
         #define STR0002  "associados a ela n†o estejam em uso por"
         #define STR0003  "outras esta‡”es."
         #define STR0004  "Fa‡a com que os outros usu rios saiam do"
         #define STR0005  "sistema."
         #define STR0006  "ATEN€ŽO"
         #define STR0007  "Atualiza‡„o Mensal de Produtos"
         #define STR0008  "Este programa far  o c lculo mensal de produtos (consumo mensal).                            "
         #define STR0009  "Calcula com base no mˆs, ano informados,somente para vendas.N„o calcula consumos (saidas)    "
         #define STR0010  "para transferˆncia ou produ‡„o . "
         #define STR0011  "Efetuando Atualiza‡„o Mensal de Produtos..."
         #define STR0012  "Selecionando Registros..."
   #ENDIF
#ENDIF
