#IFDEF SPANISH
         #define STR0001  "Esta  rutina  ser  ejecutada en modo compartido,"
         #define STR0002  "de acuerdo con lo especificado  en el par metro"
         #define STR0003  "MV_CUSTEXC."
         #define STR0004  "Los movimiento que hubieron durante el proceso"
         #define STR0005  "proceso pueden tener influencia en el c lculo."
         #define STR0006  "ATENCIàN"
         #define STR0007  "Rec lculo del Costo Medio"
         #define STR0008  "Este programa permite que el costo medio ser recalculado de tres modos diferentes, atendiendo"
         #define STR0009  "cualquier exigencia legal."
         #define STR0010  "Fecha Inicial de Procesamiento : "
         #define STR0011  "Realizando Rec lculo del Costo Medio..."
         #define STR0012  "Creando Archivo Trabajo 1..."
         #define STR0013  "Creando Archivo Trabajo 2..."
         #define STR0014  "Creando Archivo Trabajo 3..."
         #define STR0015  "Procesando Archivo de Transacci¢n"
         #define STR0016  "Seleccionando Saldo Lotes FIFO..."
         #define STR0017  "Seleccionando Mov. Lotes FIFO..."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "This routine will  be executed in"
         #define STR0002  "sharing mode, as indicated in  "
         #define STR0003  "the parameter  MV_CUSTEXC."
         #define STR0004  "The transactions that occur during the"
         #define STR0005  "process can affect the calculation."
         #define STR0006  "ATTENTION"
         #define STR0007  "Recaculating Average Cost"
         #define STR0008  "This program allows the average cost to be recalculated in three different ways, attending"
         #define STR0009  "any legal requirement   ."
         #define STR0010  "Initial Processing Date:       "
         #define STR0011  "Calculating Average Cost        ..."
         #define STR0012  "Generating the Work File 1..."
         #define STR0013  "Generating the Work File 2..."
         #define STR0014  "Generating the Work File 3..."
         #define STR0015  "Processing the Transaction File"
         #define STR0016  "Selecting FIFO Lot Balances...   "
         #define STR0017  "Selecting FIFO Lot Transactions.."
   #ELSE
         #define STR0001  "Esta rotina ser  executada em modo"
         #define STR0002  "compartilhado , conforme indicado"
         #define STR0003  "pelo parƒmetro MV_CUSTEXC."
         #define STR0004  "As movimenta‡”es que ocorrerem durante"
         #define STR0005  "o processo podem influir no c lculo."
         #define STR0006  "ATEN€ŽO"
         #define STR0007  "Rec lculo do Custo M‚dio"
         #define STR0008  "Este programa permite que o custo m‚dio seja recalculado de trˆs formas diferentes, atendendo"
         #define STR0009  "qualquer exigˆncia legal."
         #define STR0010  "Data Inicial de Processamento : "
         #define STR0011  "Efetuando Rec lculo do Custo M‚dio..."
         #define STR0012  "Criando Arquivo Trabalho 1..."
         #define STR0013  "Criando Arquivo Trabalho 2..."
         #define STR0014  "Criando Arquivo Trabalho 3..."
         #define STR0015  "Processando Arquivo de Transa‡„o"
         #define STR0016  "Selecionando Saldo Lotes FIFO..."
         #define STR0017  "Selecionando Mov. Lotes FIFO..."
   #ENDIF
#ENDIF