#IFDEF SPANISH
         #define STR0001  "Transferencias M£ltiples"
         #define STR0002  "bUscar    "
         #define STR0003  "Visualizar"
         #define STR0004  "Incluir"
         #define STR0005  "Devolver"
         #define STR0006  "Producto Origen" 
         #define STR0007  "Dep¢s."
         #define STR0008  "Localizaci¢n"
         #define STR0009  "Fecha"
         #define STR0010  "Sub Lote"
         #define STR0011  "Lote"
         #define STR0012  "Validez"
         #define STR0013  "N£mero de Serie"
         #define STR0014  "Cantidad"
         #define STR0015  "Cantidad Secundaria"
         #define STR0016  "Documento"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Multiple Transfers      "
         #define STR0002  "Search   "
         #define STR0003  "View     "
         #define STR0004  "Insert "
         #define STR0005  "Reversal"
         #define STR0006  "Source Product"
         #define STR0007  "Local "
         #define STR0008  "Location   "
         #define STR0009  "Date"
         #define STR0010  "Sub-Lot "
         #define STR0011  "Lot "
         #define STR0012  "Validity"
         #define STR0013  "Series Number  "
         #define STR0014  "Quantity  "
         #define STR0015  "Secondary Unit     "
         #define STR0016  "Document "
   #ELSE
         #define STR0001  "Transferˆncias M£ltiplas"
         #define STR0002  "Pesquisar"
         #define STR0003  "Visualizar"
         #define STR0004  "Incluir"
         #define STR0005  "Estornar"
         #define STR0006  "Produto Origem"
         #define STR0007  "Almox."
         #define STR0008  "Localiza‡„o"
         #define STR0009  "Data"
         #define STR0010  "Sub-Lote"
         #define STR0011  "Lote"
         #define STR0012  "Validade"
         #define STR0013  "N£mero de S‚rie"
         #define STR0014  "Quantidade"
         #define STR0015  "Quantidade Secund ria"
         #define STR0016  "Documento"
   #ENDIF
#ENDIF
