#IFDEF SPANISH
         #define STR0001  "bUscar"
         #define STR0002  "Visualizar"
         #define STR0003  "Incluir"
         #define STR0004  "Modificar"
         #define STR0005  "Borrar"
         #define STR0006  "Localizaci¢n F¡sica"
         #define STR0007  "Abandona"
         #define STR0008  "Confirma"
         #define STR0009  "¨Cuanto al borrar?"
         #define STR0010  "El dep¢sito   "
         #define STR0011  " localizaci¢n "
         #define STR0012  " tiene  "
         #define STR0013  "saldo en stock.  Si borrar esta localizaci¢n no podr  hacer "
         #define STR0014  "nuevas distribuciones para ella. "
         #define STR0015  "¨Confirma el borrar?"
         #define STR0016  "Atenci¢n - "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search   "
         #define STR0002  "View  "
         #define STR0003  "Insert "
         #define STR0004  "Edit   "
         #define STR0005  "Delete "
         #define STR0006  "Physical Location "
         #define STR0007  "Quit   "
         #define STR0008  "OK     "
         #define STR0009  "About Deleting?  "
         #define STR0010  "The Local     "
         #define STR0011  " location   "
         #define STR0012  " has    "
         #define STR0013  "balance in Stocks. Deleting this Local, will prevent new         "
         #define STR0014  "distributions in its favor. "
         #define STR0015  "Confirm exclusion?"
         #define STR0016  "Attention-"
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Visualizar"
         #define STR0003  "Incluir"
         #define STR0004  "Alterar"
         #define STR0005  "Excluir"
         #define STR0006  "Localiza‡„o F¡sica"
         #define STR0007  "Abandona"
         #define STR0008  "Confirma"
         #define STR0009  "Quanto … exclus„o?"
         #define STR0010  "O almoxarifado "
         #define STR0011  " localiza‡„o "
         #define STR0012  " possui "
         #define STR0013  "saldo em estoque . Excluir esta localiza‡„o impedir  nova(s) "
         #define STR0014  "distribui‡”es para a mesma. "
         #define STR0015  "Confirma exclus„o ?"
         #define STR0016  "Aten‡„o - "
   #ENDIF
#ENDIF