#IFDEF SPANISH
         #define STR0001  "Buscar"
         #define STR0002  "Consultar"
         #define STR0003  "Consulta Posici¢n de SD's"
         #define STR0004  "Ctd.Disponible"
         #define STR0005  "Ctd. en SC"
         #define STR0006  "Situaci¢n"
         #define STR0007  "N£mero de SC"
         #define STR0008  "N£mero de Req."
         #define STR0009  "Solicitud al Dep¢sito"
         #define STR0010  "&N£mero"
         #define STR0011  "&Solicitante"
         #define STR0012  "&Fecha de Emisi¢n"
         #define STR0013  "Esperando entrega del material"
         #define STR0014  "Solicitud en proceso de cotizaci¢n"
         #define STR0015  "Solicitud de Compras en abierto"
         #define STR0016  "Solicitud al Dep¢sito ya disponible"
         #define STR0017  "Solicitud al Dep¢sito ya atendida"
         #define STR0018  "Solicitud al Dep¢sito en abierto"
#ELSE
   #IFDEF ENGLISH
	      #define STR0001  "Pesquisar"
         #define STR0002  "Consultar"
         #define STR0003  "Cunsulta Posicao das SA's"
         #define STR0004  "Qtd.Disponivel"
         #define STR0005  "Qtd. em SC"
         #define STR0006  "Situacao"
         #define STR0007  "Numero da SC"
         #define STR0008  "Numero da Req."
         #define STR0009  "Solicita‡„o ao Almoxarifado"
         #define STR0010  "&N£mero"
         #define STR0011  "&Solicitante"
         #define STR0012  "&Data de Emiss„o"
         #define STR0013  "Aguardando entrega do material"
         #define STR0014  "Solicitacao em processo de cotacao"
         #define STR0015  "Solicitacao de Compras em aberto"
         #define STR0016  "Solicitacao ao Almox. ja disponivel"
         #define STR0017  "Solicitacao ao Almox. ja atendida"
         #define STR0018  "Solicitacao ao Almox. em aberto"
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Consultar"
         #define STR0003  "Consulta Posicao das SA's"
         #define STR0004  "Qtd.Disponivel"
         #define STR0005  "Qtd. em SC"
         #define STR0006  "Situacao"
         #define STR0007  "Numero da SC"
         #define STR0008  "Numero da Req."
         #define STR0009  "Solicita‡„o ao Almoxarifado"
         #define STR0010  "&N£mero"
         #define STR0011  "&Solicitante"
         #define STR0012  "&Data de Emiss„o"
         #define STR0013  "Aguardando entrega do material"
         #define STR0014  "Solicitacao em processo de cotacao"
         #define STR0015  "Solicitacao de Compras em aberto"
         #define STR0016  "Solicitacao ao Almox. ja disponivel"
         #define STR0017  "Solicitacao ao Almox. ja atendida"
         #define STR0018  "Solicitacao ao Almox. em aberto"
   #ENDIF
#ENDIF