#IFDEF SPANISH
         #define STR0001  "bUscar    "
         #define STR0002  "Consulta"
         #define STR0003  "Consulta General al Producto"
         #define STR0004  "BROWSE"
         #define STR0005  "Actualizando"
         #define STR0006  " Registros         "
         #define STR0007  " V°nculo Producto X Proveedor "
         #define STR0008  " V°nculo Grupo X Proveedor "
         #define STR0009  " V°nculo Producto X Cliente "
         #define STR0010  " Movimientos en Abierto "
         #define STR0011  "≥ Solicitudes de Compra                                                ≥"
         #define STR0012  "≥Solicit.  Fc.Entr. Cotiz.    Cant.Inf.   Cant.Entr.        Saldo      ≥"
         #define STR0013  "≥Ctd.Tot.: "
         #define STR0014  " Ctd.Entr.: "
         #define STR0015  " Sld.: "
         #define STR0016  "≥ Pedidos de Compra                                                    ≥"
         #define STR0017  "≥Pedido Fc.Entr. Proveedor    Cant.Inf.          Saldo  Saldo en Valor ≥"
         #define STR0018  " Sld.Vl.: "
         #define STR0019  "≥ Reservas                                                             ≥"
         #define STR0020  "≥Dep¢s. Orden Prod. C Costo   Fc. Res.  Cantidad                       ≥"
         #define STR0021  "≥ Cantidad Total reservada : "
         #define STR0022  "≥ Pedidos de Venta                                                     ≥"
         #define STR0023  "≥Pedido/÷t Cliente     Cant.Inf.      Vlr.Total Reserva       Saldo    ≥"
         #define STR0024  "≥Ctd.Total: "
         #define STR0025  " Saldo Total  : "
         #define STR0026  "≥O.Prod/÷t/Sec Loc   Cant.Inf.   Cant.Entr.     PÇrdida  P.Ini  P.Final≥"
         #define STR0027  " Ctd.Entreg.: "
         #define STR0028  " PÇrdida:"
         #define STR0029  " Historiales de Movimientos "
         #define STR0030  "≥ Registros de Entrada                                                 ≥"
         #define STR0031  "≥TP  F.Fiscal"
         #define STR0032  " Vlr.Total: "
         #define STR0033  " Num.Movim. "
         #define STR0034  "≥ Registros de Salida                                                  ≥"
         #define STR0035  "≥TP  F.Fiscal"
         #define STR0036  "≥TP F.Fiscal"
         #define STR0037  "≥Ctd.Total: "
         #define STR0038  " Num.Registr "
         #define STR0039  "≥TP  F.Fiscal"
         #define STR0040  "≥    Ctd : "
         #define STR0041  "≥    Ctd : "
         #define STR0042  "≥ Proyecci¢n de Saldos                                                 ≥"
         #define STR0043  "≥  Fecha   Saldo Inic.  Ctd.Entrada    Ctd.Salida  Saldo Final         ≥"
         #define STR0044  "POSICI‡N ACTUAL DE PRODUCTO"
         #define STR0045  "Este programa imprimir† la Consulta del Producto seleccionado,"
         #define STR0046  "informando los registros, Movimientos en Abierto, Histo- "
         #define STR0047  "rial de Movimientos, Saldos y Consumos.     "
         #define STR0048  "  "
         #define STR0049  "Administraci¢n"
         #define STR0050  "Consulta General al Producto"
         #define STR0051  "Continua......."
         #define STR0052  "An†lisis del Producto"
         #define STR0053  "  Emisi¢n  Entrada Proveedor  Cantidad     Vlr. Total Stc.≥"
			#define STR0054  " Pedido  Emisi¢n Cliente     Cantidad     Vlr. Total Stc. ≥"
			#define STR0055  "  Emisi¢n     Cantidad   RE/DE Local OP/Documento         ≥"
			#define STR0056  "  Emisi¢n Clie/Prov Lc   Cantidad   Vl. Unit.  Èlt.Entr   ≥"
			#define STR0057  "Ordenes de Producci¢n"
			#define STR0058  "Previsiones de Venta"
			#define STR0059  "≥Documento   Local  Cantidad            Valor   Fecha                  ≥"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search  "
         #define STR0002  "Query   "
         #define STR0003  "General Product Query"
         #define STR0004  "BROWSE"
         #define STR0005  "Updating   "
         #define STR0006  " Registration Data "
         #define STR0007  " Binding Product X Supplier "
         #define STR0008  " Binding Group X Supplier "
         #define STR0009  " Binding Product X Client "
         #define STR0010  " Pendent Transaction  "
         #define STR0011  "≥ Purchase Requisitions                                                ≥"
         #define STR0012  "≥Requesit. Inflow Dt Quotat. Inf.Qty.    Inflow Qty.       Balance    ≥"
         #define STR0013  "≥Tot.Qty.: "
         #define STR0014  " Input Qty: "
         #define STR0015  " Bal.: "
         #define STR0016  "≥ Purchase Orders                                                      ≥"
         #define STR0017  "≥Order Infl.Dt  Supplier   Inf.Qty.          Balance in Value ≥"
         #define STR0018  " Vl.Bal.: "
         #define STR0019  "≥ Allocat.                                                             ≥"
         #define STR0020  "≥Local  Produc.Ord. Cost C.   Res.Date  Quantity                        ≥"
         #define STR0021  "≥ Total Quantity Reserved:     "
         #define STR0022  "≥ Sales Orders                                                         ≥"
         #define STR0023  "≥Order It Client     Inf. Qty.     Tot.Value Reserve       Balance  ≥"
         #define STR0024  "≥Tot.Qty.: "
         #define STR0025  " Total Balance: "
         #define STR0026  "≥O.Prod/It/Seq Plc  Inf.Qty.    Infl. Qty.      Loss     Init.P. Fin.P.≥"
         #define STR0027  " Delivered Qty.: "
         #define STR0028  " Loss :"
         #define STR0029  " Transaction Reviews"
         #define STR0030  "≥ Inflow Entries                                               ≥"
         #define STR0031  "≥KD  Invoice  Issue    Supplier Entry Quantity      Tot.Rev.Value ≥"
         #define STR0032  " Tot.Value: "
         #define STR0033  " Transact.N."
         #define STR0034  "≥ Outflow Entries                                                     ≥"
         #define STR0035  "≥KD  Invoice  Order   Client Issue      Quantity     Tot. Value Rev. ≥"
         #define STR0036  "≥KD Invoice   Issue      Quantity    RE/DE Place OP/Document           ≥"
         #define STR0037  "≥Tot.Qty. : "
         #define STR0038  " Num.Entries "
         #define STR0039  "≥KD  Invoice   Issue   Clie/Suppl  Quantity   Unit Value Last Inflow≥"
         #define STR0040  "≥    Qty : "
         #define STR0041  "≥    Qty : "
         #define STR0042  "≥ Balance Projection                                                  ≥"
         #define STR0043  "≥  Date    Init. Bal.   Infl. Qty.    Outfl. Qty.  Final Balance        ≥"
         #define STR0044  "PRODUCT CURRENT POSITION"
         #define STR0045  "This program will print  the Product Query selected,   "
         #define STR0046  "informing the registration data, Pending Transactions,   "
         #define STR0047  "TRansact. Reviews, Balances Consump."
         #define STR0048  "Z.Form"
         #define STR0049  "Management"
         #define STR0050  "General Product Query    "
         #define STR0051  "Continued......."
         #define STR0052  "Product Analysis  "
         #define STR0053  "  Issue    Inflow  Supplier  Quantity      Vle. Total Sto.≥"
         #define STR0054  " Order   Issue   Client     Quantity      Vle. Total Sto. ≥"
         #define STR0055  "  Issue      Quantity    RE/DE Local PO/Document          ≥"
         #define STR0056  "  Issue   Clie/Supp Lc  Quantity    Vl. Unit.  Lst.Inflow ≥"
		 #define STR0057  "Sale Orders       "
		 #define STR0058  "Sale Forecasts    "
		 #define STR0059  "≥Document    Local  Quantity            Value   Date                   ≥"
	#ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Consulta"
         #define STR0003  "Consulta Geral ao Produto"
         #define STR0004  "BROWSE"
         #define STR0005  "Atualizando"
         #define STR0006  " Dados Cadastrais "
         #define STR0007  " Amarracao Produto X Fornecedor "
         #define STR0008  " Amarracao Grupo X Fornecedor "
         #define STR0009  " Amarracao Produto X Cliente "
         #define STR0010  " Movimentos em Aberto "
         #define STR0011  "≥ Solicitacoes de Compra                                               ≥"
         #define STR0012  "≥Solicit.  Dt.Entr. Cotac.   Quant.Inf.  Quant.Entr.        Saldo      ≥"
         #define STR0013  "≥Qtd.Tot.: "
         #define STR0014  " Qtd.Entr.: "
         #define STR0015  " Sld.: "
         #define STR0016  "≥ Pedidos de Compra                                                    ≥"
         #define STR0017  "≥Pedido Dt.Entr. Forneced.   Quant.Inf.          Saldo  Saldo em Valor ≥"
         #define STR0018  " Sld.Vl.: "
         #define STR0019  "≥ Empenhos                                                             ≥"
         #define STR0020  "≥Almox. Ordem Prod. C Custo   Dt. Emp. Quantidade                      ≥"
         #define STR0021  "≥ Quantidade Total empenhada : "
         #define STR0022  "≥ Pedidos de Venda                                                     ≥"
         #define STR0023  "≥Pedido/It Cliente    Quant.Inf.      Vlr.Total Reserva       Saldo    ≥"
         #define STR0024  "≥Qtd.Total: "
         #define STR0025  " Saldo Total  : "
         #define STR0026  "≥O.Prod/It/Seq Loc  Quant.Inf.  Quant.Entr.     Perda    P.Ini  P.Final≥"
         #define STR0027  " Qtd.Entreg.: "
         #define STR0028  " Perda:"
         #define STR0029  " Historicos de Movimentacoes "
         #define STR0030  "≥ Lancamentos de Entrada                                               ≥"
         #define STR0031  "≥TP  N.Fiscal"
         #define STR0032  " Vlr.Total: "
         #define STR0033  " Num.Movim. "
         #define STR0034  "≥ Lancamentos de Saida                                                 ≥"
         #define STR0035  "≥TP  N.Fiscal"
         #define STR0036  "≥TP N.Fiscal"
         #define STR0037  "≥Qtd.Total: "
         #define STR0038  " Num.Lanctos "
         #define STR0039  "≥TP  N.Fiscal"
         #define STR0040  "≥    Qtd : "
         #define STR0041  "≥    Qtd : "
         #define STR0042  "≥ Projecao de Saldos                                                   ≥"
         #define STR0043  "≥  Data    Saldo Inic.  Qtd.Entrada    Qtd.Saida  Saldo Final          ≥"
         #define STR0044  "POSICAO ATUAL DE PRODUTO"
         #define STR0045  "Este programa ira imprimir a Consulta do Produto selecionado,"
         #define STR0046  "informando os dados cadastrais, Movimentacoes em Aberto,"
         #define STR0047  "Historico de Movimentacoes, Saldos e Consumos."
         #define STR0048  "Zebrado"
         #define STR0049  "Administracao"
         #define STR0050  "Consulta Geral ao Produto"
         #define STR0051  "Continua......."
         #define STR0052  "Analise do Produto"
         #define STR0053  "  Emissao  Entrada Forneced. Quantidade    Vlr. Total Est.≥"
         #define STR0054  " Pedido  Emissao Cliente    Quantidade    Vlr. Total Est. ≥"
         #define STR0055  "  Emissao    Quantidade  RE/DE Local OP/Documento         ≥"
         #define STR0056  "  Emissao Clie/Forn Lc  Quantidade  Vl. Unit.  Ult.Entr   ≥"
			#define STR0057  "Ordens de Producao"
			#define STR0058  "Previsoes de Venda"
			#define STR0059  "≥Documento   Local  Quantidade          Valor   Data                   ≥"
   #ENDIF
#ENDIF