#IFDEF SPANISH
	#define STR0001 "Atenci¢n"
	#define STR0002 "Error al tentar abrir la comunicaci¢n con la impresora en el puerto: "
	#define STR0003 " Verificar..."
	#define STR0004 "Error de comunicaci¢n f¡sica con la impresora."
	#define STR0005 " Revise si la impresora est  conectada al puerto o   "
	#define STR0006 " o si est  enchuflada.    ."
	#define STR0007 "Los par metros mandados a la impresora no tienen validez."
	#define STR0008 "Revisar  ..."
	#define STR0009 "La impresora no soporta el comando que le fue enviado.            "
	#define STR0010 "Error al tentar cerrar la comunicaci¢n con la impressora en el Puerto: "
	#define STR0011 "Problemas con la Impresora Fiscal"
#ELSE
	#IFDEF ENGLISH
		#define STR0001 "Aten‡„o"
		#define STR0002 "Erro ao tentar abrir a comunica‡„o com a Impressora na Porta: "
		#define STR0003 " Verificar..."
		#define STR0004 "Erro de comunica‡„o f¡sica com a impressora."
		#define STR0005 " Verifique se a impressora est  conectada a porta "
		#define STR0006 " ou se a mesma est  ligada."
		#define STR0007 "Os parƒmetros enviados para a impressoras s„o inv lidos "
		#define STR0008 "Verificar..."
		#define STR0009 "O comando enviado para a impressora n„o ‚ suportado pela mesma."
		#define STR0010 "Erro ao tentar fechar a comunica‡„o com a Impressora na Porta: "
		#define STR0011 "Problemas com a Impressora Fiscal"
	#ELSE
		#define STR0001 "Aten‡„o"
		#define STR0002 "Erro ao tentar abrir a comunica‡„o com a Impressora na Porta: "
		#define STR0003 " Verificar..."
		#define STR0004 "Erro de comunica‡„o f¡sica com a impressora."
		#define STR0005 " Verifique se a impressora est  conectada a porta "
		#define STR0006 " ou se a mesma est  ligada."
		#define STR0007 "Os parƒmetros enviados para a impressoras s„o inv lidos "
		#define STR0008 "Verificar..."
		#define STR0009 "O comando enviado para a impressora n„o ‚ suportado pela mesma."
		#define STR0010 "Erro ao tentar fechar a comunica‡„o com a Impressora na Porta: "
		#define STR0011 "Problemas com a Impressora Fiscal"
	#ENDIF
#ENDIF