#IFDEF SPANISH
   #define STR0001  "Confirma"
   #define STR0002  "Retipea"
   #define STR0003  "Salir"
   #define STR0004  "¨Cu nto a las modificaciones?"
   #define STR0005  "¨Cu nto a la inclusi¢n?"
   #define STR0006  " Suc+Par metro"
   #define STR0007  " Dom¡nio+C.Dom¡nio"
   #define STR0008  "Orden"
   #define STR0009  " Ötem a Localizar "
   #define STR0010  "B£squeda  "
   #define STR0011  "FORMULA"
   #define STR0012  " Presione una tecla para Salir "
   #define STR0013  " Inconsistencia "
   #define STR0014  "B&uscar   "
   #define STR0015  "Visualizar"
   #define STR0016  "Incluir"
   #define STR0017  "Modificar"
   #define STR0018  "Borrar "
   #define STR0019  "¨Cu nto al Borrar?     "
   #define STR0020  "Problemas de Lock en el SX6"
   #define STR0021  "Problema de GRABACIàN en el SX8"
   #define STR0022  "Hay otro usuario utilizando el SX8. ¨Desea Cancelar?"
   #define STR0023  "Atenci¢n"
   #define STR0024  "   Hay otro usuario utilizando el SX8    "
   #define STR0025  "     ¨Desea cancelar la operaci¢n?       "
   #define STR0026  "   S¡   "
   #define STR0027  "   No   "
   #define STR0028  "Secuencia: "
   #define STR0029  "Problemas de Lock en el SX8"
   #define STR0030  "Error en el Gatillo: "
   #define STR0031  "Activo durante "
	#define STR0032  "Justificaci¢n"
	#define STR0033  "¨Cu nto a la Justificaci¢n?"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Confirm"
         #define STR0002  "Retype"
         #define STR0003  "Abandons"
         #define STR0004  "About changes?"
         #define STR0005  "About inclusion?"
         #define STR0006  " Branch+Parameter"
         #define STR0007  " Domain+C.Domain"
         #define STR0008  "Order"
         #define STR0009  " Item to Localize "
         #define STR0010  "Search"
         #define STR0011  "FORMULA"
         #define STR0012  " Press a key to abandon "
         #define STR0013  " Inconsistency "
         #define STR0014  "&Search"
         #define STR0015  "View"
         #define STR0016  "Include"
         #define STR0017  "Change"
         #define STR0018  "Exclude"
         #define STR0019  "About exclusion?"
         #define STR0020  "Lock Problems in SX6"
         #define STR0021  "Recording Problems in SX8"
         #define STR0022  "There's another user using SX8. Wish to Cancel ?"
         #define STR0023  "Attention"
         #define STR0024  " Ther's another  user using SX8    "
         #define STR0025  "  Wish to cancel the operation?    "
         #define STR0026  "   Yes   "
         #define STR0027  "   No    "
         #define STR0028  "Sequence: "
         #define STR0029  "Lock Problems in SX8"
         #define STR0030  "Error in Trigger : "
         #define STR0031  "Active during "
			#define STR0032  "Justificativa"
			#define STR0033  "Quanto … Justificativa ?"
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Quanto …s altera‡”es?"
         #define STR0005  "Quanto … inclus„o?"
         #define STR0006  " Filial+Parametro"
         #define STR0007  " Dominio+C.Dominio"
         #define STR0008  "Ordem"
         #define STR0009  " Item a Localizar "
         #define STR0010  "Pesquisa"
         #define STR0011  "FORMULA"
         #define STR0012  " Pressione uma tecla para Abandonar "
         #define STR0013  " Inconsistˆncia "
         #define STR0014  "Pesquisar"
         #define STR0015  "Visualizar"
         #define STR0016  "Incluir"
         #define STR0017  "Alterar"
         #define STR0018  "Excluir"
         #define STR0019  "Quanto … exclus„o?"
         #define STR0020  "Problemas de Lock no SX6"
         #define STR0021  "Problema de GRAVACAO NO SX8"
         #define STR0022  "H  outro usu rio utilizando o SX8. Deseja Cancelar ?"
         #define STR0023  "Aten‡„o"
         #define STR0024  "   H  outro usu rio utilizando o SX8    "
         #define STR0025  "      Deseja cancelar a opera‡„o?       "
         #define STR0026  "   Sim   "
         #define STR0027  "   Nƒo   "
         #define STR0028  "Sequencia: "
         #define STR0029  "Problemas de Lock no SX8"
         #define STR0030  "Erro no Gatilho : "
			#define STR0031  "Ativo durante "
			#define STR0032  "Justificativa"
			#define STR0033  "Quanto … Justificativa ?"
   #ENDIF
#ENDIF