#IFDEF SPANISH
	#define STR0001  'Confirma'
	#define STR0002  'Salir   '
	#define STR0003  'Totaliza'
	#define STR0004  'Retipea '
	#define STR0005  'Acumulado de las Marcaciones'
	#define STR0006  'B&uscar '
	#define STR0007  'Actualizar'
	#define STR0009  'Borrar '
	#define STR0010  'Dom'
	#define STR0011  'Lun'
	#define STR0012  'Mar'
	#define STR0013  'Mie'
	#define STR0014  'Jue'
	#define STR0015  'Vie'
	#define STR0016  'Sab'
	#define STR0018  'Fecha Ref'
	#define STR0019  'Fecha 1¦ E'
	#define STR0020  'a S'
	#define STR0024  'a E'
	#define STR0027  ' Acumulado de las Marcaciones '
	#define STR0033  '¨ Cu nto '
	#define STR0034  'a la Actualizaci¢n ?'
	#define STR0035  'al Borrar ?'
	#define STR0036  'Atenci¢n'
	#define STR0037  'Usted est  a punto de perder las modificaciones hechas.'
	#define STR0038  'Acepta'
	#define STR0039  'Matr¡cula: '
	#define STR0040  'Nombre: '
	#define STR0041  'Inconsistencia'
	#define STR0042  'Hay uno o m s d¡as con un n£mero impar de marcaciones'
	#define STR0046  ' - ******* Compensado *******'
	#define STR0047  ' - ********* D S R **********'
	#define STR0048  ' - *****  No Trabajado  *****'
	#define STR0049  '******* Licencia *********'
	#define STR0050  '******** Feriado *********'
	#define STR0051  ' Consulta de Horarios '
	#define STR0052  'Consulta de Horarios '
	#define STR0053  ' Fechas'
	#define STR0054  ' Marcaciones'
	#define STR0055  'C¢d.'
	#define STR0056  'Descripci¢n'
	#define STR0057  'Calculado'
	#define STR0059  ' Visualizaci¢n de las Anotaciones '
	#define STR0061  "Visualizaci¢n de las Anotaciones"
	#define STR0062  "C¢d"
	#define STR0063  "C lculado"
	#define STR0064  '** No Registrado  **'
	#define STR0066  'Recortar'
	#define STR0068  'Copiar'
	#define STR0070  'Pegar'
	#define STR0072  'Calculadora...'
	#define STR0074  'Agenda...'
	#define STR0075  'Controlador de Impresi¢n...'
	#define STR0076  'Help de Programa...'
	#define STR0078  'Borra Columna'
	#define STR0080  'Incluye Columna'
	#define STR0082  'Genera Valor en la Columna'
	#define STR0085  'Consulta de Horarios'
	#define STR0088  'OK - <Ctrl-O>'
	#define STR0090  'Cancelar - <Ctrl-X>'
	#define STR0091  'Espere ...'
	#define STR0092  ' Alt+H Tab.Horarios³Alt+G Genera Marc. ³Alt+Ins Inserta Col³Alt+Del Borra Col'
	#define STR0093  'Mat.: '
	#define STR0094  '     Fecha        1¦ E   1¦ S   2¦ E   2¦ S         '
#ELSE
   #IFDEF ENGLISH
         #define STR0001  'O.K.    '
         #define STR0002  'Quit    '
         #define STR0003  'Total   '
         #define STR0004  'Retype  '
         #define STR0005  'Marking Accumulated    '
         #define STR0006  'Search   '
         #define STR0007  'Edit     '
         #define STR0009  'Delete '
         #define STR0010  'Sun'
         #define STR0011  'Mon'
         #define STR0012  'Tue'
         #define STR0013  'Wen'
         #define STR0014  'Thu'
         #define STR0015  'Fri'
         #define STR0016  'Sat'
         #define STR0018  'Ref. Date'
         #define STR0019  '1st E Dt.'
         #define STR0020  'to Ex'
         #define STR0024  'to Ex'
         #define STR0027  ' Marking Accumulated     '
         #define STR0033  'About    '
         #define STR0034  'Editing    '
         #define STR0035  'Deleting'
         #define STR0036  'Attention'
         #define STR0037  'You are about to losing the modifications carried out.'
         #define STR0038  'O.K.  '
         #define STR0039  'Registrat.:'
         #define STR0040  'Name:'
         #define STR0041  'Inconsistency '
         #define STR0042  'There is one or more days with Odd Marking          '
         #define STR0046  ' - ******* Compensated *******'
         #define STR0047  ' - *******Rem.Week.Rest******'
         #define STR0048  ' - *****   Not Worked   *****'
         #define STR0049  '******* Dismessed ********'
         #define STR0050  '******** Vacation ********'
         #define STR0051  ' Checking Time Schedule'
         #define STR0052  'Checking Time Schedule'
         #define STR0053  ' Date '
         #define STR0054  ' Marking  '
         #define STR0066  'Cut     '
         #define STR0068  'Copy  '
         #define STR0070  'Pasete'
         #define STR0072  'Calculator... '
         #define STR0074  'Agenda...'
         #define STR0075  'Printer Manager...         '
         #define STR0076  'Program Help...    '
         #define STR0078  'Delete Column'
         #define STR0080  'Insert Column'
         #define STR0082  'Generate Val. Column'
         #define STR0085  'Checking Time Sched.'
         #define STR0088  'Ok - <Ctrl-O>'
         #define STR0090  'Cancel   - <Ctrl-X>'
         #define STR0091  'Wait...   '
         #define STR0092  ' Alt+H Time Table  ³Alt+G Gen. Marking ³Alt+Ins Insert.Col.³Alt+Del Delete.Col. '
         #define STR0093  'Regi.:'
         #define STR0094  '     Date         1stE   1stEx  2ndE   2ndEx        '
   #ELSE
			#define STR0001  'Confirma'
         #define STR0002  'Abandona'
         #define STR0003  'Totaliza'
         #define STR0004  'Redigita'
         #define STR0005  'Acumulado das Marca‡”es'
         #define STR0006  'Pesquisar'
         #define STR0007  'Atualizar'
         #define STR0009  'Excluir'
         #define STR0010  'Dom'
         #define STR0011  'Seg'
         #define STR0012  'Ter'
         #define STR0013  'Qua'
         #define STR0014  'Qui'
         #define STR0015  'Sex'
         #define STR0016  'Sab'
         #define STR0018  'Data Ref.'
         #define STR0019  'Data 1a E'
         #define STR0020  'a S'
         #define STR0024  'a E'
         #define STR0027  ' Acumulado das Marca‡”es '
         #define STR0033  'Quanto a '
         #define STR0034  'Atualiza‡„o'
         #define STR0035  'Exclus„o'
         #define STR0036  'Aten‡„o'
         #define STR0037  'Vo‡ˆ est  prestes a perder as altera‡”es realizadas.'
         #define STR0038  'Aceita'
         #define STR0039  'Matricula:'
         #define STR0040  'Nome:'
         #define STR0041  'Inconsistencia'
         #define STR0042  'Existe um ou mais dias com numero de marcacoes Impar'
         #define STR0046  ' - ******* Compensado *******'
         #define STR0047  ' - ********* D S R **********'
         #define STR0048  ' - ***** Nao Trabalhado *****'
         #define STR0049  '******* Afastado *********'
         #define STR0050  '******** Feriado *********'
         #define STR0051  ' Consulta de Hor rios '
         #define STR0052  'Consulta de Hor rios'
         #define STR0053  ' Datas'
         #define STR0054  ' Marca‡”es'
         #define STR0066  'Recortar'
         #define STR0068  'Copiar'
         #define STR0070  'Colar'
         #define STR0072  'Calculadora...'
         #define STR0074  'Agenda...'
         #define STR0075  'Gerenciador de ImpressÆo...'
         #define STR0076  'Help de Programa...'
         #define STR0078  'Deleta Coluna'
         #define STR0080  'Inclui Coluna'
         #define STR0082  'Gera Valor na Coluna'
         #define STR0085  'Consulta de Horarios'
         #define STR0088  'Ok - <Ctrl-O>'
         #define STR0090  'Cancelar - <Ctrl-X>'
         #define STR0091  'Aguarde...'
         #define STR0092  ' Alt+H Tab.Hor rios³Alt+G Gera Marca‡„o³Alt+Ins Insere.Col.³Alt+Del Deleta.Col. '
         #define STR0093  'Matr.:'
         #define STR0094  '     Data         1¦ E   1¦ S   2¦ E   2¦ S         '
   #ENDIF
#ENDIF