#IFDEF SPANISH
	#define STR0001  'Eliminaci¢n de las Marcaciones'
	#define STR0003  'El objetivo de este programa es hacer la Eliminaci¢n de :'
	#define STR0004  '- Resultados  (SPB)'
	#define STR0005  '- Anotaciones (SPC)'
	#define STR0006  '- Comidas     (SP5)'
	#define STR0007  '- Marcaciones (SP8)'
	#define STR0008  'Confirma'
	#define STR0009  'Retipea '
	#define STR0010  'Salir   '
	#define STR0011  'Contin£a'
	#define STR0016  'Limpiando Marcaciones...'
#ELSE
   #IFDEF ENGLISH
                #define STR0001  'Elimination of Markings '
                #define STR0003  'This program has the purpose of executing the Elimination of:'
                #define STR0004  '- Result  (SPB)'
                #define STR0005  '- Annotations (SPC)'
                #define STR0006  '- Meals       (SP5)'
                #define STR0007  '- Markings    (SP8)'
                #define STR0008  'O.K.    '
                #define STR0009  'Retype  '
                #define STR0010  'Quit    '
                #define STR0011  'Continue'
                #define STR0016  'Clearing Markings ...'
   #ELSE
		#define STR0001  'Elimina‡„o das Marca‡”es'
		#define STR0003  'Este programa tem como objetivo efetuar a Elimina‡„o de :'
		#define STR0004  '- Resultados  (SPB)'
		#define STR0005  '- Apontamentos(SPC)'
		#define STR0006  '- Refei‡”es   (SP5)'
		#define STR0007  '- Marca‡”es   (SP8)'
		#define STR0008  'Confirma'
		#define STR0009  'Redigita'
		#define STR0010  'Abandona'
		#define STR0011  'Continua'
		#define STR0016  'Limpando Marca‡”es...'
   #ENDIF
#ENDIF