#IFDEF SPANISH
         #define STR0001  "B&uscar  "
         #define STR0002  "Visualizar"
         #define STR0003  "Incluir"
         #define STR0004  "Modificar"
         #define STR0005  "Borrar "
         #define STR0006  "Archivo de Documentos"
         #define STR0007  "Salir   "
         #define STR0008  "Confirma"
         #define STR0009  "¨Cu nto a las Modificaciones"
         #define STR0010  "Cortar  "
         #define STR0011  "Copiar"
         #define STR0012  "Pegar"
         #define STR0013  "Calculadora..."
         #define STR0014  "Agenda..."
         #define STR0015  "Controlador de Impresi¢n..."
         #define STR0016  "Help de Programa..."
         #define STR0017  "Objetivo"
         #define STR0018  "Documento"
         #define STR0019  "Destinos"
         #define STR0020  "Responsables"
         #define STR0021  "Referencias"
         #define STR0022  "Solicitud de Modificaci¢n"
         #define STR0023  "Localizadores"
         #define STR0024  "Cr¡ticas"
         #define STR0026  "Carpetas"
         #define STR0027  "OK - <Ctrl-O>"
         #define STR0028  "Cancelar - <Ctrl-X>"
         #define STR0030  "Docto: "
         #define STR0031  "Revisi¢n: "
         #define STR0032  "T¡tulo  : "
         #define STR0033  "Localizadores-Palabra Clave"
         #define STR0034  "Texto"
         #define STR0035  "Comentario"
         #define STR0037  "Objetivo del Documento"
         #define STR0038  "Revisi¢n"
         #define STR0039  "Motivo de la Revisi¢n"
         #define STR0040  "Sumario"
         #define STR0041  "Terminar"
         #define STR0042  "Seleccionando Destinos..."
         #define STR0043  "Selecionando Destinatarios..."
         #define STR0044  "Archivo de Destinatarios"
         #define STR0045  "Destinos"
         #define STR0046  "Destinatarios - Usuarios"
         #define STR0047  "Suc"
         #define STR0048  "C¢digo"
         #define STR0049  "Descripci¢n"
         #define STR0050  " R "
         #define STR0051  "Tp.Recib"
         #define STR0052  " Usuarios/Carpetas"
         #define STR0053  "Destinos - Borrar  "
         #define STR0054  "Destinos - Incluir "
         #define STR0055  "Sucursal"
         #define STR0060  "Devolver Docto"
         #define STR0061  "Tipo"
         #define STR0062  "&Escrits"
         #define STR0063  "&Carpetas"
         #define STR0064  "Destinatarios - Modificaci¢n"
         #define STR0065  "&S¡ "
         #define STR0066  "&No "
         #define STR0067  "Recibe Docto"
         #define STR0068  "Usuario"
         #define STR0069  "N§ Copias"
         #define STR0070  "Escrit"
         #define STR0071  "Carpeta"
         #define STR0074  "Consulta de los Documentos"
         #define STR0075  "Documentos"
         #define STR0076  "Historial"
         #define STR0077  "Detalle"
         #define STR0078  "Tipo Docto"
         #define STR0079  "C¢d. Asunto"
         #define STR0080  "éltima Revisi¢n"
         #define STR0081  "Rv"
         #define STR0082  "Estatus"
         #define STR0083  "Asunto"
         #define STR0084  "T¡tulo"
         #define STR0085  "Pendiente"
         #define STR0086  "Apodo "
         #define STR0087  "Realizaci¢n"
         #define STR0088  "Creaci¢n"
         #define STR0089  "Cr"
         #define STR0090  "Usuario"
         #define STR0091  "Fch. Vigor "
         #define STR0092  "Pendiente"
         #define STR0093  "Cancelar"
         #define STR0094  " Seleccionando Distribuiciones "
         #define STR0095  "Espere..."
         #define STR0096  "Documento no Aprobado "
         #define STR0097  "AVISO"
         #define STR0098  "¨Confirma la Devoluci¢n del Docto?"
         #define STR0099  "Atenci¢n"
         #define STR0100  "¨Terminar Docto?"
         #define STR0101  "¨Confirma dejar este Docto Pendiente?"
         #define STR0102  "Fc.L¡m."
         #define STR0103  "Devoluci¢n del Documento"
         #define STR0104  "Devolver el Documento para "
         #define STR0105  "Tipeador"
         #define STR0106  " o para el Elaborador"
         #define STR0107  "Elaborador"
         #define STR0108  "¨Cu nto al Borrar?"
         #define STR0109  "Duplo clic para Habilitar/Inhabilitar destinatario"
         #define STR0110  "Duplo clic para Seleccionar/Filtrar distribuiciones"
         #define STR0112  "&Electr¢nica"
         #define STR0113  "&Papel"
         #define STR0114  "&Ambos"
         #define STR0115  "No &Recibe"
         #define STR0116  "Tip.Copias"
         #define STR0117  " Espere...Generando Pendientes"
         #define STR0118  "T‚rmino del Docto"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Pesquisar"
         #define STR0002  "Visualizar"
         #define STR0003  "Incluir"
         #define STR0004  "Alterar"
         #define STR0005  "Excluir"
         #define STR0006  "Cadastro de Documentos"
         #define STR0007  "Abandona"
         #define STR0008  "Confirma"
         #define STR0009  "Quanto …s altera‡”es?"
         #define STR0010  "Recortar"
         #define STR0011  "Copiar"
         #define STR0012  "Colar"
         #define STR0013  "Calculadora..."
         #define STR0014  "Agenda..."
         #define STR0015  "Gerenciador de Impress„o..."
         #define STR0016  "Help de Programa..."
         #define STR0017  "Objetivo"
         #define STR0018  "Documento"
         #define STR0019  "Destinos"
         #define STR0020  "Respons veis"
         #define STR0021  "Referˆncias"
         #define STR0022  "Solicita‡„o de Altera‡„o"
         #define STR0023  "Localizadores"
         #define STR0024  "Cr¡ticas"
         #define STR0026  "Pastas"
         #define STR0027  "OK - <Ctrl-O>"
         #define STR0028  "Cancelar - <Ctrl-X>"
         #define STR0030  "Docto: "
         #define STR0031  "Revis„o: "
         #define STR0032  "T¡tulo : "
         #define STR0033  "Localizadores-Palavra Chave"
         #define STR0034  "Texto"
         #define STR0035  "Coment rio"
         #define STR0037  "Objetivo do Documento"
         #define STR0038  "Revis„o"
         #define STR0039  "Motivo da Revis„o"
         #define STR0040  "Sum rio"
         #define STR0041  "Finalizar"
         #define STR0042  "Selecionando Destinos..."
         #define STR0043  "Selecionando Destinat rios..."
         #define STR0044  "Cadastro de Destinat rios"
         #define STR0045  "Destinos"
         #define STR0046  "Destinat rios - Usu rios"
         #define STR0047  "Fil"
         #define STR0048  "C¢digo"
         #define STR0049  "Descri‡„o"
         #define STR0050  " R "
         #define STR0051  "Tp.Recto"
         #define STR0052  " Usu rios/Pastas "
         #define STR0053  "Destinos - Exclus„o"
         #define STR0054  "Destinos - Inclus„o"
         #define STR0055  "Filial"
         #define STR0060  "Devolver Docto"
         #define STR0061  "Tipo"
         #define STR0062  "&Deptos"
         #define STR0063  "&Pastas"
         #define STR0064  "Destinat rios - Altera‡„o"
         #define STR0065  "&Sim"
         #define STR0066  "&N„o"
         #define STR0067  "Recebe Docto"
         #define STR0068  "Usu rio"
         #define STR0069  "No.C¢pias"
         #define STR0070  "Depto"
         #define STR0071  "Pasta"
         #define STR0074  "Consulta dos Documentos"
         #define STR0075  "Documentos"
         #define STR0076  "Hist¢rico"
         #define STR0077  "Detalhe"
         #define STR0078  "Tipo Docto"
         #define STR0079  "C¢d.Assunto"
         #define STR0080  "Ultima Revis„o"
         #define STR0081  "Rv"
         #define STR0082  "Status"
         #define STR0083  "Assunto"
         #define STR0084  "T¡tulo"
         #define STR0085  "Pendˆncia"
         #define STR0086  "Apelido"
         #define STR0087  "Realiza‡„o"
         #define STR0088  "Cria‡„o"
         #define STR0089  "Bx"
         #define STR0090  "Usu rio"
         #define STR0091  "Dt.Vigˆncia"
         #define STR0092  "Pendente"
         #define STR0093  "Cancelar"
         #define STR0094  " Selecionando Distribui‡”es "
         #define STR0095  "Aguarde..."
         #define STR0096  "Documento n„o Liberado"
         #define STR0097  "AVISO"
         #define STR0098  "Confirma a Devolu‡„o do Docto?"
         #define STR0099  "Aten‡„o"
         #define STR0100  "Finalizar Docto?"
         #define STR0101  "Confirma deixar esse Docto Pendente?"
         #define STR0102  "Dt.Lim."
         #define STR0103  "Devolu‡„o do Documento"
         #define STR0104  "Devolver o Documento para "
         #define STR0105  "Digitador"
         #define STR0106  " ou para o Elaborador"
         #define STR0107  "Elaborador"
         #define STR0108  "Quanto … exclus„o?"
         #define STR0109  "Duplo click para Habilitar/Desabilitar destinat rio"
         #define STR0110  "Duplo click para Selecionar/Filtrar distribui‡”es"
         #define STR0112  "&Eletr“nica"
         #define STR0113  "&Papel"
         #define STR0114  "&Ambos"
         #define STR0115  "N„o &Recebe"
         #define STR0116  "Tip.C¢pias"
         #define STR0117  " Aguarde...Gerando Pendˆncias"
         #define STR0118  "Finaliza‡„o do Docto"
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Visualizar"
         #define STR0003  "Incluir"
         #define STR0004  "Alterar"
         #define STR0005  "Excluir"
         #define STR0006  "Cadastro de Documentos"
         #define STR0007  "Abandona"
         #define STR0008  "Confirma"
         #define STR0009  "Quanto …s altera‡”es?"
         #define STR0010  "Recortar"
         #define STR0011  "Copiar"
         #define STR0012  "Colar"
         #define STR0013  "Calculadora..."
         #define STR0014  "Agenda..."
         #define STR0015  "Gerenciador de Impress„o..."
         #define STR0016  "Help de Programa..."
         #define STR0017  "Objetivo"
         #define STR0018  "Documento"
         #define STR0019  "Destinos"
         #define STR0020  "Respons veis"
         #define STR0021  "Referˆncias"
         #define STR0022  "Solicita‡„o de Altera‡„o"
         #define STR0023  "Localizadores"
         #define STR0024  "Cr¡ticas"
         #define STR0026  "Pastas"
         #define STR0027  "OK - <Ctrl-O>"
         #define STR0028  "Cancelar - <Ctrl-X>"
         #define STR0030  "Docto: "
         #define STR0031  "Revis„o: "
         #define STR0032  "T¡tulo : "
         #define STR0033  "Localizadores-Palavra Chave"
         #define STR0034  "Texto"
         #define STR0035  "Coment rio"
         #define STR0037  "Objetivo do Documento"
         #define STR0038  "Revis„o"
         #define STR0039  "Motivo da Revis„o"
         #define STR0040  "Sum rio"
         #define STR0041  "Finalizar"
         #define STR0042  "Selecionando Destinos..."
         #define STR0043  "Selecionando Destinat rios..."
         #define STR0044  "Cadastro de Destinat rios"
         #define STR0045  "Destinos"
         #define STR0046  "Destinat rios - Usu rios"
         #define STR0047  "Fil"
         #define STR0048  "C¢digo"
         #define STR0049  "Descri‡„o"
         #define STR0050  " R "
         #define STR0051  "Tp.Recto"
         #define STR0052  " Usu rios/Pastas "
         #define STR0053  "Destinos - Exclus„o"
         #define STR0054  "Destinos - Inclus„o"
         #define STR0055  "Filial"
         #define STR0060  "Devolver Docto"
         #define STR0061  "Tipo"
         #define STR0062  "&Deptos"
         #define STR0063  "&Pastas"
         #define STR0064  "Destinat rios - Altera‡„o"
         #define STR0065  "&Sim"
         #define STR0066  "&N„o"
         #define STR0067  "Recebe Docto"
         #define STR0068  "Usu rio"
         #define STR0069  "No.C¢pias"
         #define STR0070  "Depto"
         #define STR0071  "Pasta"
         #define STR0074  "Consulta dos Documentos"
         #define STR0075  "Documentos"
         #define STR0076  "Hist¢rico"
         #define STR0077  "Detalhe"
         #define STR0078  "Tipo Docto"
         #define STR0079  "C¢d.Assunto"
         #define STR0080  "Ultima Revis„o"
         #define STR0081  "Rv"
         #define STR0082  "Status"
         #define STR0083  "Assunto"
         #define STR0084  "T¡tulo"
         #define STR0085  "Pendˆncia"
         #define STR0086  "Apelido"
         #define STR0087  "Realiza‡„o"
         #define STR0088  "Cria‡„o"
         #define STR0089  "Bx"
         #define STR0090  "Usu rio"
         #define STR0091  "Dt.Vigˆncia"
         #define STR0092  "Pendente"
         #define STR0093  "Cancelar"
         #define STR0094  " Selecionando Distribui‡”es "
         #define STR0095  "Aguarde..."
         #define STR0096  "Documento n„o Liberado"
         #define STR0097  "AVISO"
         #define STR0098  "Confirma a Devolu‡„o do Docto?"
         #define STR0099  "Aten‡„o"
         #define STR0100  "Finalizar Docto?"
         #define STR0101  "Confirma deixar esse Docto Pendente?"
         #define STR0102  "Dt.Lim."
         #define STR0103  "Devolu‡„o do Documento"
         #define STR0104  "Devolver o Documento para "
         #define STR0105  "Digitador"
         #define STR0106  " ou para o Elaborador"
         #define STR0107  "Elaborador"
         #define STR0108  "Quanto … exclus„o?"
         #define STR0109  "Duplo click para Habilitar/Desabilitar destinat rio"
         #define STR0110  "Duplo click para Selecionar/Filtrar distribui‡”es"
         #define STR0112  "&Eletr“nica"
         #define STR0113  "&Papel"
         #define STR0114  "&Ambos"
         #define STR0115  "N„o &Recebe"
         #define STR0116  "Tip.C¢pias"
         #define STR0117  " Aguarde...Gerando Pendˆncias"
         #define STR0118  "Finaliza‡„o do Docto"
   #ENDIF
#ENDIF