#IFDEF SPANISH
         #define STR0001  "Niveles de Responsabilidades"
         #define STR0002  "Tipeo"
         #define STR0003  "Elaboraci¢n"
         #define STR0004  "Revisi¢n"
         #define STR0005  "Aprobaci¢n"
         #define STR0006  "Homologaci¢n"
         #define STR0007  "Distribuci¢n"
         #define STR0008  "Entrenamiento"
         #define STR0009  "Elija Norma   "
         #define STR0010  "Aviso"
         #define STR0011  "No Existe el archivo"
         #define STR0012  "en el Directorio"
         #define STR0013  "Faltan Responsables. ¨Confirma Salida?"
         #define STR0014  "Responsables por el Documento"
         #define STR0015  "El n£mero m¡nimo de Elaboradores es"
         #define STR0016  "El n£mero m¡nimo de Revisores es"
         #define STR0017  "El n£mero m¡nimo de Aprobadores es"
         #define STR0018  "El n£mero m¡nimo de Homologadores es"
         #define STR0019  "Electr¢nicas"
         #define STR0020  "Papel"
         #define STR0021  "Ambos"
         #define STR0022  "No Recibe "
         #define STR0023  "Documento ya Distribuido. ¨Genera Nueva Revisi¢n?"
         #define STR0024  "Usuario no Autorizado a Generar REVISION"
         #define STR0025  "Situaci¢n del Documento"
         #define STR0026  "Todos"
         #define STR0027  "Tipeo    "
         #define STR0028  "Elaboraci¢n"
         #define STR0029  "Revisi¢n"
         #define STR0030  "Aprobaci¢n"
         #define STR0031  "Homologaci¢n"
         #define STR0032  "Distribuci¢n"
         #define STR0033  "Entrenamiento"
         #define STR0034  "Elija Norma   "
         #define STR0035  "ATENCION"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Niveis de Responsabilidades"
         #define STR0002  "Digita‡„o"
         #define STR0003  "Elabora‡„o"
         #define STR0004  "Revis„o"
         #define STR0005  "Aprova‡„o"
         #define STR0006  "Homologa‡„o"
         #define STR0007  "Distribui‡„o"
         #define STR0008  "Treinamento"
         #define STR0009  "Escolha Padr„o"
         #define STR0010  "Aviso"
         #define STR0011  "Nao Existe o arquivo"
         #define STR0012  "no Diret¢rio"
         #define STR0013  "Faltam Respons veis. Confirma Sa¡da?"
         #define STR0014  "Respons veis pelo Documento"
         #define STR0015  "O numero minimo de Elaboradores ‚"
         #define STR0016  "O n£mero m¡nimo de Revisores ‚"
         #define STR0017  "O n£mero m¡nimo de Aprovadores ‚"
         #define STR0018  "O n£mero m¡nimo de Homologadores ‚"
         #define STR0019  "Eletr“nicas"
         #define STR0020  "Papel"
         #define STR0021  "Ambos"
         #define STR0022  "N„o Recebe"
         #define STR0023  "Documento j  Distribuido. Gera Nova Revis„o?"
         #define STR0024  "Usu rio n„o Autorizado a Gerar REVISŽO"
         #define STR0025  "Situa‡„o do Documento"
         #define STR0026  "Todos"
         #define STR0027  "Digita‡„o"
         #define STR0028  "Elabora‡„o"
         #define STR0029  "Revis„o"
         #define STR0030  "Aprova‡„o"
         #define STR0031  "Homologa‡„o"
         #define STR0032  "Distribui‡„o"
         #define STR0033  "Treinamento"
         #define STR0034  "Escolha Padr„o"
         #define STR0035  "ATEN€ŽO"
   #ELSE
         #define STR0001  "Niveis de Responsabilidades"
         #define STR0002  "Digita‡„o"
         #define STR0003  "Elabora‡„o"
         #define STR0004  "Revis„o"
         #define STR0005  "Aprova‡„o"
         #define STR0006  "Homologa‡„o"
         #define STR0007  "Distribui‡„o"
         #define STR0008  "Treinamento"
         #define STR0009  "Escolha Padr„o"
         #define STR0010  "Aviso"
         #define STR0011  "Nao Existe o arquivo"
         #define STR0012  "no Diret¢rio"
         #define STR0013  "Faltam Respons veis. Confirma Sa¡da?"
         #define STR0014  "Respons veis pelo Documento"
         #define STR0015  "O numero minimo de Elaboradores ‚"
         #define STR0016  "O n£mero m¡nimo de Revisores ‚"
         #define STR0017  "O n£mero m¡nimo de Aprovadores ‚"
         #define STR0018  "O n£mero m¡nimo de Homologadores ‚"
         #define STR0019  "Eletr“nicas"
         #define STR0020  "Papel"
         #define STR0021  "Ambos"
         #define STR0022  "N„o Recebe"
         #define STR0023  "Documento j  Distribuido. Gera Nova Revis„o?"
         #define STR0024  "Usu rio n„o Autorizado a Gerar REVISŽO"
         #define STR0025  "Situa‡„o do Documento"
         #define STR0026  "Todos"
         #define STR0027  "Digita‡„o"
         #define STR0028  "Elabora‡„o"
         #define STR0029  "Revis„o"
         #define STR0030  "Aprova‡„o"
         #define STR0031  "Homologa‡„o"
         #define STR0032  "Distribui‡„o"
         #define STR0033  "Treinamento"
         #define STR0034  "Escolha Padr„o"
         #define STR0035  "ATEN€ŽO"
   #ENDIF
#ENDIF