#IFDEF SPANISH
         #define STR0001  "Confirma"
         #define STR0002  "Retipea "
         #define STR0003  "Salir   "
         #define STR0004  "Busca"
         #define STR0005  "Visual."
         #define STR0006  "Incl."
         #define STR0007  "Mod."
         #define STR0008  "Borra"
         #define STR0009  "Texto"
         #define STR0010  "eSpec."
         #define STR0011  "Txt./Espec."
         #define STR0012  "Espec. Productos"
         #define STR0013  "¨Cu nto al Borrar?"
         #define STR0014  "Ser n borradas las entregas registradas para el Producto/Revisi¢n."
         #define STR0015  "Hay entregas registradas para el Producto/Revisi¢n, que ser n mantenidas para hist¢rico."
         #define STR0016  "Ser n borradas las mediciones registradas para el Producto/Revisi¢n"
         #define STR0017  "Deben ser asociados ensayos con sus respectivas especificaciones "
         #define STR0018  "Producto"
         #define STR0019  "Texto del Producto"
         #define STR0020  "Indexando Archivo..."
         #define STR0021  "Ensayo"
         #define STR0022  "No se har n borrados por que hay mediciones registradas    "
         #define STR0023  "Especificaciones de los Productos"
         #define STR0024  "Producto tiene mediciones registradas"
         #define STR0025  "d¡as"
         #define STR0026  "Elija una Opci¢n "
         #define STR0027  "Especificaciones"
         #define STR0028  "Texto"
         #define STR0029  "Hay entregas registradas."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Pesq."
         #define STR0005  "Visual."
         #define STR0006  "Incl."
         #define STR0007  "Alt."
         #define STR0008  "Excl."
         #define STR0009  "Texto"
         #define STR0010  "eSpec."
         #define STR0011  "Txt./Espec."
         #define STR0012  "Espec. Produtos"
         #define STR0013  "Quanto … exclus„o?"
         #define STR0014  "Ser„o exclu¡das as entregas cadastradas para o Produto/Revis„o."
         #define STR0015  "Existem entregas cadastradas para o Produto/Revis„o, as quais serao mantidas para hist¢rico."
         #define STR0016  "Ser„o exclu¡das as medi‡”es cadastradas para o Produto/Revis„o"
         #define STR0017  "Devem ser associados ensaios com suas respectivas especifica‡”es"
         #define STR0018  "Produto"
         #define STR0019  "Texto do Produto"
         #define STR0020  "Indexando Arquivo..."
         #define STR0021  "Ensaio"
         #define STR0022  "Exclu‡”es n„o ser„o efetuadas por haver medi‡”es cadastradas"
         #define STR0023  "Especifica‡”es dos Produtos"
         #define STR0024  "Produto tem medi‡”es cadastradas"
         #define STR0025  "dias"
         #define STR0026  "Escolha uma Op‡„o"
         #define STR0027  "Especifica‡”es"
         #define STR0028  "Texto"
         #define STR0029  "Existem entregas cadastradas."
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Pesq."
         #define STR0005  "Visual."
         #define STR0006  "Incl."
         #define STR0007  "Alt."
         #define STR0008  "Excl."
         #define STR0009  "Texto"
         #define STR0010  "eSpec."
         #define STR0011  "Txt./Espec."
         #define STR0012  "Espec. Produtos"
         #define STR0013  "Quanto … exclus„o?"
         #define STR0014  "Ser„o exclu¡das as entregas cadastradas para o Produto/Revis„o."
         #define STR0015  "Existem entregas cadastradas para o Produto/Revis„o, as quais serao mantidas para hist¢rico."
         #define STR0016  "Ser„o exclu¡das as medi‡”es cadastradas para o Produto/Revis„o"
         #define STR0017  "Devem ser associados ensaios com suas respectivas especifica‡”es"
         #define STR0018  "Produto"
         #define STR0019  "Texto do Produto"
         #define STR0020  "Indexando Arquivo..."
         #define STR0021  "Ensaio"
         #define STR0022  "Exclu‡”es n„o ser„o efetuadas por haver medi‡”es cadastradas"
         #define STR0023  "Especifica‡”es dos Produtos"
         #define STR0024  "Produto tem medi‡”es cadastradas"
         #define STR0025  "dias"
         #define STR0026  "Escolha uma Op‡„o"
         #define STR0027  "Especifica‡”es"
         #define STR0028  "Texto"
         #define STR0029  "Existem entregas cadastradas."
   #ENDIF
#ENDIF