#IFDEF SPANISH
			#define STR0001  "Confirma"
			#define STR0002  "Retipea "
			#define STR0003  "Salir   "
			#define STR0004  "B&usca  "
			#define STR0005  "Visualiza"
			#define STR0006  "Inclui"
			#define STR0007  "Modifica"
			#define STR0008  "Borra "
			#define STR0009  "Öndice de Calidad  "
			#define STR0010  "Generaci¢n del Öndice Calidad"
			#define STR0011  "Dia Encerramiento"
			#define STR0012  "¨Cu nto a la Inclusi¢n?"
			#define STR0013  "¨Cu nto a la Modificaci¢n?"
			#define STR0014  "Generando Öndice de Calidad"
			#define STR0015  "Deber  ser generado nuevamente el Öndice Calidad del mes/a¤o "
			#define STR0016  "Atenci¢n"
			#define STR0017  "¨Borrado del Historial"
			#define STR0018  "Podr  ser borrados los Öndices de Calidad de "
			#define STR0019  "¨Cu nto al Borrar?"
			#define STR0020  "Ya fueron generados Öndices de Calidad. Si cambia el d¡a de encerramiento, los ¡ndices ser n cancelados."
#ELSE
	#IFDEF ENGLISH
			#define STR0001  "Confirma"
			#define STR0002  "Redigita"
			#define STR0003  "Abandona"
			#define STR0004  "Pesquisa"
			#define STR0005  "Visualiza"
			#define STR0006  "Inclui"
			#define STR0007  "Altera"
			#define STR0008  "Exclui"
			#define STR0009  "Indice de Qualidade"
			#define STR0010  "Gera‡„o do Indice Qualidade"
			#define STR0011  "Dia Fechamento"
			#define STR0012  "Quanto … inclus„o ?"
			#define STR0013  "Quanto … altera‡„o ?"
			#define STR0014  "Gerando Indice de Qualidade"
			#define STR0015  "Dever  ser gerado novamente o Indice Qualidade do mˆs/ano "
			#define STR0016  "Aten‡„o"
			#define STR0017  "Exclus„o do Hist¢rico"
			#define STR0018  "Poder„o ser exclu¡dos os Indices Qualidade de "
			#define STR0019  "Quanto … exclus„o ?"
			#define STR0020  "J  foram gerados Indices de Qualidade. Se o dia de fechamento do mˆs for alterado, os ¡ndices ser„o cancelados."
	#ELSE
			#define STR0001  "Confirma"
			#define STR0002  "Redigita"
			#define STR0003  "Abandona"
			#define STR0004  "Pesquisa"
			#define STR0005  "Visualiza"
			#define STR0006  "Inclui"
			#define STR0007  "Altera"
			#define STR0008  "Exclui"
			#define STR0009  "Indice de Qualidade"
			#define STR0010  "Gera‡„o do Indice Qualidade"
			#define STR0011  "Dia Fechamento"
			#define STR0012  "Quanto … inclus„o ?"
			#define STR0013  "Quanto … altera‡„o ?"
			#define STR0014  "Gerando Indice de Qualidade"
			#define STR0015  "Dever  ser gerado novamente o Indice Qualidade do mˆs/ano "
			#define STR0016  "Aten‡„o"
			#define STR0017  "Exclus„o do Hist¢rico"
			#define STR0018  "Poder„o ser exclu¡dos os Indices Qualidade de "
			#define STR0019  "Quanto … exclus„o ?"
			#define STR0020  "J  foram gerados Indices de Qualidade. Se o dia de fechamento do mˆs for alterado, os ¡ndices ser„o cancelados."
	#ENDIF
#ENDIF
