#IFDEF SPANISH
         #define STR0001  "Confirma"
         #define STR0002  "Retipea "
         #define STR0003  "Salir   "
         #define STR0004  "B&usca  "
         #define STR0005  "Visualiza"
         #define STR0006  "Inclui"
         #define STR0007  "Modifica"
         #define STR0008  "Borra "
         #define STR0009  "Texto"
         #define STR0010  "Entregas"
         #define STR0011  "¨Cu nto al Borrar?"
         #define STR0012  "Identificador Entrega"
         #define STR0014  "Inspeccionar"
         #define STR0015  "Certificar"
         #define STR0016  "Aprobar Urgente"
         #define STR0018  "Laudo en regimen de skip-lote autom tico"
         #define STR0019  "Certificado de Calidad"
         #define STR0020  "Entrega"
         #define STR0021  "Observaciones de la Entrega"
         #define STR0022  "Inspecciona"
         #define STR0023  "Certifica"
         #define STR0024  "éltimas Entregas"
         #define STR0025  "N§ Lote Secuencial"
         #define STR0026  "No hay historial de 5 entregas consecutivas"
         #define STR0027  "con Plan Atenuado, para aplicaci¢n Skip-Lote."
         #define STR0028  "La entrega deber  ser inspeccionada."
         #define STR0029  "No hay el n£mero de entregas iniciales"
         #define STR0030  "necesario para la aplicaci¢n Skip-Lote."
         #define STR0031  "Tipo de Inspecci¢n"
         #define STR0032  "Muestreo  "
         #define STR0033  "Plan Muestreo   "
         #define STR0034  "Nivel"
         #define STR0035  "NCA"
         #define STR0036  "Muestra"
         #define STR0037  "Acepte"
         #define STR0038  "Rechaze"
         #define STR0039  "Primera entrega del Proveedor/Producto."
         #define STR0040  "Tiempo L¡mite sin Entregas Expirado."
         #define STR0041  "Primera Entrega despu‚s de Modificaci¢n de Especificaci¢n"
         #define STR0042  "Hay Laudo Reprobado o con Aceptaci¢n "
         #define STR0043  "Condicional en las £ltimas entregas. "
         #define STR0044  "La Entrega deber  ser inspeccionada, por la evaluaci¢n del Skip-Lote."
         #define STR0045  "La Entrega podr  ser aprobada"
         #define STR0046  "en regimen de Skip-Lote Autom tico."
         #define STR0047  "Aprobada Urgente"
         #define STR0048  "Justificaci¢n Plan Muestreo a"
         #define STR0049  "Justificaci¢n Plan Muestreo b"
         #define STR0050  "éltimas Entregas"
         #define STR0051  "Entrega ser  inspeccionada por tener ensayo a inspeccionar (skip-teste)."
         #define STR0052  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Pesquisa"
         #define STR0005  "Visualiza"
         #define STR0006  "Inclui"
         #define STR0007  "Altera"
         #define STR0008  "Exclui"
         #define STR0009  "Texto"
         #define STR0010  "Entregas"
         #define STR0011  "Quanto … exclus„o?"
         #define STR0012  "Identificador Entrega"
         #define STR0014  "Inspecionar"
         #define STR0015  "Certificar"
         #define STR0016  "Liberar Urgente"
         #define STR0018  "Laudo em regime de skip-lote automatico"
         #define STR0019  "Certificado de Qualidade"
         #define STR0020  "Entrega"
         #define STR0021  "Observacoes da Entrega"
         #define STR0022  "Inspeciona"
         #define STR0023  "Certifica"
         #define STR0024  "Ultimas Entregas"
         #define STR0025  "No. Lote Sequencial"
         #define STR0026  "N„o h  hist¢rico de 5 entregas consecutivas"
         #define STR0027  "com Plano Atenuado, para aplica‡„o Skip-Lote."
         #define STR0028  "A Entrega dever  ser inspecionada."
         #define STR0029  "N„o h  o n£mero de entregas iniciais "
         #define STR0030  "necess rio para a aplica‡„o Skip-Lote."
         #define STR0031  "Tipo de Inspe‡„o"
         #define STR0032  "Amostragem"
         #define STR0033  "Plano Amostragem"
         #define STR0034  "N¡vel"
         #define STR0035  "NQA"
         #define STR0036  "Amostra"
         #define STR0037  "Aceite"
         #define STR0038  "Rejeite"
         #define STR0039  "Primeira entrega do Fornecedor/Produto."
         #define STR0040  "Tempo Limite sem Entregas expirado."
         #define STR0041  "Primeira entrega ap¢s altera‡„o Especifica‡„o"
         #define STR0042  "Existe Laudo Reprovado ou com Aceita‡„o "
         #define STR0043  "Condicional nas £ltimas entregas."
         #define STR0044  "Entrega dever  ser inspecionada, pela avalia‡„o do Skip-Lote."
         #define STR0045  "Entrega poder  ser aprovada"
         #define STR0046  "em regime de Skip-Lote Autom tico."
         #define STR0047  "Libera Urgente"
         #define STR0048  "Justificativa Plano Amostragem a"
         #define STR0049  "Justificativa Plano Amostragem b"
         #define STR0050  "Ultimas Entregas"
         #define STR0051  "Entrega ser  inspecionada por ter ensaio a inspecionar (skip-teste)."
         #define STR0052  "Aten‡„o"
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Pesquisa"
         #define STR0005  "Visualiza"
         #define STR0006  "Inclui"
         #define STR0007  "Altera"
         #define STR0008  "Exclui"
         #define STR0009  "Texto"
         #define STR0010  "Entregas"
         #define STR0011  "Quanto … exclus„o?"
         #define STR0012  "Identificador Entrega"
         #define STR0014  "Inspecionar"
         #define STR0015  "Certificar"
         #define STR0016  "Liberar Urgente"
         #define STR0018  "Laudo em regime de skip-lote automatico"
         #define STR0019  "Certificado de Qualidade"
         #define STR0020  "Entrega"
         #define STR0021  "Observacoes da Entrega"
         #define STR0022  "Inspeciona"
         #define STR0023  "Certifica"
         #define STR0024  "Ultimas Entregas"
         #define STR0025  "No. Lote Sequencial"
         #define STR0026  "N„o h  hist¢rico de 5 entregas consecutivas"
         #define STR0027  "com Plano Atenuado, para aplica‡„o Skip-Lote."
         #define STR0028  "A Entrega dever  ser inspecionada."
         #define STR0029  "N„o h  o n£mero de entregas iniciais "
         #define STR0030  "necess rio para a aplica‡„o Skip-Lote."
         #define STR0031  "Tipo de Inspe‡„o"
         #define STR0032  "Amostragem"
         #define STR0033  "Plano Amostragem"
         #define STR0034  "N¡vel"
         #define STR0035  "NQA"
         #define STR0036  "Amostra"
         #define STR0037  "Aceite"
         #define STR0038  "Rejeite"
         #define STR0039  "Primeira entrega do Fornecedor/Produto."
         #define STR0040  "Tempo Limite sem Entregas expirado."
         #define STR0041  "Primeira entrega ap¢s altera‡„o Especifica‡„o"
         #define STR0042  "Existe Laudo Reprovado ou com Aceita‡„o "
         #define STR0043  "Condicional nas £ltimas entregas."
         #define STR0044  "Entrega dever  ser inspecionada, pela avalia‡„o do Skip-Lote."
         #define STR0045  "Entrega poder  ser aprovada"
         #define STR0046  "em regime de Skip-Lote Autom tico."
         #define STR0047  "Libera Urgente"
         #define STR0048  "Justificativa Plano Amostragem a"
         #define STR0049  "Justificativa Plano Amostragem b"
         #define STR0050  "Ultimas Entregas"
         #define STR0051  "Entrega ser  inspecionada por ter ensaio a inspecionar (skip-teste)."
         #define STR0052  "Aten‡„o"
   #ENDIF
#ENDIF