#IFDEF SPANISH
         #define STR0001  "Diagrama de Pareto"
         #define STR0002  "Confirma"
         #define STR0003  "Salir   "
         #define STR0004  "Indexando Archivo..."
         #define STR0005  "¨Confirma Selecci¢n?"
         #define STR0006  "Atenci¢n"
         #define STR0007  "En este informe ser n relacionadas las No Conformidades"
         #define STR0008  "relacionadas a (los) Produto(s) en el per¡odo informado."
         #define STR0009  "  "
         #define STR0010  "Administraci¢n"
         #define STR0011  "Seleccionando Registros..."
         #define STR0012  "CANCELADO POR EL OPERADOR"
         #define STR0013  "Otras"
         #define STR0014  "Otros"
         #define STR0015  "Per¡odo: "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Diagrama de Pareto"
         #define STR0002  "Confirma"
         #define STR0003  "Abandona"
         #define STR0004  "Indexando Arquivo..."
         #define STR0005  "Confirma Sele‡„o?"
         #define STR0006  "Aten‡„o"
         #define STR0007  "Neste relat¢rio ser„o relacionadas as N„o Conformidades"
         #define STR0008  "relacionadas ao(s) Produto(s) no per¡odo informado."
         #define STR0009  "Zebrado"
         #define STR0010  "Administracao"
         #define STR0011  "Selecionando Registros..."
         #define STR0012  "CANCELADO PELO OPERADOR"
         #define STR0013  "Outras"
         #define STR0014  "Outros"
         #define STR0015  "Periodo: "
   #ELSE
         #define STR0001  "Diagrama de Pareto"
         #define STR0002  "Confirma"
         #define STR0003  "Abandona"
         #define STR0004  "Indexando Arquivo..."
         #define STR0005  "Confirma Sele‡„o?"
         #define STR0006  "Aten‡„o"
         #define STR0007  "Neste relat¢rio ser„o relacionadas as N„o Conformidades"
         #define STR0008  "relacionadas ao(s) Produto(s) no per¡odo informado."
         #define STR0009  "Zebrado"
         #define STR0010  "Administracao"
         #define STR0011  "Selecionando Registros..."
         #define STR0012  "CANCELADO PELO OPERADOR"
         #define STR0013  "Outras"
         #define STR0014  "Outros"
         #define STR0015  "Periodo: "
   #ENDIF
#ENDIF