#IFDEF SPANISH
         #define STR0001  "Confirma"
         #define STR0002  "Retipea "
         #define STR0003  "Salir   "
         #define STR0004  "Cartas de Control"
         #define STR0005  "Indexando Archivo..."
         #define STR0006  "¨Confirma Selecci¢n?"
         #define STR0007  "Atenci¢n"
         #define STR0008  "Producto-Revisi¢n"
         #define STR0009  "Descripci¢n"
         #define STR0010  "Ensayo"
         #define STR0011  "De Fecha Entrega"
         #define STR0012  "A  Fecha Entrega"
         #define STR0013  "Archivos generados"
         #define STR0014  "Archivo"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Cartas de Controle"
         #define STR0005  "Indexando Arquivo..."
         #define STR0006  "Confirma Sele‡„o?"
         #define STR0007  "Aten‡„o"
         #define STR0008  "Produto-Revis„o"
         #define STR0009  "Descri‡„o"
         #define STR0010  "Ensaio"
         #define STR0011  "Data Entrega  de"
         #define STR0012  "Data Entrega  ate"
         #define STR0013  "Arquivos gerados"
         #define STR0014  "Arquivo"
   #ELSE
         #define STR0001  "Confirma"
         #define STR0002  "Redigita"
         #define STR0003  "Abandona"
         #define STR0004  "Cartas de Controle"
         #define STR0005  "Indexando Arquivo..."
         #define STR0006  "Confirma Sele‡„o?"
         #define STR0007  "Aten‡„o"
         #define STR0008  "Produto-Revis„o"
         #define STR0009  "Descri‡„o"
         #define STR0010  "Ensaio"
         #define STR0011  "Data Entrega  de"
         #define STR0012  "Data Entrega  ate"
         #define STR0013  "Arquivos gerados"
         #define STR0014  "Arquivo"
   #ENDIF
#ENDIF