#IFDEF SPANISH
         #define STR0001  "Conversor del GQREC para SIGAQIE"
         #define STR0002  "Ser  hecha la conversi¢n de los archivos del GQREC para el SIGAQIE."
         #define STR0003  "Los archivos del GQREC deber n estar en el directorio "
         #define STR0004  "Escritorios: "
         #define STR0005  "Funciones:"
         #define STR0006  "Responsables: "
         #define STR0007  "Proveedor:  "
         #define STR0008  "Skip-Lote: "
         #define STR0009  "C¢digos Muestras: "
         #define STR0010  "Tama¤os Muestras: "
         #define STR0011  "Evaluaci¢n Proveedores: "
         #define STR0012  "No Conformidad: "
         #define STR0013  "Unidad de Medida: "
         #define STR0014  "Ensayos: "
         #define STR0015  "NCs de Ensayos: "
         #define STR0016  "Grupos Productos: "
         #define STR0017  "Respons. por Equipo: "
         #define STR0018  "Producto:"
         #define STR0019  "V¡ncu. Grupo X Producto:"
         #define STR0020  "Informativos: "
         #define STR0021  "T¢picos Informativos: "
         #define STR0022  "Factores ICP: "
         #define STR0023  "Clases Situaci¢n:"
         #define STR0024  "Skip-Teste Individual: "
         #define STR0025  "Skip-Teste Grupo: "
         #define STR0026  "Entregas: "
         #define STR0027  "Importaci¢n Entregas: "
         #define STR0028  "Resultados: "
         #define STR0029  "Informe Öndice Calidad:"
         #define STR0030  "Hist. Sk.Teste Indiv.: "
         #define STR0031  "Hist. Sk.Teste Grupo: "
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Conversor do GQREC para SIGAQIE"
         #define STR0002  "Ser  efetuada a convers„o dos arquivos do GQREC para o SIGAQIE."
         #define STR0003  "Os arquivos do GQREC dever„o estar no diret¢rio "
         #define STR0004  "Departamentos: "
         #define STR0005  "Fun‡”es: "
         #define STR0006  "Respons veis: "
         #define STR0007  "Fornecedor: "
         #define STR0008  "Skip-Lote: "
         #define STR0009  "C¢digos Amostras: "
         #define STR0010  "Tamanhos Amostras: "
         #define STR0011  "Avalia‡”es Fornecedores: "
         #define STR0012  "N„o Conformidade: "
         #define STR0013  "Unidade de Medida: "
         #define STR0014  "Ensaios: "
         #define STR0015  "NCs dos Ensaios: "
         #define STR0016  "Grupos Produtos: "
         #define STR0017  "Respons. por Equipe: "
         #define STR0018  "Produto: "
         #define STR0019  "Amarr. Grupo X Produto: "
         #define STR0020  "Informativos: "
         #define STR0021  "T¢picos Informativos: "
         #define STR0022  "Fatores IQP: "
         #define STR0023  "Classes Situa‡„o: "
         #define STR0024  "Skip-Teste Individual: "
         #define STR0025  "Skip-Teste Grupo: "
         #define STR0026  "Entregas : "
         #define STR0027  "Importa‡„o Entregas: "
         #define STR0028  "Resultados: "
         #define STR0029  "Relat. Indice Qualidade: "
         #define STR0030  "Hist. Sk.Teste Indiv.: "
         #define STR0031  "Hist. Sk.Teste Grupo: "
   #ELSE
         #define STR0001  "Conversor do GQREC para SIGAQIE"
         #define STR0002  "Ser  efetuada a convers„o dos arquivos do GQREC para o SIGAQIE."
         #define STR0003  "Os arquivos do GQREC dever„o estar no diret¢rio "
         #define STR0004  "Departamentos: "
         #define STR0005  "Fun‡”es: "
         #define STR0006  "Respons veis: "
         #define STR0007  "Fornecedor: "
         #define STR0008  "Skip-Lote: "
         #define STR0009  "C¢digos Amostras: "
         #define STR0010  "Tamanhos Amostras: "
         #define STR0011  "Avalia‡”es Fornecedores: "
         #define STR0012  "N„o Conformidade: "
         #define STR0013  "Unidade de Medida: "
         #define STR0014  "Ensaios: "
         #define STR0015  "NCs dos Ensaios: "
         #define STR0016  "Grupos Produtos: "
         #define STR0017  "Respons. por Equipe: "
         #define STR0018  "Produto: "
         #define STR0019  "Amarr. Grupo X Produto: "
         #define STR0020  "Informativos: "
         #define STR0021  "T¢picos Informativos: "
         #define STR0022  "Fatores IQP: "
         #define STR0023  "Classes Situa‡„o: "
         #define STR0024  "Skip-Teste Individual: "
         #define STR0025  "Skip-Teste Grupo: "
         #define STR0026  "Entregas : "
         #define STR0027  "Importa‡„o Entregas: "
         #define STR0028  "Resultados: "
         #define STR0029  "Relat. Indice Qualidade: "
         #define STR0030  "Hist. Sk.Teste Indiv.: "
         #define STR0031  "Hist. Sk.Teste Grupo: "
   #ENDIF
#ENDIF