#IFDEF SPANISH
         #define STR0001  "Referencia Cruzada: NC x Entrega"
         #define STR0002  "Indexando Archivo..."
         #define STR0003  "Ok"
         #define STR0004  "Factor"
         #define STR0005  "Descripci¢n"
         #define STR0006  "Clase NC"
         #define STR0007  "¨Confirma Selecci¢n?"
         #define STR0008  "Atenci¢n"
         #define STR0009  "Ser n relacionadas las No Conformidades encontradas en cada entrega."
         #define STR0010  "Referencia Cruzada: NC x Entrega"
         #define STR0011  " "
         #define STR0012  "Administraci¢n"
         #define STR0013  "Per¡odo de Entrega: "
         #define STR0014  " a "
         #define STR0015  "Seleccionando Registros..."
         #define STR0016  "CANCELADO POR EL OPERADOR"
         #define STR0017  "S¡"
         #define STR0018  "No"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Referencia Cruzada : NC x Entrega"
         #define STR0002  "Indexando Arquivo..."
         #define STR0003  "Ok"
         #define STR0004  "Fator"
         #define STR0005  "Descricao"
         #define STR0006  "Classe NC"
         #define STR0007  "Confirma Sele‡„o?"
         #define STR0008  "Aten‡„o"
         #define STR0009  "Ser„o relacionadas as Nao Conformidades encontradas em cada entrega."
         #define STR0010  "Referencia Cruzada : NC x Entrega"
         #define STR0011  "Zebrado"
         #define STR0012  "Administracao"
         #define STR0013  "Periodo de Entrega : "
         #define STR0014  " a "
         #define STR0015  "Selecionando Registros..."
         #define STR0016  "CANCELADO PELO OPERADOR"
         #define STR0017  "Sim"
         #define STR0018  "Nao"
   #ELSE
         #define STR0001  "Referencia Cruzada : NC x Entrega"
         #define STR0002  "Indexando Arquivo..."
         #define STR0003  "Ok"
         #define STR0004  "Fator"
         #define STR0005  "Descricao"
         #define STR0006  "Classe NC"
         #define STR0007  "Confirma Sele‡„o?"
         #define STR0008  "Aten‡„o"
         #define STR0009  "Ser„o relacionadas as Nao Conformidades encontradas em cada entrega."
         #define STR0010  "Referencia Cruzada : NC x Entrega"
         #define STR0011  "Zebrado"
         #define STR0012  "Administracao"
         #define STR0013  "Periodo de Entrega : "
         #define STR0014  " a "
         #define STR0015  "Selecionando Registros..."
         #define STR0016  "CANCELADO PELO OPERADOR"
         #define STR0017  "Sim"
         #define STR0018  "Nao"
   #ENDIF
#ENDIF