   #define STR0001  "Campo não pode ser alterado. Caso desejar apagar o instrumento pressione a tecla DEL para deixar a linha em branco."
   #define STR0002  "O Padrão Secundário não pode ser o mesmo que o instrumento que esta sofrendo a medição. Escolha outro."
   #define STR0003  "O Padrão Secundário informado não se encontra no banco de dados. Informe um Instrumento válido."
   #define STR0004  "Padrão Secundário já relacionado a esta medição. Informe outro."
   #define STR0005  "Padrão Secundário com validade expirada ou reporvado. Informe um Padrão válido."
   #define STR0006  "Instrumento n„o pertence ao grupo de Padrões Secundarios"
   #define STR0007  "O Instrumento informado ainda não sobreu medição, sendo assim não poderá ser utilizado nesta opção. Inclua medições para o mesmo primeiro."
   #define STR0009  "Escalas"
   #define STR0010  "Duplo click confirmar a escolha"
   #define STR0011  "Escala"
   #define STR0012  "Incerteza"
   #define STR0013  "Campo não pode ser alterado. Caso desejar apagar o instrumento pressione a tecla DEL para deixar a linha em branco."
   #define STR0014  "Instrumento Utilizado não pode ser o mesmo instrumento que esta sofrendo a medição. Escolha outro."
   #define STR0015  "O Instrumento informado não se encontra no banco de dados. Informe um Instrumento válido."
   #define STR0016  "Instrumento Utilizado já relacionado a esta medição. Informe outro."
   #define STR0017  "Instrumento com validade expirada ou reporvado. Informe um Instrumento válido."
   #define STR0023  "Incerteza"
