   #define STR0001  "Medições"
   #define STR0002  "Pesquisar"
   #define STR0003  "Visualizar"
   #define STR0004  "Incluir"
   #define STR0005  "Alterar"
   #define STR0006  "Excluir"
   #define STR0007  "Hist¢rico"
   #define STR0008  "Instrumento"
   #define STR0009  "Responsável"
   #define STR0010  "Data"
   #define STR0011  "Total Horas"
   #define STR0012  "Revisão"
   #define STR0013  "Repe/Repro"
   #define STR0014  "A frequencia nao podera ser inferior ao menor numero de dias especificado na tabela de Schumacher"
   #define STR0015  "A frequencia nao podera ser superior ao maior numero de dias especificado na tabela de Schumacher"
   #define STR0016  "Extender a freq.afer. de"
   #define STR0017  "para"
   #define STR0018  "dias"
   #define STR0019  "Diminuir a freq.afer. de"
   #define STR0020  "para"
   #define STR0021  "dias"
   #define STR0022  "Frequência: "
   #define STR0023  " dias Val.Calibraçäo: "
   #define STR0024  "Frequência: "
   #define STR0025  " dias Val.Calibraçäo: "
   #define STR0026  "Data inválida, informe um data menor que a data base do Sistema."
   #define STR0027  "Já existem medições cadastradas para este instrumento nesta data. Informe outros dados"
   #define STR0028  "Data Inválida. Existem calibrações cadastradas com datas superiores"
   #define STR0029  "Medicao fora do Especificado"
   #define STR0030  "Campo não pode ser alterado. Caso desejar apagar o instrumento pressione a tecla DEL para deixar a linha em branco."
   #define STR0031  "A Não Conformidade informada não se encontra no banco de dados. Informe uma Não Conformidade válida."
   #define STR0032  "Não Conformidade já relacionado a esta medição. Informe outra."
   #define STR0033  "Instrumento não cadastrado"
   #define STR0034  "Não existem Escalas relacionadas com este instrumento, favor verificar para que possam ser digitados os resultados."
   #define STR0035  "Problemas na tabela de Schumacher (QMF). Provavelmente a tabela foi perdida. Consulte Suporte Microsiga informando esta mensagem. As medições não poderão ser gravadas."
   #define STR0036  "Este instrumento tem medições externas mas o usuário não digitou informações sobre Laboratório e Número de certificado. Estes dados são obrigatórios. Por Favor verifique na pasta de medições Externas quando a existência de falta de dados."
