#IFDEF SPANISH
			#define STR0001  "En este informe ser n mostradas las No Conformidades"
			#define STR0002  "relacionadas con las mediciones de instrumento en el per¡odo informado."
			#define STR0003  "Informe de No Conformidades"
			#define STR0004  " "
			#define STR0005  "Administraci¢n"
			#define STR0006  "¨Confirma Seleci¢n?"
			#define STR0007  "Atenci¢n"
			#define STR0008  "  C¢digo       Descripci¢n                                  Cantidad  "
			#define STR0009  "Confirma"
			#define STR0010  "Salir   "
			#define STR0011  "Indexando Archivo..."
#ELSE
	#IFDEF ENGLISH
                        #define STR0001  "In this report will be listed the Non Conformances     "
                        #define STR0002  "related to measurement of an Instrument, in a informed period."
                        #define STR0003  "Non Conformances Report       "
                        #define STR0004  "Z.Form "
                        #define STR0005  "Management   "
                        #define STR0006  "Confirm Selection?"
                        #define STR0007  "Attention"
                        #define STR0008  "  Code         Descript.                                    Quantity  "
                        #define STR0009  "OK      "
                        #define STR0010  "Quit    "
                        #define STR0011  "Indexing File  ....."
	#ELSE
			#define STR0001  "Neste relatorio serao relacionadas as Nao Conformidades"
			#define STR0002  "relacionadas as medicoes de instrumento no periodo informado."
			#define STR0003  "Relatorio de Nao Conformidades"
			#define STR0004  "Zebrado"
			#define STR0005  "Administra‡„o"
			#define STR0006  "Confirma Sele‡„o?"
			#define STR0007  "Aten‡„o"
			#define STR0008  "  Codigo       Descricao                                    Quantidade"
			#define STR0009  "Confirma"
			#define STR0010  "Abandona"
			#define STR0011  "Indexando Arquivo..."
	#ENDIF
#ENDIF
