#IFDEF SPANISH
			#define STR0001  "Confirma"
			#define STR0002  "Retipea "
			#define STR0003  "Salir   "
			#define STR0004  "Cartas Individuales"
			#define STR0005  "Indexando Archivo..."
			#define STR0006  "¨Confirma Selecci¢n?"
			#define STR0007  "Atenci¢n"
			#define STR0008  "Instrumento-Revisi¢n"
			#define STR0009  "Escala"
			#define STR0010  "Punto/Faja"
			#define STR0011  "Per¡odo de"
			#define STR0012  "Per¡odo hasta"
			#define STR0013  "Archivos generados"
			#define STR0014  "Archivo"
			#define STR0015  "Responsable"
#ELSE
	#IFDEF ENGLISH
                        #define STR0001  "OK      "
                        #define STR0002  "Retype  "
                        #define STR0003  "Quit    "
                        #define STR0004  "Individual Letters"
                        #define STR0005  "Indexing File ......"
                        #define STR0006  "Confirm Selection?"
                        #define STR0007  "Attention"
                        #define STR0008  "Revision-Instrument"
                        #define STR0009  "Scale "
                        #define STR0010  "Point/Range"
                        #define STR0011  "Period from"
                        #define STR0012  "Period to "
                        #define STR0013  "Files generated "
                        #define STR0014  "File   "
                        #define STR0015  "Responsible"
	#ELSE
			#define STR0001  "Confirma"
			#define STR0002  "Redigita"
			#define STR0003  "Abandona"
			#define STR0004  "Cartas Individuais"
			#define STR0005  "Indexando Arquivo..."
			#define STR0006  "Confirma Sele‡„o?"
			#define STR0007  "Aten‡„o"
			#define STR0008  "Instrumento-Revisao"
			#define STR0009  "Escala"
			#define STR0010  "Ponto/Faixa"
			#define STR0011  "Periodo de"
			#define STR0012  "Perido ate"
			#define STR0013  "Arquivos gerados"
			#define STR0014  "Arquivo"
			#define STR0015  "Responsavel"
	#ENDIF
#ENDIF
