#IFDEF SPANISH       
   #define STR0001  "Esta rutina permite la importaci¢n de los datos del GQCAL V.3.51 del Siga Quality Celerina compatibilizando todos los campos con la versi¢n Windows."
	#define STR0002  "Ser  hecha la conversi¢n de los archivos del GQCAL para el SIGAQMT."
	#define STR0003  "Los archivos del GQCAL deber n estar en la carpeta "
	#define STR0004  "Escritorios: "
	#define STR0005  "Funciones: "
	#define STR0006  "Responsables: "
	#define STR0007  "No Conformidades: "
	#define STR0008  "Unidad de Medida: "
	#define STR0009  "Padrones:"
	#define STR0010  "Instrumentos: "
	#define STR0011  "Familias / Escalas"
	#define STR0012  "Ensayos de Repe/Repro"
	#define STR0013  "Mediciones de Ensayos de Repe/Repro"
	#define STR0014  "Asociaci¢n de Padrones para Tipo Suma"
	#define STR0015  "Asociaci¢n de Padrones por Escala"
	#define STR0016  "Archivo de Reprogramaci¢n de Calibraci¢n"
	#define STR0017  "Manutenciones Hechas"
	#define STR0018  "Puntos de Calibraci¢n por Instr. Tipo Calibrador"
	#define STR0019  "Registro de Localizaci¢n de Instrumentos"
	#define STR0020  "Laboratorios Externos"
	#define STR0021  "Estatus de Instrumento"
	#define STR0022  "Encabezamiento de Calibraciones"
	#define STR0023  "Mediciones pa. Instrumentos Tipo Calibrador"
	#define STR0024  "Mediciones pa. Instrumentos Tipo Simple"   
	#define STR0025  "Mediciones pa. Instrumentos Tipo Completo"  
	#define STR0026  "Mediciones pa. Instrumentos Tipo Presi¢n"   
	#define STR0027  "Registros de No Conformidad por Medici¢n" 
	#define STR0028  "Calculando y grabando ensayos de R&R. Espere un momento..."
	#define STR0029  "Retornando n£mero del £ltimo certificado. Espere un momento..."
	#define STR0030  "N£mero de Registro:"
	#define STR0031  "&Adelante >>"
	#define STR0032  "&Cancelar"
	#define STR0033  "Directorio &Fuente >>"
	#define STR0034  "A  T  E  N  C  I  O  N"
	#define STR0035  "Para actualizar la  Base de Datos, el sistema no podr  "
	#define STR0036  "estar siendo usado por otras estaciones. Ahora se est  "
	#define STR0037  "esperando la liberaci¢n de los archivos. Pulse <Enter> "
	#define STR0038  "cuando todas las estaciones ya est n fuera del sistema "
	#define STR0039  "para continuar con la actualizaci¢n."
	#define STR0040  "*Procedimentos de calibracao e utilizacao"
	#define STR0041  "*Textos de procedimentos de calibracao e utilizacao" 
#ELSE
	#IFDEF ENGLISH
		#define STR0001  "Esta rotina permite a importação dos dados do GQCAL V.3.51 do Siga Quality Celerina compatibilizando todos os campos com a versão Windows."
		#define STR0002  "Ser  efetuada a convers„o dos arquivos do GQCAL para o SIGAQMT."
		#define STR0003  "Os arquivos do GQCAL dever„o estar no diret¢rio "
		#define STR0004  "Departamentos: "
		#define STR0005  "Fun‡”es: "
		#define STR0006  "Respons veis: "
		#define STR0007  "N„o Conformidade: "
		#define STR0008  "Unidade de Medida: "
		#define STR0009  "Padroes: "
		#define STR0010  "Instrumentos: "
		#define STR0011  "Fam¡lias / Escalas"
		#define STR0012  "Ensaios de Repe/Repro"
		#define STR0013  "Medicoes de Ensaios de Repe/Repro"
		#define STR0014  "Associa‡„o de Padr”es para Tipo Soma"
		#define STR0015  "Associa‡„o de Padr”es por Escala"
		#define STR0016  "Cadastro de Reprograma‡„o de Calibra‡„o"
		#define STR0017  "Manuten‡”es Realizadas"
		#define STR0018  "Pontos de Calibra‡„o por Instr.Tipo Calibrador"
		#define STR0019  "Registro de Localizacao de Instrumentos"
		#define STR0020  "Laborat¢rios Externos"
		#define STR0021  "Status de Instrumento"
		#define STR0022  "Cabe‡alho de Calibra‡”es"
		#define STR0023  "Medi‡”es p/ Instrumentos Tipo Calibrador"
		#define STR0024  "Medi‡”es p/ Instrumentos Tipo Simples"   
		#define STR0025  "Medi‡”es p/ Instrumentos Tipo Completo"  
		#define STR0026  "Medi‡”es p/ Instrumentos Tipo Press„o"   
		#define STR0027  "Registros de N„o Conformidade por Medi‡„o" 
		#define STR0028  "Calculando e gravando ensaios de R&R. Aguarde um momento..."
		#define STR0029  "Rertornando n£mero do £ltimo certificado. Aguarde um momento..."
		#define STR0030  "Número de Registro:"
		#define STR0031  "&Avançar >>"
		#define STR0032  "&Cancelar"
		#define STR0033  "Diretório &Fonte >>"
		#define STR0034 "A  T  E  N  C  A  O "
		#define STR0035 "Para Atualizar a  Base de Dados , o sistema n„o poder "
 		#define STR0036 "estar em uso por outras esta‡”es. Neste momento est "
		#define STR0037 "sendo aguardada a libera‡†o dos arquivos. Tecle <Enter>"
		#define STR0038 "quando todas as esta‡”es j  estiverem fora do sis-"
		#define STR0039 "tema para prosseguir com a atualiza‡†o."
		#define STR0040 "Procedimentos de calibracao e utilizacao"
		#define STR0041 "Textos de procedimentos de calibracao e utilizacao" 
	#ELSE
		#define STR0001  "Esta rotina permite a importação dos dados do GQCAL V.3.51 do Siga Quality Celerina compatibilizando todos os campos com a versão Windows."
		#define STR0002  "Será efetuada a conversão dos arquivos do GQCAL para o SIGAQMT."
		#define STR0003  "Os arquivos do GQCAL deverão estar no diretório "
		#define STR0004  "Departamentos: "
		#define STR0005  "Funções: "
		#define STR0006  "Responsáveis: "
		#define STR0007  "Não Conformidade: "
		#define STR0008  "Unidade de Medida: "
		#define STR0009  "Padrões: "
		#define STR0010  "Instrumentos: "
		#define STR0011  "Famílias / Escalas"
		#define STR0012  "Ensaios de Repe/Repro"
		#define STR0013  "Medições de Ensaios de Repe/Repro"
		#define STR0014  "Associação de Padrões para Tipo Soma"
		#define STR0015  "Associação de Padrões por Escala"
		#define STR0016  "Cadastro de Reprogramação de Calibração"
		#define STR0017  "Manutenções Realizadas"
		#define STR0018  "Pontos de Calibração por Instr.Tipo Calibrador"
		#define STR0019  "Registro de Localização de Instrumentos"
		#define STR0020  "Laboratórios Externos"
		#define STR0021  "Status de Instrumento"
		#define STR0022  "Cabeçalho de Calibrações"
		#define STR0023  "Medições p/ Instrumentos Tipo Calibrador"
		#define STR0024  "Medições p/ Instrumentos Tipo Simples"   
		#define STR0025  "Medições p/ Instrumentos Tipo Completo"  
		#define STR0026  "Medições p/ Instrumentos Tipo Pressão"   
		#define STR0027  "Registros de Não Conformidade por Medição" 
		#define STR0028  "Calculando e gravando ensaios de R&R. Aguarde um momento..."
		#define STR0029  "Retornando número do último certificado. Aguarde um momento..."
		#define STR0030  "Número de Registro:"
		#define STR0031  "&Avançar >>"
		#define STR0032  "&Cancelar"
		#define STR0033  "Diretório &Fonte >>"
		#define STR0034 "A  T  E  N  C  A  O "
		#define STR0035 "Para Atualizar a  Base de Dados , o sistema n„o poder "
 		#define STR0036 "estar em uso por outras esta‡”es. Neste momento est "
		#define STR0037 "sendo aguardada a libera‡†o dos arquivos. Tecle <Enter>"
		#define STR0038 "quando todas as esta‡”es j  estiverem fora do sis-"
		#define STR0039 "tema para prosseguir com a atualização."
		#define STR0040 "Procedimentos de calibração e utilização"
		#define STR0041 "Textos de procedimentos de calibração e utilização" 
	#ENDIF
#ENDIF
