#IFDEF SPANISH
   #define STR0001  "Abandona"
   #define STR0002  "Confirma"
   #define STR0003  "Redigita"
   #define STR0004  "Pesquisar"
   #define STR0005  "Visualizar"
   #define STR0006  "Incluir"
   #define STR0007  "Alterar"
   #define STR0008  "Excluir"
   #define STR0009  "Atualiza‡„o da Rela‡„o Reclama‡„o x Solu‡„o"
   #define STR0010  "Rela‡„o Reclama‡„o x Solu‡„o"
   #define STR0011  "Cadastro de Rela‡„o Reclama‡„o x Solu‡„o - Inclus„o"
   #define STR0012  "Relacionamento"
   #define STR0013  "Adiciona Reclama‡„o"
   #define STR0014  "Adiciona Solu‡„o"
   #define STR0015  "Remove item"
   #define STR0016  "Reclama‡„o"
   #define STR0017  "Informe a Reclama‡„o"
   #define STR0018  "C¢digo"
   #define STR0019  "Descri‡„o"
   #define STR0020  "Solu‡„o"
   #define STR0021  "Informe a Solu‡„o"
   #define STR0022  "Confirma a exclus„o de tudo ?"
   #define STR0023  "Confirma a exclus„o dessa solu‡„o ?"
   #define STR0024  "Cadastro de Rela‡„o Reclama‡„o x Solu‡„o - Altera‡„o"                
   #define STR0025  "Aguarde"
   #define STR0026  "Montando Estrutura do Relacionamento"
   #define STR0027  "Cadastro de Rela‡„o Reclama‡„o x Solu‡„o - Exclus„o"
   #define STR0028  "Confirma a exclus„o ?"
   #define STR0029  "Cadastro de Rela‡„o Reclama‡„o x Solu‡„o - Visualiza‡„o"
#ELSE
   #IFDEF ENGLISH
      #define STR0001  "Cancel  "
      #define STR0002  "Ok      "
      #define STR0003  "Retype  "
      #define STR0004  "Search   "
      #define STR0005  "View      "
      #define STR0006  "Insert "
      #define STR0007  "Edit   "
      #define STR0008  "Delete "
      #define STR0009  "Updating of the Binding Complaint x Solution"
      #define STR0010  "Binding Complaint x Solution"
      #define STR0011  "Register of Binding Complaint x Solution - Inclusion"
      #define STR0012  "Binding       "
      #define STR0013  "Add Complaint      "
      #define STR0014  "Add Solution    "
      #define STR0015  "Remove item"
      #define STR0016  "Complaint "
      #define STR0017  "Inform the Complaint"
      #define STR0018  "Code  "
      #define STR0019  "Description"
      #define STR0020  "Solution"
      #define STR0021  "Inform the Solution"
      #define STR0022  "Ok to Clear All?             "
      #define STR0023  "Ok to Delete this Solution?        "
      #define STR0024  "Register of Binding Complaint x Solution - Updating "                
      #define STR0025  "Wait   "
      #define STR0026  "Building the Structure of the Binding"
      #define STR0027  "Register of Binding Complaint x Solution - Deletion"
      #define STR0028  "Ok to Delete?        "
      #define STR0029  "Register of Binding Complaint x Solution - View        "   
   #ELSE
      #define STR0001  "Abandona"
      #define STR0002  "Confirma"
      #define STR0003  "Redigita"
      #define STR0004  "Pesquisar"
      #define STR0005  "Visualizar"
      #define STR0006  "Incluir"
      #define STR0007  "Alterar"
      #define STR0008  "Excluir"
      #define STR0009  "Atualiza‡„o da Rela‡„o Reclama‡„o x Solu‡„o"
      #define STR0010  "Rela‡„o Reclama‡„o x Solu‡„o"
      #define STR0011  "Cadastro de Rela‡„o Reclama‡„o x Solu‡„o - Inclus„o"
      #define STR0012  "Relacionamento"
      #define STR0013  "Adiciona Reclama‡„o"
      #define STR0014  "Adiciona Solu‡„o"
      #define STR0015  "Remove item"
      #define STR0016  "Reclama‡„o"
      #define STR0017  "Informe a Reclama‡„o"
      #define STR0018  "C¢digo"
      #define STR0019  "Descri‡„o"
      #define STR0020  "Solu‡„o"
      #define STR0021  "Informe a Solu‡„o"
      #define STR0022  "Confirma a exclus„o de tudo ?"
      #define STR0023  "Confirma a exclus„o dessa solu‡„o ?"
      #define STR0024  "Cadastro de Rela‡„o Reclama‡„o x Solu‡„o - Altera‡„o"                
      #define STR0025  "Aguarde"
      #define STR0026  "Montando Estrutura do Relacionamento"
      #define STR0027  "Cadastro de Rela‡„o Reclama‡„o x Solu‡„o - Exclus„o"
      #define STR0028  "Confirma a exclus„o ?"
      #define STR0029  "Cadastro de Rela‡„o Reclama‡„o x Solu‡„o - Visualiza‡„o"
   #ENDIF
#ENDIF
