#IFDEF SPANISH
         #define STR0001  "Salir   "
         #define STR0002  "Confirma"
         #define STR0003  "Retipea "
         #define STR0004  "B&uscar   "
         #define STR0005  "Visualizar"
         #define STR0006  "Incluir"
         #define STR0007  "Modificar"
         #define STR0008  "Borrar "
         #define STR0009  "Actualizaci¢n Motivo de la Llamada"
         #define STR0010  "Mot. de la Llamada"
         #define STR0011  "¨Cu nto al Borrar? "
         #define STR0012  "Seleccionando Llamadas ..."
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Abandona"
         #define STR0002  "Confirma"
         #define STR0003  "Redigita"
         #define STR0004  "Pesquisar"
         #define STR0005  "Visualizar"
         #define STR0006  "Incluir"
         #define STR0007  "Alterar"
         #define STR0008  "Excluir"
         #define STR0009  "Atualiza‡„o de Motivo da Liga‡„o"
         #define STR0010  "Motivo da Liga‡Æo"
         #define STR0011  "Quanto … exclus„o ?"
	 #define STR0012  "Selecionando Liga‡”es..."
   #ELSE
         #define STR0001  "Abandona"
         #define STR0002  "Confirma"
         #define STR0003  "Redigita"
         #define STR0004  "Pesquisar"
         #define STR0005  "Visualizar"
         #define STR0006  "Incluir"
         #define STR0007  "Alterar"
         #define STR0008  "Excluir"
         #define STR0009  "Atualiza‡„o de Motivo da Liga‡„o"
         #define STR0010  "Motivo da Liga‡Æo"
         #define STR0011  "Quanto … exclus„o ?"
	 #define STR0012  "Selecionando Liga‡”es..."
   #ENDIF
#ENDIF
