#IFDEF SPANISH
   #define STR0001 "B&uscar"
   #define STR0002 "Visualizar"
   #define STR0003 "Incluir"
   #define STR0004 "Modificar"
   #define STR0005 "Borrar"
   #define STR0006 "Actualizaci¢n de la Campa¤a"
   #define STR0007 "Campa¤a"
   #define STR0008 "Archivo de Campa¤as - Inclusi¢n"
   #define STR0009 "Informaciones"
   #define STR0010 "Descripci¢n"
   #define STR0011 "Activo"
   #define STR0012 "Receptivo"
   #define STR0013 "Ambos"
   #define STR0014 "Tiempo ideal de conversaci¢n"
   #define STR0015 "Responsable"
   #define STR0016 "Script Din mico"
   #define STR0017 "Objetivos:"
   #define STR0018 "Fecha Inicial"
   #define STR0019 "Fecha Final"
   #define STR0020 "Meta Total"
   #define STR0021 "Meta por Operador"
   #define STR0022 "% Suceso"
   #define STR0023 "% Fracaso"
   #define STR0024 "Mensaje:"
   #define STR0025 "Adiciona"
   #define STR0026 "Remueve"
   #define STR0027 "Pregunta"
   #define STR0028 "Respuestas:"
   #define STR0029 "Archivo de Campa¤as - Modificaci¢n"
   #define STR0030 "Espere"
   #define STR0031 "Montando Estructura de la Campa¤a ..."
   #define STR0032 "¨Confirma borrar a partir de esta respuesta?"
   #define STR0033 "¨Confirma borrar a partir de esta pregunta?"
   #define STR0034 "Archivo de Campa¤as - Visualizaci¢n"
   #define STR0035 "Modifica"
   #define STR0036 "¨Confirma el borrado de esta Campa¤a?"   
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Atualiza‡„o da Campanha"
      #define STR0007 "Campanha"
      #define STR0008 "Cadastro de Campanhas - Inclus„o"
      #define STR0009 "Informa‡”es"
      #define STR0010 "Descri‡„o"
      #define STR0011 "Ativo"
      #define STR0012 "Receptivo"
      #define STR0013 "Ambos"
      #define STR0014 "Tempo ideal de conversa‡„o"
      #define STR0015 "Respons vel"
      #define STR0016 "Script Dinamico"
      #define STR0017 "Objetivos:"
      #define STR0018 "Data Inicial"
      #define STR0019 "Data Final"
      #define STR0020 "Meta Total"
      #define STR0021 "Meta por Operador"
      #define STR0022 "% Sucesso"
      #define STR0023 "% Fracasso"
      #define STR0024 "Mensagem:"
      #define STR0025 "Adiciona"
      #define STR0026 "Remove"
      #define STR0027 "Pergunta"
      #define STR0028 "Respostas:"
      #define STR0029 "Cadastro de Campanhas - Altera‡„o"
      #define STR0030 "Aguarde"
      #define STR0031 "Montando Estrutura da Campanha ..."
      #define STR0032 "Confirma a exclus„o a partir dessa resposta ?"
      #define STR0033 "Confirma a exclus„o a partir dessa pergunta ?"
      #define STR0034 "Cadastro de Campanhas - Visualiza‡Æo"
      #define STR0035 "Altera"
      #define STR0036 "Confirma a exclus„o dessa Campanha ?"      
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Atualiza‡„o da Campanha"
      #define STR0007 "Campanha"
      #define STR0008 "Cadastro de Campanhas - Inclus„o"
      #define STR0009 "Informa‡”es"
      #define STR0010 "Descri‡„o"
      #define STR0011 "Ativo"
      #define STR0012 "Receptivo"
      #define STR0013 "Ambos"
      #define STR0014 "Tempo ideal de conversa‡„o"
      #define STR0015 "Respons vel"
      #define STR0016 "Script Dinamico"
      #define STR0017 "Objetivos:"
      #define STR0018 "Data Inicial"
      #define STR0019 "Data Final"
      #define STR0020 "Meta Total"
      #define STR0021 "Meta por Operador"
      #define STR0022 "% Sucesso"
      #define STR0023 "% Fracasso"
      #define STR0024 "Mensagem:"
      #define STR0025 "Adiciona"
      #define STR0026 "Remove"
      #define STR0027 "Pergunta"
      #define STR0028 "Respostas:"
      #define STR0029 "Cadastro de Campanhas - Altera‡„o"
      #define STR0030 "Aguarde"
      #define STR0031 "Montando Estrutura da Campanha ..."
      #define STR0032 "Confirma a exclus„o a partir dessa resposta ?"
      #define STR0033 "Confirma a exclus„o a partir dessa pergunta ?"
      #define STR0034 "Cadastro de Campanhas - Visualiza‡Æo"
      #define STR0035 "Altera"   
      #define STR0036 "Confirma a exclus„o dessa Campanha ?"
   #ENDIF
#ENDIF
