#IFDEF SPANISH
     #define STR0001  "Salir   "
     #define STR0002  "Confirma"
     #define STR0003  "Retipea "
     #define STR0004  "Buscar   "
     #define STR0005  "Visualizar"
     #define STR0006  "Incluir"
     #define STR0007  "Modificar"
     #define STR0008  "Borrar "
     #define STR0009  "Archivo de Estructura de Productos"
     #define STR0010  "Estrutura de Produto"
     #define STR0011  "¨Cu nto al Borrar?"
     #define STR0012  "Producto"
     #define STR0013  "Descripci¢n"
     #define STR0014  "Productos"
     #define STR0015  "C¢digo"
     #define STR0016  "Insertar"
     #define STR0017  "Remueve"
     #define STR0018  "¨Sale del archivo de Estructura ?"
     #define STR0019  "¨Confirma el Archivo de esta Estructura ?"
 #ELSE
   #IFDEF ENGLISH
         #define STR0001  "Abandona"
         #define STR0002  "Confirma"
         #define STR0003  "Redigita"
         #define STR0004  "Pesquisar"
         #define STR0005  "Visualizar"
         #define STR0006  "Incluir"
         #define STR0007  "Alterar"
         #define STR0008  "Excluir"
         #define STR0009  "Cadastro de Estrutura de Produtos"
         #define STR0010  "Estrutura de Produto"
         #define STR0011  "Quanto … exclus„o ?"
         #define STR0012  "Produto"
         #define STR0013  "Descri‡Æo"
         #define STR0014  "Produtos"
         #define STR0015  "C¢digo"
         #define STR0016  "Insere"
         #define STR0017  "Remove"
         #define STR0018  "Abandona o Cadastro de Estrutura ? "
         #define STR0019  "Confirma o Cadastro dessa Estrutura ?"
    #ELSE
         #define STR0001  "Abandona"
         #define STR0002  "Confirma"
         #define STR0003  "Redigita"
         #define STR0004  "Pesquisar"
         #define STR0005  "Visualizar"
         #define STR0006  "Incluir"
         #define STR0007  "Alterar"
         #define STR0008  "Excluir"
         #define STR0009  "Cadastro de Estrutura de Produtos"
         #define STR0010  "Estrutura de Produto"
         #define STR0011  "Quanto … exclus„o ?"
         #define STR0012  "Produto"
         #define STR0013  "Descri‡Æo"
         #define STR0014  "Produtos"
         #define STR0015  "C¢digo"
         #define STR0016  "Insere"
         #define STR0017  "Remove"
         #define STR0018  "Abandona o Cadastro de Estrutura ? "
         #define STR0019  "Confirma o Cadastro dessa Estrutura ?"
   #ENDIF
#ENDIF
