#IFDEF SPANISH
   #define STR0001  "Presupuesto"
   #define STR0002  "Este programa emitir  los presupuestos"
   #define STR0003  "Especial"
   #define STR0004  "Administraci¢n"
   #define STR0005  "  Sucursal    Presupuesto Vendedor                      Fecha Presup      Estatus"
   #define STR0006  "Valores en $"
   #define STR0007  "Seleccionando Registros..."
   #define STR0008  "CANCELADO POR EL OPERADOR"
   #define STR0009  "Cond. Pago: "
   #define STR0010  "Cliente: "
   #define STR0011  "Inscr. Provinc./DNI:" 
   #define STR0012  "CUIT:   "
   #define STR0013  "Direcci¢n para Cobros:"
   #define STR0014  "Local.: "
   #define STR0015  "CP: "
   #define STR0016  "Barrio: "
   #define STR0017  "Ciudad/Pv: "
   #define STR0018  "Direc. para Entrega: "
   #define STR0019  "Tel‚&fono "
   #define STR0020  "Transp.: "
   #define STR0021  "Obs:"
   #define STR0022  "C¢digo          Descripci¢n            Un     Ctd.      Vlr. Unit.        Total"
   #define STR0023  "Forma de Pago"
   #define STR0024  "Fecha"
   #define STR0025  "Valor"
   #define STR0026  "Forma"
   #define STR0027  "Este presupuesto tiene validez por"
   #define STR0028  " d¡as."
   #define STR0029  " d¡a."
   #define STR0030  "No hay informaciones para imprimir este informe"
#ELSE
   #IFDEF ENGLISH
      #define STR0001  "Orcamento"
      #define STR0002  "Este programa ira emitir os orcamentos"
      #define STR0003  "Especial"
      #define STR0004  "Administracao"
      #define STR0005  "  Filial      Or‡amento Vendedor                        Data Or‡am        Status"
      #define STR0006  "Valores em R$"
      #define STR0007  "Selecionando Registros..."
      #define STR0008  "CANCELADO PELO OPERADOR"
      #define STR0009  "Cond.Pagto: "
      #define STR0010  "Cliente: "
      #define STR0011  "Inscr.Estadual/RG: "
      #define STR0012  "CPF/CGC:"
      #define STR0013  "Endere‡o p/ Cobran‡a: "
      #define STR0014  "Compl.: "
      #define STR0015  "Cep: "
      #define STR0016  "Bairro: "
      #define STR0017  "Cidade/UF: "
      #define STR0018  "Endere‡o p/ Entrega: "
      #define STR0019  "TeleFone: "
      #define STR0020  "Transp.: "
      #define STR0021  "Obs:"
      #define STR0022  "Codigo          Descri‡„o              Un     Qtde.     Vlr. Unit.        Total"
      #define STR0023  "Forma de Pagamento"
      #define STR0024  "Data"
      #define STR0025  "Valor"
      #define STR0026  "Forma"
      #define STR0027  "Este or‡amento ‚ valido por "
      #define STR0028  " dias."
      #define STR0029  " dia."
      #define STR0030  "Nao ha informacoes para imprimir este relatorio"
   #ELSE
      #define STR0001  "Orcamento"
      #define STR0002  "Este programa ira emitir os orcamentos"
      #define STR0003  "Especial"
      #define STR0004  "Administracao"
      #define STR0005  "  Filial      Or‡amento Vendedor                        Data Or‡am        Status"
      #define STR0006  "Valores em R$"
      #define STR0007  "Selecionando Registros..."
      #define STR0008  "CANCELADO PELO OPERADOR"
      #define STR0009  "Cond.Pagto: "
      #define STR0010  "Cliente: "
      #define STR0011  "Inscr.Estadual/RG: "
      #define STR0012  "CPF/CGC:"
      #define STR0013  "Endere‡o p/ Cobran‡a: "
      #define STR0014  "Compl.: "
      #define STR0015  "Cep: "
      #define STR0016  "Bairro: "
      #define STR0017  "Cidade/UF: "
      #define STR0018  "Endere‡o p/ Entrega: "
      #define STR0019  "TeleFone: "
      #define STR0020  "Transp.: "
      #define STR0021  "Obs:"
      #define STR0022  "Codigo          Descri‡„o              Un     Qtde.     Vlr. Unit.        Total"
      #define STR0023  "Forma de Pagamento"
      #define STR0024  "Data"
      #define STR0025  "Valor"
      #define STR0026  "Forma"
      #define STR0027  "Este or‡amento ‚ valido por "
      #define STR0028  " dias."
      #define STR0029  " dia."
      #define STR0030  "Nao ha informacoes para imprimir este relatorio"
   #ENDIF
#ENDIF
