#IFDEF SPANISH
   #define STR0001  "Llamada  Autom†tica"
   #define STR0002  "No hay llamadas genÇricas para hacer hoy  "
   #define STR0003  "Atenci¢n"
   #define STR0004  "No hay llamadas para este operador"
   #define STR0005  "Cliente"
   #define STR0006  "Apodo  "
   #define STR0007  "Raz¢n Social"
   #define STR0008  "Contacto"
   #define STR0009  "TelÇfono"
   #define STR0010  "Crono Fecha"
   #define STR0011  "Hora Inicio"
   #define STR0012  "Hora Fin"
   #define STR0013  "Llamada"
   #define STR0014  "Evento al Marcar      "
   #define STR0015  " Pendientes "
   #define STR0016  "Busca   "
   #define STR0017  "Orden:"
   #define STR0018  "Localizar:"
   #define STR0019  "Ocupado"
   #define STR0020  "Error de Comando"
   #define STR0021  "Falla"
   #define STR0022  "Sin L°nea"
   #define STR0023  "Hecho con Çxito"
   #define STR0024  "Borrar "
   #define STR0025  "Esta llamada ya fue hecha por otro operador "
   #define STR0026  "Atenci¢n"
   #define STR0027  "Esta llamada est† siendo hecha por otro operador "
   #define STR0028  "Atenci¢n"
   #define STR0029  "Esta llamada fue Borrada"
   #define STR0030  "Atenci¢n"
   #define STR0031  "El Sistema ultrapas¢ el l°mite de tentativas"
   #define STR0032  "Error en la apertura del puerto serial"
   #define STR0033  "Falla al activar el Modem"
   #define STR0034  "Error en el Comando del Modem"
   #define STR0035  "No hay tono de l°nea para hacer la llamada  "
   #define STR0036  "El telÇfono esta llamando"
   #define STR0037  "Se§al de Ocupado"
   #define STR0038  "Hay un modem activo en el telÇfono llamado"
   #define STR0039  "®Confirma el êxito?"
   #define STR0040  "Domingo"
   #define STR0041  "Lunes  "
   #define STR0042  "Martes"
   #define STR0043  "MiÇrcoles"
   #define STR0044  "Jueves"
   #define STR0045  "Viernes"
   #define STR0046  "S†bado"
   #define STR0047  "Semana"
   #define STR0048  "Elija los D°as "
   #define STR0049  "Hora Inicial:"
   #define STR0050  "Final:"
   #define STR0051  "Desea hacer llamadas fuera del horario para  "
   #define STR0052  "Contactos"
   #define STR0053  "Nombre de Contacto"
   #define STR0054  "TelÇfono"
   #define STR0055  "®Confirma Borrar?"
   #define STR0056  "Este registro ya est† Borrado"
   #define STR0057  "®Confirma el êxito?"
   #define STR0058  "C¢digo"
   #define STR0059  "Raz¢n Social" 
   #define STR0060  "TelÇfono"
   #define STR0061  "Llamada"	
#ELSE
   #IFDEF ENGLISH
      #define STR0001  "Discagem Autom†tica"
      #define STR0002  "NÑo h† ligaáîes genÇricas a serem efetuadas hoje"
      #define STR0003  "AtenáÑo"
      #define STR0004  "NÑo h† ligaáîes para este operador"
      #define STR0005  "Cliente"
      #define STR0006  "Apelido"
      #define STR0007  "RazÑo Social"
      #define STR0008  "Contato"
      #define STR0009  "Telefone"
      #define STR0010  "Crono Data"
      #define STR0011  "Hora In°cio"
      #define STR0012  "Hora Fim"
      #define STR0013  "LigaáÑo"
      #define STR0014  "Ocorrencia na Discagem"
      #define STR0015  " Pendentes "
      #define STR0016  "Pesquisa"
      #define STR0017  "Ordem:"
      #define STR0018  "Localizar:"
      #define STR0019  "Ocupado"
      #define STR0020  "Erro de Comando"
      #define STR0021  "Falha"
      #define STR0022  "Sem Linha"
      #define STR0023  "Efetuado com sucesso"
      #define STR0024  "Excluir"
      #define STR0025  "Essa ligaáÑo j† foi efetuada por outro operador"
      #define STR0026  "AtenáÑo"
      #define STR0027  "Essa ligaáÑo est† sendo efetuada por outro operador"
      #define STR0028  "AtenáÑo"
      #define STR0029  "Essa ligaáÑo foi Apagada"
      #define STR0030  "AtenáÑo"
      #define STR0031  "O sistema utrapassou o limite de tentativas"
      #define STR0032  "Erro na abertura da porta serial"
      #define STR0033  "Falha na inicializaáÑo do Modem"
      #define STR0034  "Erro no Comando do Modem"
      #define STR0035  "NÑo h† tom de linha para realizar a discagem"
      #define STR0036  "O Telefone est† Tocando"
      #define STR0037  "Sinal de Ocupado"
      #define STR0038  "Ha um modem ativo no telefone discado"
      #define STR0039  "Confirma o Sucesso ?"
      #define STR0040  "Domingo"
      #define STR0041  "Segunda"
      #define STR0042  "Terca"
      #define STR0043  "Quarta"
      #define STR0044  "Quinta"
      #define STR0045  "Sexta"
      #define STR0046  "Sabado"
      #define STR0047  "Semana"
      #define STR0048  "Escolha os Dias"
      #define STR0049  "Hora Inicial:"
      #define STR0050  "Final:"
      #define STR0051  "Deseja efetuar ligacao fora do hor†rio para "
      #define STR0052  "Contatos"
      #define STR0053  "Nome do Contato"
      #define STR0054  "Telefone"
      #define STR0055  "Confirma ExclusÑo ?"
      #define STR0056  "Esse registro j† est† Apagado"
      #define STR0057  "Confirma o Sucesso ?"
      #define STR0058  "C¢digo"
      #define STR0059  "RazÑo Social" 
      #define STR0060  "Telefone"
      #define STR0061  "LigaáÑo"		
   #ELSE
      #define STR0001  "Discagem Autom†tica"
      #define STR0002  "NÑo h† ligaáîes genÇricas a serem efetuadas hoje"
      #define STR0003  "AtenáÑo"
      #define STR0004  "NÑo h† ligaáîes para este operador"
      #define STR0005  "Cliente"
      #define STR0006  "Apelido"
      #define STR0007  "RazÑo Social"
      #define STR0008  "Contato"
      #define STR0009  "Telefone"
      #define STR0010  "Crono Data"
      #define STR0011  "Hora In°cio"
      #define STR0012  "Hora Fim"
      #define STR0013  "LigaáÑo"
      #define STR0014  "Ocorrencia na Discagem"
      #define STR0015  " Pendentes "
      #define STR0016  "Pesquisa"
      #define STR0017  "Ordem:"
      #define STR0018  "Localizar:"
      #define STR0019  "Ocupado"
      #define STR0020  "Erro de Comando"
      #define STR0021  "Falha"
      #define STR0022  "Sem Linha"
      #define STR0023  "Efetuado com sucesso"
      #define STR0024  "Excluir"
      #define STR0025  "Essa ligaáÑo j† foi efetuada por outro operador"
      #define STR0026  "AtenáÑo"
      #define STR0027  "Essa ligaáÑo est† sendo efetuada por outro operador"
      #define STR0028  "AtenáÑo"
      #define STR0029  "Essa ligaáÑo foi Apagada"
      #define STR0030  "AtenáÑo"
      #define STR0031  "O sistema utrapassou o limite de tentativas"
      #define STR0032  "Erro na abertura da porta serial"
      #define STR0033  "Falha na inicializaáÑo do Modem"
      #define STR0034  "Erro no Comando do Modem"
      #define STR0035  "NÑo h† tom de linha para realizar a discagem"
      #define STR0036  "O Telefone est† Tocando"
      #define STR0037  "Sinal de Ocupado"
      #define STR0038  "Ha um modem ativo no telefone discado"
      #define STR0039  "Confirma o Sucesso ?"
      #define STR0040  "Domingo"
      #define STR0041  "Segunda"
      #define STR0042  "Terca"
      #define STR0043  "Quarta"
      #define STR0044  "Quinta"
      #define STR0045  "Sexta"
      #define STR0046  "Sabado"
      #define STR0047  "Semana"
      #define STR0048  "Escolha os Dias"
      #define STR0049  "Hora Inicial:"
      #define STR0050  "Final:"
      #define STR0051  "Deseja efetuar ligacao fora do hor†rio para "
      #define STR0052  "Contatos"
      #define STR0053  "Nome do Contato"
      #define STR0054  "Telefone"
      #define STR0055  "Confirma ExclusÑo ?"
      #define STR0056  "Esse registro j† est† Apagado"
      #define STR0057  "Confirma o Sucesso ?"
      #define STR0058  "C¢digo"
      #define STR0059  "RazÑo Social" 
      #define STR0060  "Telefone"
      #define STR0061  "LigaáÑo"
   #ENDIF
#ENDIF
